package ext_kernels

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for CurlCalc kernel
var CurlCalc_code cu.Function

// Stores the arguments for CurlCalc kernel invocation
type CurlCalc_args_t struct{
	 arg_FieldX unsafe.Pointer
	 arg_FieldY unsafe.Pointer
	 arg_FieldZ unsafe.Pointer
	 arg_curlX unsafe.Pointer
	 arg_curlY unsafe.Pointer
	 arg_curlZ unsafe.Pointer
	 arg_Nx int
	 arg_Ny int
	 arg_Nz int
	 arg_includeGeometry unsafe.Pointer
	 arg_cellsize float32
	 argptr [11]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for CurlCalc kernel invocation
var CurlCalc_args CurlCalc_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 CurlCalc_args.argptr[0] = unsafe.Pointer(&CurlCalc_args.arg_FieldX)
	 CurlCalc_args.argptr[1] = unsafe.Pointer(&CurlCalc_args.arg_FieldY)
	 CurlCalc_args.argptr[2] = unsafe.Pointer(&CurlCalc_args.arg_FieldZ)
	 CurlCalc_args.argptr[3] = unsafe.Pointer(&CurlCalc_args.arg_curlX)
	 CurlCalc_args.argptr[4] = unsafe.Pointer(&CurlCalc_args.arg_curlY)
	 CurlCalc_args.argptr[5] = unsafe.Pointer(&CurlCalc_args.arg_curlZ)
	 CurlCalc_args.argptr[6] = unsafe.Pointer(&CurlCalc_args.arg_Nx)
	 CurlCalc_args.argptr[7] = unsafe.Pointer(&CurlCalc_args.arg_Ny)
	 CurlCalc_args.argptr[8] = unsafe.Pointer(&CurlCalc_args.arg_Nz)
	 CurlCalc_args.argptr[9] = unsafe.Pointer(&CurlCalc_args.arg_includeGeometry)
	 CurlCalc_args.argptr[10] = unsafe.Pointer(&CurlCalc_args.arg_cellsize)
	 }

// Wrapper for CurlCalc CUDA kernel, asynchronous.
func K_ext_CurlCalc_async ( FieldX unsafe.Pointer, FieldY unsafe.Pointer, FieldZ unsafe.Pointer, curlX unsafe.Pointer, curlY unsafe.Pointer, curlZ unsafe.Pointer, Nx int, Ny int, Nz int, includeGeometry unsafe.Pointer, cellsize float32,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("CurlCalc")
	}

	CurlCalc_args.Lock()
	defer CurlCalc_args.Unlock()

	if CurlCalc_code == 0{
		CurlCalc_code = fatbinLoad(CurlCalc_map, "CurlCalc")
	}

	 CurlCalc_args.arg_FieldX = FieldX
	 CurlCalc_args.arg_FieldY = FieldY
	 CurlCalc_args.arg_FieldZ = FieldZ
	 CurlCalc_args.arg_curlX = curlX
	 CurlCalc_args.arg_curlY = curlY
	 CurlCalc_args.arg_curlZ = curlZ
	 CurlCalc_args.arg_Nx = Nx
	 CurlCalc_args.arg_Ny = Ny
	 CurlCalc_args.arg_Nz = Nz
	 CurlCalc_args.arg_includeGeometry = includeGeometry
	 CurlCalc_args.arg_cellsize = cellsize
	

	args := CurlCalc_args.argptr[:]
	cu.LaunchKernel(CurlCalc_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("CurlCalc")
	}
}

// maps compute capability on PTX code for CurlCalc kernel.
var CurlCalc_map = map[int]string{ 0: "" ,
20: CurlCalc_ptx_20 ,
30: CurlCalc_ptx_30 ,
35: CurlCalc_ptx_35 ,
50: CurlCalc_ptx_50 ,
52: CurlCalc_ptx_52 ,
53: CurlCalc_ptx_53  }

// CurlCalc PTX code for various compute capabilities.
const(
  CurlCalc_ptx_20 = `
.version 5.0
.target sm_20
.address_size 64

	// .globl	CurlCalc

.visible .entry CurlCalc(
	.param .u64 CurlCalc_param_0,
	.param .u64 CurlCalc_param_1,
	.param .u64 CurlCalc_param_2,
	.param .u64 CurlCalc_param_3,
	.param .u64 CurlCalc_param_4,
	.param .u64 CurlCalc_param_5,
	.param .u32 CurlCalc_param_6,
	.param .u32 CurlCalc_param_7,
	.param .u32 CurlCalc_param_8,
	.param .u64 CurlCalc_param_9,
	.param .f32 CurlCalc_param_10
)
{
	.reg .pred 	%p<13>;
	.reg .f32 	%f<31>;
	.reg .b32 	%r<45>;
	.reg .f64 	%fd<18>;
	.reg .b64 	%rd<58>;


	ld.param.u64 	%rd9, [CurlCalc_param_0];
	ld.param.u64 	%rd10, [CurlCalc_param_1];
	ld.param.u64 	%rd11, [CurlCalc_param_2];
	ld.param.u64 	%rd12, [CurlCalc_param_3];
	ld.param.u64 	%rd13, [CurlCalc_param_4];
	ld.param.u64 	%rd14, [CurlCalc_param_5];
	ld.param.u32 	%r11, [CurlCalc_param_6];
	ld.param.u32 	%r12, [CurlCalc_param_7];
	ld.param.u32 	%r13, [CurlCalc_param_8];
	ld.param.u64 	%rd15, [CurlCalc_param_9];
	ld.param.f32 	%f1, [CurlCalc_param_10];
	cvta.to.global.u64 	%rd1, %rd15;
	mov.u32 	%r14, %ntid.x;
	mov.u32 	%r15, %ctaid.x;
	mov.u32 	%r16, %tid.x;
	mad.lo.s32 	%r1, %r14, %r15, %r16;
	mov.u32 	%r17, %ntid.y;
	mov.u32 	%r18, %ctaid.y;
	mov.u32 	%r19, %tid.y;
	mad.lo.s32 	%r2, %r17, %r18, %r19;
	mov.u32 	%r20, %ntid.z;
	mov.u32 	%r21, %ctaid.z;
	mov.u32 	%r22, %tid.z;
	mad.lo.s32 	%r3, %r20, %r21, %r22;
	setp.ge.s32	%p1, %r2, %r12;
	setp.ge.s32	%p2, %r1, %r11;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r13;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_9;

	mul.lo.s32 	%r4, %r3, %r12;
	add.s32 	%r23, %r4, %r2;
	mul.lo.s32 	%r5, %r23, %r11;
	add.s32 	%r24, %r5, %r1;
	add.s32 	%r25, %r13, %r3;
	add.s32 	%r26, %r25, -1;
	rem.s32 	%r27, %r26, %r13;
	mad.lo.s32 	%r28, %r27, %r12, %r2;
	mad.lo.s32 	%r6, %r28, %r11, %r1;
	add.s32 	%r29, %r3, 1;
	rem.s32 	%r30, %r29, %r13;
	mad.lo.s32 	%r31, %r30, %r12, %r2;
	mad.lo.s32 	%r7, %r31, %r11, %r1;
	cvt.s64.s32	%rd2, %r24;
	mul.wide.s32 	%rd16, %r24, 4;
	add.s64 	%rd17, %rd1, %rd16;
	ld.global.f32 	%f2, [%rd17];
	setp.eq.f32	%p6, %f2, 0f00000000;
	@%p6 bra 	BB0_9;

	add.s32 	%r32, %r11, %r1;
	add.s32 	%r33, %r32, -1;
	rem.s32 	%r34, %r33, %r11;
	add.s32 	%r35, %r34, %r5;
	add.s32 	%r36, %r1, 1;
	rem.s32 	%r37, %r36, %r11;
	add.s32 	%r8, %r37, %r5;
	add.s32 	%r38, %r12, %r2;
	add.s32 	%r39, %r38, -1;
	rem.s32 	%r40, %r39, %r12;
	add.s32 	%r41, %r40, %r4;
	mad.lo.s32 	%r9, %r41, %r11, %r1;
	add.s32 	%r42, %r2, 1;
	rem.s32 	%r43, %r42, %r12;
	add.s32 	%r44, %r43, %r4;
	mad.lo.s32 	%r10, %r44, %r11, %r1;
	cvt.s64.s32	%rd3, %r35;
	mul.wide.s32 	%rd18, %r35, 4;
	add.s64 	%rd19, %rd1, %rd18;
	ld.global.f32 	%f3, [%rd19];
	setp.eq.f32	%p7, %f3, 0f00000000;
	@%p7 bra 	BB0_9;

	cvt.s64.s32	%rd4, %r8;
	mul.wide.s32 	%rd20, %r8, 4;
	add.s64 	%rd21, %rd1, %rd20;
	ld.global.f32 	%f4, [%rd21];
	setp.eq.f32	%p8, %f4, 0f00000000;
	@%p8 bra 	BB0_9;

	cvt.s64.s32	%rd5, %r9;
	mul.wide.s32 	%rd22, %r9, 4;
	add.s64 	%rd23, %rd1, %rd22;
	ld.global.f32 	%f5, [%rd23];
	setp.eq.f32	%p9, %f5, 0f00000000;
	@%p9 bra 	BB0_9;

	cvt.s64.s32	%rd6, %r10;
	mul.wide.s32 	%rd24, %r10, 4;
	add.s64 	%rd25, %rd1, %rd24;
	ld.global.f32 	%f6, [%rd25];
	setp.eq.f32	%p10, %f6, 0f00000000;
	@%p10 bra 	BB0_9;

	cvt.s64.s32	%rd7, %r6;
	mul.wide.s32 	%rd26, %r6, 4;
	add.s64 	%rd27, %rd1, %rd26;
	ld.global.f32 	%f7, [%rd27];
	setp.eq.f32	%p11, %f7, 0f00000000;
	@%p11 bra 	BB0_9;

	cvt.s64.s32	%rd8, %r7;
	mul.wide.s32 	%rd28, %r7, 4;
	add.s64 	%rd29, %rd1, %rd28;
	ld.global.f32 	%f8, [%rd29];
	setp.eq.f32	%p12, %f8, 0f00000000;
	@%p12 bra 	BB0_9;

	cvta.to.global.u64 	%rd30, %rd14;
	cvta.to.global.u64 	%rd31, %rd13;
	cvta.to.global.u64 	%rd32, %rd9;
	shl.b64 	%rd33, %rd5, 2;
	add.s64 	%rd34, %rd32, %rd33;
	ld.global.f32 	%f9, [%rd34];
	shl.b64 	%rd35, %rd6, 2;
	add.s64 	%rd36, %rd32, %rd35;
	ld.global.f32 	%f10, [%rd36];
	shl.b64 	%rd37, %rd7, 2;
	add.s64 	%rd38, %rd32, %rd37;
	ld.global.f32 	%f11, [%rd38];
	shl.b64 	%rd39, %rd8, 2;
	add.s64 	%rd40, %rd32, %rd39;
	ld.global.f32 	%f12, [%rd40];
	cvta.to.global.u64 	%rd41, %rd10;
	shl.b64 	%rd42, %rd3, 2;
	add.s64 	%rd43, %rd41, %rd42;
	ld.global.f32 	%f13, [%rd43];
	shl.b64 	%rd44, %rd4, 2;
	add.s64 	%rd45, %rd41, %rd44;
	ld.global.f32 	%f14, [%rd45];
	add.s64 	%rd46, %rd41, %rd37;
	add.s64 	%rd47, %rd41, %rd39;
	cvta.to.global.u64 	%rd48, %rd11;
	add.s64 	%rd49, %rd48, %rd42;
	ld.global.f32 	%f15, [%rd49];
	add.s64 	%rd50, %rd48, %rd44;
	ld.global.f32 	%f16, [%rd50];
	add.s64 	%rd51, %rd48, %rd33;
	add.s64 	%rd52, %rd48, %rd35;
	ld.global.f32 	%f17, [%rd52];
	ld.global.f32 	%f18, [%rd51];
	sub.f32 	%f19, %f17, %f18;
	cvt.f64.f32	%fd1, %f19;
	cvt.f64.f32	%fd2, %f1;
	add.f64 	%fd3, %fd2, %fd2;
	div.rn.f64 	%fd4, %fd1, %fd3;
	ld.global.f32 	%f20, [%rd47];
	ld.global.f32 	%f21, [%rd46];
	sub.f32 	%f22, %f20, %f21;
	cvt.f64.f32	%fd5, %f22;
	div.rn.f64 	%fd6, %fd5, %fd3;
	sub.f64 	%fd7, %fd4, %fd6;
	cvt.rn.f32.f64	%f23, %fd7;
	cvta.to.global.u64 	%rd53, %rd12;
	shl.b64 	%rd54, %rd2, 2;
	add.s64 	%rd55, %rd53, %rd54;
	st.global.f32 	[%rd55], %f23;
	sub.f32 	%f24, %f16, %f15;
	cvt.f64.f32	%fd8, %f24;
	div.rn.f64 	%fd9, %fd8, %fd3;
	sub.f32 	%f25, %f12, %f11;
	cvt.f64.f32	%fd10, %f25;
	div.rn.f64 	%fd11, %fd10, %fd3;
	sub.f64 	%fd12, %fd9, %fd11;
	cvt.rn.f32.f64	%f26, %fd12;
	neg.f32 	%f27, %f26;
	add.s64 	%rd56, %rd31, %rd54;
	st.global.f32 	[%rd56], %f27;
	sub.f32 	%f28, %f14, %f13;
	cvt.f64.f32	%fd13, %f28;
	div.rn.f64 	%fd14, %fd13, %fd3;
	sub.f32 	%f29, %f10, %f9;
	cvt.f64.f32	%fd15, %f29;
	div.rn.f64 	%fd16, %fd15, %fd3;
	sub.f64 	%fd17, %fd14, %fd16;
	cvt.rn.f32.f64	%f30, %fd17;
	add.s64 	%rd57, %rd30, %rd54;
	st.global.f32 	[%rd57], %f30;

BB0_9:
	ret;
}


`
   CurlCalc_ptx_30 = `
.version 5.0
.target sm_30
.address_size 64

	// .globl	CurlCalc

.visible .entry CurlCalc(
	.param .u64 CurlCalc_param_0,
	.param .u64 CurlCalc_param_1,
	.param .u64 CurlCalc_param_2,
	.param .u64 CurlCalc_param_3,
	.param .u64 CurlCalc_param_4,
	.param .u64 CurlCalc_param_5,
	.param .u32 CurlCalc_param_6,
	.param .u32 CurlCalc_param_7,
	.param .u32 CurlCalc_param_8,
	.param .u64 CurlCalc_param_9,
	.param .f32 CurlCalc_param_10
)
{
	.reg .pred 	%p<13>;
	.reg .f32 	%f<31>;
	.reg .b32 	%r<45>;
	.reg .f64 	%fd<18>;
	.reg .b64 	%rd<58>;


	ld.param.u64 	%rd9, [CurlCalc_param_0];
	ld.param.u64 	%rd10, [CurlCalc_param_1];
	ld.param.u64 	%rd11, [CurlCalc_param_2];
	ld.param.u64 	%rd12, [CurlCalc_param_3];
	ld.param.u64 	%rd13, [CurlCalc_param_4];
	ld.param.u64 	%rd14, [CurlCalc_param_5];
	ld.param.u32 	%r11, [CurlCalc_param_6];
	ld.param.u32 	%r12, [CurlCalc_param_7];
	ld.param.u32 	%r13, [CurlCalc_param_8];
	ld.param.u64 	%rd15, [CurlCalc_param_9];
	ld.param.f32 	%f1, [CurlCalc_param_10];
	cvta.to.global.u64 	%rd1, %rd15;
	mov.u32 	%r14, %ntid.x;
	mov.u32 	%r15, %ctaid.x;
	mov.u32 	%r16, %tid.x;
	mad.lo.s32 	%r1, %r14, %r15, %r16;
	mov.u32 	%r17, %ntid.y;
	mov.u32 	%r18, %ctaid.y;
	mov.u32 	%r19, %tid.y;
	mad.lo.s32 	%r2, %r17, %r18, %r19;
	mov.u32 	%r20, %ntid.z;
	mov.u32 	%r21, %ctaid.z;
	mov.u32 	%r22, %tid.z;
	mad.lo.s32 	%r3, %r20, %r21, %r22;
	setp.ge.s32	%p1, %r2, %r12;
	setp.ge.s32	%p2, %r1, %r11;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r13;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_9;

	mul.lo.s32 	%r4, %r3, %r12;
	add.s32 	%r23, %r4, %r2;
	mul.lo.s32 	%r5, %r23, %r11;
	add.s32 	%r24, %r5, %r1;
	add.s32 	%r25, %r13, %r3;
	add.s32 	%r26, %r25, -1;
	rem.s32 	%r27, %r26, %r13;
	mad.lo.s32 	%r28, %r27, %r12, %r2;
	mad.lo.s32 	%r6, %r28, %r11, %r1;
	add.s32 	%r29, %r3, 1;
	rem.s32 	%r30, %r29, %r13;
	mad.lo.s32 	%r31, %r30, %r12, %r2;
	mad.lo.s32 	%r7, %r31, %r11, %r1;
	cvt.s64.s32	%rd2, %r24;
	mul.wide.s32 	%rd16, %r24, 4;
	add.s64 	%rd17, %rd1, %rd16;
	ld.global.f32 	%f2, [%rd17];
	setp.eq.f32	%p6, %f2, 0f00000000;
	@%p6 bra 	BB0_9;

	add.s32 	%r32, %r11, %r1;
	add.s32 	%r33, %r32, -1;
	rem.s32 	%r34, %r33, %r11;
	add.s32 	%r35, %r34, %r5;
	add.s32 	%r36, %r1, 1;
	rem.s32 	%r37, %r36, %r11;
	add.s32 	%r8, %r37, %r5;
	add.s32 	%r38, %r12, %r2;
	add.s32 	%r39, %r38, -1;
	rem.s32 	%r40, %r39, %r12;
	add.s32 	%r41, %r40, %r4;
	mad.lo.s32 	%r9, %r41, %r11, %r1;
	add.s32 	%r42, %r2, 1;
	rem.s32 	%r43, %r42, %r12;
	add.s32 	%r44, %r43, %r4;
	mad.lo.s32 	%r10, %r44, %r11, %r1;
	cvt.s64.s32	%rd3, %r35;
	mul.wide.s32 	%rd18, %r35, 4;
	add.s64 	%rd19, %rd1, %rd18;
	ld.global.f32 	%f3, [%rd19];
	setp.eq.f32	%p7, %f3, 0f00000000;
	@%p7 bra 	BB0_9;

	cvt.s64.s32	%rd4, %r8;
	mul.wide.s32 	%rd20, %r8, 4;
	add.s64 	%rd21, %rd1, %rd20;
	ld.global.f32 	%f4, [%rd21];
	setp.eq.f32	%p8, %f4, 0f00000000;
	@%p8 bra 	BB0_9;

	cvt.s64.s32	%rd5, %r9;
	mul.wide.s32 	%rd22, %r9, 4;
	add.s64 	%rd23, %rd1, %rd22;
	ld.global.f32 	%f5, [%rd23];
	setp.eq.f32	%p9, %f5, 0f00000000;
	@%p9 bra 	BB0_9;

	cvt.s64.s32	%rd6, %r10;
	mul.wide.s32 	%rd24, %r10, 4;
	add.s64 	%rd25, %rd1, %rd24;
	ld.global.f32 	%f6, [%rd25];
	setp.eq.f32	%p10, %f6, 0f00000000;
	@%p10 bra 	BB0_9;

	cvt.s64.s32	%rd7, %r6;
	mul.wide.s32 	%rd26, %r6, 4;
	add.s64 	%rd27, %rd1, %rd26;
	ld.global.f32 	%f7, [%rd27];
	setp.eq.f32	%p11, %f7, 0f00000000;
	@%p11 bra 	BB0_9;

	cvt.s64.s32	%rd8, %r7;
	mul.wide.s32 	%rd28, %r7, 4;
	add.s64 	%rd29, %rd1, %rd28;
	ld.global.f32 	%f8, [%rd29];
	setp.eq.f32	%p12, %f8, 0f00000000;
	@%p12 bra 	BB0_9;

	cvta.to.global.u64 	%rd30, %rd14;
	cvta.to.global.u64 	%rd31, %rd13;
	cvta.to.global.u64 	%rd32, %rd9;
	shl.b64 	%rd33, %rd5, 2;
	add.s64 	%rd34, %rd32, %rd33;
	ld.global.f32 	%f9, [%rd34];
	shl.b64 	%rd35, %rd6, 2;
	add.s64 	%rd36, %rd32, %rd35;
	ld.global.f32 	%f10, [%rd36];
	shl.b64 	%rd37, %rd7, 2;
	add.s64 	%rd38, %rd32, %rd37;
	ld.global.f32 	%f11, [%rd38];
	shl.b64 	%rd39, %rd8, 2;
	add.s64 	%rd40, %rd32, %rd39;
	ld.global.f32 	%f12, [%rd40];
	cvta.to.global.u64 	%rd41, %rd10;
	shl.b64 	%rd42, %rd3, 2;
	add.s64 	%rd43, %rd41, %rd42;
	ld.global.f32 	%f13, [%rd43];
	shl.b64 	%rd44, %rd4, 2;
	add.s64 	%rd45, %rd41, %rd44;
	ld.global.f32 	%f14, [%rd45];
	add.s64 	%rd46, %rd41, %rd37;
	add.s64 	%rd47, %rd41, %rd39;
	cvta.to.global.u64 	%rd48, %rd11;
	add.s64 	%rd49, %rd48, %rd42;
	ld.global.f32 	%f15, [%rd49];
	add.s64 	%rd50, %rd48, %rd44;
	ld.global.f32 	%f16, [%rd50];
	add.s64 	%rd51, %rd48, %rd33;
	add.s64 	%rd52, %rd48, %rd35;
	ld.global.f32 	%f17, [%rd52];
	ld.global.f32 	%f18, [%rd51];
	sub.f32 	%f19, %f17, %f18;
	cvt.f64.f32	%fd1, %f19;
	cvt.f64.f32	%fd2, %f1;
	add.f64 	%fd3, %fd2, %fd2;
	div.rn.f64 	%fd4, %fd1, %fd3;
	ld.global.f32 	%f20, [%rd47];
	ld.global.f32 	%f21, [%rd46];
	sub.f32 	%f22, %f20, %f21;
	cvt.f64.f32	%fd5, %f22;
	div.rn.f64 	%fd6, %fd5, %fd3;
	sub.f64 	%fd7, %fd4, %fd6;
	cvt.rn.f32.f64	%f23, %fd7;
	cvta.to.global.u64 	%rd53, %rd12;
	shl.b64 	%rd54, %rd2, 2;
	add.s64 	%rd55, %rd53, %rd54;
	st.global.f32 	[%rd55], %f23;
	sub.f32 	%f24, %f16, %f15;
	cvt.f64.f32	%fd8, %f24;
	div.rn.f64 	%fd9, %fd8, %fd3;
	sub.f32 	%f25, %f12, %f11;
	cvt.f64.f32	%fd10, %f25;
	div.rn.f64 	%fd11, %fd10, %fd3;
	sub.f64 	%fd12, %fd9, %fd11;
	cvt.rn.f32.f64	%f26, %fd12;
	neg.f32 	%f27, %f26;
	add.s64 	%rd56, %rd31, %rd54;
	st.global.f32 	[%rd56], %f27;
	sub.f32 	%f28, %f14, %f13;
	cvt.f64.f32	%fd13, %f28;
	div.rn.f64 	%fd14, %fd13, %fd3;
	sub.f32 	%f29, %f10, %f9;
	cvt.f64.f32	%fd15, %f29;
	div.rn.f64 	%fd16, %fd15, %fd3;
	sub.f64 	%fd17, %fd14, %fd16;
	cvt.rn.f32.f64	%f30, %fd17;
	add.s64 	%rd57, %rd30, %rd54;
	st.global.f32 	[%rd57], %f30;

BB0_9:
	ret;
}


`
   CurlCalc_ptx_35 = `
.version 5.0
.target sm_35
.address_size 64

	// .globl	CurlCalc

.visible .entry CurlCalc(
	.param .u64 CurlCalc_param_0,
	.param .u64 CurlCalc_param_1,
	.param .u64 CurlCalc_param_2,
	.param .u64 CurlCalc_param_3,
	.param .u64 CurlCalc_param_4,
	.param .u64 CurlCalc_param_5,
	.param .u32 CurlCalc_param_6,
	.param .u32 CurlCalc_param_7,
	.param .u32 CurlCalc_param_8,
	.param .u64 CurlCalc_param_9,
	.param .f32 CurlCalc_param_10
)
{
	.reg .pred 	%p<13>;
	.reg .f32 	%f<31>;
	.reg .b32 	%r<45>;
	.reg .f64 	%fd<18>;
	.reg .b64 	%rd<58>;


	ld.param.u64 	%rd9, [CurlCalc_param_0];
	ld.param.u64 	%rd10, [CurlCalc_param_1];
	ld.param.u64 	%rd11, [CurlCalc_param_2];
	ld.param.u64 	%rd12, [CurlCalc_param_3];
	ld.param.u64 	%rd13, [CurlCalc_param_4];
	ld.param.u64 	%rd14, [CurlCalc_param_5];
	ld.param.u32 	%r11, [CurlCalc_param_6];
	ld.param.u32 	%r12, [CurlCalc_param_7];
	ld.param.u32 	%r13, [CurlCalc_param_8];
	ld.param.u64 	%rd15, [CurlCalc_param_9];
	ld.param.f32 	%f1, [CurlCalc_param_10];
	cvta.to.global.u64 	%rd1, %rd15;
	mov.u32 	%r14, %ntid.x;
	mov.u32 	%r15, %ctaid.x;
	mov.u32 	%r16, %tid.x;
	mad.lo.s32 	%r1, %r14, %r15, %r16;
	mov.u32 	%r17, %ntid.y;
	mov.u32 	%r18, %ctaid.y;
	mov.u32 	%r19, %tid.y;
	mad.lo.s32 	%r2, %r17, %r18, %r19;
	mov.u32 	%r20, %ntid.z;
	mov.u32 	%r21, %ctaid.z;
	mov.u32 	%r22, %tid.z;
	mad.lo.s32 	%r3, %r20, %r21, %r22;
	setp.ge.s32	%p1, %r2, %r12;
	setp.ge.s32	%p2, %r1, %r11;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r13;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_9;

	mul.lo.s32 	%r4, %r3, %r12;
	add.s32 	%r23, %r4, %r2;
	mul.lo.s32 	%r5, %r23, %r11;
	add.s32 	%r24, %r5, %r1;
	add.s32 	%r25, %r13, %r3;
	add.s32 	%r26, %r25, -1;
	rem.s32 	%r27, %r26, %r13;
	mad.lo.s32 	%r28, %r27, %r12, %r2;
	mad.lo.s32 	%r6, %r28, %r11, %r1;
	add.s32 	%r29, %r3, 1;
	rem.s32 	%r30, %r29, %r13;
	mad.lo.s32 	%r31, %r30, %r12, %r2;
	mad.lo.s32 	%r7, %r31, %r11, %r1;
	cvt.s64.s32	%rd2, %r24;
	mul.wide.s32 	%rd16, %r24, 4;
	add.s64 	%rd17, %rd1, %rd16;
	ld.global.nc.f32 	%f2, [%rd17];
	setp.eq.f32	%p6, %f2, 0f00000000;
	@%p6 bra 	BB0_9;

	add.s32 	%r32, %r11, %r1;
	add.s32 	%r33, %r32, -1;
	rem.s32 	%r34, %r33, %r11;
	add.s32 	%r35, %r34, %r5;
	add.s32 	%r36, %r1, 1;
	rem.s32 	%r37, %r36, %r11;
	add.s32 	%r8, %r37, %r5;
	add.s32 	%r38, %r12, %r2;
	add.s32 	%r39, %r38, -1;
	rem.s32 	%r40, %r39, %r12;
	add.s32 	%r41, %r40, %r4;
	mad.lo.s32 	%r9, %r41, %r11, %r1;
	add.s32 	%r42, %r2, 1;
	rem.s32 	%r43, %r42, %r12;
	add.s32 	%r44, %r43, %r4;
	mad.lo.s32 	%r10, %r44, %r11, %r1;
	cvt.s64.s32	%rd3, %r35;
	mul.wide.s32 	%rd18, %r35, 4;
	add.s64 	%rd19, %rd1, %rd18;
	ld.global.nc.f32 	%f3, [%rd19];
	setp.eq.f32	%p7, %f3, 0f00000000;
	@%p7 bra 	BB0_9;

	cvt.s64.s32	%rd4, %r8;
	mul.wide.s32 	%rd20, %r8, 4;
	add.s64 	%rd21, %rd1, %rd20;
	ld.global.nc.f32 	%f4, [%rd21];
	setp.eq.f32	%p8, %f4, 0f00000000;
	@%p8 bra 	BB0_9;

	cvt.s64.s32	%rd5, %r9;
	mul.wide.s32 	%rd22, %r9, 4;
	add.s64 	%rd23, %rd1, %rd22;
	ld.global.nc.f32 	%f5, [%rd23];
	setp.eq.f32	%p9, %f5, 0f00000000;
	@%p9 bra 	BB0_9;

	cvt.s64.s32	%rd6, %r10;
	mul.wide.s32 	%rd24, %r10, 4;
	add.s64 	%rd25, %rd1, %rd24;
	ld.global.nc.f32 	%f6, [%rd25];
	setp.eq.f32	%p10, %f6, 0f00000000;
	@%p10 bra 	BB0_9;

	cvt.s64.s32	%rd7, %r6;
	mul.wide.s32 	%rd26, %r6, 4;
	add.s64 	%rd27, %rd1, %rd26;
	ld.global.nc.f32 	%f7, [%rd27];
	setp.eq.f32	%p11, %f7, 0f00000000;
	@%p11 bra 	BB0_9;

	cvt.s64.s32	%rd8, %r7;
	mul.wide.s32 	%rd28, %r7, 4;
	add.s64 	%rd29, %rd1, %rd28;
	ld.global.nc.f32 	%f8, [%rd29];
	setp.eq.f32	%p12, %f8, 0f00000000;
	@%p12 bra 	BB0_9;

	cvta.to.global.u64 	%rd30, %rd14;
	cvta.to.global.u64 	%rd31, %rd13;
	cvta.to.global.u64 	%rd32, %rd12;
	cvta.to.global.u64 	%rd33, %rd11;
	cvta.to.global.u64 	%rd34, %rd10;
	cvta.to.global.u64 	%rd35, %rd9;
	shl.b64 	%rd36, %rd5, 2;
	add.s64 	%rd37, %rd35, %rd36;
	ld.global.nc.f32 	%f9, [%rd37];
	shl.b64 	%rd38, %rd6, 2;
	add.s64 	%rd39, %rd35, %rd38;
	ld.global.nc.f32 	%f10, [%rd39];
	shl.b64 	%rd40, %rd7, 2;
	add.s64 	%rd41, %rd35, %rd40;
	ld.global.nc.f32 	%f11, [%rd41];
	shl.b64 	%rd42, %rd8, 2;
	add.s64 	%rd43, %rd35, %rd42;
	ld.global.nc.f32 	%f12, [%rd43];
	shl.b64 	%rd44, %rd3, 2;
	add.s64 	%rd45, %rd34, %rd44;
	ld.global.nc.f32 	%f13, [%rd45];
	shl.b64 	%rd46, %rd4, 2;
	add.s64 	%rd47, %rd34, %rd46;
	ld.global.nc.f32 	%f14, [%rd47];
	add.s64 	%rd48, %rd33, %rd44;
	ld.global.nc.f32 	%f15, [%rd48];
	add.s64 	%rd49, %rd33, %rd46;
	ld.global.nc.f32 	%f16, [%rd49];
	add.s64 	%rd50, %rd33, %rd38;
	ld.global.nc.f32 	%f17, [%rd50];
	add.s64 	%rd51, %rd33, %rd36;
	ld.global.nc.f32 	%f18, [%rd51];
	sub.f32 	%f19, %f17, %f18;
	cvt.f64.f32	%fd1, %f19;
	cvt.f64.f32	%fd2, %f1;
	add.f64 	%fd3, %fd2, %fd2;
	div.rn.f64 	%fd4, %fd1, %fd3;
	add.s64 	%rd52, %rd34, %rd42;
	ld.global.nc.f32 	%f20, [%rd52];
	add.s64 	%rd53, %rd34, %rd40;
	ld.global.nc.f32 	%f21, [%rd53];
	sub.f32 	%f22, %f20, %f21;
	cvt.f64.f32	%fd5, %f22;
	div.rn.f64 	%fd6, %fd5, %fd3;
	sub.f64 	%fd7, %fd4, %fd6;
	cvt.rn.f32.f64	%f23, %fd7;
	shl.b64 	%rd54, %rd2, 2;
	add.s64 	%rd55, %rd32, %rd54;
	st.global.f32 	[%rd55], %f23;
	sub.f32 	%f24, %f16, %f15;
	cvt.f64.f32	%fd8, %f24;
	div.rn.f64 	%fd9, %fd8, %fd3;
	sub.f32 	%f25, %f12, %f11;
	cvt.f64.f32	%fd10, %f25;
	div.rn.f64 	%fd11, %fd10, %fd3;
	sub.f64 	%fd12, %fd9, %fd11;
	cvt.rn.f32.f64	%f26, %fd12;
	neg.f32 	%f27, %f26;
	add.s64 	%rd56, %rd31, %rd54;
	st.global.f32 	[%rd56], %f27;
	sub.f32 	%f28, %f14, %f13;
	cvt.f64.f32	%fd13, %f28;
	div.rn.f64 	%fd14, %fd13, %fd3;
	sub.f32 	%f29, %f10, %f9;
	cvt.f64.f32	%fd15, %f29;
	div.rn.f64 	%fd16, %fd15, %fd3;
	sub.f64 	%fd17, %fd14, %fd16;
	cvt.rn.f32.f64	%f30, %fd17;
	add.s64 	%rd57, %rd30, %rd54;
	st.global.f32 	[%rd57], %f30;

BB0_9:
	ret;
}


`
   CurlCalc_ptx_50 = `
.version 5.0
.target sm_50
.address_size 64

	// .globl	CurlCalc

.visible .entry CurlCalc(
	.param .u64 CurlCalc_param_0,
	.param .u64 CurlCalc_param_1,
	.param .u64 CurlCalc_param_2,
	.param .u64 CurlCalc_param_3,
	.param .u64 CurlCalc_param_4,
	.param .u64 CurlCalc_param_5,
	.param .u32 CurlCalc_param_6,
	.param .u32 CurlCalc_param_7,
	.param .u32 CurlCalc_param_8,
	.param .u64 CurlCalc_param_9,
	.param .f32 CurlCalc_param_10
)
{
	.reg .pred 	%p<13>;
	.reg .f32 	%f<31>;
	.reg .b32 	%r<45>;
	.reg .f64 	%fd<18>;
	.reg .b64 	%rd<58>;


	ld.param.u64 	%rd9, [CurlCalc_param_0];
	ld.param.u64 	%rd10, [CurlCalc_param_1];
	ld.param.u64 	%rd11, [CurlCalc_param_2];
	ld.param.u64 	%rd12, [CurlCalc_param_3];
	ld.param.u64 	%rd13, [CurlCalc_param_4];
	ld.param.u64 	%rd14, [CurlCalc_param_5];
	ld.param.u32 	%r11, [CurlCalc_param_6];
	ld.param.u32 	%r12, [CurlCalc_param_7];
	ld.param.u32 	%r13, [CurlCalc_param_8];
	ld.param.u64 	%rd15, [CurlCalc_param_9];
	ld.param.f32 	%f1, [CurlCalc_param_10];
	cvta.to.global.u64 	%rd1, %rd15;
	mov.u32 	%r14, %ntid.x;
	mov.u32 	%r15, %ctaid.x;
	mov.u32 	%r16, %tid.x;
	mad.lo.s32 	%r1, %r14, %r15, %r16;
	mov.u32 	%r17, %ntid.y;
	mov.u32 	%r18, %ctaid.y;
	mov.u32 	%r19, %tid.y;
	mad.lo.s32 	%r2, %r17, %r18, %r19;
	mov.u32 	%r20, %ntid.z;
	mov.u32 	%r21, %ctaid.z;
	mov.u32 	%r22, %tid.z;
	mad.lo.s32 	%r3, %r20, %r21, %r22;
	setp.ge.s32	%p1, %r2, %r12;
	setp.ge.s32	%p2, %r1, %r11;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r13;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_9;

	mul.lo.s32 	%r4, %r3, %r12;
	add.s32 	%r23, %r4, %r2;
	mul.lo.s32 	%r5, %r23, %r11;
	add.s32 	%r24, %r5, %r1;
	add.s32 	%r25, %r13, %r3;
	add.s32 	%r26, %r25, -1;
	rem.s32 	%r27, %r26, %r13;
	mad.lo.s32 	%r28, %r27, %r12, %r2;
	mad.lo.s32 	%r6, %r28, %r11, %r1;
	add.s32 	%r29, %r3, 1;
	rem.s32 	%r30, %r29, %r13;
	mad.lo.s32 	%r31, %r30, %r12, %r2;
	mad.lo.s32 	%r7, %r31, %r11, %r1;
	cvt.s64.s32	%rd2, %r24;
	mul.wide.s32 	%rd16, %r24, 4;
	add.s64 	%rd17, %rd1, %rd16;
	ld.global.nc.f32 	%f2, [%rd17];
	setp.eq.f32	%p6, %f2, 0f00000000;
	@%p6 bra 	BB0_9;

	add.s32 	%r32, %r11, %r1;
	add.s32 	%r33, %r32, -1;
	rem.s32 	%r34, %r33, %r11;
	add.s32 	%r35, %r34, %r5;
	add.s32 	%r36, %r1, 1;
	rem.s32 	%r37, %r36, %r11;
	add.s32 	%r8, %r37, %r5;
	add.s32 	%r38, %r12, %r2;
	add.s32 	%r39, %r38, -1;
	rem.s32 	%r40, %r39, %r12;
	add.s32 	%r41, %r40, %r4;
	mad.lo.s32 	%r9, %r41, %r11, %r1;
	add.s32 	%r42, %r2, 1;
	rem.s32 	%r43, %r42, %r12;
	add.s32 	%r44, %r43, %r4;
	mad.lo.s32 	%r10, %r44, %r11, %r1;
	cvt.s64.s32	%rd3, %r35;
	mul.wide.s32 	%rd18, %r35, 4;
	add.s64 	%rd19, %rd1, %rd18;
	ld.global.nc.f32 	%f3, [%rd19];
	setp.eq.f32	%p7, %f3, 0f00000000;
	@%p7 bra 	BB0_9;

	cvt.s64.s32	%rd4, %r8;
	mul.wide.s32 	%rd20, %r8, 4;
	add.s64 	%rd21, %rd1, %rd20;
	ld.global.nc.f32 	%f4, [%rd21];
	setp.eq.f32	%p8, %f4, 0f00000000;
	@%p8 bra 	BB0_9;

	cvt.s64.s32	%rd5, %r9;
	mul.wide.s32 	%rd22, %r9, 4;
	add.s64 	%rd23, %rd1, %rd22;
	ld.global.nc.f32 	%f5, [%rd23];
	setp.eq.f32	%p9, %f5, 0f00000000;
	@%p9 bra 	BB0_9;

	cvt.s64.s32	%rd6, %r10;
	mul.wide.s32 	%rd24, %r10, 4;
	add.s64 	%rd25, %rd1, %rd24;
	ld.global.nc.f32 	%f6, [%rd25];
	setp.eq.f32	%p10, %f6, 0f00000000;
	@%p10 bra 	BB0_9;

	cvt.s64.s32	%rd7, %r6;
	mul.wide.s32 	%rd26, %r6, 4;
	add.s64 	%rd27, %rd1, %rd26;
	ld.global.nc.f32 	%f7, [%rd27];
	setp.eq.f32	%p11, %f7, 0f00000000;
	@%p11 bra 	BB0_9;

	cvt.s64.s32	%rd8, %r7;
	mul.wide.s32 	%rd28, %r7, 4;
	add.s64 	%rd29, %rd1, %rd28;
	ld.global.nc.f32 	%f8, [%rd29];
	setp.eq.f32	%p12, %f8, 0f00000000;
	@%p12 bra 	BB0_9;

	cvta.to.global.u64 	%rd30, %rd14;
	cvta.to.global.u64 	%rd31, %rd13;
	cvta.to.global.u64 	%rd32, %rd12;
	cvta.to.global.u64 	%rd33, %rd11;
	cvta.to.global.u64 	%rd34, %rd10;
	cvta.to.global.u64 	%rd35, %rd9;
	shl.b64 	%rd36, %rd5, 2;
	add.s64 	%rd37, %rd35, %rd36;
	ld.global.nc.f32 	%f9, [%rd37];
	shl.b64 	%rd38, %rd6, 2;
	add.s64 	%rd39, %rd35, %rd38;
	ld.global.nc.f32 	%f10, [%rd39];
	shl.b64 	%rd40, %rd7, 2;
	add.s64 	%rd41, %rd35, %rd40;
	ld.global.nc.f32 	%f11, [%rd41];
	shl.b64 	%rd42, %rd8, 2;
	add.s64 	%rd43, %rd35, %rd42;
	ld.global.nc.f32 	%f12, [%rd43];
	shl.b64 	%rd44, %rd3, 2;
	add.s64 	%rd45, %rd34, %rd44;
	ld.global.nc.f32 	%f13, [%rd45];
	shl.b64 	%rd46, %rd4, 2;
	add.s64 	%rd47, %rd34, %rd46;
	ld.global.nc.f32 	%f14, [%rd47];
	add.s64 	%rd48, %rd33, %rd44;
	ld.global.nc.f32 	%f15, [%rd48];
	add.s64 	%rd49, %rd33, %rd46;
	ld.global.nc.f32 	%f16, [%rd49];
	add.s64 	%rd50, %rd33, %rd38;
	ld.global.nc.f32 	%f17, [%rd50];
	add.s64 	%rd51, %rd33, %rd36;
	ld.global.nc.f32 	%f18, [%rd51];
	sub.f32 	%f19, %f17, %f18;
	cvt.f64.f32	%fd1, %f19;
	cvt.f64.f32	%fd2, %f1;
	add.f64 	%fd3, %fd2, %fd2;
	div.rn.f64 	%fd4, %fd1, %fd3;
	add.s64 	%rd52, %rd34, %rd42;
	ld.global.nc.f32 	%f20, [%rd52];
	add.s64 	%rd53, %rd34, %rd40;
	ld.global.nc.f32 	%f21, [%rd53];
	sub.f32 	%f22, %f20, %f21;
	cvt.f64.f32	%fd5, %f22;
	div.rn.f64 	%fd6, %fd5, %fd3;
	sub.f64 	%fd7, %fd4, %fd6;
	cvt.rn.f32.f64	%f23, %fd7;
	shl.b64 	%rd54, %rd2, 2;
	add.s64 	%rd55, %rd32, %rd54;
	st.global.f32 	[%rd55], %f23;
	sub.f32 	%f24, %f16, %f15;
	cvt.f64.f32	%fd8, %f24;
	div.rn.f64 	%fd9, %fd8, %fd3;
	sub.f32 	%f25, %f12, %f11;
	cvt.f64.f32	%fd10, %f25;
	div.rn.f64 	%fd11, %fd10, %fd3;
	sub.f64 	%fd12, %fd9, %fd11;
	cvt.rn.f32.f64	%f26, %fd12;
	neg.f32 	%f27, %f26;
	add.s64 	%rd56, %rd31, %rd54;
	st.global.f32 	[%rd56], %f27;
	sub.f32 	%f28, %f14, %f13;
	cvt.f64.f32	%fd13, %f28;
	div.rn.f64 	%fd14, %fd13, %fd3;
	sub.f32 	%f29, %f10, %f9;
	cvt.f64.f32	%fd15, %f29;
	div.rn.f64 	%fd16, %fd15, %fd3;
	sub.f64 	%fd17, %fd14, %fd16;
	cvt.rn.f32.f64	%f30, %fd17;
	add.s64 	%rd57, %rd30, %rd54;
	st.global.f32 	[%rd57], %f30;

BB0_9:
	ret;
}


`
   CurlCalc_ptx_52 = `
.version 5.0
.target sm_52
.address_size 64

	// .globl	CurlCalc

.visible .entry CurlCalc(
	.param .u64 CurlCalc_param_0,
	.param .u64 CurlCalc_param_1,
	.param .u64 CurlCalc_param_2,
	.param .u64 CurlCalc_param_3,
	.param .u64 CurlCalc_param_4,
	.param .u64 CurlCalc_param_5,
	.param .u32 CurlCalc_param_6,
	.param .u32 CurlCalc_param_7,
	.param .u32 CurlCalc_param_8,
	.param .u64 CurlCalc_param_9,
	.param .f32 CurlCalc_param_10
)
{
	.reg .pred 	%p<13>;
	.reg .f32 	%f<31>;
	.reg .b32 	%r<45>;
	.reg .f64 	%fd<18>;
	.reg .b64 	%rd<58>;


	ld.param.u64 	%rd9, [CurlCalc_param_0];
	ld.param.u64 	%rd10, [CurlCalc_param_1];
	ld.param.u64 	%rd11, [CurlCalc_param_2];
	ld.param.u64 	%rd12, [CurlCalc_param_3];
	ld.param.u64 	%rd13, [CurlCalc_param_4];
	ld.param.u64 	%rd14, [CurlCalc_param_5];
	ld.param.u32 	%r11, [CurlCalc_param_6];
	ld.param.u32 	%r12, [CurlCalc_param_7];
	ld.param.u32 	%r13, [CurlCalc_param_8];
	ld.param.u64 	%rd15, [CurlCalc_param_9];
	ld.param.f32 	%f1, [CurlCalc_param_10];
	cvta.to.global.u64 	%rd1, %rd15;
	mov.u32 	%r14, %ntid.x;
	mov.u32 	%r15, %ctaid.x;
	mov.u32 	%r16, %tid.x;
	mad.lo.s32 	%r1, %r14, %r15, %r16;
	mov.u32 	%r17, %ntid.y;
	mov.u32 	%r18, %ctaid.y;
	mov.u32 	%r19, %tid.y;
	mad.lo.s32 	%r2, %r17, %r18, %r19;
	mov.u32 	%r20, %ntid.z;
	mov.u32 	%r21, %ctaid.z;
	mov.u32 	%r22, %tid.z;
	mad.lo.s32 	%r3, %r20, %r21, %r22;
	setp.ge.s32	%p1, %r2, %r12;
	setp.ge.s32	%p2, %r1, %r11;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r13;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_9;

	mul.lo.s32 	%r4, %r3, %r12;
	add.s32 	%r23, %r4, %r2;
	mul.lo.s32 	%r5, %r23, %r11;
	add.s32 	%r24, %r5, %r1;
	add.s32 	%r25, %r13, %r3;
	add.s32 	%r26, %r25, -1;
	rem.s32 	%r27, %r26, %r13;
	mad.lo.s32 	%r28, %r27, %r12, %r2;
	mad.lo.s32 	%r6, %r28, %r11, %r1;
	add.s32 	%r29, %r3, 1;
	rem.s32 	%r30, %r29, %r13;
	mad.lo.s32 	%r31, %r30, %r12, %r2;
	mad.lo.s32 	%r7, %r31, %r11, %r1;
	cvt.s64.s32	%rd2, %r24;
	mul.wide.s32 	%rd16, %r24, 4;
	add.s64 	%rd17, %rd1, %rd16;
	ld.global.nc.f32 	%f2, [%rd17];
	setp.eq.f32	%p6, %f2, 0f00000000;
	@%p6 bra 	BB0_9;

	add.s32 	%r32, %r11, %r1;
	add.s32 	%r33, %r32, -1;
	rem.s32 	%r34, %r33, %r11;
	add.s32 	%r35, %r34, %r5;
	add.s32 	%r36, %r1, 1;
	rem.s32 	%r37, %r36, %r11;
	add.s32 	%r8, %r37, %r5;
	add.s32 	%r38, %r12, %r2;
	add.s32 	%r39, %r38, -1;
	rem.s32 	%r40, %r39, %r12;
	add.s32 	%r41, %r40, %r4;
	mad.lo.s32 	%r9, %r41, %r11, %r1;
	add.s32 	%r42, %r2, 1;
	rem.s32 	%r43, %r42, %r12;
	add.s32 	%r44, %r43, %r4;
	mad.lo.s32 	%r10, %r44, %r11, %r1;
	cvt.s64.s32	%rd3, %r35;
	mul.wide.s32 	%rd18, %r35, 4;
	add.s64 	%rd19, %rd1, %rd18;
	ld.global.nc.f32 	%f3, [%rd19];
	setp.eq.f32	%p7, %f3, 0f00000000;
	@%p7 bra 	BB0_9;

	cvt.s64.s32	%rd4, %r8;
	mul.wide.s32 	%rd20, %r8, 4;
	add.s64 	%rd21, %rd1, %rd20;
	ld.global.nc.f32 	%f4, [%rd21];
	setp.eq.f32	%p8, %f4, 0f00000000;
	@%p8 bra 	BB0_9;

	cvt.s64.s32	%rd5, %r9;
	mul.wide.s32 	%rd22, %r9, 4;
	add.s64 	%rd23, %rd1, %rd22;
	ld.global.nc.f32 	%f5, [%rd23];
	setp.eq.f32	%p9, %f5, 0f00000000;
	@%p9 bra 	BB0_9;

	cvt.s64.s32	%rd6, %r10;
	mul.wide.s32 	%rd24, %r10, 4;
	add.s64 	%rd25, %rd1, %rd24;
	ld.global.nc.f32 	%f6, [%rd25];
	setp.eq.f32	%p10, %f6, 0f00000000;
	@%p10 bra 	BB0_9;

	cvt.s64.s32	%rd7, %r6;
	mul.wide.s32 	%rd26, %r6, 4;
	add.s64 	%rd27, %rd1, %rd26;
	ld.global.nc.f32 	%f7, [%rd27];
	setp.eq.f32	%p11, %f7, 0f00000000;
	@%p11 bra 	BB0_9;

	cvt.s64.s32	%rd8, %r7;
	mul.wide.s32 	%rd28, %r7, 4;
	add.s64 	%rd29, %rd1, %rd28;
	ld.global.nc.f32 	%f8, [%rd29];
	setp.eq.f32	%p12, %f8, 0f00000000;
	@%p12 bra 	BB0_9;

	cvta.to.global.u64 	%rd30, %rd14;
	cvta.to.global.u64 	%rd31, %rd13;
	cvta.to.global.u64 	%rd32, %rd12;
	cvta.to.global.u64 	%rd33, %rd11;
	cvta.to.global.u64 	%rd34, %rd10;
	cvta.to.global.u64 	%rd35, %rd9;
	shl.b64 	%rd36, %rd5, 2;
	add.s64 	%rd37, %rd35, %rd36;
	ld.global.nc.f32 	%f9, [%rd37];
	shl.b64 	%rd38, %rd6, 2;
	add.s64 	%rd39, %rd35, %rd38;
	ld.global.nc.f32 	%f10, [%rd39];
	shl.b64 	%rd40, %rd7, 2;
	add.s64 	%rd41, %rd35, %rd40;
	ld.global.nc.f32 	%f11, [%rd41];
	shl.b64 	%rd42, %rd8, 2;
	add.s64 	%rd43, %rd35, %rd42;
	ld.global.nc.f32 	%f12, [%rd43];
	shl.b64 	%rd44, %rd3, 2;
	add.s64 	%rd45, %rd34, %rd44;
	ld.global.nc.f32 	%f13, [%rd45];
	shl.b64 	%rd46, %rd4, 2;
	add.s64 	%rd47, %rd34, %rd46;
	ld.global.nc.f32 	%f14, [%rd47];
	add.s64 	%rd48, %rd33, %rd44;
	ld.global.nc.f32 	%f15, [%rd48];
	add.s64 	%rd49, %rd33, %rd46;
	ld.global.nc.f32 	%f16, [%rd49];
	add.s64 	%rd50, %rd33, %rd38;
	ld.global.nc.f32 	%f17, [%rd50];
	add.s64 	%rd51, %rd33, %rd36;
	ld.global.nc.f32 	%f18, [%rd51];
	sub.f32 	%f19, %f17, %f18;
	cvt.f64.f32	%fd1, %f19;
	cvt.f64.f32	%fd2, %f1;
	add.f64 	%fd3, %fd2, %fd2;
	div.rn.f64 	%fd4, %fd1, %fd3;
	add.s64 	%rd52, %rd34, %rd42;
	ld.global.nc.f32 	%f20, [%rd52];
	add.s64 	%rd53, %rd34, %rd40;
	ld.global.nc.f32 	%f21, [%rd53];
	sub.f32 	%f22, %f20, %f21;
	cvt.f64.f32	%fd5, %f22;
	div.rn.f64 	%fd6, %fd5, %fd3;
	sub.f64 	%fd7, %fd4, %fd6;
	cvt.rn.f32.f64	%f23, %fd7;
	shl.b64 	%rd54, %rd2, 2;
	add.s64 	%rd55, %rd32, %rd54;
	st.global.f32 	[%rd55], %f23;
	sub.f32 	%f24, %f16, %f15;
	cvt.f64.f32	%fd8, %f24;
	div.rn.f64 	%fd9, %fd8, %fd3;
	sub.f32 	%f25, %f12, %f11;
	cvt.f64.f32	%fd10, %f25;
	div.rn.f64 	%fd11, %fd10, %fd3;
	sub.f64 	%fd12, %fd9, %fd11;
	cvt.rn.f32.f64	%f26, %fd12;
	neg.f32 	%f27, %f26;
	add.s64 	%rd56, %rd31, %rd54;
	st.global.f32 	[%rd56], %f27;
	sub.f32 	%f28, %f14, %f13;
	cvt.f64.f32	%fd13, %f28;
	div.rn.f64 	%fd14, %fd13, %fd3;
	sub.f32 	%f29, %f10, %f9;
	cvt.f64.f32	%fd15, %f29;
	div.rn.f64 	%fd16, %fd15, %fd3;
	sub.f64 	%fd17, %fd14, %fd16;
	cvt.rn.f32.f64	%f30, %fd17;
	add.s64 	%rd57, %rd30, %rd54;
	st.global.f32 	[%rd57], %f30;

BB0_9:
	ret;
}


`
   CurlCalc_ptx_53 = `
.version 5.0
.target sm_53
.address_size 64

	// .globl	CurlCalc

.visible .entry CurlCalc(
	.param .u64 CurlCalc_param_0,
	.param .u64 CurlCalc_param_1,
	.param .u64 CurlCalc_param_2,
	.param .u64 CurlCalc_param_3,
	.param .u64 CurlCalc_param_4,
	.param .u64 CurlCalc_param_5,
	.param .u32 CurlCalc_param_6,
	.param .u32 CurlCalc_param_7,
	.param .u32 CurlCalc_param_8,
	.param .u64 CurlCalc_param_9,
	.param .f32 CurlCalc_param_10
)
{
	.reg .pred 	%p<13>;
	.reg .f32 	%f<31>;
	.reg .b32 	%r<45>;
	.reg .f64 	%fd<18>;
	.reg .b64 	%rd<58>;


	ld.param.u64 	%rd9, [CurlCalc_param_0];
	ld.param.u64 	%rd10, [CurlCalc_param_1];
	ld.param.u64 	%rd11, [CurlCalc_param_2];
	ld.param.u64 	%rd12, [CurlCalc_param_3];
	ld.param.u64 	%rd13, [CurlCalc_param_4];
	ld.param.u64 	%rd14, [CurlCalc_param_5];
	ld.param.u32 	%r11, [CurlCalc_param_6];
	ld.param.u32 	%r12, [CurlCalc_param_7];
	ld.param.u32 	%r13, [CurlCalc_param_8];
	ld.param.u64 	%rd15, [CurlCalc_param_9];
	ld.param.f32 	%f1, [CurlCalc_param_10];
	cvta.to.global.u64 	%rd1, %rd15;
	mov.u32 	%r14, %ntid.x;
	mov.u32 	%r15, %ctaid.x;
	mov.u32 	%r16, %tid.x;
	mad.lo.s32 	%r1, %r14, %r15, %r16;
	mov.u32 	%r17, %ntid.y;
	mov.u32 	%r18, %ctaid.y;
	mov.u32 	%r19, %tid.y;
	mad.lo.s32 	%r2, %r17, %r18, %r19;
	mov.u32 	%r20, %ntid.z;
	mov.u32 	%r21, %ctaid.z;
	mov.u32 	%r22, %tid.z;
	mad.lo.s32 	%r3, %r20, %r21, %r22;
	setp.ge.s32	%p1, %r2, %r12;
	setp.ge.s32	%p2, %r1, %r11;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r13;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_9;

	mul.lo.s32 	%r4, %r3, %r12;
	add.s32 	%r23, %r4, %r2;
	mul.lo.s32 	%r5, %r23, %r11;
	add.s32 	%r24, %r5, %r1;
	add.s32 	%r25, %r13, %r3;
	add.s32 	%r26, %r25, -1;
	rem.s32 	%r27, %r26, %r13;
	mad.lo.s32 	%r28, %r27, %r12, %r2;
	mad.lo.s32 	%r6, %r28, %r11, %r1;
	add.s32 	%r29, %r3, 1;
	rem.s32 	%r30, %r29, %r13;
	mad.lo.s32 	%r31, %r30, %r12, %r2;
	mad.lo.s32 	%r7, %r31, %r11, %r1;
	cvt.s64.s32	%rd2, %r24;
	mul.wide.s32 	%rd16, %r24, 4;
	add.s64 	%rd17, %rd1, %rd16;
	ld.global.nc.f32 	%f2, [%rd17];
	setp.eq.f32	%p6, %f2, 0f00000000;
	@%p6 bra 	BB0_9;

	add.s32 	%r32, %r11, %r1;
	add.s32 	%r33, %r32, -1;
	rem.s32 	%r34, %r33, %r11;
	add.s32 	%r35, %r34, %r5;
	add.s32 	%r36, %r1, 1;
	rem.s32 	%r37, %r36, %r11;
	add.s32 	%r8, %r37, %r5;
	add.s32 	%r38, %r12, %r2;
	add.s32 	%r39, %r38, -1;
	rem.s32 	%r40, %r39, %r12;
	add.s32 	%r41, %r40, %r4;
	mad.lo.s32 	%r9, %r41, %r11, %r1;
	add.s32 	%r42, %r2, 1;
	rem.s32 	%r43, %r42, %r12;
	add.s32 	%r44, %r43, %r4;
	mad.lo.s32 	%r10, %r44, %r11, %r1;
	cvt.s64.s32	%rd3, %r35;
	mul.wide.s32 	%rd18, %r35, 4;
	add.s64 	%rd19, %rd1, %rd18;
	ld.global.nc.f32 	%f3, [%rd19];
	setp.eq.f32	%p7, %f3, 0f00000000;
	@%p7 bra 	BB0_9;

	cvt.s64.s32	%rd4, %r8;
	mul.wide.s32 	%rd20, %r8, 4;
	add.s64 	%rd21, %rd1, %rd20;
	ld.global.nc.f32 	%f4, [%rd21];
	setp.eq.f32	%p8, %f4, 0f00000000;
	@%p8 bra 	BB0_9;

	cvt.s64.s32	%rd5, %r9;
	mul.wide.s32 	%rd22, %r9, 4;
	add.s64 	%rd23, %rd1, %rd22;
	ld.global.nc.f32 	%f5, [%rd23];
	setp.eq.f32	%p9, %f5, 0f00000000;
	@%p9 bra 	BB0_9;

	cvt.s64.s32	%rd6, %r10;
	mul.wide.s32 	%rd24, %r10, 4;
	add.s64 	%rd25, %rd1, %rd24;
	ld.global.nc.f32 	%f6, [%rd25];
	setp.eq.f32	%p10, %f6, 0f00000000;
	@%p10 bra 	BB0_9;

	cvt.s64.s32	%rd7, %r6;
	mul.wide.s32 	%rd26, %r6, 4;
	add.s64 	%rd27, %rd1, %rd26;
	ld.global.nc.f32 	%f7, [%rd27];
	setp.eq.f32	%p11, %f7, 0f00000000;
	@%p11 bra 	BB0_9;

	cvt.s64.s32	%rd8, %r7;
	mul.wide.s32 	%rd28, %r7, 4;
	add.s64 	%rd29, %rd1, %rd28;
	ld.global.nc.f32 	%f8, [%rd29];
	setp.eq.f32	%p12, %f8, 0f00000000;
	@%p12 bra 	BB0_9;

	cvta.to.global.u64 	%rd30, %rd14;
	cvta.to.global.u64 	%rd31, %rd13;
	cvta.to.global.u64 	%rd32, %rd12;
	cvta.to.global.u64 	%rd33, %rd11;
	cvta.to.global.u64 	%rd34, %rd10;
	cvta.to.global.u64 	%rd35, %rd9;
	shl.b64 	%rd36, %rd5, 2;
	add.s64 	%rd37, %rd35, %rd36;
	ld.global.nc.f32 	%f9, [%rd37];
	shl.b64 	%rd38, %rd6, 2;
	add.s64 	%rd39, %rd35, %rd38;
	ld.global.nc.f32 	%f10, [%rd39];
	shl.b64 	%rd40, %rd7, 2;
	add.s64 	%rd41, %rd35, %rd40;
	ld.global.nc.f32 	%f11, [%rd41];
	shl.b64 	%rd42, %rd8, 2;
	add.s64 	%rd43, %rd35, %rd42;
	ld.global.nc.f32 	%f12, [%rd43];
	shl.b64 	%rd44, %rd3, 2;
	add.s64 	%rd45, %rd34, %rd44;
	ld.global.nc.f32 	%f13, [%rd45];
	shl.b64 	%rd46, %rd4, 2;
	add.s64 	%rd47, %rd34, %rd46;
	ld.global.nc.f32 	%f14, [%rd47];
	add.s64 	%rd48, %rd33, %rd44;
	ld.global.nc.f32 	%f15, [%rd48];
	add.s64 	%rd49, %rd33, %rd46;
	ld.global.nc.f32 	%f16, [%rd49];
	add.s64 	%rd50, %rd33, %rd38;
	ld.global.nc.f32 	%f17, [%rd50];
	add.s64 	%rd51, %rd33, %rd36;
	ld.global.nc.f32 	%f18, [%rd51];
	sub.f32 	%f19, %f17, %f18;
	cvt.f64.f32	%fd1, %f19;
	cvt.f64.f32	%fd2, %f1;
	add.f64 	%fd3, %fd2, %fd2;
	div.rn.f64 	%fd4, %fd1, %fd3;
	add.s64 	%rd52, %rd34, %rd42;
	ld.global.nc.f32 	%f20, [%rd52];
	add.s64 	%rd53, %rd34, %rd40;
	ld.global.nc.f32 	%f21, [%rd53];
	sub.f32 	%f22, %f20, %f21;
	cvt.f64.f32	%fd5, %f22;
	div.rn.f64 	%fd6, %fd5, %fd3;
	sub.f64 	%fd7, %fd4, %fd6;
	cvt.rn.f32.f64	%f23, %fd7;
	shl.b64 	%rd54, %rd2, 2;
	add.s64 	%rd55, %rd32, %rd54;
	st.global.f32 	[%rd55], %f23;
	sub.f32 	%f24, %f16, %f15;
	cvt.f64.f32	%fd8, %f24;
	div.rn.f64 	%fd9, %fd8, %fd3;
	sub.f32 	%f25, %f12, %f11;
	cvt.f64.f32	%fd10, %f25;
	div.rn.f64 	%fd11, %fd10, %fd3;
	sub.f64 	%fd12, %fd9, %fd11;
	cvt.rn.f32.f64	%f26, %fd12;
	neg.f32 	%f27, %f26;
	add.s64 	%rd56, %rd31, %rd54;
	st.global.f32 	[%rd56], %f27;
	sub.f32 	%f28, %f14, %f13;
	cvt.f64.f32	%fd13, %f28;
	div.rn.f64 	%fd14, %fd13, %fd3;
	sub.f32 	%f29, %f10, %f9;
	cvt.f64.f32	%fd15, %f29;
	div.rn.f64 	%fd16, %fd15, %fd3;
	sub.f64 	%fd17, %fd14, %fd16;
	cvt.rn.f32.f64	%f30, %fd17;
	add.s64 	%rd57, %rd30, %rd54;
	st.global.f32 	[%rd57], %f30;

BB0_9:
	ret;
}


`
 )
