package ext_kernels

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for DivergenceCalc kernel
var DivergenceCalc_code cu.Function

// Stores the arguments for DivergenceCalc kernel invocation
type DivergenceCalc_args_t struct{
	 arg_FieldX unsafe.Pointer
	 arg_FieldY unsafe.Pointer
	 arg_FieldZ unsafe.Pointer
	 arg_divergence unsafe.Pointer
	 arg_Nx int
	 arg_Ny int
	 arg_Nz int
	 arg_includeGeometry unsafe.Pointer
	 arg_cellsize float32
	 argptr [9]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for DivergenceCalc kernel invocation
var DivergenceCalc_args DivergenceCalc_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 DivergenceCalc_args.argptr[0] = unsafe.Pointer(&DivergenceCalc_args.arg_FieldX)
	 DivergenceCalc_args.argptr[1] = unsafe.Pointer(&DivergenceCalc_args.arg_FieldY)
	 DivergenceCalc_args.argptr[2] = unsafe.Pointer(&DivergenceCalc_args.arg_FieldZ)
	 DivergenceCalc_args.argptr[3] = unsafe.Pointer(&DivergenceCalc_args.arg_divergence)
	 DivergenceCalc_args.argptr[4] = unsafe.Pointer(&DivergenceCalc_args.arg_Nx)
	 DivergenceCalc_args.argptr[5] = unsafe.Pointer(&DivergenceCalc_args.arg_Ny)
	 DivergenceCalc_args.argptr[6] = unsafe.Pointer(&DivergenceCalc_args.arg_Nz)
	 DivergenceCalc_args.argptr[7] = unsafe.Pointer(&DivergenceCalc_args.arg_includeGeometry)
	 DivergenceCalc_args.argptr[8] = unsafe.Pointer(&DivergenceCalc_args.arg_cellsize)
	 }

// Wrapper for DivergenceCalc CUDA kernel, asynchronous.
func K_ext_DivergenceCalc_async ( FieldX unsafe.Pointer, FieldY unsafe.Pointer, FieldZ unsafe.Pointer, divergence unsafe.Pointer, Nx int, Ny int, Nz int, includeGeometry unsafe.Pointer, cellsize float32,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("DivergenceCalc")
	}

	DivergenceCalc_args.Lock()
	defer DivergenceCalc_args.Unlock()

	if DivergenceCalc_code == 0{
		DivergenceCalc_code = fatbinLoad(DivergenceCalc_map, "DivergenceCalc")
	}

	 DivergenceCalc_args.arg_FieldX = FieldX
	 DivergenceCalc_args.arg_FieldY = FieldY
	 DivergenceCalc_args.arg_FieldZ = FieldZ
	 DivergenceCalc_args.arg_divergence = divergence
	 DivergenceCalc_args.arg_Nx = Nx
	 DivergenceCalc_args.arg_Ny = Ny
	 DivergenceCalc_args.arg_Nz = Nz
	 DivergenceCalc_args.arg_includeGeometry = includeGeometry
	 DivergenceCalc_args.arg_cellsize = cellsize
	

	args := DivergenceCalc_args.argptr[:]
	cu.LaunchKernel(DivergenceCalc_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("DivergenceCalc")
	}
}

// maps compute capability on PTX code for DivergenceCalc kernel.
var DivergenceCalc_map = map[int]string{ 0: "" ,
20: DivergenceCalc_ptx_20 ,
30: DivergenceCalc_ptx_30 ,
35: DivergenceCalc_ptx_35 ,
50: DivergenceCalc_ptx_50 ,
52: DivergenceCalc_ptx_52 ,
53: DivergenceCalc_ptx_53  }

// DivergenceCalc PTX code for various compute capabilities.
const(
  DivergenceCalc_ptx_20 = `
.version 5.0
.target sm_20
.address_size 64

	// .globl	DivergenceCalc

.visible .entry DivergenceCalc(
	.param .u64 DivergenceCalc_param_0,
	.param .u64 DivergenceCalc_param_1,
	.param .u64 DivergenceCalc_param_2,
	.param .u64 DivergenceCalc_param_3,
	.param .u32 DivergenceCalc_param_4,
	.param .u32 DivergenceCalc_param_5,
	.param .u32 DivergenceCalc_param_6,
	.param .u64 DivergenceCalc_param_7,
	.param .f32 DivergenceCalc_param_8
)
{
	.reg .pred 	%p<13>;
	.reg .f32 	%f<21>;
	.reg .b32 	%r<45>;
	.reg .f64 	%fd<5>;
	.reg .b64 	%rd<46>;


	ld.param.u64 	%rd9, [DivergenceCalc_param_0];
	ld.param.u64 	%rd10, [DivergenceCalc_param_1];
	ld.param.u64 	%rd11, [DivergenceCalc_param_2];
	ld.param.u64 	%rd12, [DivergenceCalc_param_3];
	ld.param.u32 	%r11, [DivergenceCalc_param_4];
	ld.param.u32 	%r12, [DivergenceCalc_param_5];
	ld.param.u32 	%r13, [DivergenceCalc_param_6];
	ld.param.u64 	%rd13, [DivergenceCalc_param_7];
	ld.param.f32 	%f1, [DivergenceCalc_param_8];
	cvta.to.global.u64 	%rd1, %rd13;
	mov.u32 	%r14, %ntid.x;
	mov.u32 	%r15, %ctaid.x;
	mov.u32 	%r16, %tid.x;
	mad.lo.s32 	%r1, %r14, %r15, %r16;
	mov.u32 	%r17, %ntid.y;
	mov.u32 	%r18, %ctaid.y;
	mov.u32 	%r19, %tid.y;
	mad.lo.s32 	%r2, %r17, %r18, %r19;
	mov.u32 	%r20, %ntid.z;
	mov.u32 	%r21, %ctaid.z;
	mov.u32 	%r22, %tid.z;
	mad.lo.s32 	%r3, %r20, %r21, %r22;
	setp.ge.s32	%p1, %r2, %r12;
	setp.ge.s32	%p2, %r1, %r11;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r13;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_9;

	mul.lo.s32 	%r4, %r3, %r12;
	add.s32 	%r23, %r4, %r2;
	mul.lo.s32 	%r5, %r23, %r11;
	add.s32 	%r24, %r5, %r1;
	add.s32 	%r25, %r13, %r3;
	add.s32 	%r26, %r25, -1;
	rem.s32 	%r27, %r26, %r13;
	mad.lo.s32 	%r28, %r27, %r12, %r2;
	mad.lo.s32 	%r6, %r28, %r11, %r1;
	add.s32 	%r29, %r3, 1;
	rem.s32 	%r30, %r29, %r13;
	mad.lo.s32 	%r31, %r30, %r12, %r2;
	mad.lo.s32 	%r7, %r31, %r11, %r1;
	cvt.s64.s32	%rd2, %r24;
	mul.wide.s32 	%rd14, %r24, 4;
	add.s64 	%rd15, %rd1, %rd14;
	ld.global.f32 	%f2, [%rd15];
	setp.eq.f32	%p6, %f2, 0f00000000;
	@%p6 bra 	BB0_9;

	add.s32 	%r32, %r11, %r1;
	add.s32 	%r33, %r32, -1;
	rem.s32 	%r34, %r33, %r11;
	add.s32 	%r35, %r34, %r5;
	add.s32 	%r36, %r1, 1;
	rem.s32 	%r37, %r36, %r11;
	add.s32 	%r8, %r37, %r5;
	add.s32 	%r38, %r12, %r2;
	add.s32 	%r39, %r38, -1;
	rem.s32 	%r40, %r39, %r12;
	add.s32 	%r41, %r40, %r4;
	mad.lo.s32 	%r9, %r41, %r11, %r1;
	add.s32 	%r42, %r2, 1;
	rem.s32 	%r43, %r42, %r12;
	add.s32 	%r44, %r43, %r4;
	mad.lo.s32 	%r10, %r44, %r11, %r1;
	cvt.s64.s32	%rd3, %r35;
	mul.wide.s32 	%rd16, %r35, 4;
	add.s64 	%rd17, %rd1, %rd16;
	ld.global.f32 	%f3, [%rd17];
	setp.eq.f32	%p7, %f3, 0f00000000;
	@%p7 bra 	BB0_9;

	cvt.s64.s32	%rd4, %r8;
	mul.wide.s32 	%rd18, %r8, 4;
	add.s64 	%rd19, %rd1, %rd18;
	ld.global.f32 	%f4, [%rd19];
	setp.eq.f32	%p8, %f4, 0f00000000;
	@%p8 bra 	BB0_9;

	cvt.s64.s32	%rd5, %r9;
	mul.wide.s32 	%rd20, %r9, 4;
	add.s64 	%rd21, %rd1, %rd20;
	ld.global.f32 	%f5, [%rd21];
	setp.eq.f32	%p9, %f5, 0f00000000;
	@%p9 bra 	BB0_9;

	cvt.s64.s32	%rd6, %r10;
	mul.wide.s32 	%rd22, %r10, 4;
	add.s64 	%rd23, %rd1, %rd22;
	ld.global.f32 	%f6, [%rd23];
	setp.eq.f32	%p10, %f6, 0f00000000;
	@%p10 bra 	BB0_9;

	cvt.s64.s32	%rd7, %r6;
	mul.wide.s32 	%rd24, %r6, 4;
	add.s64 	%rd25, %rd1, %rd24;
	ld.global.f32 	%f7, [%rd25];
	setp.eq.f32	%p11, %f7, 0f00000000;
	@%p11 bra 	BB0_9;

	cvt.s64.s32	%rd8, %r7;
	mul.wide.s32 	%rd26, %r7, 4;
	add.s64 	%rd27, %rd1, %rd26;
	ld.global.f32 	%f8, [%rd27];
	setp.eq.f32	%p12, %f8, 0f00000000;
	@%p12 bra 	BB0_9;

	cvta.to.global.u64 	%rd28, %rd12;
	cvta.to.global.u64 	%rd29, %rd11;
	cvta.to.global.u64 	%rd30, %rd9;
	shl.b64 	%rd31, %rd3, 2;
	add.s64 	%rd32, %rd30, %rd31;
	shl.b64 	%rd33, %rd4, 2;
	add.s64 	%rd34, %rd30, %rd33;
	cvta.to.global.u64 	%rd35, %rd10;
	shl.b64 	%rd36, %rd5, 2;
	add.s64 	%rd37, %rd35, %rd36;
	shl.b64 	%rd38, %rd6, 2;
	add.s64 	%rd39, %rd35, %rd38;
	ld.global.f32 	%f9, [%rd39];
	ld.global.f32 	%f10, [%rd34];
	add.f32 	%f11, %f10, %f9;
	shl.b64 	%rd40, %rd8, 2;
	add.s64 	%rd41, %rd29, %rd40;
	ld.global.f32 	%f12, [%rd41];
	add.f32 	%f13, %f11, %f12;
	ld.global.f32 	%f14, [%rd37];
	ld.global.f32 	%f15, [%rd32];
	add.f32 	%f16, %f15, %f14;
	shl.b64 	%rd42, %rd7, 2;
	add.s64 	%rd43, %rd29, %rd42;
	ld.global.f32 	%f17, [%rd43];
	add.f32 	%f18, %f16, %f17;
	sub.f32 	%f19, %f13, %f18;
	cvt.f64.f32	%fd1, %f19;
	cvt.f64.f32	%fd2, %f1;
	add.f64 	%fd3, %fd2, %fd2;
	div.rn.f64 	%fd4, %fd1, %fd3;
	cvt.rn.f32.f64	%f20, %fd4;
	shl.b64 	%rd44, %rd2, 2;
	add.s64 	%rd45, %rd28, %rd44;
	st.global.f32 	[%rd45], %f20;

BB0_9:
	ret;
}


`
   DivergenceCalc_ptx_30 = `
.version 5.0
.target sm_30
.address_size 64

	// .globl	DivergenceCalc

.visible .entry DivergenceCalc(
	.param .u64 DivergenceCalc_param_0,
	.param .u64 DivergenceCalc_param_1,
	.param .u64 DivergenceCalc_param_2,
	.param .u64 DivergenceCalc_param_3,
	.param .u32 DivergenceCalc_param_4,
	.param .u32 DivergenceCalc_param_5,
	.param .u32 DivergenceCalc_param_6,
	.param .u64 DivergenceCalc_param_7,
	.param .f32 DivergenceCalc_param_8
)
{
	.reg .pred 	%p<13>;
	.reg .f32 	%f<21>;
	.reg .b32 	%r<45>;
	.reg .f64 	%fd<5>;
	.reg .b64 	%rd<46>;


	ld.param.u64 	%rd9, [DivergenceCalc_param_0];
	ld.param.u64 	%rd10, [DivergenceCalc_param_1];
	ld.param.u64 	%rd11, [DivergenceCalc_param_2];
	ld.param.u64 	%rd12, [DivergenceCalc_param_3];
	ld.param.u32 	%r11, [DivergenceCalc_param_4];
	ld.param.u32 	%r12, [DivergenceCalc_param_5];
	ld.param.u32 	%r13, [DivergenceCalc_param_6];
	ld.param.u64 	%rd13, [DivergenceCalc_param_7];
	ld.param.f32 	%f1, [DivergenceCalc_param_8];
	cvta.to.global.u64 	%rd1, %rd13;
	mov.u32 	%r14, %ntid.x;
	mov.u32 	%r15, %ctaid.x;
	mov.u32 	%r16, %tid.x;
	mad.lo.s32 	%r1, %r14, %r15, %r16;
	mov.u32 	%r17, %ntid.y;
	mov.u32 	%r18, %ctaid.y;
	mov.u32 	%r19, %tid.y;
	mad.lo.s32 	%r2, %r17, %r18, %r19;
	mov.u32 	%r20, %ntid.z;
	mov.u32 	%r21, %ctaid.z;
	mov.u32 	%r22, %tid.z;
	mad.lo.s32 	%r3, %r20, %r21, %r22;
	setp.ge.s32	%p1, %r2, %r12;
	setp.ge.s32	%p2, %r1, %r11;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r13;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_9;

	mul.lo.s32 	%r4, %r3, %r12;
	add.s32 	%r23, %r4, %r2;
	mul.lo.s32 	%r5, %r23, %r11;
	add.s32 	%r24, %r5, %r1;
	add.s32 	%r25, %r13, %r3;
	add.s32 	%r26, %r25, -1;
	rem.s32 	%r27, %r26, %r13;
	mad.lo.s32 	%r28, %r27, %r12, %r2;
	mad.lo.s32 	%r6, %r28, %r11, %r1;
	add.s32 	%r29, %r3, 1;
	rem.s32 	%r30, %r29, %r13;
	mad.lo.s32 	%r31, %r30, %r12, %r2;
	mad.lo.s32 	%r7, %r31, %r11, %r1;
	cvt.s64.s32	%rd2, %r24;
	mul.wide.s32 	%rd14, %r24, 4;
	add.s64 	%rd15, %rd1, %rd14;
	ld.global.f32 	%f2, [%rd15];
	setp.eq.f32	%p6, %f2, 0f00000000;
	@%p6 bra 	BB0_9;

	add.s32 	%r32, %r11, %r1;
	add.s32 	%r33, %r32, -1;
	rem.s32 	%r34, %r33, %r11;
	add.s32 	%r35, %r34, %r5;
	add.s32 	%r36, %r1, 1;
	rem.s32 	%r37, %r36, %r11;
	add.s32 	%r8, %r37, %r5;
	add.s32 	%r38, %r12, %r2;
	add.s32 	%r39, %r38, -1;
	rem.s32 	%r40, %r39, %r12;
	add.s32 	%r41, %r40, %r4;
	mad.lo.s32 	%r9, %r41, %r11, %r1;
	add.s32 	%r42, %r2, 1;
	rem.s32 	%r43, %r42, %r12;
	add.s32 	%r44, %r43, %r4;
	mad.lo.s32 	%r10, %r44, %r11, %r1;
	cvt.s64.s32	%rd3, %r35;
	mul.wide.s32 	%rd16, %r35, 4;
	add.s64 	%rd17, %rd1, %rd16;
	ld.global.f32 	%f3, [%rd17];
	setp.eq.f32	%p7, %f3, 0f00000000;
	@%p7 bra 	BB0_9;

	cvt.s64.s32	%rd4, %r8;
	mul.wide.s32 	%rd18, %r8, 4;
	add.s64 	%rd19, %rd1, %rd18;
	ld.global.f32 	%f4, [%rd19];
	setp.eq.f32	%p8, %f4, 0f00000000;
	@%p8 bra 	BB0_9;

	cvt.s64.s32	%rd5, %r9;
	mul.wide.s32 	%rd20, %r9, 4;
	add.s64 	%rd21, %rd1, %rd20;
	ld.global.f32 	%f5, [%rd21];
	setp.eq.f32	%p9, %f5, 0f00000000;
	@%p9 bra 	BB0_9;

	cvt.s64.s32	%rd6, %r10;
	mul.wide.s32 	%rd22, %r10, 4;
	add.s64 	%rd23, %rd1, %rd22;
	ld.global.f32 	%f6, [%rd23];
	setp.eq.f32	%p10, %f6, 0f00000000;
	@%p10 bra 	BB0_9;

	cvt.s64.s32	%rd7, %r6;
	mul.wide.s32 	%rd24, %r6, 4;
	add.s64 	%rd25, %rd1, %rd24;
	ld.global.f32 	%f7, [%rd25];
	setp.eq.f32	%p11, %f7, 0f00000000;
	@%p11 bra 	BB0_9;

	cvt.s64.s32	%rd8, %r7;
	mul.wide.s32 	%rd26, %r7, 4;
	add.s64 	%rd27, %rd1, %rd26;
	ld.global.f32 	%f8, [%rd27];
	setp.eq.f32	%p12, %f8, 0f00000000;
	@%p12 bra 	BB0_9;

	cvta.to.global.u64 	%rd28, %rd12;
	cvta.to.global.u64 	%rd29, %rd11;
	cvta.to.global.u64 	%rd30, %rd9;
	shl.b64 	%rd31, %rd3, 2;
	add.s64 	%rd32, %rd30, %rd31;
	shl.b64 	%rd33, %rd4, 2;
	add.s64 	%rd34, %rd30, %rd33;
	cvta.to.global.u64 	%rd35, %rd10;
	shl.b64 	%rd36, %rd5, 2;
	add.s64 	%rd37, %rd35, %rd36;
	shl.b64 	%rd38, %rd6, 2;
	add.s64 	%rd39, %rd35, %rd38;
	ld.global.f32 	%f9, [%rd39];
	ld.global.f32 	%f10, [%rd34];
	add.f32 	%f11, %f10, %f9;
	shl.b64 	%rd40, %rd8, 2;
	add.s64 	%rd41, %rd29, %rd40;
	ld.global.f32 	%f12, [%rd41];
	add.f32 	%f13, %f11, %f12;
	ld.global.f32 	%f14, [%rd37];
	ld.global.f32 	%f15, [%rd32];
	add.f32 	%f16, %f15, %f14;
	shl.b64 	%rd42, %rd7, 2;
	add.s64 	%rd43, %rd29, %rd42;
	ld.global.f32 	%f17, [%rd43];
	add.f32 	%f18, %f16, %f17;
	sub.f32 	%f19, %f13, %f18;
	cvt.f64.f32	%fd1, %f19;
	cvt.f64.f32	%fd2, %f1;
	add.f64 	%fd3, %fd2, %fd2;
	div.rn.f64 	%fd4, %fd1, %fd3;
	cvt.rn.f32.f64	%f20, %fd4;
	shl.b64 	%rd44, %rd2, 2;
	add.s64 	%rd45, %rd28, %rd44;
	st.global.f32 	[%rd45], %f20;

BB0_9:
	ret;
}


`
   DivergenceCalc_ptx_35 = `
.version 5.0
.target sm_35
.address_size 64

	// .globl	DivergenceCalc

.visible .entry DivergenceCalc(
	.param .u64 DivergenceCalc_param_0,
	.param .u64 DivergenceCalc_param_1,
	.param .u64 DivergenceCalc_param_2,
	.param .u64 DivergenceCalc_param_3,
	.param .u32 DivergenceCalc_param_4,
	.param .u32 DivergenceCalc_param_5,
	.param .u32 DivergenceCalc_param_6,
	.param .u64 DivergenceCalc_param_7,
	.param .f32 DivergenceCalc_param_8
)
{
	.reg .pred 	%p<13>;
	.reg .f32 	%f<21>;
	.reg .b32 	%r<45>;
	.reg .f64 	%fd<5>;
	.reg .b64 	%rd<46>;


	ld.param.u64 	%rd9, [DivergenceCalc_param_0];
	ld.param.u64 	%rd10, [DivergenceCalc_param_1];
	ld.param.u64 	%rd11, [DivergenceCalc_param_2];
	ld.param.u64 	%rd12, [DivergenceCalc_param_3];
	ld.param.u32 	%r11, [DivergenceCalc_param_4];
	ld.param.u32 	%r12, [DivergenceCalc_param_5];
	ld.param.u32 	%r13, [DivergenceCalc_param_6];
	ld.param.u64 	%rd13, [DivergenceCalc_param_7];
	ld.param.f32 	%f1, [DivergenceCalc_param_8];
	cvta.to.global.u64 	%rd1, %rd13;
	mov.u32 	%r14, %ntid.x;
	mov.u32 	%r15, %ctaid.x;
	mov.u32 	%r16, %tid.x;
	mad.lo.s32 	%r1, %r14, %r15, %r16;
	mov.u32 	%r17, %ntid.y;
	mov.u32 	%r18, %ctaid.y;
	mov.u32 	%r19, %tid.y;
	mad.lo.s32 	%r2, %r17, %r18, %r19;
	mov.u32 	%r20, %ntid.z;
	mov.u32 	%r21, %ctaid.z;
	mov.u32 	%r22, %tid.z;
	mad.lo.s32 	%r3, %r20, %r21, %r22;
	setp.ge.s32	%p1, %r2, %r12;
	setp.ge.s32	%p2, %r1, %r11;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r13;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_9;

	mul.lo.s32 	%r4, %r3, %r12;
	add.s32 	%r23, %r4, %r2;
	mul.lo.s32 	%r5, %r23, %r11;
	add.s32 	%r24, %r5, %r1;
	add.s32 	%r25, %r13, %r3;
	add.s32 	%r26, %r25, -1;
	rem.s32 	%r27, %r26, %r13;
	mad.lo.s32 	%r28, %r27, %r12, %r2;
	mad.lo.s32 	%r6, %r28, %r11, %r1;
	add.s32 	%r29, %r3, 1;
	rem.s32 	%r30, %r29, %r13;
	mad.lo.s32 	%r31, %r30, %r12, %r2;
	mad.lo.s32 	%r7, %r31, %r11, %r1;
	cvt.s64.s32	%rd2, %r24;
	mul.wide.s32 	%rd14, %r24, 4;
	add.s64 	%rd15, %rd1, %rd14;
	ld.global.nc.f32 	%f2, [%rd15];
	setp.eq.f32	%p6, %f2, 0f00000000;
	@%p6 bra 	BB0_9;

	add.s32 	%r32, %r11, %r1;
	add.s32 	%r33, %r32, -1;
	rem.s32 	%r34, %r33, %r11;
	add.s32 	%r35, %r34, %r5;
	add.s32 	%r36, %r1, 1;
	rem.s32 	%r37, %r36, %r11;
	add.s32 	%r8, %r37, %r5;
	add.s32 	%r38, %r12, %r2;
	add.s32 	%r39, %r38, -1;
	rem.s32 	%r40, %r39, %r12;
	add.s32 	%r41, %r40, %r4;
	mad.lo.s32 	%r9, %r41, %r11, %r1;
	add.s32 	%r42, %r2, 1;
	rem.s32 	%r43, %r42, %r12;
	add.s32 	%r44, %r43, %r4;
	mad.lo.s32 	%r10, %r44, %r11, %r1;
	cvt.s64.s32	%rd3, %r35;
	mul.wide.s32 	%rd16, %r35, 4;
	add.s64 	%rd17, %rd1, %rd16;
	ld.global.nc.f32 	%f3, [%rd17];
	setp.eq.f32	%p7, %f3, 0f00000000;
	@%p7 bra 	BB0_9;

	cvt.s64.s32	%rd4, %r8;
	mul.wide.s32 	%rd18, %r8, 4;
	add.s64 	%rd19, %rd1, %rd18;
	ld.global.nc.f32 	%f4, [%rd19];
	setp.eq.f32	%p8, %f4, 0f00000000;
	@%p8 bra 	BB0_9;

	cvt.s64.s32	%rd5, %r9;
	mul.wide.s32 	%rd20, %r9, 4;
	add.s64 	%rd21, %rd1, %rd20;
	ld.global.nc.f32 	%f5, [%rd21];
	setp.eq.f32	%p9, %f5, 0f00000000;
	@%p9 bra 	BB0_9;

	cvt.s64.s32	%rd6, %r10;
	mul.wide.s32 	%rd22, %r10, 4;
	add.s64 	%rd23, %rd1, %rd22;
	ld.global.nc.f32 	%f6, [%rd23];
	setp.eq.f32	%p10, %f6, 0f00000000;
	@%p10 bra 	BB0_9;

	cvt.s64.s32	%rd7, %r6;
	mul.wide.s32 	%rd24, %r6, 4;
	add.s64 	%rd25, %rd1, %rd24;
	ld.global.nc.f32 	%f7, [%rd25];
	setp.eq.f32	%p11, %f7, 0f00000000;
	@%p11 bra 	BB0_9;

	cvt.s64.s32	%rd8, %r7;
	mul.wide.s32 	%rd26, %r7, 4;
	add.s64 	%rd27, %rd1, %rd26;
	ld.global.nc.f32 	%f8, [%rd27];
	setp.eq.f32	%p12, %f8, 0f00000000;
	@%p12 bra 	BB0_9;

	cvta.to.global.u64 	%rd28, %rd12;
	cvta.to.global.u64 	%rd29, %rd11;
	cvta.to.global.u64 	%rd30, %rd10;
	cvta.to.global.u64 	%rd31, %rd9;
	shl.b64 	%rd32, %rd3, 2;
	add.s64 	%rd33, %rd31, %rd32;
	shl.b64 	%rd34, %rd6, 2;
	add.s64 	%rd35, %rd30, %rd34;
	ld.global.nc.f32 	%f9, [%rd35];
	shl.b64 	%rd36, %rd4, 2;
	add.s64 	%rd37, %rd31, %rd36;
	ld.global.nc.f32 	%f10, [%rd37];
	add.f32 	%f11, %f10, %f9;
	shl.b64 	%rd38, %rd8, 2;
	add.s64 	%rd39, %rd29, %rd38;
	ld.global.nc.f32 	%f12, [%rd39];
	add.f32 	%f13, %f11, %f12;
	shl.b64 	%rd40, %rd5, 2;
	add.s64 	%rd41, %rd30, %rd40;
	ld.global.nc.f32 	%f14, [%rd41];
	ld.global.nc.f32 	%f15, [%rd33];
	add.f32 	%f16, %f15, %f14;
	shl.b64 	%rd42, %rd7, 2;
	add.s64 	%rd43, %rd29, %rd42;
	ld.global.nc.f32 	%f17, [%rd43];
	add.f32 	%f18, %f16, %f17;
	sub.f32 	%f19, %f13, %f18;
	cvt.f64.f32	%fd1, %f19;
	cvt.f64.f32	%fd2, %f1;
	add.f64 	%fd3, %fd2, %fd2;
	div.rn.f64 	%fd4, %fd1, %fd3;
	cvt.rn.f32.f64	%f20, %fd4;
	shl.b64 	%rd44, %rd2, 2;
	add.s64 	%rd45, %rd28, %rd44;
	st.global.f32 	[%rd45], %f20;

BB0_9:
	ret;
}


`
   DivergenceCalc_ptx_50 = `
.version 5.0
.target sm_50
.address_size 64

	// .globl	DivergenceCalc

.visible .entry DivergenceCalc(
	.param .u64 DivergenceCalc_param_0,
	.param .u64 DivergenceCalc_param_1,
	.param .u64 DivergenceCalc_param_2,
	.param .u64 DivergenceCalc_param_3,
	.param .u32 DivergenceCalc_param_4,
	.param .u32 DivergenceCalc_param_5,
	.param .u32 DivergenceCalc_param_6,
	.param .u64 DivergenceCalc_param_7,
	.param .f32 DivergenceCalc_param_8
)
{
	.reg .pred 	%p<13>;
	.reg .f32 	%f<21>;
	.reg .b32 	%r<45>;
	.reg .f64 	%fd<5>;
	.reg .b64 	%rd<46>;


	ld.param.u64 	%rd9, [DivergenceCalc_param_0];
	ld.param.u64 	%rd10, [DivergenceCalc_param_1];
	ld.param.u64 	%rd11, [DivergenceCalc_param_2];
	ld.param.u64 	%rd12, [DivergenceCalc_param_3];
	ld.param.u32 	%r11, [DivergenceCalc_param_4];
	ld.param.u32 	%r12, [DivergenceCalc_param_5];
	ld.param.u32 	%r13, [DivergenceCalc_param_6];
	ld.param.u64 	%rd13, [DivergenceCalc_param_7];
	ld.param.f32 	%f1, [DivergenceCalc_param_8];
	cvta.to.global.u64 	%rd1, %rd13;
	mov.u32 	%r14, %ntid.x;
	mov.u32 	%r15, %ctaid.x;
	mov.u32 	%r16, %tid.x;
	mad.lo.s32 	%r1, %r14, %r15, %r16;
	mov.u32 	%r17, %ntid.y;
	mov.u32 	%r18, %ctaid.y;
	mov.u32 	%r19, %tid.y;
	mad.lo.s32 	%r2, %r17, %r18, %r19;
	mov.u32 	%r20, %ntid.z;
	mov.u32 	%r21, %ctaid.z;
	mov.u32 	%r22, %tid.z;
	mad.lo.s32 	%r3, %r20, %r21, %r22;
	setp.ge.s32	%p1, %r2, %r12;
	setp.ge.s32	%p2, %r1, %r11;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r13;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_9;

	mul.lo.s32 	%r4, %r3, %r12;
	add.s32 	%r23, %r4, %r2;
	mul.lo.s32 	%r5, %r23, %r11;
	add.s32 	%r24, %r5, %r1;
	add.s32 	%r25, %r13, %r3;
	add.s32 	%r26, %r25, -1;
	rem.s32 	%r27, %r26, %r13;
	mad.lo.s32 	%r28, %r27, %r12, %r2;
	mad.lo.s32 	%r6, %r28, %r11, %r1;
	add.s32 	%r29, %r3, 1;
	rem.s32 	%r30, %r29, %r13;
	mad.lo.s32 	%r31, %r30, %r12, %r2;
	mad.lo.s32 	%r7, %r31, %r11, %r1;
	cvt.s64.s32	%rd2, %r24;
	mul.wide.s32 	%rd14, %r24, 4;
	add.s64 	%rd15, %rd1, %rd14;
	ld.global.nc.f32 	%f2, [%rd15];
	setp.eq.f32	%p6, %f2, 0f00000000;
	@%p6 bra 	BB0_9;

	add.s32 	%r32, %r11, %r1;
	add.s32 	%r33, %r32, -1;
	rem.s32 	%r34, %r33, %r11;
	add.s32 	%r35, %r34, %r5;
	add.s32 	%r36, %r1, 1;
	rem.s32 	%r37, %r36, %r11;
	add.s32 	%r8, %r37, %r5;
	add.s32 	%r38, %r12, %r2;
	add.s32 	%r39, %r38, -1;
	rem.s32 	%r40, %r39, %r12;
	add.s32 	%r41, %r40, %r4;
	mad.lo.s32 	%r9, %r41, %r11, %r1;
	add.s32 	%r42, %r2, 1;
	rem.s32 	%r43, %r42, %r12;
	add.s32 	%r44, %r43, %r4;
	mad.lo.s32 	%r10, %r44, %r11, %r1;
	cvt.s64.s32	%rd3, %r35;
	mul.wide.s32 	%rd16, %r35, 4;
	add.s64 	%rd17, %rd1, %rd16;
	ld.global.nc.f32 	%f3, [%rd17];
	setp.eq.f32	%p7, %f3, 0f00000000;
	@%p7 bra 	BB0_9;

	cvt.s64.s32	%rd4, %r8;
	mul.wide.s32 	%rd18, %r8, 4;
	add.s64 	%rd19, %rd1, %rd18;
	ld.global.nc.f32 	%f4, [%rd19];
	setp.eq.f32	%p8, %f4, 0f00000000;
	@%p8 bra 	BB0_9;

	cvt.s64.s32	%rd5, %r9;
	mul.wide.s32 	%rd20, %r9, 4;
	add.s64 	%rd21, %rd1, %rd20;
	ld.global.nc.f32 	%f5, [%rd21];
	setp.eq.f32	%p9, %f5, 0f00000000;
	@%p9 bra 	BB0_9;

	cvt.s64.s32	%rd6, %r10;
	mul.wide.s32 	%rd22, %r10, 4;
	add.s64 	%rd23, %rd1, %rd22;
	ld.global.nc.f32 	%f6, [%rd23];
	setp.eq.f32	%p10, %f6, 0f00000000;
	@%p10 bra 	BB0_9;

	cvt.s64.s32	%rd7, %r6;
	mul.wide.s32 	%rd24, %r6, 4;
	add.s64 	%rd25, %rd1, %rd24;
	ld.global.nc.f32 	%f7, [%rd25];
	setp.eq.f32	%p11, %f7, 0f00000000;
	@%p11 bra 	BB0_9;

	cvt.s64.s32	%rd8, %r7;
	mul.wide.s32 	%rd26, %r7, 4;
	add.s64 	%rd27, %rd1, %rd26;
	ld.global.nc.f32 	%f8, [%rd27];
	setp.eq.f32	%p12, %f8, 0f00000000;
	@%p12 bra 	BB0_9;

	cvta.to.global.u64 	%rd28, %rd12;
	cvta.to.global.u64 	%rd29, %rd11;
	cvta.to.global.u64 	%rd30, %rd10;
	cvta.to.global.u64 	%rd31, %rd9;
	shl.b64 	%rd32, %rd3, 2;
	add.s64 	%rd33, %rd31, %rd32;
	shl.b64 	%rd34, %rd6, 2;
	add.s64 	%rd35, %rd30, %rd34;
	ld.global.nc.f32 	%f9, [%rd35];
	shl.b64 	%rd36, %rd4, 2;
	add.s64 	%rd37, %rd31, %rd36;
	ld.global.nc.f32 	%f10, [%rd37];
	add.f32 	%f11, %f10, %f9;
	shl.b64 	%rd38, %rd8, 2;
	add.s64 	%rd39, %rd29, %rd38;
	ld.global.nc.f32 	%f12, [%rd39];
	add.f32 	%f13, %f11, %f12;
	shl.b64 	%rd40, %rd5, 2;
	add.s64 	%rd41, %rd30, %rd40;
	ld.global.nc.f32 	%f14, [%rd41];
	ld.global.nc.f32 	%f15, [%rd33];
	add.f32 	%f16, %f15, %f14;
	shl.b64 	%rd42, %rd7, 2;
	add.s64 	%rd43, %rd29, %rd42;
	ld.global.nc.f32 	%f17, [%rd43];
	add.f32 	%f18, %f16, %f17;
	sub.f32 	%f19, %f13, %f18;
	cvt.f64.f32	%fd1, %f19;
	cvt.f64.f32	%fd2, %f1;
	add.f64 	%fd3, %fd2, %fd2;
	div.rn.f64 	%fd4, %fd1, %fd3;
	cvt.rn.f32.f64	%f20, %fd4;
	shl.b64 	%rd44, %rd2, 2;
	add.s64 	%rd45, %rd28, %rd44;
	st.global.f32 	[%rd45], %f20;

BB0_9:
	ret;
}


`
   DivergenceCalc_ptx_52 = `
.version 5.0
.target sm_52
.address_size 64

	// .globl	DivergenceCalc

.visible .entry DivergenceCalc(
	.param .u64 DivergenceCalc_param_0,
	.param .u64 DivergenceCalc_param_1,
	.param .u64 DivergenceCalc_param_2,
	.param .u64 DivergenceCalc_param_3,
	.param .u32 DivergenceCalc_param_4,
	.param .u32 DivergenceCalc_param_5,
	.param .u32 DivergenceCalc_param_6,
	.param .u64 DivergenceCalc_param_7,
	.param .f32 DivergenceCalc_param_8
)
{
	.reg .pred 	%p<13>;
	.reg .f32 	%f<21>;
	.reg .b32 	%r<45>;
	.reg .f64 	%fd<5>;
	.reg .b64 	%rd<46>;


	ld.param.u64 	%rd9, [DivergenceCalc_param_0];
	ld.param.u64 	%rd10, [DivergenceCalc_param_1];
	ld.param.u64 	%rd11, [DivergenceCalc_param_2];
	ld.param.u64 	%rd12, [DivergenceCalc_param_3];
	ld.param.u32 	%r11, [DivergenceCalc_param_4];
	ld.param.u32 	%r12, [DivergenceCalc_param_5];
	ld.param.u32 	%r13, [DivergenceCalc_param_6];
	ld.param.u64 	%rd13, [DivergenceCalc_param_7];
	ld.param.f32 	%f1, [DivergenceCalc_param_8];
	cvta.to.global.u64 	%rd1, %rd13;
	mov.u32 	%r14, %ntid.x;
	mov.u32 	%r15, %ctaid.x;
	mov.u32 	%r16, %tid.x;
	mad.lo.s32 	%r1, %r14, %r15, %r16;
	mov.u32 	%r17, %ntid.y;
	mov.u32 	%r18, %ctaid.y;
	mov.u32 	%r19, %tid.y;
	mad.lo.s32 	%r2, %r17, %r18, %r19;
	mov.u32 	%r20, %ntid.z;
	mov.u32 	%r21, %ctaid.z;
	mov.u32 	%r22, %tid.z;
	mad.lo.s32 	%r3, %r20, %r21, %r22;
	setp.ge.s32	%p1, %r2, %r12;
	setp.ge.s32	%p2, %r1, %r11;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r13;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_9;

	mul.lo.s32 	%r4, %r3, %r12;
	add.s32 	%r23, %r4, %r2;
	mul.lo.s32 	%r5, %r23, %r11;
	add.s32 	%r24, %r5, %r1;
	add.s32 	%r25, %r13, %r3;
	add.s32 	%r26, %r25, -1;
	rem.s32 	%r27, %r26, %r13;
	mad.lo.s32 	%r28, %r27, %r12, %r2;
	mad.lo.s32 	%r6, %r28, %r11, %r1;
	add.s32 	%r29, %r3, 1;
	rem.s32 	%r30, %r29, %r13;
	mad.lo.s32 	%r31, %r30, %r12, %r2;
	mad.lo.s32 	%r7, %r31, %r11, %r1;
	cvt.s64.s32	%rd2, %r24;
	mul.wide.s32 	%rd14, %r24, 4;
	add.s64 	%rd15, %rd1, %rd14;
	ld.global.nc.f32 	%f2, [%rd15];
	setp.eq.f32	%p6, %f2, 0f00000000;
	@%p6 bra 	BB0_9;

	add.s32 	%r32, %r11, %r1;
	add.s32 	%r33, %r32, -1;
	rem.s32 	%r34, %r33, %r11;
	add.s32 	%r35, %r34, %r5;
	add.s32 	%r36, %r1, 1;
	rem.s32 	%r37, %r36, %r11;
	add.s32 	%r8, %r37, %r5;
	add.s32 	%r38, %r12, %r2;
	add.s32 	%r39, %r38, -1;
	rem.s32 	%r40, %r39, %r12;
	add.s32 	%r41, %r40, %r4;
	mad.lo.s32 	%r9, %r41, %r11, %r1;
	add.s32 	%r42, %r2, 1;
	rem.s32 	%r43, %r42, %r12;
	add.s32 	%r44, %r43, %r4;
	mad.lo.s32 	%r10, %r44, %r11, %r1;
	cvt.s64.s32	%rd3, %r35;
	mul.wide.s32 	%rd16, %r35, 4;
	add.s64 	%rd17, %rd1, %rd16;
	ld.global.nc.f32 	%f3, [%rd17];
	setp.eq.f32	%p7, %f3, 0f00000000;
	@%p7 bra 	BB0_9;

	cvt.s64.s32	%rd4, %r8;
	mul.wide.s32 	%rd18, %r8, 4;
	add.s64 	%rd19, %rd1, %rd18;
	ld.global.nc.f32 	%f4, [%rd19];
	setp.eq.f32	%p8, %f4, 0f00000000;
	@%p8 bra 	BB0_9;

	cvt.s64.s32	%rd5, %r9;
	mul.wide.s32 	%rd20, %r9, 4;
	add.s64 	%rd21, %rd1, %rd20;
	ld.global.nc.f32 	%f5, [%rd21];
	setp.eq.f32	%p9, %f5, 0f00000000;
	@%p9 bra 	BB0_9;

	cvt.s64.s32	%rd6, %r10;
	mul.wide.s32 	%rd22, %r10, 4;
	add.s64 	%rd23, %rd1, %rd22;
	ld.global.nc.f32 	%f6, [%rd23];
	setp.eq.f32	%p10, %f6, 0f00000000;
	@%p10 bra 	BB0_9;

	cvt.s64.s32	%rd7, %r6;
	mul.wide.s32 	%rd24, %r6, 4;
	add.s64 	%rd25, %rd1, %rd24;
	ld.global.nc.f32 	%f7, [%rd25];
	setp.eq.f32	%p11, %f7, 0f00000000;
	@%p11 bra 	BB0_9;

	cvt.s64.s32	%rd8, %r7;
	mul.wide.s32 	%rd26, %r7, 4;
	add.s64 	%rd27, %rd1, %rd26;
	ld.global.nc.f32 	%f8, [%rd27];
	setp.eq.f32	%p12, %f8, 0f00000000;
	@%p12 bra 	BB0_9;

	cvta.to.global.u64 	%rd28, %rd12;
	cvta.to.global.u64 	%rd29, %rd11;
	cvta.to.global.u64 	%rd30, %rd10;
	cvta.to.global.u64 	%rd31, %rd9;
	shl.b64 	%rd32, %rd3, 2;
	add.s64 	%rd33, %rd31, %rd32;
	shl.b64 	%rd34, %rd6, 2;
	add.s64 	%rd35, %rd30, %rd34;
	ld.global.nc.f32 	%f9, [%rd35];
	shl.b64 	%rd36, %rd4, 2;
	add.s64 	%rd37, %rd31, %rd36;
	ld.global.nc.f32 	%f10, [%rd37];
	add.f32 	%f11, %f10, %f9;
	shl.b64 	%rd38, %rd8, 2;
	add.s64 	%rd39, %rd29, %rd38;
	ld.global.nc.f32 	%f12, [%rd39];
	add.f32 	%f13, %f11, %f12;
	shl.b64 	%rd40, %rd5, 2;
	add.s64 	%rd41, %rd30, %rd40;
	ld.global.nc.f32 	%f14, [%rd41];
	ld.global.nc.f32 	%f15, [%rd33];
	add.f32 	%f16, %f15, %f14;
	shl.b64 	%rd42, %rd7, 2;
	add.s64 	%rd43, %rd29, %rd42;
	ld.global.nc.f32 	%f17, [%rd43];
	add.f32 	%f18, %f16, %f17;
	sub.f32 	%f19, %f13, %f18;
	cvt.f64.f32	%fd1, %f19;
	cvt.f64.f32	%fd2, %f1;
	add.f64 	%fd3, %fd2, %fd2;
	div.rn.f64 	%fd4, %fd1, %fd3;
	cvt.rn.f32.f64	%f20, %fd4;
	shl.b64 	%rd44, %rd2, 2;
	add.s64 	%rd45, %rd28, %rd44;
	st.global.f32 	[%rd45], %f20;

BB0_9:
	ret;
}


`
   DivergenceCalc_ptx_53 = `
.version 5.0
.target sm_53
.address_size 64

	// .globl	DivergenceCalc

.visible .entry DivergenceCalc(
	.param .u64 DivergenceCalc_param_0,
	.param .u64 DivergenceCalc_param_1,
	.param .u64 DivergenceCalc_param_2,
	.param .u64 DivergenceCalc_param_3,
	.param .u32 DivergenceCalc_param_4,
	.param .u32 DivergenceCalc_param_5,
	.param .u32 DivergenceCalc_param_6,
	.param .u64 DivergenceCalc_param_7,
	.param .f32 DivergenceCalc_param_8
)
{
	.reg .pred 	%p<13>;
	.reg .f32 	%f<21>;
	.reg .b32 	%r<45>;
	.reg .f64 	%fd<5>;
	.reg .b64 	%rd<46>;


	ld.param.u64 	%rd9, [DivergenceCalc_param_0];
	ld.param.u64 	%rd10, [DivergenceCalc_param_1];
	ld.param.u64 	%rd11, [DivergenceCalc_param_2];
	ld.param.u64 	%rd12, [DivergenceCalc_param_3];
	ld.param.u32 	%r11, [DivergenceCalc_param_4];
	ld.param.u32 	%r12, [DivergenceCalc_param_5];
	ld.param.u32 	%r13, [DivergenceCalc_param_6];
	ld.param.u64 	%rd13, [DivergenceCalc_param_7];
	ld.param.f32 	%f1, [DivergenceCalc_param_8];
	cvta.to.global.u64 	%rd1, %rd13;
	mov.u32 	%r14, %ntid.x;
	mov.u32 	%r15, %ctaid.x;
	mov.u32 	%r16, %tid.x;
	mad.lo.s32 	%r1, %r14, %r15, %r16;
	mov.u32 	%r17, %ntid.y;
	mov.u32 	%r18, %ctaid.y;
	mov.u32 	%r19, %tid.y;
	mad.lo.s32 	%r2, %r17, %r18, %r19;
	mov.u32 	%r20, %ntid.z;
	mov.u32 	%r21, %ctaid.z;
	mov.u32 	%r22, %tid.z;
	mad.lo.s32 	%r3, %r20, %r21, %r22;
	setp.ge.s32	%p1, %r2, %r12;
	setp.ge.s32	%p2, %r1, %r11;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r13;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_9;

	mul.lo.s32 	%r4, %r3, %r12;
	add.s32 	%r23, %r4, %r2;
	mul.lo.s32 	%r5, %r23, %r11;
	add.s32 	%r24, %r5, %r1;
	add.s32 	%r25, %r13, %r3;
	add.s32 	%r26, %r25, -1;
	rem.s32 	%r27, %r26, %r13;
	mad.lo.s32 	%r28, %r27, %r12, %r2;
	mad.lo.s32 	%r6, %r28, %r11, %r1;
	add.s32 	%r29, %r3, 1;
	rem.s32 	%r30, %r29, %r13;
	mad.lo.s32 	%r31, %r30, %r12, %r2;
	mad.lo.s32 	%r7, %r31, %r11, %r1;
	cvt.s64.s32	%rd2, %r24;
	mul.wide.s32 	%rd14, %r24, 4;
	add.s64 	%rd15, %rd1, %rd14;
	ld.global.nc.f32 	%f2, [%rd15];
	setp.eq.f32	%p6, %f2, 0f00000000;
	@%p6 bra 	BB0_9;

	add.s32 	%r32, %r11, %r1;
	add.s32 	%r33, %r32, -1;
	rem.s32 	%r34, %r33, %r11;
	add.s32 	%r35, %r34, %r5;
	add.s32 	%r36, %r1, 1;
	rem.s32 	%r37, %r36, %r11;
	add.s32 	%r8, %r37, %r5;
	add.s32 	%r38, %r12, %r2;
	add.s32 	%r39, %r38, -1;
	rem.s32 	%r40, %r39, %r12;
	add.s32 	%r41, %r40, %r4;
	mad.lo.s32 	%r9, %r41, %r11, %r1;
	add.s32 	%r42, %r2, 1;
	rem.s32 	%r43, %r42, %r12;
	add.s32 	%r44, %r43, %r4;
	mad.lo.s32 	%r10, %r44, %r11, %r1;
	cvt.s64.s32	%rd3, %r35;
	mul.wide.s32 	%rd16, %r35, 4;
	add.s64 	%rd17, %rd1, %rd16;
	ld.global.nc.f32 	%f3, [%rd17];
	setp.eq.f32	%p7, %f3, 0f00000000;
	@%p7 bra 	BB0_9;

	cvt.s64.s32	%rd4, %r8;
	mul.wide.s32 	%rd18, %r8, 4;
	add.s64 	%rd19, %rd1, %rd18;
	ld.global.nc.f32 	%f4, [%rd19];
	setp.eq.f32	%p8, %f4, 0f00000000;
	@%p8 bra 	BB0_9;

	cvt.s64.s32	%rd5, %r9;
	mul.wide.s32 	%rd20, %r9, 4;
	add.s64 	%rd21, %rd1, %rd20;
	ld.global.nc.f32 	%f5, [%rd21];
	setp.eq.f32	%p9, %f5, 0f00000000;
	@%p9 bra 	BB0_9;

	cvt.s64.s32	%rd6, %r10;
	mul.wide.s32 	%rd22, %r10, 4;
	add.s64 	%rd23, %rd1, %rd22;
	ld.global.nc.f32 	%f6, [%rd23];
	setp.eq.f32	%p10, %f6, 0f00000000;
	@%p10 bra 	BB0_9;

	cvt.s64.s32	%rd7, %r6;
	mul.wide.s32 	%rd24, %r6, 4;
	add.s64 	%rd25, %rd1, %rd24;
	ld.global.nc.f32 	%f7, [%rd25];
	setp.eq.f32	%p11, %f7, 0f00000000;
	@%p11 bra 	BB0_9;

	cvt.s64.s32	%rd8, %r7;
	mul.wide.s32 	%rd26, %r7, 4;
	add.s64 	%rd27, %rd1, %rd26;
	ld.global.nc.f32 	%f8, [%rd27];
	setp.eq.f32	%p12, %f8, 0f00000000;
	@%p12 bra 	BB0_9;

	cvta.to.global.u64 	%rd28, %rd12;
	cvta.to.global.u64 	%rd29, %rd11;
	cvta.to.global.u64 	%rd30, %rd10;
	cvta.to.global.u64 	%rd31, %rd9;
	shl.b64 	%rd32, %rd3, 2;
	add.s64 	%rd33, %rd31, %rd32;
	shl.b64 	%rd34, %rd6, 2;
	add.s64 	%rd35, %rd30, %rd34;
	ld.global.nc.f32 	%f9, [%rd35];
	shl.b64 	%rd36, %rd4, 2;
	add.s64 	%rd37, %rd31, %rd36;
	ld.global.nc.f32 	%f10, [%rd37];
	add.f32 	%f11, %f10, %f9;
	shl.b64 	%rd38, %rd8, 2;
	add.s64 	%rd39, %rd29, %rd38;
	ld.global.nc.f32 	%f12, [%rd39];
	add.f32 	%f13, %f11, %f12;
	shl.b64 	%rd40, %rd5, 2;
	add.s64 	%rd41, %rd30, %rd40;
	ld.global.nc.f32 	%f14, [%rd41];
	ld.global.nc.f32 	%f15, [%rd33];
	add.f32 	%f16, %f15, %f14;
	shl.b64 	%rd42, %rd7, 2;
	add.s64 	%rd43, %rd29, %rd42;
	ld.global.nc.f32 	%f17, [%rd43];
	add.f32 	%f18, %f16, %f17;
	sub.f32 	%f19, %f13, %f18;
	cvt.f64.f32	%fd1, %f19;
	cvt.f64.f32	%fd2, %f1;
	add.f64 	%fd3, %fd2, %fd2;
	div.rn.f64 	%fd4, %fd1, %fd3;
	cvt.rn.f32.f64	%f20, %fd4;
	shl.b64 	%rd44, %rd2, 2;
	add.s64 	%rd45, %rd28, %rd44;
	st.global.f32 	[%rd45], %f20;

BB0_9:
	ret;
}


`
 )
