package ext_kernels

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for eddyLaplaceMove kernel
var eddyLaplaceMove_code cu.Function

// Stores the arguments for eddyLaplaceMove kernel invocation
type eddyLaplaceMove_args_t struct{
	 arg_field unsafe.Pointer
	 arg_solFieldX unsafe.Pointer
	 arg_solFieldY unsafe.Pointer
	 arg_solFieldZ unsafe.Pointer
	 arg_Nx int
	 arg_Ny int
	 arg_Nz int
	 arg_sliderGeometry unsafe.Pointer
	 arg_baseGeometry unsafe.Pointer
	 arg_even int
	 arg_cellsize float32
	 argptr [11]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for eddyLaplaceMove kernel invocation
var eddyLaplaceMove_args eddyLaplaceMove_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 eddyLaplaceMove_args.argptr[0] = unsafe.Pointer(&eddyLaplaceMove_args.arg_field)
	 eddyLaplaceMove_args.argptr[1] = unsafe.Pointer(&eddyLaplaceMove_args.arg_solFieldX)
	 eddyLaplaceMove_args.argptr[2] = unsafe.Pointer(&eddyLaplaceMove_args.arg_solFieldY)
	 eddyLaplaceMove_args.argptr[3] = unsafe.Pointer(&eddyLaplaceMove_args.arg_solFieldZ)
	 eddyLaplaceMove_args.argptr[4] = unsafe.Pointer(&eddyLaplaceMove_args.arg_Nx)
	 eddyLaplaceMove_args.argptr[5] = unsafe.Pointer(&eddyLaplaceMove_args.arg_Ny)
	 eddyLaplaceMove_args.argptr[6] = unsafe.Pointer(&eddyLaplaceMove_args.arg_Nz)
	 eddyLaplaceMove_args.argptr[7] = unsafe.Pointer(&eddyLaplaceMove_args.arg_sliderGeometry)
	 eddyLaplaceMove_args.argptr[8] = unsafe.Pointer(&eddyLaplaceMove_args.arg_baseGeometry)
	 eddyLaplaceMove_args.argptr[9] = unsafe.Pointer(&eddyLaplaceMove_args.arg_even)
	 eddyLaplaceMove_args.argptr[10] = unsafe.Pointer(&eddyLaplaceMove_args.arg_cellsize)
	 }

// Wrapper for eddyLaplaceMove CUDA kernel, asynchronous.
func K_ext_eddyLaplaceMove_async ( field unsafe.Pointer, solFieldX unsafe.Pointer, solFieldY unsafe.Pointer, solFieldZ unsafe.Pointer, Nx int, Ny int, Nz int, sliderGeometry unsafe.Pointer, baseGeometry unsafe.Pointer, even int, cellsize float32,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("eddyLaplaceMove")
	}

	eddyLaplaceMove_args.Lock()
	defer eddyLaplaceMove_args.Unlock()

	if eddyLaplaceMove_code == 0{
		eddyLaplaceMove_code = fatbinLoad(eddyLaplaceMove_map, "eddyLaplaceMove")
	}

	 eddyLaplaceMove_args.arg_field = field
	 eddyLaplaceMove_args.arg_solFieldX = solFieldX
	 eddyLaplaceMove_args.arg_solFieldY = solFieldY
	 eddyLaplaceMove_args.arg_solFieldZ = solFieldZ
	 eddyLaplaceMove_args.arg_Nx = Nx
	 eddyLaplaceMove_args.arg_Ny = Ny
	 eddyLaplaceMove_args.arg_Nz = Nz
	 eddyLaplaceMove_args.arg_sliderGeometry = sliderGeometry
	 eddyLaplaceMove_args.arg_baseGeometry = baseGeometry
	 eddyLaplaceMove_args.arg_even = even
	 eddyLaplaceMove_args.arg_cellsize = cellsize
	

	args := eddyLaplaceMove_args.argptr[:]
	cu.LaunchKernel(eddyLaplaceMove_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("eddyLaplaceMove")
	}
}

// maps compute capability on PTX code for eddyLaplaceMove kernel.
var eddyLaplaceMove_map = map[int]string{ 0: "" ,
20: eddyLaplaceMove_ptx_20 ,
30: eddyLaplaceMove_ptx_30 ,
35: eddyLaplaceMove_ptx_35 ,
50: eddyLaplaceMove_ptx_50 ,
52: eddyLaplaceMove_ptx_52 ,
53: eddyLaplaceMove_ptx_53  }

// eddyLaplaceMove PTX code for various compute capabilities.
const(
  eddyLaplaceMove_ptx_20 = `
.version 5.0
.target sm_20
.address_size 64

	// .globl	eddyLaplaceMove

.visible .entry eddyLaplaceMove(
	.param .u64 eddyLaplaceMove_param_0,
	.param .u64 eddyLaplaceMove_param_1,
	.param .u64 eddyLaplaceMove_param_2,
	.param .u64 eddyLaplaceMove_param_3,
	.param .u32 eddyLaplaceMove_param_4,
	.param .u32 eddyLaplaceMove_param_5,
	.param .u32 eddyLaplaceMove_param_6,
	.param .u64 eddyLaplaceMove_param_7,
	.param .u64 eddyLaplaceMove_param_8,
	.param .u32 eddyLaplaceMove_param_9,
	.param .f32 eddyLaplaceMove_param_10
)
{
	.reg .pred 	%p<79>;
	.reg .f32 	%f<81>;
	.reg .b32 	%r<120>;
	.reg .f64 	%fd<65>;
	.reg .b64 	%rd<71>;


	ld.param.u64 	%rd16, [eddyLaplaceMove_param_0];
	ld.param.u64 	%rd17, [eddyLaplaceMove_param_1];
	ld.param.u64 	%rd18, [eddyLaplaceMove_param_2];
	ld.param.u64 	%rd19, [eddyLaplaceMove_param_3];
	ld.param.u32 	%r7, [eddyLaplaceMove_param_4];
	ld.param.u32 	%r8, [eddyLaplaceMove_param_5];
	ld.param.u32 	%r9, [eddyLaplaceMove_param_6];
	ld.param.u64 	%rd20, [eddyLaplaceMove_param_7];
	ld.param.u64 	%rd21, [eddyLaplaceMove_param_8];
	ld.param.u32 	%r10, [eddyLaplaceMove_param_9];
	ld.param.f32 	%f41, [eddyLaplaceMove_param_10];
	cvta.to.global.u64 	%rd1, %rd21;
	cvta.to.global.u64 	%rd2, %rd20;
	mov.u32 	%r11, %ntid.x;
	mov.u32 	%r12, %ctaid.x;
	mov.u32 	%r13, %tid.x;
	mad.lo.s32 	%r1, %r11, %r12, %r13;
	mov.u32 	%r14, %ntid.y;
	mov.u32 	%r15, %ctaid.y;
	mov.u32 	%r16, %tid.y;
	mad.lo.s32 	%r2, %r14, %r15, %r16;
	mov.u32 	%r17, %ntid.z;
	mov.u32 	%r18, %ctaid.z;
	mov.u32 	%r19, %tid.z;
	mad.lo.s32 	%r3, %r17, %r18, %r19;
	setp.ge.s32	%p19, %r2, %r8;
	setp.ge.s32	%p20, %r1, %r7;
	or.pred  	%p21, %p19, %p20;
	setp.ge.s32	%p22, %r3, %r9;
	or.pred  	%p23, %p21, %p22;
	@%p23 bra 	BB0_48;

	add.s32 	%r20, %r2, %r1;
	add.s32 	%r21, %r20, %r3;
	and.b32  	%r4, %r21, 1;
	setp.eq.s32	%p24, %r4, 0;
	setp.eq.s32	%p25, %r10, 1;
	and.pred  	%p26, %p25, %p24;
	@%p26 bra 	BB0_48;

	setp.eq.s32	%p27, %r10, 0;
	setp.ne.s32	%p28, %r4, 0;
	and.pred  	%p29, %p27, %p28;
	@%p29 bra 	BB0_48;

	mul.lo.s32 	%r22, %r3, %r8;
	add.s32 	%r23, %r22, %r2;
	mul.lo.s32 	%r24, %r23, %r7;
	cvta.to.global.u64 	%rd22, %rd16;
	add.s32 	%r25, %r24, %r1;
	add.s32 	%r26, %r7, %r1;
	add.s32 	%r27, %r26, -1;
	rem.s32 	%r28, %r27, %r7;
	add.s32 	%r29, %r28, %r24;
	add.s32 	%r30, %r1, 1;
	rem.s32 	%r31, %r30, %r7;
	add.s32 	%r32, %r31, %r24;
	add.s32 	%r33, %r8, %r2;
	add.s32 	%r34, %r33, -1;
	rem.s32 	%r35, %r34, %r8;
	add.s32 	%r36, %r35, %r22;
	mad.lo.s32 	%r37, %r36, %r7, %r1;
	add.s32 	%r38, %r2, 1;
	rem.s32 	%r39, %r38, %r8;
	add.s32 	%r40, %r39, %r22;
	mad.lo.s32 	%r41, %r40, %r7, %r1;
	add.s32 	%r42, %r9, %r3;
	add.s32 	%r43, %r42, -1;
	rem.s32 	%r44, %r43, %r9;
	mad.lo.s32 	%r45, %r44, %r8, %r2;
	mad.lo.s32 	%r46, %r45, %r7, %r1;
	add.s32 	%r47, %r3, 1;
	rem.s32 	%r48, %r47, %r9;
	mad.lo.s32 	%r49, %r48, %r8, %r2;
	mad.lo.s32 	%r50, %r49, %r7, %r1;
	cvt.s64.s32	%rd3, %r29;
	mul.wide.s32 	%rd23, %r29, 4;
	add.s64 	%rd24, %rd22, %rd23;
	ld.global.f32 	%f75, [%rd24];
	cvt.s64.s32	%rd4, %r32;
	mul.wide.s32 	%rd25, %r32, 4;
	add.s64 	%rd26, %rd22, %rd25;
	ld.global.f32 	%f76, [%rd26];
	cvt.s64.s32	%rd5, %r37;
	mul.wide.s32 	%rd27, %r37, 4;
	add.s64 	%rd28, %rd22, %rd27;
	ld.global.f32 	%f77, [%rd28];
	cvt.s64.s32	%rd6, %r41;
	mul.wide.s32 	%rd29, %r41, 4;
	add.s64 	%rd30, %rd22, %rd29;
	ld.global.f32 	%f78, [%rd30];
	cvt.s64.s32	%rd7, %r46;
	mul.wide.s32 	%rd31, %r46, 4;
	add.s64 	%rd32, %rd22, %rd31;
	ld.global.f32 	%f79, [%rd32];
	cvt.s64.s32	%rd8, %r50;
	mul.wide.s32 	%rd33, %r50, 4;
	add.s64 	%rd34, %rd22, %rd33;
	ld.global.f32 	%f80, [%rd34];
	mul.wide.s32 	%rd35, %r25, 4;
	add.s64 	%rd36, %rd2, %rd35;
	ld.global.f32 	%f7, [%rd36];
	setp.eq.f32	%p31, %f7, 0f40000000;
	add.s64 	%rd9, %rd1, %rd35;
	mov.pred 	%p30, -1;
	mov.pred 	%p78, %p30;
	@%p31 bra 	BB0_5;

	ld.global.f32 	%f42, [%rd9];
	setp.eq.f32	%p1, %f42, 0f40000000;
	mov.pred 	%p78, %p1;

BB0_5:
	mov.pred 	%p2, %p78;
	shl.b64 	%rd37, %rd3, 2;
	add.s64 	%rd38, %rd2, %rd37;
	ld.global.f32 	%f8, [%rd38];
	setp.eq.f32	%p33, %f8, 0f3F800000;
	add.s64 	%rd10, %rd1, %rd37;
	mov.pred 	%p77, %p30;
	@%p33 bra 	BB0_7;

	ld.global.f32 	%f43, [%rd10];
	setp.eq.f32	%p77, %f43, 0f3F800000;

BB0_7:
	shl.b64 	%rd39, %rd4, 2;
	add.s64 	%rd40, %rd2, %rd39;
	ld.global.f32 	%f9, [%rd40];
	setp.eq.f32	%p35, %f9, 0f3F800000;
	add.s64 	%rd11, %rd1, %rd39;
	mov.pred 	%p76, %p30;
	@%p35 bra 	BB0_9;

	ld.global.f32 	%f44, [%rd11];
	setp.eq.f32	%p76, %f44, 0f3F800000;

BB0_9:
	selp.s32	%r51, -1, 0, %p77;
	selp.u32	%r52, 1, 0, %p76;
	add.s32 	%r53, %r52, %r51;
	selp.b32	%r5, %r53, 0, %p2;
	mov.pred 	%p75, %p30;
	@%p31 bra 	BB0_11;

	ld.global.f32 	%f45, [%rd9];
	setp.eq.f32	%p75, %f45, 0f40000000;

BB0_11:
	shl.b64 	%rd41, %rd5, 2;
	add.s64 	%rd42, %rd2, %rd41;
	ld.global.f32 	%f10, [%rd42];
	setp.eq.f32	%p39, %f10, 0f3F800000;
	add.s64 	%rd12, %rd1, %rd41;
	mov.pred 	%p74, %p30;
	@%p39 bra 	BB0_13;

	ld.global.f32 	%f46, [%rd12];
	setp.eq.f32	%p74, %f46, 0f3F800000;

BB0_13:
	shl.b64 	%rd44, %rd6, 2;
	add.s64 	%rd45, %rd2, %rd44;
	ld.global.f32 	%f11, [%rd45];
	setp.eq.f32	%p41, %f11, 0f3F800000;
	add.s64 	%rd13, %rd1, %rd44;
	mov.pred 	%p73, %p30;
	@%p41 bra 	BB0_15;

	ld.global.f32 	%f47, [%rd13];
	setp.eq.f32	%p73, %f47, 0f3F800000;

BB0_15:
	selp.s32	%r54, -1, 0, %p74;
	selp.u32	%r55, 1, 0, %p73;
	add.s32 	%r56, %r55, %r54;
	selp.b32	%r6, %r56, 0, %p75;
	mov.pred 	%p72, %p30;
	@%p31 bra 	BB0_17;

	mad.lo.s32 	%r65, %r3, %r8, %r2;
	mad.lo.s32 	%r70, %r65, %r7, %r1;
	mul.wide.s32 	%rd48, %r70, 4;
	add.s64 	%rd49, %rd1, %rd48;
	ld.global.f32 	%f48, [%rd49];
	setp.eq.f32	%p72, %f48, 0f40000000;

BB0_17:
	shl.b64 	%rd51, %rd7, 2;
	add.s64 	%rd52, %rd2, %rd51;
	ld.global.f32 	%f12, [%rd52];
	setp.eq.f32	%p45, %f12, 0f3F800000;
	add.s64 	%rd14, %rd1, %rd51;
	mov.pred 	%p71, %p30;
	@%p45 bra 	BB0_19;

	ld.global.f32 	%f49, [%rd14];
	setp.eq.f32	%p71, %f49, 0f3F800000;

BB0_19:
	shl.b64 	%rd55, %rd8, 2;
	add.s64 	%rd56, %rd2, %rd55;
	ld.global.f32 	%f13, [%rd56];
	setp.eq.f32	%p47, %f13, 0f3F800000;
	add.s64 	%rd15, %rd1, %rd55;
	mov.pred 	%p70, %p30;
	@%p47 bra 	BB0_21;

	ld.global.f32 	%f50, [%rd15];
	setp.eq.f32	%p70, %f50, 0f3F800000;

BB0_21:
	selp.s32	%r71, -1, 0, %p71;
	selp.u32	%r72, 1, 0, %p70;
	add.s32 	%r73, %r72, %r71;
	selp.b32	%r74, %r73, 0, %p72;
	mad.lo.s32 	%r83, %r3, %r8, %r2;
	mad.lo.s32 	%r88, %r83, %r7, %r1;
	cvta.to.global.u64 	%rd58, %rd17;
	mul.wide.s32 	%rd59, %r88, 4;
	add.s64 	%rd60, %rd58, %rd59;
	cvt.rn.f32.s32	%f51, %r5;
	ld.global.f32 	%f52, [%rd60];
	cvta.to.global.u64 	%rd61, %rd18;
	add.s64 	%rd62, %rd61, %rd59;
	cvt.rn.f32.s32	%f53, %r6;
	ld.global.f32 	%f54, [%rd62];
	mul.f32 	%f55, %f53, %f54;
	fma.rn.f32 	%f56, %f51, %f52, %f55;
	cvta.to.global.u64 	%rd63, %rd19;
	add.s64 	%rd64, %rd63, %rd59;
	cvt.rn.f32.s32	%f57, %r74;
	ld.global.f32 	%f58, [%rd64];
	fma.rn.f32 	%f59, %f58, %f57, %f56;
	mul.lo.s32 	%r89, %r5, %r5;
	mad.lo.s32 	%r90, %r6, %r6, %r89;
	mad.lo.s32 	%r91, %r74, %r74, %r90;
	cvt.rn.f32.s32	%f60, %r91;
	div.rn.f32 	%f14, %f59, %f60;
	@%p31 bra 	BB0_35;
	bra.uni 	BB0_22;

BB0_35:
	@%p33 bra 	BB0_38;
	bra.uni 	BB0_36;

BB0_38:
	cvt.f64.f32	%fd36, %f14;
	add.f64 	%fd37, %fd36, %fd36;
	cvt.f64.f32	%fd38, %f41;
	cvt.f64.f32	%fd39, %f76;
	fma.rn.f64 	%fd40, %fd38, %fd37, %fd39;
	cvt.rn.f32.f64	%f75, %fd40;
	bra.uni 	BB0_39;

BB0_22:
	add.s64 	%rd67, %rd1, %rd59;
	ld.global.f32 	%f61, [%rd67];
	setp.neu.f32	%p49, %f61, 0f40000000;
	@%p49 bra 	BB0_47;

	ld.global.f32 	%f62, [%rd10];
	setp.eq.f32	%p50, %f62, 0f3F800000;
	@%p50 bra 	BB0_26;
	bra.uni 	BB0_24;

BB0_26:
	cvt.f64.f32	%fd6, %f14;
	add.f64 	%fd7, %fd6, %fd6;
	cvt.f64.f32	%fd8, %f41;
	cvt.f64.f32	%fd9, %f76;
	fma.rn.f64 	%fd10, %fd8, %fd7, %fd9;
	cvt.rn.f32.f64	%f75, %fd10;
	bra.uni 	BB0_27;

BB0_36:
	setp.neu.f32	%p57, %f9, 0f3F800000;
	@%p57 bra 	BB0_39;

	cvt.f64.f32	%fd31, %f14;
	add.f64 	%fd32, %fd31, %fd31;
	cvt.f64.f32	%fd33, %f41;
	cvt.f64.f32	%fd34, %f75;
	fma.rn.f64 	%fd35, %fd33, %fd32, %fd34;
	cvt.rn.f32.f64	%f76, %fd35;

BB0_39:
	@%p39 bra 	BB0_42;
	bra.uni 	BB0_40;

BB0_42:
	cvt.f64.f32	%fd46, %f14;
	add.f64 	%fd47, %fd46, %fd46;
	cvt.f64.f32	%fd48, %f41;
	cvt.f64.f32	%fd49, %f78;
	fma.rn.f64 	%fd50, %fd48, %fd47, %fd49;
	cvt.rn.f32.f64	%f77, %fd50;
	bra.uni 	BB0_43;

BB0_40:
	setp.neu.f32	%p59, %f11, 0f3F800000;
	@%p59 bra 	BB0_43;

	cvt.f64.f32	%fd41, %f14;
	add.f64 	%fd42, %fd41, %fd41;
	cvt.f64.f32	%fd43, %f41;
	cvt.f64.f32	%fd44, %f77;
	fma.rn.f64 	%fd45, %fd43, %fd42, %fd44;
	cvt.rn.f32.f64	%f78, %fd45;

BB0_43:
	@%p45 bra 	BB0_46;
	bra.uni 	BB0_44;

BB0_46:
	cvt.f64.f32	%fd56, %f14;
	add.f64 	%fd57, %fd56, %fd56;
	cvt.f64.f32	%fd58, %f41;
	cvt.f64.f32	%fd59, %f80;
	fma.rn.f64 	%fd60, %fd58, %fd57, %fd59;
	cvt.rn.f32.f64	%f79, %fd60;
	bra.uni 	BB0_47;

BB0_44:
	setp.neu.f32	%p61, %f13, 0f3F800000;
	@%p61 bra 	BB0_47;

	cvt.f64.f32	%fd51, %f14;
	add.f64 	%fd52, %fd51, %fd51;
	cvt.f64.f32	%fd53, %f41;
	cvt.f64.f32	%fd54, %f79;
	fma.rn.f64 	%fd55, %fd53, %fd52, %fd54;
	cvt.rn.f32.f64	%f80, %fd55;
	bra.uni 	BB0_47;

BB0_24:
	ld.global.f32 	%f63, [%rd11];
	setp.neu.f32	%p51, %f63, 0f3F800000;
	@%p51 bra 	BB0_27;

	cvt.f64.f32	%fd1, %f14;
	add.f64 	%fd2, %fd1, %fd1;
	cvt.f64.f32	%fd3, %f41;
	cvt.f64.f32	%fd4, %f75;
	fma.rn.f64 	%fd5, %fd3, %fd2, %fd4;
	cvt.rn.f32.f64	%f76, %fd5;

BB0_27:
	ld.global.f32 	%f64, [%rd12];
	setp.eq.f32	%p52, %f64, 0f3F800000;
	@%p52 bra 	BB0_30;
	bra.uni 	BB0_28;

BB0_30:
	cvt.f64.f32	%fd16, %f14;
	add.f64 	%fd17, %fd16, %fd16;
	cvt.f64.f32	%fd18, %f41;
	cvt.f64.f32	%fd19, %f78;
	fma.rn.f64 	%fd20, %fd18, %fd17, %fd19;
	cvt.rn.f32.f64	%f77, %fd20;
	bra.uni 	BB0_31;

BB0_28:
	ld.global.f32 	%f65, [%rd13];
	setp.neu.f32	%p53, %f65, 0f3F800000;
	@%p53 bra 	BB0_31;

	cvt.f64.f32	%fd11, %f14;
	add.f64 	%fd12, %fd11, %fd11;
	cvt.f64.f32	%fd13, %f41;
	cvt.f64.f32	%fd14, %f77;
	fma.rn.f64 	%fd15, %fd13, %fd12, %fd14;
	cvt.rn.f32.f64	%f78, %fd15;

BB0_31:
	ld.global.f32 	%f66, [%rd14];
	setp.eq.f32	%p54, %f66, 0f3F800000;
	@%p54 bra 	BB0_34;
	bra.uni 	BB0_32;

BB0_34:
	cvt.f64.f32	%fd26, %f14;
	add.f64 	%fd27, %fd26, %fd26;
	cvt.f64.f32	%fd28, %f41;
	cvt.f64.f32	%fd29, %f80;
	fma.rn.f64 	%fd30, %fd28, %fd27, %fd29;
	cvt.rn.f32.f64	%f79, %fd30;
	bra.uni 	BB0_47;

BB0_32:
	ld.global.f32 	%f67, [%rd15];
	setp.neu.f32	%p55, %f67, 0f3F800000;
	@%p55 bra 	BB0_47;

	cvt.f64.f32	%fd21, %f14;
	add.f64 	%fd22, %fd21, %fd21;
	cvt.f64.f32	%fd23, %f41;
	cvt.f64.f32	%fd24, %f79;
	fma.rn.f64 	%fd25, %fd23, %fd22, %fd24;
	cvt.rn.f32.f64	%f80, %fd25;

BB0_47:
	add.s64 	%rd70, %rd22, %rd59;
	ld.global.f32 	%f68, [%rd70];
	cvt.f64.f32	%fd61, %f68;
	add.f32 	%f69, %f75, %f76;
	add.f32 	%f70, %f69, %f77;
	add.f32 	%f71, %f70, %f78;
	add.f32 	%f72, %f71, %f79;
	add.f32 	%f73, %f72, %f80;
	cvt.f64.f32	%fd62, %f73;
	mul.f64 	%fd63, %fd62, 0d3FCDDDDDDDDDDDDD;
	fma.rn.f64 	%fd64, %fd61, 0dBFD999999999999A, %fd63;
	cvt.rn.f32.f64	%f74, %fd64;
	st.global.f32 	[%rd70], %f74;

BB0_48:
	ret;
}


`
   eddyLaplaceMove_ptx_30 = `
.version 5.0
.target sm_30
.address_size 64

	// .globl	eddyLaplaceMove

.visible .entry eddyLaplaceMove(
	.param .u64 eddyLaplaceMove_param_0,
	.param .u64 eddyLaplaceMove_param_1,
	.param .u64 eddyLaplaceMove_param_2,
	.param .u64 eddyLaplaceMove_param_3,
	.param .u32 eddyLaplaceMove_param_4,
	.param .u32 eddyLaplaceMove_param_5,
	.param .u32 eddyLaplaceMove_param_6,
	.param .u64 eddyLaplaceMove_param_7,
	.param .u64 eddyLaplaceMove_param_8,
	.param .u32 eddyLaplaceMove_param_9,
	.param .f32 eddyLaplaceMove_param_10
)
{
	.reg .pred 	%p<79>;
	.reg .f32 	%f<81>;
	.reg .b32 	%r<120>;
	.reg .f64 	%fd<65>;
	.reg .b64 	%rd<71>;


	ld.param.u64 	%rd16, [eddyLaplaceMove_param_0];
	ld.param.u64 	%rd17, [eddyLaplaceMove_param_1];
	ld.param.u64 	%rd18, [eddyLaplaceMove_param_2];
	ld.param.u64 	%rd19, [eddyLaplaceMove_param_3];
	ld.param.u32 	%r7, [eddyLaplaceMove_param_4];
	ld.param.u32 	%r8, [eddyLaplaceMove_param_5];
	ld.param.u32 	%r9, [eddyLaplaceMove_param_6];
	ld.param.u64 	%rd20, [eddyLaplaceMove_param_7];
	ld.param.u64 	%rd21, [eddyLaplaceMove_param_8];
	ld.param.u32 	%r10, [eddyLaplaceMove_param_9];
	ld.param.f32 	%f41, [eddyLaplaceMove_param_10];
	cvta.to.global.u64 	%rd1, %rd21;
	cvta.to.global.u64 	%rd2, %rd20;
	mov.u32 	%r11, %ntid.x;
	mov.u32 	%r12, %ctaid.x;
	mov.u32 	%r13, %tid.x;
	mad.lo.s32 	%r1, %r11, %r12, %r13;
	mov.u32 	%r14, %ntid.y;
	mov.u32 	%r15, %ctaid.y;
	mov.u32 	%r16, %tid.y;
	mad.lo.s32 	%r2, %r14, %r15, %r16;
	mov.u32 	%r17, %ntid.z;
	mov.u32 	%r18, %ctaid.z;
	mov.u32 	%r19, %tid.z;
	mad.lo.s32 	%r3, %r17, %r18, %r19;
	setp.ge.s32	%p19, %r2, %r8;
	setp.ge.s32	%p20, %r1, %r7;
	or.pred  	%p21, %p19, %p20;
	setp.ge.s32	%p22, %r3, %r9;
	or.pred  	%p23, %p21, %p22;
	@%p23 bra 	BB0_48;

	add.s32 	%r20, %r2, %r1;
	add.s32 	%r21, %r20, %r3;
	and.b32  	%r4, %r21, 1;
	setp.eq.s32	%p24, %r4, 0;
	setp.eq.s32	%p25, %r10, 1;
	and.pred  	%p26, %p25, %p24;
	@%p26 bra 	BB0_48;

	setp.eq.s32	%p27, %r10, 0;
	setp.ne.s32	%p28, %r4, 0;
	and.pred  	%p29, %p27, %p28;
	@%p29 bra 	BB0_48;

	mul.lo.s32 	%r22, %r3, %r8;
	add.s32 	%r23, %r22, %r2;
	mul.lo.s32 	%r24, %r23, %r7;
	cvta.to.global.u64 	%rd22, %rd16;
	add.s32 	%r25, %r24, %r1;
	add.s32 	%r26, %r7, %r1;
	add.s32 	%r27, %r26, -1;
	rem.s32 	%r28, %r27, %r7;
	add.s32 	%r29, %r28, %r24;
	add.s32 	%r30, %r1, 1;
	rem.s32 	%r31, %r30, %r7;
	add.s32 	%r32, %r31, %r24;
	add.s32 	%r33, %r8, %r2;
	add.s32 	%r34, %r33, -1;
	rem.s32 	%r35, %r34, %r8;
	add.s32 	%r36, %r35, %r22;
	mad.lo.s32 	%r37, %r36, %r7, %r1;
	add.s32 	%r38, %r2, 1;
	rem.s32 	%r39, %r38, %r8;
	add.s32 	%r40, %r39, %r22;
	mad.lo.s32 	%r41, %r40, %r7, %r1;
	add.s32 	%r42, %r9, %r3;
	add.s32 	%r43, %r42, -1;
	rem.s32 	%r44, %r43, %r9;
	mad.lo.s32 	%r45, %r44, %r8, %r2;
	mad.lo.s32 	%r46, %r45, %r7, %r1;
	add.s32 	%r47, %r3, 1;
	rem.s32 	%r48, %r47, %r9;
	mad.lo.s32 	%r49, %r48, %r8, %r2;
	mad.lo.s32 	%r50, %r49, %r7, %r1;
	cvt.s64.s32	%rd3, %r29;
	mul.wide.s32 	%rd23, %r29, 4;
	add.s64 	%rd24, %rd22, %rd23;
	ld.global.f32 	%f75, [%rd24];
	cvt.s64.s32	%rd4, %r32;
	mul.wide.s32 	%rd25, %r32, 4;
	add.s64 	%rd26, %rd22, %rd25;
	ld.global.f32 	%f76, [%rd26];
	cvt.s64.s32	%rd5, %r37;
	mul.wide.s32 	%rd27, %r37, 4;
	add.s64 	%rd28, %rd22, %rd27;
	ld.global.f32 	%f77, [%rd28];
	cvt.s64.s32	%rd6, %r41;
	mul.wide.s32 	%rd29, %r41, 4;
	add.s64 	%rd30, %rd22, %rd29;
	ld.global.f32 	%f78, [%rd30];
	cvt.s64.s32	%rd7, %r46;
	mul.wide.s32 	%rd31, %r46, 4;
	add.s64 	%rd32, %rd22, %rd31;
	ld.global.f32 	%f79, [%rd32];
	cvt.s64.s32	%rd8, %r50;
	mul.wide.s32 	%rd33, %r50, 4;
	add.s64 	%rd34, %rd22, %rd33;
	ld.global.f32 	%f80, [%rd34];
	mul.wide.s32 	%rd35, %r25, 4;
	add.s64 	%rd36, %rd2, %rd35;
	ld.global.f32 	%f7, [%rd36];
	setp.eq.f32	%p31, %f7, 0f40000000;
	add.s64 	%rd9, %rd1, %rd35;
	mov.pred 	%p30, -1;
	mov.pred 	%p78, %p30;
	@%p31 bra 	BB0_5;

	ld.global.f32 	%f42, [%rd9];
	setp.eq.f32	%p1, %f42, 0f40000000;
	mov.pred 	%p78, %p1;

BB0_5:
	mov.pred 	%p2, %p78;
	shl.b64 	%rd37, %rd3, 2;
	add.s64 	%rd38, %rd2, %rd37;
	ld.global.f32 	%f8, [%rd38];
	setp.eq.f32	%p33, %f8, 0f3F800000;
	add.s64 	%rd10, %rd1, %rd37;
	mov.pred 	%p77, %p30;
	@%p33 bra 	BB0_7;

	ld.global.f32 	%f43, [%rd10];
	setp.eq.f32	%p77, %f43, 0f3F800000;

BB0_7:
	shl.b64 	%rd39, %rd4, 2;
	add.s64 	%rd40, %rd2, %rd39;
	ld.global.f32 	%f9, [%rd40];
	setp.eq.f32	%p35, %f9, 0f3F800000;
	add.s64 	%rd11, %rd1, %rd39;
	mov.pred 	%p76, %p30;
	@%p35 bra 	BB0_9;

	ld.global.f32 	%f44, [%rd11];
	setp.eq.f32	%p76, %f44, 0f3F800000;

BB0_9:
	selp.s32	%r51, -1, 0, %p77;
	selp.u32	%r52, 1, 0, %p76;
	add.s32 	%r53, %r52, %r51;
	selp.b32	%r5, %r53, 0, %p2;
	mov.pred 	%p75, %p30;
	@%p31 bra 	BB0_11;

	ld.global.f32 	%f45, [%rd9];
	setp.eq.f32	%p75, %f45, 0f40000000;

BB0_11:
	shl.b64 	%rd41, %rd5, 2;
	add.s64 	%rd42, %rd2, %rd41;
	ld.global.f32 	%f10, [%rd42];
	setp.eq.f32	%p39, %f10, 0f3F800000;
	add.s64 	%rd12, %rd1, %rd41;
	mov.pred 	%p74, %p30;
	@%p39 bra 	BB0_13;

	ld.global.f32 	%f46, [%rd12];
	setp.eq.f32	%p74, %f46, 0f3F800000;

BB0_13:
	shl.b64 	%rd44, %rd6, 2;
	add.s64 	%rd45, %rd2, %rd44;
	ld.global.f32 	%f11, [%rd45];
	setp.eq.f32	%p41, %f11, 0f3F800000;
	add.s64 	%rd13, %rd1, %rd44;
	mov.pred 	%p73, %p30;
	@%p41 bra 	BB0_15;

	ld.global.f32 	%f47, [%rd13];
	setp.eq.f32	%p73, %f47, 0f3F800000;

BB0_15:
	selp.s32	%r54, -1, 0, %p74;
	selp.u32	%r55, 1, 0, %p73;
	add.s32 	%r56, %r55, %r54;
	selp.b32	%r6, %r56, 0, %p75;
	mov.pred 	%p72, %p30;
	@%p31 bra 	BB0_17;

	mad.lo.s32 	%r65, %r3, %r8, %r2;
	mad.lo.s32 	%r70, %r65, %r7, %r1;
	mul.wide.s32 	%rd48, %r70, 4;
	add.s64 	%rd49, %rd1, %rd48;
	ld.global.f32 	%f48, [%rd49];
	setp.eq.f32	%p72, %f48, 0f40000000;

BB0_17:
	shl.b64 	%rd51, %rd7, 2;
	add.s64 	%rd52, %rd2, %rd51;
	ld.global.f32 	%f12, [%rd52];
	setp.eq.f32	%p45, %f12, 0f3F800000;
	add.s64 	%rd14, %rd1, %rd51;
	mov.pred 	%p71, %p30;
	@%p45 bra 	BB0_19;

	ld.global.f32 	%f49, [%rd14];
	setp.eq.f32	%p71, %f49, 0f3F800000;

BB0_19:
	shl.b64 	%rd55, %rd8, 2;
	add.s64 	%rd56, %rd2, %rd55;
	ld.global.f32 	%f13, [%rd56];
	setp.eq.f32	%p47, %f13, 0f3F800000;
	add.s64 	%rd15, %rd1, %rd55;
	mov.pred 	%p70, %p30;
	@%p47 bra 	BB0_21;

	ld.global.f32 	%f50, [%rd15];
	setp.eq.f32	%p70, %f50, 0f3F800000;

BB0_21:
	selp.s32	%r71, -1, 0, %p71;
	selp.u32	%r72, 1, 0, %p70;
	add.s32 	%r73, %r72, %r71;
	selp.b32	%r74, %r73, 0, %p72;
	mad.lo.s32 	%r83, %r3, %r8, %r2;
	mad.lo.s32 	%r88, %r83, %r7, %r1;
	cvta.to.global.u64 	%rd58, %rd17;
	mul.wide.s32 	%rd59, %r88, 4;
	add.s64 	%rd60, %rd58, %rd59;
	cvt.rn.f32.s32	%f51, %r5;
	ld.global.f32 	%f52, [%rd60];
	cvta.to.global.u64 	%rd61, %rd18;
	add.s64 	%rd62, %rd61, %rd59;
	cvt.rn.f32.s32	%f53, %r6;
	ld.global.f32 	%f54, [%rd62];
	mul.f32 	%f55, %f53, %f54;
	fma.rn.f32 	%f56, %f51, %f52, %f55;
	cvta.to.global.u64 	%rd63, %rd19;
	add.s64 	%rd64, %rd63, %rd59;
	cvt.rn.f32.s32	%f57, %r74;
	ld.global.f32 	%f58, [%rd64];
	fma.rn.f32 	%f59, %f58, %f57, %f56;
	mul.lo.s32 	%r89, %r5, %r5;
	mad.lo.s32 	%r90, %r6, %r6, %r89;
	mad.lo.s32 	%r91, %r74, %r74, %r90;
	cvt.rn.f32.s32	%f60, %r91;
	div.rn.f32 	%f14, %f59, %f60;
	@%p31 bra 	BB0_35;
	bra.uni 	BB0_22;

BB0_35:
	@%p33 bra 	BB0_38;
	bra.uni 	BB0_36;

BB0_38:
	cvt.f64.f32	%fd36, %f14;
	add.f64 	%fd37, %fd36, %fd36;
	cvt.f64.f32	%fd38, %f41;
	cvt.f64.f32	%fd39, %f76;
	fma.rn.f64 	%fd40, %fd38, %fd37, %fd39;
	cvt.rn.f32.f64	%f75, %fd40;
	bra.uni 	BB0_39;

BB0_22:
	add.s64 	%rd67, %rd1, %rd59;
	ld.global.f32 	%f61, [%rd67];
	setp.neu.f32	%p49, %f61, 0f40000000;
	@%p49 bra 	BB0_47;

	ld.global.f32 	%f62, [%rd10];
	setp.eq.f32	%p50, %f62, 0f3F800000;
	@%p50 bra 	BB0_26;
	bra.uni 	BB0_24;

BB0_26:
	cvt.f64.f32	%fd6, %f14;
	add.f64 	%fd7, %fd6, %fd6;
	cvt.f64.f32	%fd8, %f41;
	cvt.f64.f32	%fd9, %f76;
	fma.rn.f64 	%fd10, %fd8, %fd7, %fd9;
	cvt.rn.f32.f64	%f75, %fd10;
	bra.uni 	BB0_27;

BB0_36:
	setp.neu.f32	%p57, %f9, 0f3F800000;
	@%p57 bra 	BB0_39;

	cvt.f64.f32	%fd31, %f14;
	add.f64 	%fd32, %fd31, %fd31;
	cvt.f64.f32	%fd33, %f41;
	cvt.f64.f32	%fd34, %f75;
	fma.rn.f64 	%fd35, %fd33, %fd32, %fd34;
	cvt.rn.f32.f64	%f76, %fd35;

BB0_39:
	@%p39 bra 	BB0_42;
	bra.uni 	BB0_40;

BB0_42:
	cvt.f64.f32	%fd46, %f14;
	add.f64 	%fd47, %fd46, %fd46;
	cvt.f64.f32	%fd48, %f41;
	cvt.f64.f32	%fd49, %f78;
	fma.rn.f64 	%fd50, %fd48, %fd47, %fd49;
	cvt.rn.f32.f64	%f77, %fd50;
	bra.uni 	BB0_43;

BB0_40:
	setp.neu.f32	%p59, %f11, 0f3F800000;
	@%p59 bra 	BB0_43;

	cvt.f64.f32	%fd41, %f14;
	add.f64 	%fd42, %fd41, %fd41;
	cvt.f64.f32	%fd43, %f41;
	cvt.f64.f32	%fd44, %f77;
	fma.rn.f64 	%fd45, %fd43, %fd42, %fd44;
	cvt.rn.f32.f64	%f78, %fd45;

BB0_43:
	@%p45 bra 	BB0_46;
	bra.uni 	BB0_44;

BB0_46:
	cvt.f64.f32	%fd56, %f14;
	add.f64 	%fd57, %fd56, %fd56;
	cvt.f64.f32	%fd58, %f41;
	cvt.f64.f32	%fd59, %f80;
	fma.rn.f64 	%fd60, %fd58, %fd57, %fd59;
	cvt.rn.f32.f64	%f79, %fd60;
	bra.uni 	BB0_47;

BB0_44:
	setp.neu.f32	%p61, %f13, 0f3F800000;
	@%p61 bra 	BB0_47;

	cvt.f64.f32	%fd51, %f14;
	add.f64 	%fd52, %fd51, %fd51;
	cvt.f64.f32	%fd53, %f41;
	cvt.f64.f32	%fd54, %f79;
	fma.rn.f64 	%fd55, %fd53, %fd52, %fd54;
	cvt.rn.f32.f64	%f80, %fd55;
	bra.uni 	BB0_47;

BB0_24:
	ld.global.f32 	%f63, [%rd11];
	setp.neu.f32	%p51, %f63, 0f3F800000;
	@%p51 bra 	BB0_27;

	cvt.f64.f32	%fd1, %f14;
	add.f64 	%fd2, %fd1, %fd1;
	cvt.f64.f32	%fd3, %f41;
	cvt.f64.f32	%fd4, %f75;
	fma.rn.f64 	%fd5, %fd3, %fd2, %fd4;
	cvt.rn.f32.f64	%f76, %fd5;

BB0_27:
	ld.global.f32 	%f64, [%rd12];
	setp.eq.f32	%p52, %f64, 0f3F800000;
	@%p52 bra 	BB0_30;
	bra.uni 	BB0_28;

BB0_30:
	cvt.f64.f32	%fd16, %f14;
	add.f64 	%fd17, %fd16, %fd16;
	cvt.f64.f32	%fd18, %f41;
	cvt.f64.f32	%fd19, %f78;
	fma.rn.f64 	%fd20, %fd18, %fd17, %fd19;
	cvt.rn.f32.f64	%f77, %fd20;
	bra.uni 	BB0_31;

BB0_28:
	ld.global.f32 	%f65, [%rd13];
	setp.neu.f32	%p53, %f65, 0f3F800000;
	@%p53 bra 	BB0_31;

	cvt.f64.f32	%fd11, %f14;
	add.f64 	%fd12, %fd11, %fd11;
	cvt.f64.f32	%fd13, %f41;
	cvt.f64.f32	%fd14, %f77;
	fma.rn.f64 	%fd15, %fd13, %fd12, %fd14;
	cvt.rn.f32.f64	%f78, %fd15;

BB0_31:
	ld.global.f32 	%f66, [%rd14];
	setp.eq.f32	%p54, %f66, 0f3F800000;
	@%p54 bra 	BB0_34;
	bra.uni 	BB0_32;

BB0_34:
	cvt.f64.f32	%fd26, %f14;
	add.f64 	%fd27, %fd26, %fd26;
	cvt.f64.f32	%fd28, %f41;
	cvt.f64.f32	%fd29, %f80;
	fma.rn.f64 	%fd30, %fd28, %fd27, %fd29;
	cvt.rn.f32.f64	%f79, %fd30;
	bra.uni 	BB0_47;

BB0_32:
	ld.global.f32 	%f67, [%rd15];
	setp.neu.f32	%p55, %f67, 0f3F800000;
	@%p55 bra 	BB0_47;

	cvt.f64.f32	%fd21, %f14;
	add.f64 	%fd22, %fd21, %fd21;
	cvt.f64.f32	%fd23, %f41;
	cvt.f64.f32	%fd24, %f79;
	fma.rn.f64 	%fd25, %fd23, %fd22, %fd24;
	cvt.rn.f32.f64	%f80, %fd25;

BB0_47:
	add.s64 	%rd70, %rd22, %rd59;
	ld.global.f32 	%f68, [%rd70];
	cvt.f64.f32	%fd61, %f68;
	add.f32 	%f69, %f75, %f76;
	add.f32 	%f70, %f69, %f77;
	add.f32 	%f71, %f70, %f78;
	add.f32 	%f72, %f71, %f79;
	add.f32 	%f73, %f72, %f80;
	cvt.f64.f32	%fd62, %f73;
	mul.f64 	%fd63, %fd62, 0d3FCDDDDDDDDDDDDD;
	fma.rn.f64 	%fd64, %fd61, 0dBFD999999999999A, %fd63;
	cvt.rn.f32.f64	%f74, %fd64;
	st.global.f32 	[%rd70], %f74;

BB0_48:
	ret;
}


`
   eddyLaplaceMove_ptx_35 = `
.version 5.0
.target sm_35
.address_size 64

	// .globl	eddyLaplaceMove

.visible .entry eddyLaplaceMove(
	.param .u64 eddyLaplaceMove_param_0,
	.param .u64 eddyLaplaceMove_param_1,
	.param .u64 eddyLaplaceMove_param_2,
	.param .u64 eddyLaplaceMove_param_3,
	.param .u32 eddyLaplaceMove_param_4,
	.param .u32 eddyLaplaceMove_param_5,
	.param .u32 eddyLaplaceMove_param_6,
	.param .u64 eddyLaplaceMove_param_7,
	.param .u64 eddyLaplaceMove_param_8,
	.param .u32 eddyLaplaceMove_param_9,
	.param .f32 eddyLaplaceMove_param_10
)
{
	.reg .pred 	%p<79>;
	.reg .f32 	%f<81>;
	.reg .b32 	%r<64>;
	.reg .f64 	%fd<65>;
	.reg .b64 	%rd<59>;


	ld.param.u64 	%rd21, [eddyLaplaceMove_param_0];
	ld.param.u64 	%rd18, [eddyLaplaceMove_param_1];
	ld.param.u64 	%rd19, [eddyLaplaceMove_param_2];
	ld.param.u64 	%rd20, [eddyLaplaceMove_param_3];
	ld.param.u32 	%r7, [eddyLaplaceMove_param_4];
	ld.param.u32 	%r8, [eddyLaplaceMove_param_5];
	ld.param.u32 	%r9, [eddyLaplaceMove_param_6];
	ld.param.u64 	%rd22, [eddyLaplaceMove_param_7];
	ld.param.u64 	%rd23, [eddyLaplaceMove_param_8];
	ld.param.u32 	%r10, [eddyLaplaceMove_param_9];
	ld.param.f32 	%f41, [eddyLaplaceMove_param_10];
	cvta.to.global.u64 	%rd1, %rd23;
	cvta.to.global.u64 	%rd2, %rd22;
	cvta.to.global.u64 	%rd3, %rd21;
	mov.u32 	%r11, %ntid.x;
	mov.u32 	%r12, %ctaid.x;
	mov.u32 	%r13, %tid.x;
	mad.lo.s32 	%r1, %r11, %r12, %r13;
	mov.u32 	%r14, %ntid.y;
	mov.u32 	%r15, %ctaid.y;
	mov.u32 	%r16, %tid.y;
	mad.lo.s32 	%r2, %r14, %r15, %r16;
	mov.u32 	%r17, %ntid.z;
	mov.u32 	%r18, %ctaid.z;
	mov.u32 	%r19, %tid.z;
	mad.lo.s32 	%r3, %r17, %r18, %r19;
	setp.ge.s32	%p19, %r2, %r8;
	setp.ge.s32	%p20, %r1, %r7;
	or.pred  	%p21, %p19, %p20;
	setp.ge.s32	%p22, %r3, %r9;
	or.pred  	%p23, %p21, %p22;
	@%p23 bra 	BB0_48;

	add.s32 	%r20, %r2, %r1;
	add.s32 	%r21, %r20, %r3;
	and.b32  	%r4, %r21, 1;
	setp.eq.s32	%p24, %r4, 0;
	setp.eq.s32	%p25, %r10, 1;
	and.pred  	%p26, %p25, %p24;
	@%p26 bra 	BB0_48;

	setp.eq.s32	%p27, %r10, 0;
	setp.ne.s32	%p28, %r4, 0;
	and.pred  	%p29, %p27, %p28;
	@%p29 bra 	BB0_48;

	mul.lo.s32 	%r22, %r3, %r8;
	add.s32 	%r23, %r22, %r2;
	mul.lo.s32 	%r24, %r23, %r7;
	add.s32 	%r25, %r24, %r1;
	add.s32 	%r26, %r7, %r1;
	add.s32 	%r27, %r26, -1;
	rem.s32 	%r28, %r27, %r7;
	add.s32 	%r29, %r28, %r24;
	add.s32 	%r30, %r1, 1;
	rem.s32 	%r31, %r30, %r7;
	add.s32 	%r32, %r31, %r24;
	add.s32 	%r33, %r8, %r2;
	add.s32 	%r34, %r33, -1;
	rem.s32 	%r35, %r34, %r8;
	add.s32 	%r36, %r35, %r22;
	mad.lo.s32 	%r37, %r36, %r7, %r1;
	add.s32 	%r38, %r2, 1;
	rem.s32 	%r39, %r38, %r8;
	add.s32 	%r40, %r39, %r22;
	mad.lo.s32 	%r41, %r40, %r7, %r1;
	add.s32 	%r42, %r9, %r3;
	add.s32 	%r43, %r42, -1;
	rem.s32 	%r44, %r43, %r9;
	mad.lo.s32 	%r45, %r44, %r8, %r2;
	mad.lo.s32 	%r46, %r45, %r7, %r1;
	add.s32 	%r47, %r3, 1;
	rem.s32 	%r48, %r47, %r9;
	mad.lo.s32 	%r49, %r48, %r8, %r2;
	mad.lo.s32 	%r50, %r49, %r7, %r1;
	cvt.s64.s32	%rd4, %r29;
	mul.wide.s32 	%rd24, %r29, 4;
	add.s64 	%rd25, %rd3, %rd24;
	ld.global.f32 	%f75, [%rd25];
	cvt.s64.s32	%rd5, %r32;
	mul.wide.s32 	%rd26, %r32, 4;
	add.s64 	%rd27, %rd3, %rd26;
	ld.global.f32 	%f76, [%rd27];
	cvt.s64.s32	%rd6, %r37;
	mul.wide.s32 	%rd28, %r37, 4;
	add.s64 	%rd29, %rd3, %rd28;
	ld.global.f32 	%f77, [%rd29];
	cvt.s64.s32	%rd7, %r41;
	mul.wide.s32 	%rd30, %r41, 4;
	add.s64 	%rd31, %rd3, %rd30;
	ld.global.f32 	%f78, [%rd31];
	cvt.s64.s32	%rd8, %r46;
	mul.wide.s32 	%rd32, %r46, 4;
	add.s64 	%rd33, %rd3, %rd32;
	ld.global.f32 	%f79, [%rd33];
	cvt.s64.s32	%rd9, %r50;
	mul.wide.s32 	%rd34, %r50, 4;
	add.s64 	%rd35, %rd3, %rd34;
	ld.global.f32 	%f80, [%rd35];
	cvt.s64.s32	%rd10, %r25;
	mul.wide.s32 	%rd36, %r25, 4;
	add.s64 	%rd37, %rd2, %rd36;
	ld.global.nc.f32 	%f7, [%rd37];
	setp.eq.f32	%p31, %f7, 0f40000000;
	add.s64 	%rd11, %rd1, %rd36;
	mov.pred 	%p30, -1;
	mov.pred 	%p78, %p30;
	@%p31 bra 	BB0_5;

	ld.global.nc.f32 	%f42, [%rd11];
	setp.eq.f32	%p1, %f42, 0f40000000;
	mov.pred 	%p78, %p1;

BB0_5:
	mov.pred 	%p2, %p78;
	shl.b64 	%rd38, %rd4, 2;
	add.s64 	%rd39, %rd2, %rd38;
	ld.global.nc.f32 	%f8, [%rd39];
	setp.eq.f32	%p33, %f8, 0f3F800000;
	add.s64 	%rd12, %rd1, %rd38;
	mov.pred 	%p77, %p30;
	@%p33 bra 	BB0_7;

	ld.global.nc.f32 	%f43, [%rd12];
	setp.eq.f32	%p77, %f43, 0f3F800000;

BB0_7:
	shl.b64 	%rd40, %rd5, 2;
	add.s64 	%rd41, %rd2, %rd40;
	ld.global.nc.f32 	%f9, [%rd41];
	setp.eq.f32	%p35, %f9, 0f3F800000;
	add.s64 	%rd13, %rd1, %rd40;
	mov.pred 	%p76, %p30;
	@%p35 bra 	BB0_9;

	ld.global.nc.f32 	%f44, [%rd13];
	setp.eq.f32	%p76, %f44, 0f3F800000;

BB0_9:
	mov.pred 	%p75, %p30;
	@%p31 bra 	BB0_11;

	ld.global.nc.f32 	%f45, [%rd11];
	setp.eq.f32	%p75, %f45, 0f40000000;

BB0_11:
	selp.s32	%r51, -1, 0, %p77;
	selp.u32	%r52, 1, 0, %p76;
	add.s32 	%r53, %r52, %r51;
	selp.b32	%r5, %r53, 0, %p2;
	shl.b64 	%rd42, %rd6, 2;
	add.s64 	%rd43, %rd2, %rd42;
	ld.global.nc.f32 	%f10, [%rd43];
	setp.eq.f32	%p39, %f10, 0f3F800000;
	add.s64 	%rd14, %rd1, %rd42;
	mov.pred 	%p74, %p30;
	@%p39 bra 	BB0_13;

	ld.global.nc.f32 	%f46, [%rd14];
	setp.eq.f32	%p74, %f46, 0f3F800000;

BB0_13:
	shl.b64 	%rd44, %rd7, 2;
	add.s64 	%rd45, %rd2, %rd44;
	ld.global.nc.f32 	%f11, [%rd45];
	setp.eq.f32	%p41, %f11, 0f3F800000;
	add.s64 	%rd15, %rd1, %rd44;
	mov.pred 	%p73, %p30;
	@%p41 bra 	BB0_15;

	ld.global.nc.f32 	%f47, [%rd15];
	setp.eq.f32	%p73, %f47, 0f3F800000;

BB0_15:
	mov.pred 	%p72, %p30;
	@%p31 bra 	BB0_17;

	ld.global.nc.f32 	%f48, [%rd11];
	setp.eq.f32	%p72, %f48, 0f40000000;

BB0_17:
	selp.s32	%r54, -1, 0, %p74;
	selp.u32	%r55, 1, 0, %p73;
	add.s32 	%r56, %r55, %r54;
	selp.b32	%r6, %r56, 0, %p75;
	shl.b64 	%rd46, %rd8, 2;
	add.s64 	%rd47, %rd2, %rd46;
	ld.global.nc.f32 	%f12, [%rd47];
	setp.eq.f32	%p45, %f12, 0f3F800000;
	add.s64 	%rd16, %rd1, %rd46;
	mov.pred 	%p71, %p30;
	@%p45 bra 	BB0_19;

	ld.global.nc.f32 	%f49, [%rd16];
	setp.eq.f32	%p71, %f49, 0f3F800000;

BB0_19:
	shl.b64 	%rd48, %rd9, 2;
	add.s64 	%rd49, %rd2, %rd48;
	ld.global.nc.f32 	%f13, [%rd49];
	setp.eq.f32	%p47, %f13, 0f3F800000;
	add.s64 	%rd17, %rd1, %rd48;
	mov.pred 	%p70, %p30;
	@%p47 bra 	BB0_21;

	ld.global.nc.f32 	%f50, [%rd17];
	setp.eq.f32	%p70, %f50, 0f3F800000;

BB0_21:
	cvta.to.global.u64 	%rd50, %rd20;
	cvta.to.global.u64 	%rd51, %rd19;
	cvta.to.global.u64 	%rd52, %rd18;
	selp.s32	%r57, -1, 0, %p71;
	selp.u32	%r58, 1, 0, %p70;
	add.s32 	%r59, %r58, %r57;
	selp.b32	%r60, %r59, 0, %p72;
	cvt.rn.f32.s32	%f51, %r5;
	shl.b64 	%rd53, %rd10, 2;
	add.s64 	%rd54, %rd52, %rd53;
	ld.global.nc.f32 	%f52, [%rd54];
	cvt.rn.f32.s32	%f53, %r6;
	add.s64 	%rd55, %rd51, %rd53;
	ld.global.nc.f32 	%f54, [%rd55];
	mul.f32 	%f55, %f53, %f54;
	fma.rn.f32 	%f56, %f51, %f52, %f55;
	cvt.rn.f32.s32	%f57, %r60;
	add.s64 	%rd56, %rd50, %rd53;
	ld.global.nc.f32 	%f58, [%rd56];
	fma.rn.f32 	%f59, %f58, %f57, %f56;
	mul.lo.s32 	%r61, %r5, %r5;
	mad.lo.s32 	%r62, %r6, %r6, %r61;
	mad.lo.s32 	%r63, %r60, %r60, %r62;
	cvt.rn.f32.s32	%f60, %r63;
	div.rn.f32 	%f14, %f59, %f60;
	@%p31 bra 	BB0_35;
	bra.uni 	BB0_22;

BB0_35:
	@%p33 bra 	BB0_38;
	bra.uni 	BB0_36;

BB0_38:
	cvt.f64.f32	%fd36, %f14;
	add.f64 	%fd37, %fd36, %fd36;
	cvt.f64.f32	%fd38, %f41;
	cvt.f64.f32	%fd39, %f76;
	fma.rn.f64 	%fd40, %fd38, %fd37, %fd39;
	cvt.rn.f32.f64	%f75, %fd40;
	bra.uni 	BB0_39;

BB0_22:
	ld.global.nc.f32 	%f61, [%rd11];
	setp.neu.f32	%p49, %f61, 0f40000000;
	@%p49 bra 	BB0_47;

	ld.global.nc.f32 	%f62, [%rd12];
	setp.eq.f32	%p50, %f62, 0f3F800000;
	@%p50 bra 	BB0_26;
	bra.uni 	BB0_24;

BB0_26:
	cvt.f64.f32	%fd6, %f14;
	add.f64 	%fd7, %fd6, %fd6;
	cvt.f64.f32	%fd8, %f41;
	cvt.f64.f32	%fd9, %f76;
	fma.rn.f64 	%fd10, %fd8, %fd7, %fd9;
	cvt.rn.f32.f64	%f75, %fd10;
	bra.uni 	BB0_27;

BB0_36:
	setp.neu.f32	%p57, %f9, 0f3F800000;
	@%p57 bra 	BB0_39;

	cvt.f64.f32	%fd31, %f14;
	add.f64 	%fd32, %fd31, %fd31;
	cvt.f64.f32	%fd33, %f41;
	cvt.f64.f32	%fd34, %f75;
	fma.rn.f64 	%fd35, %fd33, %fd32, %fd34;
	cvt.rn.f32.f64	%f76, %fd35;

BB0_39:
	@%p39 bra 	BB0_42;
	bra.uni 	BB0_40;

BB0_42:
	cvt.f64.f32	%fd46, %f14;
	add.f64 	%fd47, %fd46, %fd46;
	cvt.f64.f32	%fd48, %f41;
	cvt.f64.f32	%fd49, %f78;
	fma.rn.f64 	%fd50, %fd48, %fd47, %fd49;
	cvt.rn.f32.f64	%f77, %fd50;
	bra.uni 	BB0_43;

BB0_40:
	setp.neu.f32	%p59, %f11, 0f3F800000;
	@%p59 bra 	BB0_43;

	cvt.f64.f32	%fd41, %f14;
	add.f64 	%fd42, %fd41, %fd41;
	cvt.f64.f32	%fd43, %f41;
	cvt.f64.f32	%fd44, %f77;
	fma.rn.f64 	%fd45, %fd43, %fd42, %fd44;
	cvt.rn.f32.f64	%f78, %fd45;

BB0_43:
	@%p45 bra 	BB0_46;
	bra.uni 	BB0_44;

BB0_46:
	cvt.f64.f32	%fd56, %f14;
	add.f64 	%fd57, %fd56, %fd56;
	cvt.f64.f32	%fd58, %f41;
	cvt.f64.f32	%fd59, %f80;
	fma.rn.f64 	%fd60, %fd58, %fd57, %fd59;
	cvt.rn.f32.f64	%f79, %fd60;
	bra.uni 	BB0_47;

BB0_44:
	setp.neu.f32	%p61, %f13, 0f3F800000;
	@%p61 bra 	BB0_47;

	cvt.f64.f32	%fd51, %f14;
	add.f64 	%fd52, %fd51, %fd51;
	cvt.f64.f32	%fd53, %f41;
	cvt.f64.f32	%fd54, %f79;
	fma.rn.f64 	%fd55, %fd53, %fd52, %fd54;
	cvt.rn.f32.f64	%f80, %fd55;
	bra.uni 	BB0_47;

BB0_24:
	ld.global.nc.f32 	%f63, [%rd13];
	setp.neu.f32	%p51, %f63, 0f3F800000;
	@%p51 bra 	BB0_27;

	cvt.f64.f32	%fd1, %f14;
	add.f64 	%fd2, %fd1, %fd1;
	cvt.f64.f32	%fd3, %f41;
	cvt.f64.f32	%fd4, %f75;
	fma.rn.f64 	%fd5, %fd3, %fd2, %fd4;
	cvt.rn.f32.f64	%f76, %fd5;

BB0_27:
	ld.global.nc.f32 	%f64, [%rd14];
	setp.eq.f32	%p52, %f64, 0f3F800000;
	@%p52 bra 	BB0_30;
	bra.uni 	BB0_28;

BB0_30:
	cvt.f64.f32	%fd16, %f14;
	add.f64 	%fd17, %fd16, %fd16;
	cvt.f64.f32	%fd18, %f41;
	cvt.f64.f32	%fd19, %f78;
	fma.rn.f64 	%fd20, %fd18, %fd17, %fd19;
	cvt.rn.f32.f64	%f77, %fd20;
	bra.uni 	BB0_31;

BB0_28:
	ld.global.nc.f32 	%f65, [%rd15];
	setp.neu.f32	%p53, %f65, 0f3F800000;
	@%p53 bra 	BB0_31;

	cvt.f64.f32	%fd11, %f14;
	add.f64 	%fd12, %fd11, %fd11;
	cvt.f64.f32	%fd13, %f41;
	cvt.f64.f32	%fd14, %f77;
	fma.rn.f64 	%fd15, %fd13, %fd12, %fd14;
	cvt.rn.f32.f64	%f78, %fd15;

BB0_31:
	ld.global.nc.f32 	%f66, [%rd16];
	setp.eq.f32	%p54, %f66, 0f3F800000;
	@%p54 bra 	BB0_34;
	bra.uni 	BB0_32;

BB0_34:
	cvt.f64.f32	%fd26, %f14;
	add.f64 	%fd27, %fd26, %fd26;
	cvt.f64.f32	%fd28, %f41;
	cvt.f64.f32	%fd29, %f80;
	fma.rn.f64 	%fd30, %fd28, %fd27, %fd29;
	cvt.rn.f32.f64	%f79, %fd30;
	bra.uni 	BB0_47;

BB0_32:
	ld.global.nc.f32 	%f67, [%rd17];
	setp.neu.f32	%p55, %f67, 0f3F800000;
	@%p55 bra 	BB0_47;

	cvt.f64.f32	%fd21, %f14;
	add.f64 	%fd22, %fd21, %fd21;
	cvt.f64.f32	%fd23, %f41;
	cvt.f64.f32	%fd24, %f79;
	fma.rn.f64 	%fd25, %fd23, %fd22, %fd24;
	cvt.rn.f32.f64	%f80, %fd25;

BB0_47:
	add.s64 	%rd58, %rd3, %rd53;
	ld.global.f32 	%f68, [%rd58];
	cvt.f64.f32	%fd61, %f68;
	add.f32 	%f69, %f75, %f76;
	add.f32 	%f70, %f69, %f77;
	add.f32 	%f71, %f70, %f78;
	add.f32 	%f72, %f71, %f79;
	add.f32 	%f73, %f72, %f80;
	cvt.f64.f32	%fd62, %f73;
	mul.f64 	%fd63, %fd62, 0d3FCDDDDDDDDDDDDD;
	fma.rn.f64 	%fd64, %fd61, 0dBFD999999999999A, %fd63;
	cvt.rn.f32.f64	%f74, %fd64;
	st.global.f32 	[%rd58], %f74;

BB0_48:
	ret;
}


`
   eddyLaplaceMove_ptx_50 = `
.version 5.0
.target sm_50
.address_size 64

	// .globl	eddyLaplaceMove

.visible .entry eddyLaplaceMove(
	.param .u64 eddyLaplaceMove_param_0,
	.param .u64 eddyLaplaceMove_param_1,
	.param .u64 eddyLaplaceMove_param_2,
	.param .u64 eddyLaplaceMove_param_3,
	.param .u32 eddyLaplaceMove_param_4,
	.param .u32 eddyLaplaceMove_param_5,
	.param .u32 eddyLaplaceMove_param_6,
	.param .u64 eddyLaplaceMove_param_7,
	.param .u64 eddyLaplaceMove_param_8,
	.param .u32 eddyLaplaceMove_param_9,
	.param .f32 eddyLaplaceMove_param_10
)
{
	.reg .pred 	%p<79>;
	.reg .f32 	%f<81>;
	.reg .b32 	%r<64>;
	.reg .f64 	%fd<65>;
	.reg .b64 	%rd<59>;


	ld.param.u64 	%rd21, [eddyLaplaceMove_param_0];
	ld.param.u64 	%rd18, [eddyLaplaceMove_param_1];
	ld.param.u64 	%rd19, [eddyLaplaceMove_param_2];
	ld.param.u64 	%rd20, [eddyLaplaceMove_param_3];
	ld.param.u32 	%r7, [eddyLaplaceMove_param_4];
	ld.param.u32 	%r8, [eddyLaplaceMove_param_5];
	ld.param.u32 	%r9, [eddyLaplaceMove_param_6];
	ld.param.u64 	%rd22, [eddyLaplaceMove_param_7];
	ld.param.u64 	%rd23, [eddyLaplaceMove_param_8];
	ld.param.u32 	%r10, [eddyLaplaceMove_param_9];
	ld.param.f32 	%f41, [eddyLaplaceMove_param_10];
	cvta.to.global.u64 	%rd1, %rd23;
	cvta.to.global.u64 	%rd2, %rd22;
	cvta.to.global.u64 	%rd3, %rd21;
	mov.u32 	%r11, %ntid.x;
	mov.u32 	%r12, %ctaid.x;
	mov.u32 	%r13, %tid.x;
	mad.lo.s32 	%r1, %r11, %r12, %r13;
	mov.u32 	%r14, %ntid.y;
	mov.u32 	%r15, %ctaid.y;
	mov.u32 	%r16, %tid.y;
	mad.lo.s32 	%r2, %r14, %r15, %r16;
	mov.u32 	%r17, %ntid.z;
	mov.u32 	%r18, %ctaid.z;
	mov.u32 	%r19, %tid.z;
	mad.lo.s32 	%r3, %r17, %r18, %r19;
	setp.ge.s32	%p19, %r2, %r8;
	setp.ge.s32	%p20, %r1, %r7;
	or.pred  	%p21, %p19, %p20;
	setp.ge.s32	%p22, %r3, %r9;
	or.pred  	%p23, %p21, %p22;
	@%p23 bra 	BB0_48;

	add.s32 	%r20, %r2, %r1;
	add.s32 	%r21, %r20, %r3;
	and.b32  	%r4, %r21, 1;
	setp.eq.s32	%p24, %r4, 0;
	setp.eq.s32	%p25, %r10, 1;
	and.pred  	%p26, %p25, %p24;
	@%p26 bra 	BB0_48;

	setp.eq.s32	%p27, %r10, 0;
	setp.ne.s32	%p28, %r4, 0;
	and.pred  	%p29, %p27, %p28;
	@%p29 bra 	BB0_48;

	mul.lo.s32 	%r22, %r3, %r8;
	add.s32 	%r23, %r22, %r2;
	mul.lo.s32 	%r24, %r23, %r7;
	add.s32 	%r25, %r24, %r1;
	add.s32 	%r26, %r7, %r1;
	add.s32 	%r27, %r26, -1;
	rem.s32 	%r28, %r27, %r7;
	add.s32 	%r29, %r28, %r24;
	add.s32 	%r30, %r1, 1;
	rem.s32 	%r31, %r30, %r7;
	add.s32 	%r32, %r31, %r24;
	add.s32 	%r33, %r8, %r2;
	add.s32 	%r34, %r33, -1;
	rem.s32 	%r35, %r34, %r8;
	add.s32 	%r36, %r35, %r22;
	mad.lo.s32 	%r37, %r36, %r7, %r1;
	add.s32 	%r38, %r2, 1;
	rem.s32 	%r39, %r38, %r8;
	add.s32 	%r40, %r39, %r22;
	mad.lo.s32 	%r41, %r40, %r7, %r1;
	add.s32 	%r42, %r9, %r3;
	add.s32 	%r43, %r42, -1;
	rem.s32 	%r44, %r43, %r9;
	mad.lo.s32 	%r45, %r44, %r8, %r2;
	mad.lo.s32 	%r46, %r45, %r7, %r1;
	add.s32 	%r47, %r3, 1;
	rem.s32 	%r48, %r47, %r9;
	mad.lo.s32 	%r49, %r48, %r8, %r2;
	mad.lo.s32 	%r50, %r49, %r7, %r1;
	cvt.s64.s32	%rd4, %r29;
	mul.wide.s32 	%rd24, %r29, 4;
	add.s64 	%rd25, %rd3, %rd24;
	ld.global.f32 	%f75, [%rd25];
	cvt.s64.s32	%rd5, %r32;
	mul.wide.s32 	%rd26, %r32, 4;
	add.s64 	%rd27, %rd3, %rd26;
	ld.global.f32 	%f76, [%rd27];
	cvt.s64.s32	%rd6, %r37;
	mul.wide.s32 	%rd28, %r37, 4;
	add.s64 	%rd29, %rd3, %rd28;
	ld.global.f32 	%f77, [%rd29];
	cvt.s64.s32	%rd7, %r41;
	mul.wide.s32 	%rd30, %r41, 4;
	add.s64 	%rd31, %rd3, %rd30;
	ld.global.f32 	%f78, [%rd31];
	cvt.s64.s32	%rd8, %r46;
	mul.wide.s32 	%rd32, %r46, 4;
	add.s64 	%rd33, %rd3, %rd32;
	ld.global.f32 	%f79, [%rd33];
	cvt.s64.s32	%rd9, %r50;
	mul.wide.s32 	%rd34, %r50, 4;
	add.s64 	%rd35, %rd3, %rd34;
	ld.global.f32 	%f80, [%rd35];
	cvt.s64.s32	%rd10, %r25;
	mul.wide.s32 	%rd36, %r25, 4;
	add.s64 	%rd37, %rd2, %rd36;
	ld.global.nc.f32 	%f7, [%rd37];
	setp.eq.f32	%p31, %f7, 0f40000000;
	add.s64 	%rd11, %rd1, %rd36;
	mov.pred 	%p30, -1;
	mov.pred 	%p78, %p30;
	@%p31 bra 	BB0_5;

	ld.global.nc.f32 	%f42, [%rd11];
	setp.eq.f32	%p1, %f42, 0f40000000;
	mov.pred 	%p78, %p1;

BB0_5:
	mov.pred 	%p2, %p78;
	shl.b64 	%rd38, %rd4, 2;
	add.s64 	%rd39, %rd2, %rd38;
	ld.global.nc.f32 	%f8, [%rd39];
	setp.eq.f32	%p33, %f8, 0f3F800000;
	add.s64 	%rd12, %rd1, %rd38;
	mov.pred 	%p77, %p30;
	@%p33 bra 	BB0_7;

	ld.global.nc.f32 	%f43, [%rd12];
	setp.eq.f32	%p77, %f43, 0f3F800000;

BB0_7:
	shl.b64 	%rd40, %rd5, 2;
	add.s64 	%rd41, %rd2, %rd40;
	ld.global.nc.f32 	%f9, [%rd41];
	setp.eq.f32	%p35, %f9, 0f3F800000;
	add.s64 	%rd13, %rd1, %rd40;
	mov.pred 	%p76, %p30;
	@%p35 bra 	BB0_9;

	ld.global.nc.f32 	%f44, [%rd13];
	setp.eq.f32	%p76, %f44, 0f3F800000;

BB0_9:
	mov.pred 	%p75, %p30;
	@%p31 bra 	BB0_11;

	ld.global.nc.f32 	%f45, [%rd11];
	setp.eq.f32	%p75, %f45, 0f40000000;

BB0_11:
	selp.s32	%r51, -1, 0, %p77;
	selp.u32	%r52, 1, 0, %p76;
	add.s32 	%r53, %r52, %r51;
	selp.b32	%r5, %r53, 0, %p2;
	shl.b64 	%rd42, %rd6, 2;
	add.s64 	%rd43, %rd2, %rd42;
	ld.global.nc.f32 	%f10, [%rd43];
	setp.eq.f32	%p39, %f10, 0f3F800000;
	add.s64 	%rd14, %rd1, %rd42;
	mov.pred 	%p74, %p30;
	@%p39 bra 	BB0_13;

	ld.global.nc.f32 	%f46, [%rd14];
	setp.eq.f32	%p74, %f46, 0f3F800000;

BB0_13:
	shl.b64 	%rd44, %rd7, 2;
	add.s64 	%rd45, %rd2, %rd44;
	ld.global.nc.f32 	%f11, [%rd45];
	setp.eq.f32	%p41, %f11, 0f3F800000;
	add.s64 	%rd15, %rd1, %rd44;
	mov.pred 	%p73, %p30;
	@%p41 bra 	BB0_15;

	ld.global.nc.f32 	%f47, [%rd15];
	setp.eq.f32	%p73, %f47, 0f3F800000;

BB0_15:
	mov.pred 	%p72, %p30;
	@%p31 bra 	BB0_17;

	ld.global.nc.f32 	%f48, [%rd11];
	setp.eq.f32	%p72, %f48, 0f40000000;

BB0_17:
	selp.s32	%r54, -1, 0, %p74;
	selp.u32	%r55, 1, 0, %p73;
	add.s32 	%r56, %r55, %r54;
	selp.b32	%r6, %r56, 0, %p75;
	shl.b64 	%rd46, %rd8, 2;
	add.s64 	%rd47, %rd2, %rd46;
	ld.global.nc.f32 	%f12, [%rd47];
	setp.eq.f32	%p45, %f12, 0f3F800000;
	add.s64 	%rd16, %rd1, %rd46;
	mov.pred 	%p71, %p30;
	@%p45 bra 	BB0_19;

	ld.global.nc.f32 	%f49, [%rd16];
	setp.eq.f32	%p71, %f49, 0f3F800000;

BB0_19:
	shl.b64 	%rd48, %rd9, 2;
	add.s64 	%rd49, %rd2, %rd48;
	ld.global.nc.f32 	%f13, [%rd49];
	setp.eq.f32	%p47, %f13, 0f3F800000;
	add.s64 	%rd17, %rd1, %rd48;
	mov.pred 	%p70, %p30;
	@%p47 bra 	BB0_21;

	ld.global.nc.f32 	%f50, [%rd17];
	setp.eq.f32	%p70, %f50, 0f3F800000;

BB0_21:
	cvta.to.global.u64 	%rd50, %rd20;
	cvta.to.global.u64 	%rd51, %rd19;
	cvta.to.global.u64 	%rd52, %rd18;
	selp.s32	%r57, -1, 0, %p71;
	selp.u32	%r58, 1, 0, %p70;
	add.s32 	%r59, %r58, %r57;
	selp.b32	%r60, %r59, 0, %p72;
	cvt.rn.f32.s32	%f51, %r5;
	shl.b64 	%rd53, %rd10, 2;
	add.s64 	%rd54, %rd52, %rd53;
	ld.global.nc.f32 	%f52, [%rd54];
	cvt.rn.f32.s32	%f53, %r6;
	add.s64 	%rd55, %rd51, %rd53;
	ld.global.nc.f32 	%f54, [%rd55];
	mul.f32 	%f55, %f53, %f54;
	fma.rn.f32 	%f56, %f51, %f52, %f55;
	cvt.rn.f32.s32	%f57, %r60;
	add.s64 	%rd56, %rd50, %rd53;
	ld.global.nc.f32 	%f58, [%rd56];
	fma.rn.f32 	%f59, %f58, %f57, %f56;
	mul.lo.s32 	%r61, %r5, %r5;
	mad.lo.s32 	%r62, %r6, %r6, %r61;
	mad.lo.s32 	%r63, %r60, %r60, %r62;
	cvt.rn.f32.s32	%f60, %r63;
	div.rn.f32 	%f14, %f59, %f60;
	@%p31 bra 	BB0_35;
	bra.uni 	BB0_22;

BB0_35:
	@%p33 bra 	BB0_38;
	bra.uni 	BB0_36;

BB0_38:
	cvt.f64.f32	%fd36, %f14;
	add.f64 	%fd37, %fd36, %fd36;
	cvt.f64.f32	%fd38, %f41;
	cvt.f64.f32	%fd39, %f76;
	fma.rn.f64 	%fd40, %fd38, %fd37, %fd39;
	cvt.rn.f32.f64	%f75, %fd40;
	bra.uni 	BB0_39;

BB0_22:
	ld.global.nc.f32 	%f61, [%rd11];
	setp.neu.f32	%p49, %f61, 0f40000000;
	@%p49 bra 	BB0_47;

	ld.global.nc.f32 	%f62, [%rd12];
	setp.eq.f32	%p50, %f62, 0f3F800000;
	@%p50 bra 	BB0_26;
	bra.uni 	BB0_24;

BB0_26:
	cvt.f64.f32	%fd6, %f14;
	add.f64 	%fd7, %fd6, %fd6;
	cvt.f64.f32	%fd8, %f41;
	cvt.f64.f32	%fd9, %f76;
	fma.rn.f64 	%fd10, %fd8, %fd7, %fd9;
	cvt.rn.f32.f64	%f75, %fd10;
	bra.uni 	BB0_27;

BB0_36:
	setp.neu.f32	%p57, %f9, 0f3F800000;
	@%p57 bra 	BB0_39;

	cvt.f64.f32	%fd31, %f14;
	add.f64 	%fd32, %fd31, %fd31;
	cvt.f64.f32	%fd33, %f41;
	cvt.f64.f32	%fd34, %f75;
	fma.rn.f64 	%fd35, %fd33, %fd32, %fd34;
	cvt.rn.f32.f64	%f76, %fd35;

BB0_39:
	@%p39 bra 	BB0_42;
	bra.uni 	BB0_40;

BB0_42:
	cvt.f64.f32	%fd46, %f14;
	add.f64 	%fd47, %fd46, %fd46;
	cvt.f64.f32	%fd48, %f41;
	cvt.f64.f32	%fd49, %f78;
	fma.rn.f64 	%fd50, %fd48, %fd47, %fd49;
	cvt.rn.f32.f64	%f77, %fd50;
	bra.uni 	BB0_43;

BB0_40:
	setp.neu.f32	%p59, %f11, 0f3F800000;
	@%p59 bra 	BB0_43;

	cvt.f64.f32	%fd41, %f14;
	add.f64 	%fd42, %fd41, %fd41;
	cvt.f64.f32	%fd43, %f41;
	cvt.f64.f32	%fd44, %f77;
	fma.rn.f64 	%fd45, %fd43, %fd42, %fd44;
	cvt.rn.f32.f64	%f78, %fd45;

BB0_43:
	@%p45 bra 	BB0_46;
	bra.uni 	BB0_44;

BB0_46:
	cvt.f64.f32	%fd56, %f14;
	add.f64 	%fd57, %fd56, %fd56;
	cvt.f64.f32	%fd58, %f41;
	cvt.f64.f32	%fd59, %f80;
	fma.rn.f64 	%fd60, %fd58, %fd57, %fd59;
	cvt.rn.f32.f64	%f79, %fd60;
	bra.uni 	BB0_47;

BB0_44:
	setp.neu.f32	%p61, %f13, 0f3F800000;
	@%p61 bra 	BB0_47;

	cvt.f64.f32	%fd51, %f14;
	add.f64 	%fd52, %fd51, %fd51;
	cvt.f64.f32	%fd53, %f41;
	cvt.f64.f32	%fd54, %f79;
	fma.rn.f64 	%fd55, %fd53, %fd52, %fd54;
	cvt.rn.f32.f64	%f80, %fd55;
	bra.uni 	BB0_47;

BB0_24:
	ld.global.nc.f32 	%f63, [%rd13];
	setp.neu.f32	%p51, %f63, 0f3F800000;
	@%p51 bra 	BB0_27;

	cvt.f64.f32	%fd1, %f14;
	add.f64 	%fd2, %fd1, %fd1;
	cvt.f64.f32	%fd3, %f41;
	cvt.f64.f32	%fd4, %f75;
	fma.rn.f64 	%fd5, %fd3, %fd2, %fd4;
	cvt.rn.f32.f64	%f76, %fd5;

BB0_27:
	ld.global.nc.f32 	%f64, [%rd14];
	setp.eq.f32	%p52, %f64, 0f3F800000;
	@%p52 bra 	BB0_30;
	bra.uni 	BB0_28;

BB0_30:
	cvt.f64.f32	%fd16, %f14;
	add.f64 	%fd17, %fd16, %fd16;
	cvt.f64.f32	%fd18, %f41;
	cvt.f64.f32	%fd19, %f78;
	fma.rn.f64 	%fd20, %fd18, %fd17, %fd19;
	cvt.rn.f32.f64	%f77, %fd20;
	bra.uni 	BB0_31;

BB0_28:
	ld.global.nc.f32 	%f65, [%rd15];
	setp.neu.f32	%p53, %f65, 0f3F800000;
	@%p53 bra 	BB0_31;

	cvt.f64.f32	%fd11, %f14;
	add.f64 	%fd12, %fd11, %fd11;
	cvt.f64.f32	%fd13, %f41;
	cvt.f64.f32	%fd14, %f77;
	fma.rn.f64 	%fd15, %fd13, %fd12, %fd14;
	cvt.rn.f32.f64	%f78, %fd15;

BB0_31:
	ld.global.nc.f32 	%f66, [%rd16];
	setp.eq.f32	%p54, %f66, 0f3F800000;
	@%p54 bra 	BB0_34;
	bra.uni 	BB0_32;

BB0_34:
	cvt.f64.f32	%fd26, %f14;
	add.f64 	%fd27, %fd26, %fd26;
	cvt.f64.f32	%fd28, %f41;
	cvt.f64.f32	%fd29, %f80;
	fma.rn.f64 	%fd30, %fd28, %fd27, %fd29;
	cvt.rn.f32.f64	%f79, %fd30;
	bra.uni 	BB0_47;

BB0_32:
	ld.global.nc.f32 	%f67, [%rd17];
	setp.neu.f32	%p55, %f67, 0f3F800000;
	@%p55 bra 	BB0_47;

	cvt.f64.f32	%fd21, %f14;
	add.f64 	%fd22, %fd21, %fd21;
	cvt.f64.f32	%fd23, %f41;
	cvt.f64.f32	%fd24, %f79;
	fma.rn.f64 	%fd25, %fd23, %fd22, %fd24;
	cvt.rn.f32.f64	%f80, %fd25;

BB0_47:
	add.s64 	%rd58, %rd3, %rd53;
	ld.global.f32 	%f68, [%rd58];
	cvt.f64.f32	%fd61, %f68;
	add.f32 	%f69, %f75, %f76;
	add.f32 	%f70, %f69, %f77;
	add.f32 	%f71, %f70, %f78;
	add.f32 	%f72, %f71, %f79;
	add.f32 	%f73, %f72, %f80;
	cvt.f64.f32	%fd62, %f73;
	mul.f64 	%fd63, %fd62, 0d3FCDDDDDDDDDDDDD;
	fma.rn.f64 	%fd64, %fd61, 0dBFD999999999999A, %fd63;
	cvt.rn.f32.f64	%f74, %fd64;
	st.global.f32 	[%rd58], %f74;

BB0_48:
	ret;
}


`
   eddyLaplaceMove_ptx_52 = `
.version 5.0
.target sm_52
.address_size 64

	// .globl	eddyLaplaceMove

.visible .entry eddyLaplaceMove(
	.param .u64 eddyLaplaceMove_param_0,
	.param .u64 eddyLaplaceMove_param_1,
	.param .u64 eddyLaplaceMove_param_2,
	.param .u64 eddyLaplaceMove_param_3,
	.param .u32 eddyLaplaceMove_param_4,
	.param .u32 eddyLaplaceMove_param_5,
	.param .u32 eddyLaplaceMove_param_6,
	.param .u64 eddyLaplaceMove_param_7,
	.param .u64 eddyLaplaceMove_param_8,
	.param .u32 eddyLaplaceMove_param_9,
	.param .f32 eddyLaplaceMove_param_10
)
{
	.reg .pred 	%p<79>;
	.reg .f32 	%f<81>;
	.reg .b32 	%r<64>;
	.reg .f64 	%fd<65>;
	.reg .b64 	%rd<59>;


	ld.param.u64 	%rd21, [eddyLaplaceMove_param_0];
	ld.param.u64 	%rd18, [eddyLaplaceMove_param_1];
	ld.param.u64 	%rd19, [eddyLaplaceMove_param_2];
	ld.param.u64 	%rd20, [eddyLaplaceMove_param_3];
	ld.param.u32 	%r7, [eddyLaplaceMove_param_4];
	ld.param.u32 	%r8, [eddyLaplaceMove_param_5];
	ld.param.u32 	%r9, [eddyLaplaceMove_param_6];
	ld.param.u64 	%rd22, [eddyLaplaceMove_param_7];
	ld.param.u64 	%rd23, [eddyLaplaceMove_param_8];
	ld.param.u32 	%r10, [eddyLaplaceMove_param_9];
	ld.param.f32 	%f41, [eddyLaplaceMove_param_10];
	cvta.to.global.u64 	%rd1, %rd23;
	cvta.to.global.u64 	%rd2, %rd22;
	cvta.to.global.u64 	%rd3, %rd21;
	mov.u32 	%r11, %ntid.x;
	mov.u32 	%r12, %ctaid.x;
	mov.u32 	%r13, %tid.x;
	mad.lo.s32 	%r1, %r11, %r12, %r13;
	mov.u32 	%r14, %ntid.y;
	mov.u32 	%r15, %ctaid.y;
	mov.u32 	%r16, %tid.y;
	mad.lo.s32 	%r2, %r14, %r15, %r16;
	mov.u32 	%r17, %ntid.z;
	mov.u32 	%r18, %ctaid.z;
	mov.u32 	%r19, %tid.z;
	mad.lo.s32 	%r3, %r17, %r18, %r19;
	setp.ge.s32	%p19, %r2, %r8;
	setp.ge.s32	%p20, %r1, %r7;
	or.pred  	%p21, %p19, %p20;
	setp.ge.s32	%p22, %r3, %r9;
	or.pred  	%p23, %p21, %p22;
	@%p23 bra 	BB0_48;

	add.s32 	%r20, %r2, %r1;
	add.s32 	%r21, %r20, %r3;
	and.b32  	%r4, %r21, 1;
	setp.eq.s32	%p24, %r4, 0;
	setp.eq.s32	%p25, %r10, 1;
	and.pred  	%p26, %p25, %p24;
	@%p26 bra 	BB0_48;

	setp.eq.s32	%p27, %r10, 0;
	setp.ne.s32	%p28, %r4, 0;
	and.pred  	%p29, %p27, %p28;
	@%p29 bra 	BB0_48;

	mul.lo.s32 	%r22, %r3, %r8;
	add.s32 	%r23, %r22, %r2;
	mul.lo.s32 	%r24, %r23, %r7;
	add.s32 	%r25, %r24, %r1;
	add.s32 	%r26, %r7, %r1;
	add.s32 	%r27, %r26, -1;
	rem.s32 	%r28, %r27, %r7;
	add.s32 	%r29, %r28, %r24;
	add.s32 	%r30, %r1, 1;
	rem.s32 	%r31, %r30, %r7;
	add.s32 	%r32, %r31, %r24;
	add.s32 	%r33, %r8, %r2;
	add.s32 	%r34, %r33, -1;
	rem.s32 	%r35, %r34, %r8;
	add.s32 	%r36, %r35, %r22;
	mad.lo.s32 	%r37, %r36, %r7, %r1;
	add.s32 	%r38, %r2, 1;
	rem.s32 	%r39, %r38, %r8;
	add.s32 	%r40, %r39, %r22;
	mad.lo.s32 	%r41, %r40, %r7, %r1;
	add.s32 	%r42, %r9, %r3;
	add.s32 	%r43, %r42, -1;
	rem.s32 	%r44, %r43, %r9;
	mad.lo.s32 	%r45, %r44, %r8, %r2;
	mad.lo.s32 	%r46, %r45, %r7, %r1;
	add.s32 	%r47, %r3, 1;
	rem.s32 	%r48, %r47, %r9;
	mad.lo.s32 	%r49, %r48, %r8, %r2;
	mad.lo.s32 	%r50, %r49, %r7, %r1;
	cvt.s64.s32	%rd4, %r29;
	mul.wide.s32 	%rd24, %r29, 4;
	add.s64 	%rd25, %rd3, %rd24;
	ld.global.f32 	%f75, [%rd25];
	cvt.s64.s32	%rd5, %r32;
	mul.wide.s32 	%rd26, %r32, 4;
	add.s64 	%rd27, %rd3, %rd26;
	ld.global.f32 	%f76, [%rd27];
	cvt.s64.s32	%rd6, %r37;
	mul.wide.s32 	%rd28, %r37, 4;
	add.s64 	%rd29, %rd3, %rd28;
	ld.global.f32 	%f77, [%rd29];
	cvt.s64.s32	%rd7, %r41;
	mul.wide.s32 	%rd30, %r41, 4;
	add.s64 	%rd31, %rd3, %rd30;
	ld.global.f32 	%f78, [%rd31];
	cvt.s64.s32	%rd8, %r46;
	mul.wide.s32 	%rd32, %r46, 4;
	add.s64 	%rd33, %rd3, %rd32;
	ld.global.f32 	%f79, [%rd33];
	cvt.s64.s32	%rd9, %r50;
	mul.wide.s32 	%rd34, %r50, 4;
	add.s64 	%rd35, %rd3, %rd34;
	ld.global.f32 	%f80, [%rd35];
	cvt.s64.s32	%rd10, %r25;
	mul.wide.s32 	%rd36, %r25, 4;
	add.s64 	%rd37, %rd2, %rd36;
	ld.global.nc.f32 	%f7, [%rd37];
	setp.eq.f32	%p31, %f7, 0f40000000;
	add.s64 	%rd11, %rd1, %rd36;
	mov.pred 	%p30, -1;
	mov.pred 	%p78, %p30;
	@%p31 bra 	BB0_5;

	ld.global.nc.f32 	%f42, [%rd11];
	setp.eq.f32	%p1, %f42, 0f40000000;
	mov.pred 	%p78, %p1;

BB0_5:
	mov.pred 	%p2, %p78;
	shl.b64 	%rd38, %rd4, 2;
	add.s64 	%rd39, %rd2, %rd38;
	ld.global.nc.f32 	%f8, [%rd39];
	setp.eq.f32	%p33, %f8, 0f3F800000;
	add.s64 	%rd12, %rd1, %rd38;
	mov.pred 	%p77, %p30;
	@%p33 bra 	BB0_7;

	ld.global.nc.f32 	%f43, [%rd12];
	setp.eq.f32	%p77, %f43, 0f3F800000;

BB0_7:
	shl.b64 	%rd40, %rd5, 2;
	add.s64 	%rd41, %rd2, %rd40;
	ld.global.nc.f32 	%f9, [%rd41];
	setp.eq.f32	%p35, %f9, 0f3F800000;
	add.s64 	%rd13, %rd1, %rd40;
	mov.pred 	%p76, %p30;
	@%p35 bra 	BB0_9;

	ld.global.nc.f32 	%f44, [%rd13];
	setp.eq.f32	%p76, %f44, 0f3F800000;

BB0_9:
	mov.pred 	%p75, %p30;
	@%p31 bra 	BB0_11;

	ld.global.nc.f32 	%f45, [%rd11];
	setp.eq.f32	%p75, %f45, 0f40000000;

BB0_11:
	selp.s32	%r51, -1, 0, %p77;
	selp.u32	%r52, 1, 0, %p76;
	add.s32 	%r53, %r52, %r51;
	selp.b32	%r5, %r53, 0, %p2;
	shl.b64 	%rd42, %rd6, 2;
	add.s64 	%rd43, %rd2, %rd42;
	ld.global.nc.f32 	%f10, [%rd43];
	setp.eq.f32	%p39, %f10, 0f3F800000;
	add.s64 	%rd14, %rd1, %rd42;
	mov.pred 	%p74, %p30;
	@%p39 bra 	BB0_13;

	ld.global.nc.f32 	%f46, [%rd14];
	setp.eq.f32	%p74, %f46, 0f3F800000;

BB0_13:
	shl.b64 	%rd44, %rd7, 2;
	add.s64 	%rd45, %rd2, %rd44;
	ld.global.nc.f32 	%f11, [%rd45];
	setp.eq.f32	%p41, %f11, 0f3F800000;
	add.s64 	%rd15, %rd1, %rd44;
	mov.pred 	%p73, %p30;
	@%p41 bra 	BB0_15;

	ld.global.nc.f32 	%f47, [%rd15];
	setp.eq.f32	%p73, %f47, 0f3F800000;

BB0_15:
	mov.pred 	%p72, %p30;
	@%p31 bra 	BB0_17;

	ld.global.nc.f32 	%f48, [%rd11];
	setp.eq.f32	%p72, %f48, 0f40000000;

BB0_17:
	selp.s32	%r54, -1, 0, %p74;
	selp.u32	%r55, 1, 0, %p73;
	add.s32 	%r56, %r55, %r54;
	selp.b32	%r6, %r56, 0, %p75;
	shl.b64 	%rd46, %rd8, 2;
	add.s64 	%rd47, %rd2, %rd46;
	ld.global.nc.f32 	%f12, [%rd47];
	setp.eq.f32	%p45, %f12, 0f3F800000;
	add.s64 	%rd16, %rd1, %rd46;
	mov.pred 	%p71, %p30;
	@%p45 bra 	BB0_19;

	ld.global.nc.f32 	%f49, [%rd16];
	setp.eq.f32	%p71, %f49, 0f3F800000;

BB0_19:
	shl.b64 	%rd48, %rd9, 2;
	add.s64 	%rd49, %rd2, %rd48;
	ld.global.nc.f32 	%f13, [%rd49];
	setp.eq.f32	%p47, %f13, 0f3F800000;
	add.s64 	%rd17, %rd1, %rd48;
	mov.pred 	%p70, %p30;
	@%p47 bra 	BB0_21;

	ld.global.nc.f32 	%f50, [%rd17];
	setp.eq.f32	%p70, %f50, 0f3F800000;

BB0_21:
	cvta.to.global.u64 	%rd50, %rd20;
	cvta.to.global.u64 	%rd51, %rd19;
	cvta.to.global.u64 	%rd52, %rd18;
	selp.s32	%r57, -1, 0, %p71;
	selp.u32	%r58, 1, 0, %p70;
	add.s32 	%r59, %r58, %r57;
	selp.b32	%r60, %r59, 0, %p72;
	cvt.rn.f32.s32	%f51, %r5;
	shl.b64 	%rd53, %rd10, 2;
	add.s64 	%rd54, %rd52, %rd53;
	ld.global.nc.f32 	%f52, [%rd54];
	cvt.rn.f32.s32	%f53, %r6;
	add.s64 	%rd55, %rd51, %rd53;
	ld.global.nc.f32 	%f54, [%rd55];
	mul.f32 	%f55, %f53, %f54;
	fma.rn.f32 	%f56, %f51, %f52, %f55;
	cvt.rn.f32.s32	%f57, %r60;
	add.s64 	%rd56, %rd50, %rd53;
	ld.global.nc.f32 	%f58, [%rd56];
	fma.rn.f32 	%f59, %f58, %f57, %f56;
	mul.lo.s32 	%r61, %r5, %r5;
	mad.lo.s32 	%r62, %r6, %r6, %r61;
	mad.lo.s32 	%r63, %r60, %r60, %r62;
	cvt.rn.f32.s32	%f60, %r63;
	div.rn.f32 	%f14, %f59, %f60;
	@%p31 bra 	BB0_35;
	bra.uni 	BB0_22;

BB0_35:
	@%p33 bra 	BB0_38;
	bra.uni 	BB0_36;

BB0_38:
	cvt.f64.f32	%fd36, %f14;
	add.f64 	%fd37, %fd36, %fd36;
	cvt.f64.f32	%fd38, %f41;
	cvt.f64.f32	%fd39, %f76;
	fma.rn.f64 	%fd40, %fd38, %fd37, %fd39;
	cvt.rn.f32.f64	%f75, %fd40;
	bra.uni 	BB0_39;

BB0_22:
	ld.global.nc.f32 	%f61, [%rd11];
	setp.neu.f32	%p49, %f61, 0f40000000;
	@%p49 bra 	BB0_47;

	ld.global.nc.f32 	%f62, [%rd12];
	setp.eq.f32	%p50, %f62, 0f3F800000;
	@%p50 bra 	BB0_26;
	bra.uni 	BB0_24;

BB0_26:
	cvt.f64.f32	%fd6, %f14;
	add.f64 	%fd7, %fd6, %fd6;
	cvt.f64.f32	%fd8, %f41;
	cvt.f64.f32	%fd9, %f76;
	fma.rn.f64 	%fd10, %fd8, %fd7, %fd9;
	cvt.rn.f32.f64	%f75, %fd10;
	bra.uni 	BB0_27;

BB0_36:
	setp.neu.f32	%p57, %f9, 0f3F800000;
	@%p57 bra 	BB0_39;

	cvt.f64.f32	%fd31, %f14;
	add.f64 	%fd32, %fd31, %fd31;
	cvt.f64.f32	%fd33, %f41;
	cvt.f64.f32	%fd34, %f75;
	fma.rn.f64 	%fd35, %fd33, %fd32, %fd34;
	cvt.rn.f32.f64	%f76, %fd35;

BB0_39:
	@%p39 bra 	BB0_42;
	bra.uni 	BB0_40;

BB0_42:
	cvt.f64.f32	%fd46, %f14;
	add.f64 	%fd47, %fd46, %fd46;
	cvt.f64.f32	%fd48, %f41;
	cvt.f64.f32	%fd49, %f78;
	fma.rn.f64 	%fd50, %fd48, %fd47, %fd49;
	cvt.rn.f32.f64	%f77, %fd50;
	bra.uni 	BB0_43;

BB0_40:
	setp.neu.f32	%p59, %f11, 0f3F800000;
	@%p59 bra 	BB0_43;

	cvt.f64.f32	%fd41, %f14;
	add.f64 	%fd42, %fd41, %fd41;
	cvt.f64.f32	%fd43, %f41;
	cvt.f64.f32	%fd44, %f77;
	fma.rn.f64 	%fd45, %fd43, %fd42, %fd44;
	cvt.rn.f32.f64	%f78, %fd45;

BB0_43:
	@%p45 bra 	BB0_46;
	bra.uni 	BB0_44;

BB0_46:
	cvt.f64.f32	%fd56, %f14;
	add.f64 	%fd57, %fd56, %fd56;
	cvt.f64.f32	%fd58, %f41;
	cvt.f64.f32	%fd59, %f80;
	fma.rn.f64 	%fd60, %fd58, %fd57, %fd59;
	cvt.rn.f32.f64	%f79, %fd60;
	bra.uni 	BB0_47;

BB0_44:
	setp.neu.f32	%p61, %f13, 0f3F800000;
	@%p61 bra 	BB0_47;

	cvt.f64.f32	%fd51, %f14;
	add.f64 	%fd52, %fd51, %fd51;
	cvt.f64.f32	%fd53, %f41;
	cvt.f64.f32	%fd54, %f79;
	fma.rn.f64 	%fd55, %fd53, %fd52, %fd54;
	cvt.rn.f32.f64	%f80, %fd55;
	bra.uni 	BB0_47;

BB0_24:
	ld.global.nc.f32 	%f63, [%rd13];
	setp.neu.f32	%p51, %f63, 0f3F800000;
	@%p51 bra 	BB0_27;

	cvt.f64.f32	%fd1, %f14;
	add.f64 	%fd2, %fd1, %fd1;
	cvt.f64.f32	%fd3, %f41;
	cvt.f64.f32	%fd4, %f75;
	fma.rn.f64 	%fd5, %fd3, %fd2, %fd4;
	cvt.rn.f32.f64	%f76, %fd5;

BB0_27:
	ld.global.nc.f32 	%f64, [%rd14];
	setp.eq.f32	%p52, %f64, 0f3F800000;
	@%p52 bra 	BB0_30;
	bra.uni 	BB0_28;

BB0_30:
	cvt.f64.f32	%fd16, %f14;
	add.f64 	%fd17, %fd16, %fd16;
	cvt.f64.f32	%fd18, %f41;
	cvt.f64.f32	%fd19, %f78;
	fma.rn.f64 	%fd20, %fd18, %fd17, %fd19;
	cvt.rn.f32.f64	%f77, %fd20;
	bra.uni 	BB0_31;

BB0_28:
	ld.global.nc.f32 	%f65, [%rd15];
	setp.neu.f32	%p53, %f65, 0f3F800000;
	@%p53 bra 	BB0_31;

	cvt.f64.f32	%fd11, %f14;
	add.f64 	%fd12, %fd11, %fd11;
	cvt.f64.f32	%fd13, %f41;
	cvt.f64.f32	%fd14, %f77;
	fma.rn.f64 	%fd15, %fd13, %fd12, %fd14;
	cvt.rn.f32.f64	%f78, %fd15;

BB0_31:
	ld.global.nc.f32 	%f66, [%rd16];
	setp.eq.f32	%p54, %f66, 0f3F800000;
	@%p54 bra 	BB0_34;
	bra.uni 	BB0_32;

BB0_34:
	cvt.f64.f32	%fd26, %f14;
	add.f64 	%fd27, %fd26, %fd26;
	cvt.f64.f32	%fd28, %f41;
	cvt.f64.f32	%fd29, %f80;
	fma.rn.f64 	%fd30, %fd28, %fd27, %fd29;
	cvt.rn.f32.f64	%f79, %fd30;
	bra.uni 	BB0_47;

BB0_32:
	ld.global.nc.f32 	%f67, [%rd17];
	setp.neu.f32	%p55, %f67, 0f3F800000;
	@%p55 bra 	BB0_47;

	cvt.f64.f32	%fd21, %f14;
	add.f64 	%fd22, %fd21, %fd21;
	cvt.f64.f32	%fd23, %f41;
	cvt.f64.f32	%fd24, %f79;
	fma.rn.f64 	%fd25, %fd23, %fd22, %fd24;
	cvt.rn.f32.f64	%f80, %fd25;

BB0_47:
	add.s64 	%rd58, %rd3, %rd53;
	ld.global.f32 	%f68, [%rd58];
	cvt.f64.f32	%fd61, %f68;
	add.f32 	%f69, %f75, %f76;
	add.f32 	%f70, %f69, %f77;
	add.f32 	%f71, %f70, %f78;
	add.f32 	%f72, %f71, %f79;
	add.f32 	%f73, %f72, %f80;
	cvt.f64.f32	%fd62, %f73;
	mul.f64 	%fd63, %fd62, 0d3FCDDDDDDDDDDDDD;
	fma.rn.f64 	%fd64, %fd61, 0dBFD999999999999A, %fd63;
	cvt.rn.f32.f64	%f74, %fd64;
	st.global.f32 	[%rd58], %f74;

BB0_48:
	ret;
}


`
   eddyLaplaceMove_ptx_53 = `
.version 5.0
.target sm_20
.address_size 64

	// .globl	eddyLaplaceMove

.visible .entry eddyLaplaceMove(
	.param .u64 eddyLaplaceMove_param_0,
	.param .u64 eddyLaplaceMove_param_1,
	.param .u64 eddyLaplaceMove_param_2,
	.param .u64 eddyLaplaceMove_param_3,
	.param .u32 eddyLaplaceMove_param_4,
	.param .u32 eddyLaplaceMove_param_5,
	.param .u32 eddyLaplaceMove_param_6,
	.param .u64 eddyLaplaceMove_param_7,
	.param .u64 eddyLaplaceMove_param_8,
	.param .u32 eddyLaplaceMove_param_9,
	.param .f32 eddyLaplaceMove_param_10
)
{
	.reg .pred 	%p<79>;
	.reg .f32 	%f<81>;
	.reg .b32 	%r<120>;
	.reg .f64 	%fd<65>;
	.reg .b64 	%rd<71>;


	ld.param.u64 	%rd16, [eddyLaplaceMove_param_0];
	ld.param.u64 	%rd17, [eddyLaplaceMove_param_1];
	ld.param.u64 	%rd18, [eddyLaplaceMove_param_2];
	ld.param.u64 	%rd19, [eddyLaplaceMove_param_3];
	ld.param.u32 	%r7, [eddyLaplaceMove_param_4];
	ld.param.u32 	%r8, [eddyLaplaceMove_param_5];
	ld.param.u32 	%r9, [eddyLaplaceMove_param_6];
	ld.param.u64 	%rd20, [eddyLaplaceMove_param_7];
	ld.param.u64 	%rd21, [eddyLaplaceMove_param_8];
	ld.param.u32 	%r10, [eddyLaplaceMove_param_9];
	ld.param.f32 	%f41, [eddyLaplaceMove_param_10];
	cvta.to.global.u64 	%rd1, %rd21;
	cvta.to.global.u64 	%rd2, %rd20;
	mov.u32 	%r11, %ntid.x;
	mov.u32 	%r12, %ctaid.x;
	mov.u32 	%r13, %tid.x;
	mad.lo.s32 	%r1, %r11, %r12, %r13;
	mov.u32 	%r14, %ntid.y;
	mov.u32 	%r15, %ctaid.y;
	mov.u32 	%r16, %tid.y;
	mad.lo.s32 	%r2, %r14, %r15, %r16;
	mov.u32 	%r17, %ntid.z;
	mov.u32 	%r18, %ctaid.z;
	mov.u32 	%r19, %tid.z;
	mad.lo.s32 	%r3, %r17, %r18, %r19;
	setp.ge.s32	%p19, %r2, %r8;
	setp.ge.s32	%p20, %r1, %r7;
	or.pred  	%p21, %p19, %p20;
	setp.ge.s32	%p22, %r3, %r9;
	or.pred  	%p23, %p21, %p22;
	@%p23 bra 	BB0_48;

	add.s32 	%r20, %r2, %r1;
	add.s32 	%r21, %r20, %r3;
	and.b32  	%r4, %r21, 1;
	setp.eq.s32	%p24, %r4, 0;
	setp.eq.s32	%p25, %r10, 1;
	and.pred  	%p26, %p25, %p24;
	@%p26 bra 	BB0_48;

	setp.eq.s32	%p27, %r10, 0;
	setp.ne.s32	%p28, %r4, 0;
	and.pred  	%p29, %p27, %p28;
	@%p29 bra 	BB0_48;

	mul.lo.s32 	%r22, %r3, %r8;
	add.s32 	%r23, %r22, %r2;
	mul.lo.s32 	%r24, %r23, %r7;
	cvta.to.global.u64 	%rd22, %rd16;
	add.s32 	%r25, %r24, %r1;
	add.s32 	%r26, %r7, %r1;
	add.s32 	%r27, %r26, -1;
	rem.s32 	%r28, %r27, %r7;
	add.s32 	%r29, %r28, %r24;
	add.s32 	%r30, %r1, 1;
	rem.s32 	%r31, %r30, %r7;
	add.s32 	%r32, %r31, %r24;
	add.s32 	%r33, %r8, %r2;
	add.s32 	%r34, %r33, -1;
	rem.s32 	%r35, %r34, %r8;
	add.s32 	%r36, %r35, %r22;
	mad.lo.s32 	%r37, %r36, %r7, %r1;
	add.s32 	%r38, %r2, 1;
	rem.s32 	%r39, %r38, %r8;
	add.s32 	%r40, %r39, %r22;
	mad.lo.s32 	%r41, %r40, %r7, %r1;
	add.s32 	%r42, %r9, %r3;
	add.s32 	%r43, %r42, -1;
	rem.s32 	%r44, %r43, %r9;
	mad.lo.s32 	%r45, %r44, %r8, %r2;
	mad.lo.s32 	%r46, %r45, %r7, %r1;
	add.s32 	%r47, %r3, 1;
	rem.s32 	%r48, %r47, %r9;
	mad.lo.s32 	%r49, %r48, %r8, %r2;
	mad.lo.s32 	%r50, %r49, %r7, %r1;
	cvt.s64.s32	%rd3, %r29;
	mul.wide.s32 	%rd23, %r29, 4;
	add.s64 	%rd24, %rd22, %rd23;
	ld.global.f32 	%f75, [%rd24];
	cvt.s64.s32	%rd4, %r32;
	mul.wide.s32 	%rd25, %r32, 4;
	add.s64 	%rd26, %rd22, %rd25;
	ld.global.f32 	%f76, [%rd26];
	cvt.s64.s32	%rd5, %r37;
	mul.wide.s32 	%rd27, %r37, 4;
	add.s64 	%rd28, %rd22, %rd27;
	ld.global.f32 	%f77, [%rd28];
	cvt.s64.s32	%rd6, %r41;
	mul.wide.s32 	%rd29, %r41, 4;
	add.s64 	%rd30, %rd22, %rd29;
	ld.global.f32 	%f78, [%rd30];
	cvt.s64.s32	%rd7, %r46;
	mul.wide.s32 	%rd31, %r46, 4;
	add.s64 	%rd32, %rd22, %rd31;
	ld.global.f32 	%f79, [%rd32];
	cvt.s64.s32	%rd8, %r50;
	mul.wide.s32 	%rd33, %r50, 4;
	add.s64 	%rd34, %rd22, %rd33;
	ld.global.f32 	%f80, [%rd34];
	mul.wide.s32 	%rd35, %r25, 4;
	add.s64 	%rd36, %rd2, %rd35;
	ld.global.f32 	%f7, [%rd36];
	setp.eq.f32	%p31, %f7, 0f40000000;
	add.s64 	%rd9, %rd1, %rd35;
	mov.pred 	%p30, -1;
	mov.pred 	%p78, %p30;
	@%p31 bra 	BB0_5;

	ld.global.f32 	%f42, [%rd9];
	setp.eq.f32	%p1, %f42, 0f40000000;
	mov.pred 	%p78, %p1;

BB0_5:
	mov.pred 	%p2, %p78;
	shl.b64 	%rd37, %rd3, 2;
	add.s64 	%rd38, %rd2, %rd37;
	ld.global.f32 	%f8, [%rd38];
	setp.eq.f32	%p33, %f8, 0f3F800000;
	add.s64 	%rd10, %rd1, %rd37;
	mov.pred 	%p77, %p30;
	@%p33 bra 	BB0_7;

	ld.global.f32 	%f43, [%rd10];
	setp.eq.f32	%p77, %f43, 0f3F800000;

BB0_7:
	shl.b64 	%rd39, %rd4, 2;
	add.s64 	%rd40, %rd2, %rd39;
	ld.global.f32 	%f9, [%rd40];
	setp.eq.f32	%p35, %f9, 0f3F800000;
	add.s64 	%rd11, %rd1, %rd39;
	mov.pred 	%p76, %p30;
	@%p35 bra 	BB0_9;

	ld.global.f32 	%f44, [%rd11];
	setp.eq.f32	%p76, %f44, 0f3F800000;

BB0_9:
	selp.s32	%r51, -1, 0, %p77;
	selp.u32	%r52, 1, 0, %p76;
	add.s32 	%r53, %r52, %r51;
	selp.b32	%r5, %r53, 0, %p2;
	mov.pred 	%p75, %p30;
	@%p31 bra 	BB0_11;

	ld.global.f32 	%f45, [%rd9];
	setp.eq.f32	%p75, %f45, 0f40000000;

BB0_11:
	shl.b64 	%rd41, %rd5, 2;
	add.s64 	%rd42, %rd2, %rd41;
	ld.global.f32 	%f10, [%rd42];
	setp.eq.f32	%p39, %f10, 0f3F800000;
	add.s64 	%rd12, %rd1, %rd41;
	mov.pred 	%p74, %p30;
	@%p39 bra 	BB0_13;

	ld.global.f32 	%f46, [%rd12];
	setp.eq.f32	%p74, %f46, 0f3F800000;

BB0_13:
	shl.b64 	%rd44, %rd6, 2;
	add.s64 	%rd45, %rd2, %rd44;
	ld.global.f32 	%f11, [%rd45];
	setp.eq.f32	%p41, %f11, 0f3F800000;
	add.s64 	%rd13, %rd1, %rd44;
	mov.pred 	%p73, %p30;
	@%p41 bra 	BB0_15;

	ld.global.f32 	%f47, [%rd13];
	setp.eq.f32	%p73, %f47, 0f3F800000;

BB0_15:
	selp.s32	%r54, -1, 0, %p74;
	selp.u32	%r55, 1, 0, %p73;
	add.s32 	%r56, %r55, %r54;
	selp.b32	%r6, %r56, 0, %p75;
	mov.pred 	%p72, %p30;
	@%p31 bra 	BB0_17;

	mad.lo.s32 	%r65, %r3, %r8, %r2;
	mad.lo.s32 	%r70, %r65, %r7, %r1;
	mul.wide.s32 	%rd48, %r70, 4;
	add.s64 	%rd49, %rd1, %rd48;
	ld.global.f32 	%f48, [%rd49];
	setp.eq.f32	%p72, %f48, 0f40000000;

BB0_17:
	shl.b64 	%rd51, %rd7, 2;
	add.s64 	%rd52, %rd2, %rd51;
	ld.global.f32 	%f12, [%rd52];
	setp.eq.f32	%p45, %f12, 0f3F800000;
	add.s64 	%rd14, %rd1, %rd51;
	mov.pred 	%p71, %p30;
	@%p45 bra 	BB0_19;

	ld.global.f32 	%f49, [%rd14];
	setp.eq.f32	%p71, %f49, 0f3F800000;

BB0_19:
	shl.b64 	%rd55, %rd8, 2;
	add.s64 	%rd56, %rd2, %rd55;
	ld.global.f32 	%f13, [%rd56];
	setp.eq.f32	%p47, %f13, 0f3F800000;
	add.s64 	%rd15, %rd1, %rd55;
	mov.pred 	%p70, %p30;
	@%p47 bra 	BB0_21;

	ld.global.f32 	%f50, [%rd15];
	setp.eq.f32	%p70, %f50, 0f3F800000;

BB0_21:
	selp.s32	%r71, -1, 0, %p71;
	selp.u32	%r72, 1, 0, %p70;
	add.s32 	%r73, %r72, %r71;
	selp.b32	%r74, %r73, 0, %p72;
	mad.lo.s32 	%r83, %r3, %r8, %r2;
	mad.lo.s32 	%r88, %r83, %r7, %r1;
	cvta.to.global.u64 	%rd58, %rd17;
	mul.wide.s32 	%rd59, %r88, 4;
	add.s64 	%rd60, %rd58, %rd59;
	cvt.rn.f32.s32	%f51, %r5;
	ld.global.f32 	%f52, [%rd60];
	cvta.to.global.u64 	%rd61, %rd18;
	add.s64 	%rd62, %rd61, %rd59;
	cvt.rn.f32.s32	%f53, %r6;
	ld.global.f32 	%f54, [%rd62];
	mul.f32 	%f55, %f53, %f54;
	fma.rn.f32 	%f56, %f51, %f52, %f55;
	cvta.to.global.u64 	%rd63, %rd19;
	add.s64 	%rd64, %rd63, %rd59;
	cvt.rn.f32.s32	%f57, %r74;
	ld.global.f32 	%f58, [%rd64];
	fma.rn.f32 	%f59, %f58, %f57, %f56;
	mul.lo.s32 	%r89, %r5, %r5;
	mad.lo.s32 	%r90, %r6, %r6, %r89;
	mad.lo.s32 	%r91, %r74, %r74, %r90;
	cvt.rn.f32.s32	%f60, %r91;
	div.rn.f32 	%f14, %f59, %f60;
	@%p31 bra 	BB0_35;
	bra.uni 	BB0_22;

BB0_35:
	@%p33 bra 	BB0_38;
	bra.uni 	BB0_36;

BB0_38:
	cvt.f64.f32	%fd36, %f14;
	add.f64 	%fd37, %fd36, %fd36;
	cvt.f64.f32	%fd38, %f41;
	cvt.f64.f32	%fd39, %f76;
	fma.rn.f64 	%fd40, %fd38, %fd37, %fd39;
	cvt.rn.f32.f64	%f75, %fd40;
	bra.uni 	BB0_39;

BB0_22:
	add.s64 	%rd67, %rd1, %rd59;
	ld.global.f32 	%f61, [%rd67];
	setp.neu.f32	%p49, %f61, 0f40000000;
	@%p49 bra 	BB0_47;

	ld.global.f32 	%f62, [%rd10];
	setp.eq.f32	%p50, %f62, 0f3F800000;
	@%p50 bra 	BB0_26;
	bra.uni 	BB0_24;

BB0_26:
	cvt.f64.f32	%fd6, %f14;
	add.f64 	%fd7, %fd6, %fd6;
	cvt.f64.f32	%fd8, %f41;
	cvt.f64.f32	%fd9, %f76;
	fma.rn.f64 	%fd10, %fd8, %fd7, %fd9;
	cvt.rn.f32.f64	%f75, %fd10;
	bra.uni 	BB0_27;

BB0_36:
	setp.neu.f32	%p57, %f9, 0f3F800000;
	@%p57 bra 	BB0_39;

	cvt.f64.f32	%fd31, %f14;
	add.f64 	%fd32, %fd31, %fd31;
	cvt.f64.f32	%fd33, %f41;
	cvt.f64.f32	%fd34, %f75;
	fma.rn.f64 	%fd35, %fd33, %fd32, %fd34;
	cvt.rn.f32.f64	%f76, %fd35;

BB0_39:
	@%p39 bra 	BB0_42;
	bra.uni 	BB0_40;

BB0_42:
	cvt.f64.f32	%fd46, %f14;
	add.f64 	%fd47, %fd46, %fd46;
	cvt.f64.f32	%fd48, %f41;
	cvt.f64.f32	%fd49, %f78;
	fma.rn.f64 	%fd50, %fd48, %fd47, %fd49;
	cvt.rn.f32.f64	%f77, %fd50;
	bra.uni 	BB0_43;

BB0_40:
	setp.neu.f32	%p59, %f11, 0f3F800000;
	@%p59 bra 	BB0_43;

	cvt.f64.f32	%fd41, %f14;
	add.f64 	%fd42, %fd41, %fd41;
	cvt.f64.f32	%fd43, %f41;
	cvt.f64.f32	%fd44, %f77;
	fma.rn.f64 	%fd45, %fd43, %fd42, %fd44;
	cvt.rn.f32.f64	%f78, %fd45;

BB0_43:
	@%p45 bra 	BB0_46;
	bra.uni 	BB0_44;

BB0_46:
	cvt.f64.f32	%fd56, %f14;
	add.f64 	%fd57, %fd56, %fd56;
	cvt.f64.f32	%fd58, %f41;
	cvt.f64.f32	%fd59, %f80;
	fma.rn.f64 	%fd60, %fd58, %fd57, %fd59;
	cvt.rn.f32.f64	%f79, %fd60;
	bra.uni 	BB0_47;

BB0_44:
	setp.neu.f32	%p61, %f13, 0f3F800000;
	@%p61 bra 	BB0_47;

	cvt.f64.f32	%fd51, %f14;
	add.f64 	%fd52, %fd51, %fd51;
	cvt.f64.f32	%fd53, %f41;
	cvt.f64.f32	%fd54, %f79;
	fma.rn.f64 	%fd55, %fd53, %fd52, %fd54;
	cvt.rn.f32.f64	%f80, %fd55;
	bra.uni 	BB0_47;

BB0_24:
	ld.global.f32 	%f63, [%rd11];
	setp.neu.f32	%p51, %f63, 0f3F800000;
	@%p51 bra 	BB0_27;

	cvt.f64.f32	%fd1, %f14;
	add.f64 	%fd2, %fd1, %fd1;
	cvt.f64.f32	%fd3, %f41;
	cvt.f64.f32	%fd4, %f75;
	fma.rn.f64 	%fd5, %fd3, %fd2, %fd4;
	cvt.rn.f32.f64	%f76, %fd5;

BB0_27:
	ld.global.f32 	%f64, [%rd12];
	setp.eq.f32	%p52, %f64, 0f3F800000;
	@%p52 bra 	BB0_30;
	bra.uni 	BB0_28;

BB0_30:
	cvt.f64.f32	%fd16, %f14;
	add.f64 	%fd17, %fd16, %fd16;
	cvt.f64.f32	%fd18, %f41;
	cvt.f64.f32	%fd19, %f78;
	fma.rn.f64 	%fd20, %fd18, %fd17, %fd19;
	cvt.rn.f32.f64	%f77, %fd20;
	bra.uni 	BB0_31;

BB0_28:
	ld.global.f32 	%f65, [%rd13];
	setp.neu.f32	%p53, %f65, 0f3F800000;
	@%p53 bra 	BB0_31;

	cvt.f64.f32	%fd11, %f14;
	add.f64 	%fd12, %fd11, %fd11;
	cvt.f64.f32	%fd13, %f41;
	cvt.f64.f32	%fd14, %f77;
	fma.rn.f64 	%fd15, %fd13, %fd12, %fd14;
	cvt.rn.f32.f64	%f78, %fd15;

BB0_31:
	ld.global.f32 	%f66, [%rd14];
	setp.eq.f32	%p54, %f66, 0f3F800000;
	@%p54 bra 	BB0_34;
	bra.uni 	BB0_32;

BB0_34:
	cvt.f64.f32	%fd26, %f14;
	add.f64 	%fd27, %fd26, %fd26;
	cvt.f64.f32	%fd28, %f41;
	cvt.f64.f32	%fd29, %f80;
	fma.rn.f64 	%fd30, %fd28, %fd27, %fd29;
	cvt.rn.f32.f64	%f79, %fd30;
	bra.uni 	BB0_47;

BB0_32:
	ld.global.f32 	%f67, [%rd15];
	setp.neu.f32	%p55, %f67, 0f3F800000;
	@%p55 bra 	BB0_47;

	cvt.f64.f32	%fd21, %f14;
	add.f64 	%fd22, %fd21, %fd21;
	cvt.f64.f32	%fd23, %f41;
	cvt.f64.f32	%fd24, %f79;
	fma.rn.f64 	%fd25, %fd23, %fd22, %fd24;
	cvt.rn.f32.f64	%f80, %fd25;

BB0_47:
	add.s64 	%rd70, %rd22, %rd59;
	ld.global.f32 	%f68, [%rd70];
	cvt.f64.f32	%fd61, %f68;
	add.f32 	%f69, %f75, %f76;
	add.f32 	%f70, %f69, %f77;
	add.f32 	%f71, %f70, %f78;
	add.f32 	%f72, %f71, %f79;
	add.f32 	%f73, %f72, %f80;
	cvt.f64.f32	%fd62, %f73;
	mul.f64 	%fd63, %fd62, 0d3FCDDDDDDDDDDDDD;
	fma.rn.f64 	%fd64, %fd61, 0dBFD999999999999A, %fd63;
	cvt.rn.f32.f64	%f74, %fd64;
	st.global.f32 	[%rd70], %f74;

BB0_48:
	ret;
}


`
 )
