package ext_kernels

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for Gradient kernel
var Gradient_code cu.Function

// Stores the arguments for Gradient kernel invocation
type Gradient_args_t struct{
	 arg_dstX unsafe.Pointer
	 arg_dstY unsafe.Pointer
	 arg_dstZ unsafe.Pointer
	 arg_src unsafe.Pointer
	 arg_Nx int
	 arg_Ny int
	 arg_Nz int
	 arg_Sx int
	 arg_Sy int
	 arg_Sz int
	 arg_geometry unsafe.Pointer
	 arg_includeOrExclude int
	 arg_cellsize float32
	 arg_cellshift int
	 argptr [14]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for Gradient kernel invocation
var Gradient_args Gradient_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 Gradient_args.argptr[0] = unsafe.Pointer(&Gradient_args.arg_dstX)
	 Gradient_args.argptr[1] = unsafe.Pointer(&Gradient_args.arg_dstY)
	 Gradient_args.argptr[2] = unsafe.Pointer(&Gradient_args.arg_dstZ)
	 Gradient_args.argptr[3] = unsafe.Pointer(&Gradient_args.arg_src)
	 Gradient_args.argptr[4] = unsafe.Pointer(&Gradient_args.arg_Nx)
	 Gradient_args.argptr[5] = unsafe.Pointer(&Gradient_args.arg_Ny)
	 Gradient_args.argptr[6] = unsafe.Pointer(&Gradient_args.arg_Nz)
	 Gradient_args.argptr[7] = unsafe.Pointer(&Gradient_args.arg_Sx)
	 Gradient_args.argptr[8] = unsafe.Pointer(&Gradient_args.arg_Sy)
	 Gradient_args.argptr[9] = unsafe.Pointer(&Gradient_args.arg_Sz)
	 Gradient_args.argptr[10] = unsafe.Pointer(&Gradient_args.arg_geometry)
	 Gradient_args.argptr[11] = unsafe.Pointer(&Gradient_args.arg_includeOrExclude)
	 Gradient_args.argptr[12] = unsafe.Pointer(&Gradient_args.arg_cellsize)
	 Gradient_args.argptr[13] = unsafe.Pointer(&Gradient_args.arg_cellshift)
	 }

// Wrapper for Gradient CUDA kernel, asynchronous.
func K_ext_Gradient_async ( dstX unsafe.Pointer, dstY unsafe.Pointer, dstZ unsafe.Pointer, src unsafe.Pointer, Nx int, Ny int, Nz int, Sx int, Sy int, Sz int, geometry unsafe.Pointer, includeOrExclude int, cellsize float32, cellshift int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("Gradient")
	}

	Gradient_args.Lock()
	defer Gradient_args.Unlock()

	if Gradient_code == 0{
		Gradient_code = fatbinLoad(Gradient_map, "Gradient")
	}

	 Gradient_args.arg_dstX = dstX
	 Gradient_args.arg_dstY = dstY
	 Gradient_args.arg_dstZ = dstZ
	 Gradient_args.arg_src = src
	 Gradient_args.arg_Nx = Nx
	 Gradient_args.arg_Ny = Ny
	 Gradient_args.arg_Nz = Nz
	 Gradient_args.arg_Sx = Sx
	 Gradient_args.arg_Sy = Sy
	 Gradient_args.arg_Sz = Sz
	 Gradient_args.arg_geometry = geometry
	 Gradient_args.arg_includeOrExclude = includeOrExclude
	 Gradient_args.arg_cellsize = cellsize
	 Gradient_args.arg_cellshift = cellshift
	

	args := Gradient_args.argptr[:]
	cu.LaunchKernel(Gradient_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("Gradient")
	}
}

// maps compute capability on PTX code for Gradient kernel.
var Gradient_map = map[int]string{ 0: "" ,
20: Gradient_ptx_20 ,
30: Gradient_ptx_30 ,
35: Gradient_ptx_35 ,
50: Gradient_ptx_50 ,
52: Gradient_ptx_52 ,
53: Gradient_ptx_53  }

// Gradient PTX code for various compute capabilities.
const(
  Gradient_ptx_20 = `
.version 5.0
.target sm_20
.address_size 64

	// .globl	Gradient

.visible .entry Gradient(
	.param .u64 Gradient_param_0,
	.param .u64 Gradient_param_1,
	.param .u64 Gradient_param_2,
	.param .u64 Gradient_param_3,
	.param .u32 Gradient_param_4,
	.param .u32 Gradient_param_5,
	.param .u32 Gradient_param_6,
	.param .u32 Gradient_param_7,
	.param .u32 Gradient_param_8,
	.param .u32 Gradient_param_9,
	.param .u64 Gradient_param_10,
	.param .u32 Gradient_param_11,
	.param .f32 Gradient_param_12,
	.param .u32 Gradient_param_13
)
{
	.reg .pred 	%p<10>;
	.reg .f32 	%f<34>;
	.reg .b32 	%r<47>;
	.reg .f64 	%fd<18>;
	.reg .b64 	%rd<36>;


	ld.param.u64 	%rd3, [Gradient_param_0];
	ld.param.u64 	%rd4, [Gradient_param_1];
	ld.param.u64 	%rd5, [Gradient_param_2];
	ld.param.u64 	%rd6, [Gradient_param_3];
	ld.param.u32 	%r4, [Gradient_param_4];
	ld.param.u32 	%r5, [Gradient_param_5];
	ld.param.u32 	%r10, [Gradient_param_6];
	ld.param.u32 	%r6, [Gradient_param_7];
	ld.param.u32 	%r7, [Gradient_param_8];
	ld.param.u64 	%rd7, [Gradient_param_10];
	ld.param.u32 	%r8, [Gradient_param_11];
	ld.param.f32 	%f1, [Gradient_param_12];
	ld.param.u32 	%r9, [Gradient_param_13];
	mov.u32 	%r11, %ntid.x;
	mov.u32 	%r12, %ctaid.x;
	mov.u32 	%r13, %tid.x;
	mad.lo.s32 	%r1, %r11, %r12, %r13;
	mov.u32 	%r14, %ntid.y;
	mov.u32 	%r15, %ctaid.y;
	mov.u32 	%r16, %tid.y;
	mad.lo.s32 	%r2, %r14, %r15, %r16;
	mov.u32 	%r17, %ntid.z;
	mov.u32 	%r18, %ctaid.z;
	mov.u32 	%r19, %tid.z;
	mad.lo.s32 	%r3, %r17, %r18, %r19;
	setp.ge.s32	%p1, %r2, %r5;
	setp.ge.s32	%p2, %r1, %r4;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r10;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_6;

	cvta.to.global.u64 	%rd8, %rd7;
	mad.lo.s32 	%r20, %r3, %r5, %r2;
	mad.lo.s32 	%r21, %r20, %r4, %r1;
	cvt.s64.s32	%rd1, %r21;
	mul.wide.s32 	%rd9, %r21, 4;
	add.s64 	%rd2, %rd8, %rd9;
	setp.eq.s32	%p6, %r8, 1;
	@%p6 bra 	BB0_4;
	bra.uni 	BB0_2;

BB0_4:
	ld.global.f32 	%f3, [%rd2];
	setp.eq.f32	%p9, %f3, 0f00000000;
	@%p9 bra 	BB0_6;
	bra.uni 	BB0_5;

BB0_2:
	setp.ne.s32	%p7, %r8, 0;
	@%p7 bra 	BB0_5;

	ld.global.f32 	%f2, [%rd2];
	setp.neu.f32	%p8, %f2, 0f00000000;
	@%p8 bra 	BB0_6;

BB0_5:
	cvta.to.global.u64 	%rd10, %rd5;
	cvta.to.global.u64 	%rd11, %rd4;
	cvta.to.global.u64 	%rd12, %rd3;
	cvta.to.global.u64 	%rd13, %rd6;
	add.s32 	%r22, %r1, %r9;
	add.s32 	%r23, %r2, %r9;
	add.s32 	%r24, %r3, %r9;
	mad.lo.s32 	%r25, %r24, %r7, %r23;
	mad.lo.s32 	%r26, %r25, %r6, %r22;
	add.s32 	%r27, %r25, -1;
	mad.lo.s32 	%r28, %r27, %r6, %r22;
	add.s32 	%r29, %r24, -1;
	mad.lo.s32 	%r30, %r29, %r7, %r23;
	mad.lo.s32 	%r31, %r30, %r6, %r22;
	add.s32 	%r32, %r25, 1;
	mad.lo.s32 	%r33, %r32, %r6, %r22;
	add.s32 	%r34, %r24, 1;
	mad.lo.s32 	%r35, %r34, %r7, %r23;
	mad.lo.s32 	%r36, %r35, %r6, %r22;
	add.s32 	%r37, %r25, -2;
	mad.lo.s32 	%r38, %r37, %r6, %r22;
	add.s32 	%r39, %r24, -2;
	mad.lo.s32 	%r40, %r39, %r7, %r23;
	mad.lo.s32 	%r41, %r40, %r6, %r22;
	add.s32 	%r42, %r25, 2;
	mad.lo.s32 	%r43, %r42, %r6, %r22;
	add.s32 	%r44, %r24, 2;
	mad.lo.s32 	%r45, %r44, %r7, %r23;
	mad.lo.s32 	%r46, %r45, %r6, %r22;
	mul.wide.s32 	%rd14, %r26, 4;
	add.s64 	%rd15, %rd13, %rd14;
	mul.wide.s32 	%rd16, %r33, 4;
	add.s64 	%rd17, %rd13, %rd16;
	ld.global.f32 	%f4, [%rd17];
	mul.wide.s32 	%rd18, %r28, 4;
	add.s64 	%rd19, %rd13, %rd18;
	ld.global.f32 	%f5, [%rd19];
	mul.wide.s32 	%rd20, %r36, 4;
	add.s64 	%rd21, %rd13, %rd20;
	ld.global.f32 	%f6, [%rd21];
	mul.wide.s32 	%rd22, %r31, 4;
	add.s64 	%rd23, %rd13, %rd22;
	ld.global.f32 	%f7, [%rd23];
	mul.wide.s32 	%rd24, %r43, 4;
	add.s64 	%rd25, %rd13, %rd24;
	ld.global.f32 	%f8, [%rd25];
	mul.wide.s32 	%rd26, %r38, 4;
	add.s64 	%rd27, %rd13, %rd26;
	ld.global.f32 	%f9, [%rd27];
	mul.wide.s32 	%rd28, %r46, 4;
	add.s64 	%rd29, %rd13, %rd28;
	ld.global.f32 	%f10, [%rd29];
	mul.wide.s32 	%rd30, %r41, 4;
	add.s64 	%rd31, %rd13, %rd30;
	ld.global.f32 	%f11, [%rd31];
	ld.global.f32 	%f12, [%rd15+-8];
	ld.global.f32 	%f13, [%rd15+8];
	sub.f32 	%f14, %f13, %f12;
	cvt.f64.f32	%fd1, %f14;
	cvt.f64.f32	%fd2, %f1;
	mul.f64 	%fd3, %fd2, 0d4028000000000000;
	div.rn.f64 	%fd4, %fd1, %fd3;
	ld.global.f32 	%f15, [%rd15+-4];
	ld.global.f32 	%f16, [%rd15+4];
	sub.f32 	%f17, %f15, %f16;
	mul.f32 	%f18, %f17, 0f41000000;
	cvt.f64.f32	%fd5, %f18;
	div.rn.f64 	%fd6, %fd5, %fd3;
	add.f64 	%fd7, %fd4, %fd6;
	cvt.rn.f32.f64	%f19, %fd7;
	shl.b64 	%rd32, %rd1, 2;
	add.s64 	%rd33, %rd12, %rd32;
	ld.global.f32 	%f20, [%rd33];
	add.f32 	%f21, %f20, %f19;
	st.global.f32 	[%rd33], %f21;
	sub.f32 	%f22, %f8, %f9;
	cvt.f64.f32	%fd8, %f22;
	div.rn.f64 	%fd9, %fd8, %fd3;
	sub.f32 	%f23, %f5, %f4;
	mul.f32 	%f24, %f23, 0f41000000;
	cvt.f64.f32	%fd10, %f24;
	div.rn.f64 	%fd11, %fd10, %fd3;
	add.f64 	%fd12, %fd9, %fd11;
	cvt.rn.f32.f64	%f25, %fd12;
	add.s64 	%rd34, %rd11, %rd32;
	ld.global.f32 	%f26, [%rd34];
	add.f32 	%f27, %f26, %f25;
	st.global.f32 	[%rd34], %f27;
	sub.f32 	%f28, %f10, %f11;
	cvt.f64.f32	%fd13, %f28;
	div.rn.f64 	%fd14, %fd13, %fd3;
	sub.f32 	%f29, %f7, %f6;
	mul.f32 	%f30, %f29, 0f41000000;
	cvt.f64.f32	%fd15, %f30;
	div.rn.f64 	%fd16, %fd15, %fd3;
	add.f64 	%fd17, %fd14, %fd16;
	cvt.rn.f32.f64	%f31, %fd17;
	add.s64 	%rd35, %rd10, %rd32;
	ld.global.f32 	%f32, [%rd35];
	add.f32 	%f33, %f32, %f31;
	st.global.f32 	[%rd35], %f33;

BB0_6:
	ret;
}


`
   Gradient_ptx_30 = `
.version 5.0
.target sm_30
.address_size 64

	// .globl	Gradient

.visible .entry Gradient(
	.param .u64 Gradient_param_0,
	.param .u64 Gradient_param_1,
	.param .u64 Gradient_param_2,
	.param .u64 Gradient_param_3,
	.param .u32 Gradient_param_4,
	.param .u32 Gradient_param_5,
	.param .u32 Gradient_param_6,
	.param .u32 Gradient_param_7,
	.param .u32 Gradient_param_8,
	.param .u32 Gradient_param_9,
	.param .u64 Gradient_param_10,
	.param .u32 Gradient_param_11,
	.param .f32 Gradient_param_12,
	.param .u32 Gradient_param_13
)
{
	.reg .pred 	%p<10>;
	.reg .f32 	%f<34>;
	.reg .b32 	%r<47>;
	.reg .f64 	%fd<18>;
	.reg .b64 	%rd<36>;


	ld.param.u64 	%rd3, [Gradient_param_0];
	ld.param.u64 	%rd4, [Gradient_param_1];
	ld.param.u64 	%rd5, [Gradient_param_2];
	ld.param.u64 	%rd6, [Gradient_param_3];
	ld.param.u32 	%r4, [Gradient_param_4];
	ld.param.u32 	%r5, [Gradient_param_5];
	ld.param.u32 	%r10, [Gradient_param_6];
	ld.param.u32 	%r6, [Gradient_param_7];
	ld.param.u32 	%r7, [Gradient_param_8];
	ld.param.u64 	%rd7, [Gradient_param_10];
	ld.param.u32 	%r8, [Gradient_param_11];
	ld.param.f32 	%f1, [Gradient_param_12];
	ld.param.u32 	%r9, [Gradient_param_13];
	mov.u32 	%r11, %ntid.x;
	mov.u32 	%r12, %ctaid.x;
	mov.u32 	%r13, %tid.x;
	mad.lo.s32 	%r1, %r11, %r12, %r13;
	mov.u32 	%r14, %ntid.y;
	mov.u32 	%r15, %ctaid.y;
	mov.u32 	%r16, %tid.y;
	mad.lo.s32 	%r2, %r14, %r15, %r16;
	mov.u32 	%r17, %ntid.z;
	mov.u32 	%r18, %ctaid.z;
	mov.u32 	%r19, %tid.z;
	mad.lo.s32 	%r3, %r17, %r18, %r19;
	setp.ge.s32	%p1, %r2, %r5;
	setp.ge.s32	%p2, %r1, %r4;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r10;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_6;

	cvta.to.global.u64 	%rd8, %rd7;
	mad.lo.s32 	%r20, %r3, %r5, %r2;
	mad.lo.s32 	%r21, %r20, %r4, %r1;
	cvt.s64.s32	%rd1, %r21;
	mul.wide.s32 	%rd9, %r21, 4;
	add.s64 	%rd2, %rd8, %rd9;
	setp.eq.s32	%p6, %r8, 1;
	@%p6 bra 	BB0_4;
	bra.uni 	BB0_2;

BB0_4:
	ld.global.f32 	%f3, [%rd2];
	setp.eq.f32	%p9, %f3, 0f00000000;
	@%p9 bra 	BB0_6;
	bra.uni 	BB0_5;

BB0_2:
	setp.ne.s32	%p7, %r8, 0;
	@%p7 bra 	BB0_5;

	ld.global.f32 	%f2, [%rd2];
	setp.neu.f32	%p8, %f2, 0f00000000;
	@%p8 bra 	BB0_6;

BB0_5:
	cvta.to.global.u64 	%rd10, %rd5;
	cvta.to.global.u64 	%rd11, %rd4;
	cvta.to.global.u64 	%rd12, %rd3;
	cvta.to.global.u64 	%rd13, %rd6;
	add.s32 	%r22, %r1, %r9;
	add.s32 	%r23, %r2, %r9;
	add.s32 	%r24, %r3, %r9;
	mad.lo.s32 	%r25, %r24, %r7, %r23;
	mad.lo.s32 	%r26, %r25, %r6, %r22;
	add.s32 	%r27, %r25, -1;
	mad.lo.s32 	%r28, %r27, %r6, %r22;
	add.s32 	%r29, %r24, -1;
	mad.lo.s32 	%r30, %r29, %r7, %r23;
	mad.lo.s32 	%r31, %r30, %r6, %r22;
	add.s32 	%r32, %r25, 1;
	mad.lo.s32 	%r33, %r32, %r6, %r22;
	add.s32 	%r34, %r24, 1;
	mad.lo.s32 	%r35, %r34, %r7, %r23;
	mad.lo.s32 	%r36, %r35, %r6, %r22;
	add.s32 	%r37, %r25, -2;
	mad.lo.s32 	%r38, %r37, %r6, %r22;
	add.s32 	%r39, %r24, -2;
	mad.lo.s32 	%r40, %r39, %r7, %r23;
	mad.lo.s32 	%r41, %r40, %r6, %r22;
	add.s32 	%r42, %r25, 2;
	mad.lo.s32 	%r43, %r42, %r6, %r22;
	add.s32 	%r44, %r24, 2;
	mad.lo.s32 	%r45, %r44, %r7, %r23;
	mad.lo.s32 	%r46, %r45, %r6, %r22;
	mul.wide.s32 	%rd14, %r26, 4;
	add.s64 	%rd15, %rd13, %rd14;
	mul.wide.s32 	%rd16, %r33, 4;
	add.s64 	%rd17, %rd13, %rd16;
	ld.global.f32 	%f4, [%rd17];
	mul.wide.s32 	%rd18, %r28, 4;
	add.s64 	%rd19, %rd13, %rd18;
	ld.global.f32 	%f5, [%rd19];
	mul.wide.s32 	%rd20, %r36, 4;
	add.s64 	%rd21, %rd13, %rd20;
	ld.global.f32 	%f6, [%rd21];
	mul.wide.s32 	%rd22, %r31, 4;
	add.s64 	%rd23, %rd13, %rd22;
	ld.global.f32 	%f7, [%rd23];
	mul.wide.s32 	%rd24, %r43, 4;
	add.s64 	%rd25, %rd13, %rd24;
	ld.global.f32 	%f8, [%rd25];
	mul.wide.s32 	%rd26, %r38, 4;
	add.s64 	%rd27, %rd13, %rd26;
	ld.global.f32 	%f9, [%rd27];
	mul.wide.s32 	%rd28, %r46, 4;
	add.s64 	%rd29, %rd13, %rd28;
	ld.global.f32 	%f10, [%rd29];
	mul.wide.s32 	%rd30, %r41, 4;
	add.s64 	%rd31, %rd13, %rd30;
	ld.global.f32 	%f11, [%rd31];
	ld.global.f32 	%f12, [%rd15+-8];
	ld.global.f32 	%f13, [%rd15+8];
	sub.f32 	%f14, %f13, %f12;
	cvt.f64.f32	%fd1, %f14;
	cvt.f64.f32	%fd2, %f1;
	mul.f64 	%fd3, %fd2, 0d4028000000000000;
	div.rn.f64 	%fd4, %fd1, %fd3;
	ld.global.f32 	%f15, [%rd15+-4];
	ld.global.f32 	%f16, [%rd15+4];
	sub.f32 	%f17, %f15, %f16;
	mul.f32 	%f18, %f17, 0f41000000;
	cvt.f64.f32	%fd5, %f18;
	div.rn.f64 	%fd6, %fd5, %fd3;
	add.f64 	%fd7, %fd4, %fd6;
	cvt.rn.f32.f64	%f19, %fd7;
	shl.b64 	%rd32, %rd1, 2;
	add.s64 	%rd33, %rd12, %rd32;
	ld.global.f32 	%f20, [%rd33];
	add.f32 	%f21, %f20, %f19;
	st.global.f32 	[%rd33], %f21;
	sub.f32 	%f22, %f8, %f9;
	cvt.f64.f32	%fd8, %f22;
	div.rn.f64 	%fd9, %fd8, %fd3;
	sub.f32 	%f23, %f5, %f4;
	mul.f32 	%f24, %f23, 0f41000000;
	cvt.f64.f32	%fd10, %f24;
	div.rn.f64 	%fd11, %fd10, %fd3;
	add.f64 	%fd12, %fd9, %fd11;
	cvt.rn.f32.f64	%f25, %fd12;
	add.s64 	%rd34, %rd11, %rd32;
	ld.global.f32 	%f26, [%rd34];
	add.f32 	%f27, %f26, %f25;
	st.global.f32 	[%rd34], %f27;
	sub.f32 	%f28, %f10, %f11;
	cvt.f64.f32	%fd13, %f28;
	div.rn.f64 	%fd14, %fd13, %fd3;
	sub.f32 	%f29, %f7, %f6;
	mul.f32 	%f30, %f29, 0f41000000;
	cvt.f64.f32	%fd15, %f30;
	div.rn.f64 	%fd16, %fd15, %fd3;
	add.f64 	%fd17, %fd14, %fd16;
	cvt.rn.f32.f64	%f31, %fd17;
	add.s64 	%rd35, %rd10, %rd32;
	ld.global.f32 	%f32, [%rd35];
	add.f32 	%f33, %f32, %f31;
	st.global.f32 	[%rd35], %f33;

BB0_6:
	ret;
}


`
   Gradient_ptx_35 = `
.version 5.0
.target sm_35
.address_size 64

	// .globl	Gradient

.visible .entry Gradient(
	.param .u64 Gradient_param_0,
	.param .u64 Gradient_param_1,
	.param .u64 Gradient_param_2,
	.param .u64 Gradient_param_3,
	.param .u32 Gradient_param_4,
	.param .u32 Gradient_param_5,
	.param .u32 Gradient_param_6,
	.param .u32 Gradient_param_7,
	.param .u32 Gradient_param_8,
	.param .u32 Gradient_param_9,
	.param .u64 Gradient_param_10,
	.param .u32 Gradient_param_11,
	.param .f32 Gradient_param_12,
	.param .u32 Gradient_param_13
)
{
	.reg .pred 	%p<10>;
	.reg .f32 	%f<34>;
	.reg .b32 	%r<47>;
	.reg .f64 	%fd<18>;
	.reg .b64 	%rd<36>;


	ld.param.u64 	%rd3, [Gradient_param_0];
	ld.param.u64 	%rd4, [Gradient_param_1];
	ld.param.u64 	%rd5, [Gradient_param_2];
	ld.param.u64 	%rd6, [Gradient_param_3];
	ld.param.u32 	%r4, [Gradient_param_4];
	ld.param.u32 	%r5, [Gradient_param_5];
	ld.param.u32 	%r10, [Gradient_param_6];
	ld.param.u32 	%r6, [Gradient_param_7];
	ld.param.u32 	%r7, [Gradient_param_8];
	ld.param.u64 	%rd7, [Gradient_param_10];
	ld.param.u32 	%r8, [Gradient_param_11];
	ld.param.f32 	%f1, [Gradient_param_12];
	ld.param.u32 	%r9, [Gradient_param_13];
	mov.u32 	%r11, %ntid.x;
	mov.u32 	%r12, %ctaid.x;
	mov.u32 	%r13, %tid.x;
	mad.lo.s32 	%r1, %r11, %r12, %r13;
	mov.u32 	%r14, %ntid.y;
	mov.u32 	%r15, %ctaid.y;
	mov.u32 	%r16, %tid.y;
	mad.lo.s32 	%r2, %r14, %r15, %r16;
	mov.u32 	%r17, %ntid.z;
	mov.u32 	%r18, %ctaid.z;
	mov.u32 	%r19, %tid.z;
	mad.lo.s32 	%r3, %r17, %r18, %r19;
	setp.ge.s32	%p1, %r2, %r5;
	setp.ge.s32	%p2, %r1, %r4;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r10;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_6;

	cvta.to.global.u64 	%rd8, %rd7;
	mad.lo.s32 	%r20, %r3, %r5, %r2;
	mad.lo.s32 	%r21, %r20, %r4, %r1;
	cvt.s64.s32	%rd1, %r21;
	mul.wide.s32 	%rd9, %r21, 4;
	add.s64 	%rd2, %rd8, %rd9;
	setp.eq.s32	%p6, %r8, 1;
	@%p6 bra 	BB0_4;
	bra.uni 	BB0_2;

BB0_4:
	ld.global.nc.f32 	%f3, [%rd2];
	setp.eq.f32	%p9, %f3, 0f00000000;
	@%p9 bra 	BB0_6;
	bra.uni 	BB0_5;

BB0_2:
	setp.ne.s32	%p7, %r8, 0;
	@%p7 bra 	BB0_5;

	ld.global.nc.f32 	%f2, [%rd2];
	setp.neu.f32	%p8, %f2, 0f00000000;
	@%p8 bra 	BB0_6;

BB0_5:
	cvta.to.global.u64 	%rd10, %rd5;
	cvta.to.global.u64 	%rd11, %rd4;
	cvta.to.global.u64 	%rd12, %rd3;
	cvta.to.global.u64 	%rd13, %rd6;
	add.s32 	%r22, %r1, %r9;
	add.s32 	%r23, %r2, %r9;
	add.s32 	%r24, %r3, %r9;
	mad.lo.s32 	%r25, %r24, %r7, %r23;
	mad.lo.s32 	%r26, %r25, %r6, %r22;
	add.s32 	%r27, %r25, -1;
	mad.lo.s32 	%r28, %r27, %r6, %r22;
	add.s32 	%r29, %r24, -1;
	mad.lo.s32 	%r30, %r29, %r7, %r23;
	mad.lo.s32 	%r31, %r30, %r6, %r22;
	add.s32 	%r32, %r25, 1;
	mad.lo.s32 	%r33, %r32, %r6, %r22;
	add.s32 	%r34, %r24, 1;
	mad.lo.s32 	%r35, %r34, %r7, %r23;
	mad.lo.s32 	%r36, %r35, %r6, %r22;
	add.s32 	%r37, %r25, -2;
	mad.lo.s32 	%r38, %r37, %r6, %r22;
	add.s32 	%r39, %r24, -2;
	mad.lo.s32 	%r40, %r39, %r7, %r23;
	mad.lo.s32 	%r41, %r40, %r6, %r22;
	add.s32 	%r42, %r25, 2;
	mad.lo.s32 	%r43, %r42, %r6, %r22;
	add.s32 	%r44, %r24, 2;
	mad.lo.s32 	%r45, %r44, %r7, %r23;
	mad.lo.s32 	%r46, %r45, %r6, %r22;
	mul.wide.s32 	%rd14, %r26, 4;
	add.s64 	%rd15, %rd13, %rd14;
	mul.wide.s32 	%rd16, %r33, 4;
	add.s64 	%rd17, %rd13, %rd16;
	ld.global.nc.f32 	%f4, [%rd17];
	mul.wide.s32 	%rd18, %r28, 4;
	add.s64 	%rd19, %rd13, %rd18;
	ld.global.nc.f32 	%f5, [%rd19];
	mul.wide.s32 	%rd20, %r36, 4;
	add.s64 	%rd21, %rd13, %rd20;
	ld.global.nc.f32 	%f6, [%rd21];
	mul.wide.s32 	%rd22, %r31, 4;
	add.s64 	%rd23, %rd13, %rd22;
	ld.global.nc.f32 	%f7, [%rd23];
	mul.wide.s32 	%rd24, %r43, 4;
	add.s64 	%rd25, %rd13, %rd24;
	ld.global.nc.f32 	%f8, [%rd25];
	mul.wide.s32 	%rd26, %r38, 4;
	add.s64 	%rd27, %rd13, %rd26;
	ld.global.nc.f32 	%f9, [%rd27];
	mul.wide.s32 	%rd28, %r46, 4;
	add.s64 	%rd29, %rd13, %rd28;
	ld.global.nc.f32 	%f10, [%rd29];
	mul.wide.s32 	%rd30, %r41, 4;
	add.s64 	%rd31, %rd13, %rd30;
	ld.global.nc.f32 	%f11, [%rd31];
	ld.global.nc.f32 	%f12, [%rd15+-8];
	ld.global.nc.f32 	%f13, [%rd15+8];
	sub.f32 	%f14, %f13, %f12;
	cvt.f64.f32	%fd1, %f14;
	cvt.f64.f32	%fd2, %f1;
	mul.f64 	%fd3, %fd2, 0d4028000000000000;
	div.rn.f64 	%fd4, %fd1, %fd3;
	ld.global.nc.f32 	%f15, [%rd15+-4];
	ld.global.nc.f32 	%f16, [%rd15+4];
	sub.f32 	%f17, %f15, %f16;
	mul.f32 	%f18, %f17, 0f41000000;
	cvt.f64.f32	%fd5, %f18;
	div.rn.f64 	%fd6, %fd5, %fd3;
	add.f64 	%fd7, %fd4, %fd6;
	cvt.rn.f32.f64	%f19, %fd7;
	shl.b64 	%rd32, %rd1, 2;
	add.s64 	%rd33, %rd12, %rd32;
	ld.global.f32 	%f20, [%rd33];
	add.f32 	%f21, %f20, %f19;
	st.global.f32 	[%rd33], %f21;
	sub.f32 	%f22, %f8, %f9;
	cvt.f64.f32	%fd8, %f22;
	div.rn.f64 	%fd9, %fd8, %fd3;
	sub.f32 	%f23, %f5, %f4;
	mul.f32 	%f24, %f23, 0f41000000;
	cvt.f64.f32	%fd10, %f24;
	div.rn.f64 	%fd11, %fd10, %fd3;
	add.f64 	%fd12, %fd9, %fd11;
	cvt.rn.f32.f64	%f25, %fd12;
	add.s64 	%rd34, %rd11, %rd32;
	ld.global.f32 	%f26, [%rd34];
	add.f32 	%f27, %f26, %f25;
	st.global.f32 	[%rd34], %f27;
	sub.f32 	%f28, %f10, %f11;
	cvt.f64.f32	%fd13, %f28;
	div.rn.f64 	%fd14, %fd13, %fd3;
	sub.f32 	%f29, %f7, %f6;
	mul.f32 	%f30, %f29, 0f41000000;
	cvt.f64.f32	%fd15, %f30;
	div.rn.f64 	%fd16, %fd15, %fd3;
	add.f64 	%fd17, %fd14, %fd16;
	cvt.rn.f32.f64	%f31, %fd17;
	add.s64 	%rd35, %rd10, %rd32;
	ld.global.f32 	%f32, [%rd35];
	add.f32 	%f33, %f32, %f31;
	st.global.f32 	[%rd35], %f33;

BB0_6:
	ret;
}


`
   Gradient_ptx_50 = `
.version 5.0
.target sm_50
.address_size 64

	// .globl	Gradient

.visible .entry Gradient(
	.param .u64 Gradient_param_0,
	.param .u64 Gradient_param_1,
	.param .u64 Gradient_param_2,
	.param .u64 Gradient_param_3,
	.param .u32 Gradient_param_4,
	.param .u32 Gradient_param_5,
	.param .u32 Gradient_param_6,
	.param .u32 Gradient_param_7,
	.param .u32 Gradient_param_8,
	.param .u32 Gradient_param_9,
	.param .u64 Gradient_param_10,
	.param .u32 Gradient_param_11,
	.param .f32 Gradient_param_12,
	.param .u32 Gradient_param_13
)
{
	.reg .pred 	%p<10>;
	.reg .f32 	%f<34>;
	.reg .b32 	%r<47>;
	.reg .f64 	%fd<18>;
	.reg .b64 	%rd<36>;


	ld.param.u64 	%rd3, [Gradient_param_0];
	ld.param.u64 	%rd4, [Gradient_param_1];
	ld.param.u64 	%rd5, [Gradient_param_2];
	ld.param.u64 	%rd6, [Gradient_param_3];
	ld.param.u32 	%r4, [Gradient_param_4];
	ld.param.u32 	%r5, [Gradient_param_5];
	ld.param.u32 	%r10, [Gradient_param_6];
	ld.param.u32 	%r6, [Gradient_param_7];
	ld.param.u32 	%r7, [Gradient_param_8];
	ld.param.u64 	%rd7, [Gradient_param_10];
	ld.param.u32 	%r8, [Gradient_param_11];
	ld.param.f32 	%f1, [Gradient_param_12];
	ld.param.u32 	%r9, [Gradient_param_13];
	mov.u32 	%r11, %ntid.x;
	mov.u32 	%r12, %ctaid.x;
	mov.u32 	%r13, %tid.x;
	mad.lo.s32 	%r1, %r11, %r12, %r13;
	mov.u32 	%r14, %ntid.y;
	mov.u32 	%r15, %ctaid.y;
	mov.u32 	%r16, %tid.y;
	mad.lo.s32 	%r2, %r14, %r15, %r16;
	mov.u32 	%r17, %ntid.z;
	mov.u32 	%r18, %ctaid.z;
	mov.u32 	%r19, %tid.z;
	mad.lo.s32 	%r3, %r17, %r18, %r19;
	setp.ge.s32	%p1, %r2, %r5;
	setp.ge.s32	%p2, %r1, %r4;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r10;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_6;

	cvta.to.global.u64 	%rd8, %rd7;
	mad.lo.s32 	%r20, %r3, %r5, %r2;
	mad.lo.s32 	%r21, %r20, %r4, %r1;
	cvt.s64.s32	%rd1, %r21;
	mul.wide.s32 	%rd9, %r21, 4;
	add.s64 	%rd2, %rd8, %rd9;
	setp.eq.s32	%p6, %r8, 1;
	@%p6 bra 	BB0_4;
	bra.uni 	BB0_2;

BB0_4:
	ld.global.nc.f32 	%f3, [%rd2];
	setp.eq.f32	%p9, %f3, 0f00000000;
	@%p9 bra 	BB0_6;
	bra.uni 	BB0_5;

BB0_2:
	setp.ne.s32	%p7, %r8, 0;
	@%p7 bra 	BB0_5;

	ld.global.nc.f32 	%f2, [%rd2];
	setp.neu.f32	%p8, %f2, 0f00000000;
	@%p8 bra 	BB0_6;

BB0_5:
	cvta.to.global.u64 	%rd10, %rd5;
	cvta.to.global.u64 	%rd11, %rd4;
	cvta.to.global.u64 	%rd12, %rd3;
	cvta.to.global.u64 	%rd13, %rd6;
	add.s32 	%r22, %r1, %r9;
	add.s32 	%r23, %r2, %r9;
	add.s32 	%r24, %r3, %r9;
	mad.lo.s32 	%r25, %r24, %r7, %r23;
	mad.lo.s32 	%r26, %r25, %r6, %r22;
	add.s32 	%r27, %r25, -1;
	mad.lo.s32 	%r28, %r27, %r6, %r22;
	add.s32 	%r29, %r24, -1;
	mad.lo.s32 	%r30, %r29, %r7, %r23;
	mad.lo.s32 	%r31, %r30, %r6, %r22;
	add.s32 	%r32, %r25, 1;
	mad.lo.s32 	%r33, %r32, %r6, %r22;
	add.s32 	%r34, %r24, 1;
	mad.lo.s32 	%r35, %r34, %r7, %r23;
	mad.lo.s32 	%r36, %r35, %r6, %r22;
	add.s32 	%r37, %r25, -2;
	mad.lo.s32 	%r38, %r37, %r6, %r22;
	add.s32 	%r39, %r24, -2;
	mad.lo.s32 	%r40, %r39, %r7, %r23;
	mad.lo.s32 	%r41, %r40, %r6, %r22;
	add.s32 	%r42, %r25, 2;
	mad.lo.s32 	%r43, %r42, %r6, %r22;
	add.s32 	%r44, %r24, 2;
	mad.lo.s32 	%r45, %r44, %r7, %r23;
	mad.lo.s32 	%r46, %r45, %r6, %r22;
	mul.wide.s32 	%rd14, %r26, 4;
	add.s64 	%rd15, %rd13, %rd14;
	mul.wide.s32 	%rd16, %r33, 4;
	add.s64 	%rd17, %rd13, %rd16;
	ld.global.nc.f32 	%f4, [%rd17];
	mul.wide.s32 	%rd18, %r28, 4;
	add.s64 	%rd19, %rd13, %rd18;
	ld.global.nc.f32 	%f5, [%rd19];
	mul.wide.s32 	%rd20, %r36, 4;
	add.s64 	%rd21, %rd13, %rd20;
	ld.global.nc.f32 	%f6, [%rd21];
	mul.wide.s32 	%rd22, %r31, 4;
	add.s64 	%rd23, %rd13, %rd22;
	ld.global.nc.f32 	%f7, [%rd23];
	mul.wide.s32 	%rd24, %r43, 4;
	add.s64 	%rd25, %rd13, %rd24;
	ld.global.nc.f32 	%f8, [%rd25];
	mul.wide.s32 	%rd26, %r38, 4;
	add.s64 	%rd27, %rd13, %rd26;
	ld.global.nc.f32 	%f9, [%rd27];
	mul.wide.s32 	%rd28, %r46, 4;
	add.s64 	%rd29, %rd13, %rd28;
	ld.global.nc.f32 	%f10, [%rd29];
	mul.wide.s32 	%rd30, %r41, 4;
	add.s64 	%rd31, %rd13, %rd30;
	ld.global.nc.f32 	%f11, [%rd31];
	ld.global.nc.f32 	%f12, [%rd15+-8];
	ld.global.nc.f32 	%f13, [%rd15+8];
	sub.f32 	%f14, %f13, %f12;
	cvt.f64.f32	%fd1, %f14;
	cvt.f64.f32	%fd2, %f1;
	mul.f64 	%fd3, %fd2, 0d4028000000000000;
	div.rn.f64 	%fd4, %fd1, %fd3;
	ld.global.nc.f32 	%f15, [%rd15+-4];
	ld.global.nc.f32 	%f16, [%rd15+4];
	sub.f32 	%f17, %f15, %f16;
	mul.f32 	%f18, %f17, 0f41000000;
	cvt.f64.f32	%fd5, %f18;
	div.rn.f64 	%fd6, %fd5, %fd3;
	add.f64 	%fd7, %fd4, %fd6;
	cvt.rn.f32.f64	%f19, %fd7;
	shl.b64 	%rd32, %rd1, 2;
	add.s64 	%rd33, %rd12, %rd32;
	ld.global.f32 	%f20, [%rd33];
	add.f32 	%f21, %f20, %f19;
	st.global.f32 	[%rd33], %f21;
	sub.f32 	%f22, %f8, %f9;
	cvt.f64.f32	%fd8, %f22;
	div.rn.f64 	%fd9, %fd8, %fd3;
	sub.f32 	%f23, %f5, %f4;
	mul.f32 	%f24, %f23, 0f41000000;
	cvt.f64.f32	%fd10, %f24;
	div.rn.f64 	%fd11, %fd10, %fd3;
	add.f64 	%fd12, %fd9, %fd11;
	cvt.rn.f32.f64	%f25, %fd12;
	add.s64 	%rd34, %rd11, %rd32;
	ld.global.f32 	%f26, [%rd34];
	add.f32 	%f27, %f26, %f25;
	st.global.f32 	[%rd34], %f27;
	sub.f32 	%f28, %f10, %f11;
	cvt.f64.f32	%fd13, %f28;
	div.rn.f64 	%fd14, %fd13, %fd3;
	sub.f32 	%f29, %f7, %f6;
	mul.f32 	%f30, %f29, 0f41000000;
	cvt.f64.f32	%fd15, %f30;
	div.rn.f64 	%fd16, %fd15, %fd3;
	add.f64 	%fd17, %fd14, %fd16;
	cvt.rn.f32.f64	%f31, %fd17;
	add.s64 	%rd35, %rd10, %rd32;
	ld.global.f32 	%f32, [%rd35];
	add.f32 	%f33, %f32, %f31;
	st.global.f32 	[%rd35], %f33;

BB0_6:
	ret;
}


`
   Gradient_ptx_52 = `
.version 5.0
.target sm_52
.address_size 64

	// .globl	Gradient

.visible .entry Gradient(
	.param .u64 Gradient_param_0,
	.param .u64 Gradient_param_1,
	.param .u64 Gradient_param_2,
	.param .u64 Gradient_param_3,
	.param .u32 Gradient_param_4,
	.param .u32 Gradient_param_5,
	.param .u32 Gradient_param_6,
	.param .u32 Gradient_param_7,
	.param .u32 Gradient_param_8,
	.param .u32 Gradient_param_9,
	.param .u64 Gradient_param_10,
	.param .u32 Gradient_param_11,
	.param .f32 Gradient_param_12,
	.param .u32 Gradient_param_13
)
{
	.reg .pred 	%p<10>;
	.reg .f32 	%f<34>;
	.reg .b32 	%r<47>;
	.reg .f64 	%fd<18>;
	.reg .b64 	%rd<36>;


	ld.param.u64 	%rd3, [Gradient_param_0];
	ld.param.u64 	%rd4, [Gradient_param_1];
	ld.param.u64 	%rd5, [Gradient_param_2];
	ld.param.u64 	%rd6, [Gradient_param_3];
	ld.param.u32 	%r4, [Gradient_param_4];
	ld.param.u32 	%r5, [Gradient_param_5];
	ld.param.u32 	%r10, [Gradient_param_6];
	ld.param.u32 	%r6, [Gradient_param_7];
	ld.param.u32 	%r7, [Gradient_param_8];
	ld.param.u64 	%rd7, [Gradient_param_10];
	ld.param.u32 	%r8, [Gradient_param_11];
	ld.param.f32 	%f1, [Gradient_param_12];
	ld.param.u32 	%r9, [Gradient_param_13];
	mov.u32 	%r11, %ntid.x;
	mov.u32 	%r12, %ctaid.x;
	mov.u32 	%r13, %tid.x;
	mad.lo.s32 	%r1, %r11, %r12, %r13;
	mov.u32 	%r14, %ntid.y;
	mov.u32 	%r15, %ctaid.y;
	mov.u32 	%r16, %tid.y;
	mad.lo.s32 	%r2, %r14, %r15, %r16;
	mov.u32 	%r17, %ntid.z;
	mov.u32 	%r18, %ctaid.z;
	mov.u32 	%r19, %tid.z;
	mad.lo.s32 	%r3, %r17, %r18, %r19;
	setp.ge.s32	%p1, %r2, %r5;
	setp.ge.s32	%p2, %r1, %r4;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r10;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_6;

	cvta.to.global.u64 	%rd8, %rd7;
	mad.lo.s32 	%r20, %r3, %r5, %r2;
	mad.lo.s32 	%r21, %r20, %r4, %r1;
	cvt.s64.s32	%rd1, %r21;
	mul.wide.s32 	%rd9, %r21, 4;
	add.s64 	%rd2, %rd8, %rd9;
	setp.eq.s32	%p6, %r8, 1;
	@%p6 bra 	BB0_4;
	bra.uni 	BB0_2;

BB0_4:
	ld.global.nc.f32 	%f3, [%rd2];
	setp.eq.f32	%p9, %f3, 0f00000000;
	@%p9 bra 	BB0_6;
	bra.uni 	BB0_5;

BB0_2:
	setp.ne.s32	%p7, %r8, 0;
	@%p7 bra 	BB0_5;

	ld.global.nc.f32 	%f2, [%rd2];
	setp.neu.f32	%p8, %f2, 0f00000000;
	@%p8 bra 	BB0_6;

BB0_5:
	cvta.to.global.u64 	%rd10, %rd5;
	cvta.to.global.u64 	%rd11, %rd4;
	cvta.to.global.u64 	%rd12, %rd3;
	cvta.to.global.u64 	%rd13, %rd6;
	add.s32 	%r22, %r1, %r9;
	add.s32 	%r23, %r2, %r9;
	add.s32 	%r24, %r3, %r9;
	mad.lo.s32 	%r25, %r24, %r7, %r23;
	mad.lo.s32 	%r26, %r25, %r6, %r22;
	add.s32 	%r27, %r25, -1;
	mad.lo.s32 	%r28, %r27, %r6, %r22;
	add.s32 	%r29, %r24, -1;
	mad.lo.s32 	%r30, %r29, %r7, %r23;
	mad.lo.s32 	%r31, %r30, %r6, %r22;
	add.s32 	%r32, %r25, 1;
	mad.lo.s32 	%r33, %r32, %r6, %r22;
	add.s32 	%r34, %r24, 1;
	mad.lo.s32 	%r35, %r34, %r7, %r23;
	mad.lo.s32 	%r36, %r35, %r6, %r22;
	add.s32 	%r37, %r25, -2;
	mad.lo.s32 	%r38, %r37, %r6, %r22;
	add.s32 	%r39, %r24, -2;
	mad.lo.s32 	%r40, %r39, %r7, %r23;
	mad.lo.s32 	%r41, %r40, %r6, %r22;
	add.s32 	%r42, %r25, 2;
	mad.lo.s32 	%r43, %r42, %r6, %r22;
	add.s32 	%r44, %r24, 2;
	mad.lo.s32 	%r45, %r44, %r7, %r23;
	mad.lo.s32 	%r46, %r45, %r6, %r22;
	mul.wide.s32 	%rd14, %r26, 4;
	add.s64 	%rd15, %rd13, %rd14;
	mul.wide.s32 	%rd16, %r33, 4;
	add.s64 	%rd17, %rd13, %rd16;
	ld.global.nc.f32 	%f4, [%rd17];
	mul.wide.s32 	%rd18, %r28, 4;
	add.s64 	%rd19, %rd13, %rd18;
	ld.global.nc.f32 	%f5, [%rd19];
	mul.wide.s32 	%rd20, %r36, 4;
	add.s64 	%rd21, %rd13, %rd20;
	ld.global.nc.f32 	%f6, [%rd21];
	mul.wide.s32 	%rd22, %r31, 4;
	add.s64 	%rd23, %rd13, %rd22;
	ld.global.nc.f32 	%f7, [%rd23];
	mul.wide.s32 	%rd24, %r43, 4;
	add.s64 	%rd25, %rd13, %rd24;
	ld.global.nc.f32 	%f8, [%rd25];
	mul.wide.s32 	%rd26, %r38, 4;
	add.s64 	%rd27, %rd13, %rd26;
	ld.global.nc.f32 	%f9, [%rd27];
	mul.wide.s32 	%rd28, %r46, 4;
	add.s64 	%rd29, %rd13, %rd28;
	ld.global.nc.f32 	%f10, [%rd29];
	mul.wide.s32 	%rd30, %r41, 4;
	add.s64 	%rd31, %rd13, %rd30;
	ld.global.nc.f32 	%f11, [%rd31];
	ld.global.nc.f32 	%f12, [%rd15+-8];
	ld.global.nc.f32 	%f13, [%rd15+8];
	sub.f32 	%f14, %f13, %f12;
	cvt.f64.f32	%fd1, %f14;
	cvt.f64.f32	%fd2, %f1;
	mul.f64 	%fd3, %fd2, 0d4028000000000000;
	div.rn.f64 	%fd4, %fd1, %fd3;
	ld.global.nc.f32 	%f15, [%rd15+-4];
	ld.global.nc.f32 	%f16, [%rd15+4];
	sub.f32 	%f17, %f15, %f16;
	mul.f32 	%f18, %f17, 0f41000000;
	cvt.f64.f32	%fd5, %f18;
	div.rn.f64 	%fd6, %fd5, %fd3;
	add.f64 	%fd7, %fd4, %fd6;
	cvt.rn.f32.f64	%f19, %fd7;
	shl.b64 	%rd32, %rd1, 2;
	add.s64 	%rd33, %rd12, %rd32;
	ld.global.f32 	%f20, [%rd33];
	add.f32 	%f21, %f20, %f19;
	st.global.f32 	[%rd33], %f21;
	sub.f32 	%f22, %f8, %f9;
	cvt.f64.f32	%fd8, %f22;
	div.rn.f64 	%fd9, %fd8, %fd3;
	sub.f32 	%f23, %f5, %f4;
	mul.f32 	%f24, %f23, 0f41000000;
	cvt.f64.f32	%fd10, %f24;
	div.rn.f64 	%fd11, %fd10, %fd3;
	add.f64 	%fd12, %fd9, %fd11;
	cvt.rn.f32.f64	%f25, %fd12;
	add.s64 	%rd34, %rd11, %rd32;
	ld.global.f32 	%f26, [%rd34];
	add.f32 	%f27, %f26, %f25;
	st.global.f32 	[%rd34], %f27;
	sub.f32 	%f28, %f10, %f11;
	cvt.f64.f32	%fd13, %f28;
	div.rn.f64 	%fd14, %fd13, %fd3;
	sub.f32 	%f29, %f7, %f6;
	mul.f32 	%f30, %f29, 0f41000000;
	cvt.f64.f32	%fd15, %f30;
	div.rn.f64 	%fd16, %fd15, %fd3;
	add.f64 	%fd17, %fd14, %fd16;
	cvt.rn.f32.f64	%f31, %fd17;
	add.s64 	%rd35, %rd10, %rd32;
	ld.global.f32 	%f32, [%rd35];
	add.f32 	%f33, %f32, %f31;
	st.global.f32 	[%rd35], %f33;

BB0_6:
	ret;
}


`
   Gradient_ptx_53 = `
.version 5.0
.target sm_20
.address_size 64

	// .globl	Gradient

.visible .entry Gradient(
	.param .u64 Gradient_param_0,
	.param .u64 Gradient_param_1,
	.param .u64 Gradient_param_2,
	.param .u64 Gradient_param_3,
	.param .u32 Gradient_param_4,
	.param .u32 Gradient_param_5,
	.param .u32 Gradient_param_6,
	.param .u32 Gradient_param_7,
	.param .u32 Gradient_param_8,
	.param .u32 Gradient_param_9,
	.param .u64 Gradient_param_10,
	.param .u32 Gradient_param_11,
	.param .f32 Gradient_param_12,
	.param .u32 Gradient_param_13
)
{
	.reg .pred 	%p<10>;
	.reg .f32 	%f<34>;
	.reg .b32 	%r<47>;
	.reg .f64 	%fd<18>;
	.reg .b64 	%rd<36>;


	ld.param.u64 	%rd3, [Gradient_param_0];
	ld.param.u64 	%rd4, [Gradient_param_1];
	ld.param.u64 	%rd5, [Gradient_param_2];
	ld.param.u64 	%rd6, [Gradient_param_3];
	ld.param.u32 	%r4, [Gradient_param_4];
	ld.param.u32 	%r5, [Gradient_param_5];
	ld.param.u32 	%r10, [Gradient_param_6];
	ld.param.u32 	%r6, [Gradient_param_7];
	ld.param.u32 	%r7, [Gradient_param_8];
	ld.param.u64 	%rd7, [Gradient_param_10];
	ld.param.u32 	%r8, [Gradient_param_11];
	ld.param.f32 	%f1, [Gradient_param_12];
	ld.param.u32 	%r9, [Gradient_param_13];
	mov.u32 	%r11, %ntid.x;
	mov.u32 	%r12, %ctaid.x;
	mov.u32 	%r13, %tid.x;
	mad.lo.s32 	%r1, %r11, %r12, %r13;
	mov.u32 	%r14, %ntid.y;
	mov.u32 	%r15, %ctaid.y;
	mov.u32 	%r16, %tid.y;
	mad.lo.s32 	%r2, %r14, %r15, %r16;
	mov.u32 	%r17, %ntid.z;
	mov.u32 	%r18, %ctaid.z;
	mov.u32 	%r19, %tid.z;
	mad.lo.s32 	%r3, %r17, %r18, %r19;
	setp.ge.s32	%p1, %r2, %r5;
	setp.ge.s32	%p2, %r1, %r4;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r10;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_6;

	cvta.to.global.u64 	%rd8, %rd7;
	mad.lo.s32 	%r20, %r3, %r5, %r2;
	mad.lo.s32 	%r21, %r20, %r4, %r1;
	cvt.s64.s32	%rd1, %r21;
	mul.wide.s32 	%rd9, %r21, 4;
	add.s64 	%rd2, %rd8, %rd9;
	setp.eq.s32	%p6, %r8, 1;
	@%p6 bra 	BB0_4;
	bra.uni 	BB0_2;

BB0_4:
	ld.global.f32 	%f3, [%rd2];
	setp.eq.f32	%p9, %f3, 0f00000000;
	@%p9 bra 	BB0_6;
	bra.uni 	BB0_5;

BB0_2:
	setp.ne.s32	%p7, %r8, 0;
	@%p7 bra 	BB0_5;

	ld.global.f32 	%f2, [%rd2];
	setp.neu.f32	%p8, %f2, 0f00000000;
	@%p8 bra 	BB0_6;

BB0_5:
	cvta.to.global.u64 	%rd10, %rd5;
	cvta.to.global.u64 	%rd11, %rd4;
	cvta.to.global.u64 	%rd12, %rd3;
	cvta.to.global.u64 	%rd13, %rd6;
	add.s32 	%r22, %r1, %r9;
	add.s32 	%r23, %r2, %r9;
	add.s32 	%r24, %r3, %r9;
	mad.lo.s32 	%r25, %r24, %r7, %r23;
	mad.lo.s32 	%r26, %r25, %r6, %r22;
	add.s32 	%r27, %r25, -1;
	mad.lo.s32 	%r28, %r27, %r6, %r22;
	add.s32 	%r29, %r24, -1;
	mad.lo.s32 	%r30, %r29, %r7, %r23;
	mad.lo.s32 	%r31, %r30, %r6, %r22;
	add.s32 	%r32, %r25, 1;
	mad.lo.s32 	%r33, %r32, %r6, %r22;
	add.s32 	%r34, %r24, 1;
	mad.lo.s32 	%r35, %r34, %r7, %r23;
	mad.lo.s32 	%r36, %r35, %r6, %r22;
	add.s32 	%r37, %r25, -2;
	mad.lo.s32 	%r38, %r37, %r6, %r22;
	add.s32 	%r39, %r24, -2;
	mad.lo.s32 	%r40, %r39, %r7, %r23;
	mad.lo.s32 	%r41, %r40, %r6, %r22;
	add.s32 	%r42, %r25, 2;
	mad.lo.s32 	%r43, %r42, %r6, %r22;
	add.s32 	%r44, %r24, 2;
	mad.lo.s32 	%r45, %r44, %r7, %r23;
	mad.lo.s32 	%r46, %r45, %r6, %r22;
	mul.wide.s32 	%rd14, %r26, 4;
	add.s64 	%rd15, %rd13, %rd14;
	mul.wide.s32 	%rd16, %r33, 4;
	add.s64 	%rd17, %rd13, %rd16;
	ld.global.f32 	%f4, [%rd17];
	mul.wide.s32 	%rd18, %r28, 4;
	add.s64 	%rd19, %rd13, %rd18;
	ld.global.f32 	%f5, [%rd19];
	mul.wide.s32 	%rd20, %r36, 4;
	add.s64 	%rd21, %rd13, %rd20;
	ld.global.f32 	%f6, [%rd21];
	mul.wide.s32 	%rd22, %r31, 4;
	add.s64 	%rd23, %rd13, %rd22;
	ld.global.f32 	%f7, [%rd23];
	mul.wide.s32 	%rd24, %r43, 4;
	add.s64 	%rd25, %rd13, %rd24;
	ld.global.f32 	%f8, [%rd25];
	mul.wide.s32 	%rd26, %r38, 4;
	add.s64 	%rd27, %rd13, %rd26;
	ld.global.f32 	%f9, [%rd27];
	mul.wide.s32 	%rd28, %r46, 4;
	add.s64 	%rd29, %rd13, %rd28;
	ld.global.f32 	%f10, [%rd29];
	mul.wide.s32 	%rd30, %r41, 4;
	add.s64 	%rd31, %rd13, %rd30;
	ld.global.f32 	%f11, [%rd31];
	ld.global.f32 	%f12, [%rd15+-8];
	ld.global.f32 	%f13, [%rd15+8];
	sub.f32 	%f14, %f13, %f12;
	cvt.f64.f32	%fd1, %f14;
	cvt.f64.f32	%fd2, %f1;
	mul.f64 	%fd3, %fd2, 0d4028000000000000;
	div.rn.f64 	%fd4, %fd1, %fd3;
	ld.global.f32 	%f15, [%rd15+-4];
	ld.global.f32 	%f16, [%rd15+4];
	sub.f32 	%f17, %f15, %f16;
	mul.f32 	%f18, %f17, 0f41000000;
	cvt.f64.f32	%fd5, %f18;
	div.rn.f64 	%fd6, %fd5, %fd3;
	add.f64 	%fd7, %fd4, %fd6;
	cvt.rn.f32.f64	%f19, %fd7;
	shl.b64 	%rd32, %rd1, 2;
	add.s64 	%rd33, %rd12, %rd32;
	ld.global.f32 	%f20, [%rd33];
	add.f32 	%f21, %f20, %f19;
	st.global.f32 	[%rd33], %f21;
	sub.f32 	%f22, %f8, %f9;
	cvt.f64.f32	%fd8, %f22;
	div.rn.f64 	%fd9, %fd8, %fd3;
	sub.f32 	%f23, %f5, %f4;
	mul.f32 	%f24, %f23, 0f41000000;
	cvt.f64.f32	%fd10, %f24;
	div.rn.f64 	%fd11, %fd10, %fd3;
	add.f64 	%fd12, %fd9, %fd11;
	cvt.rn.f32.f64	%f25, %fd12;
	add.s64 	%rd34, %rd11, %rd32;
	ld.global.f32 	%f26, [%rd34];
	add.f32 	%f27, %f26, %f25;
	st.global.f32 	[%rd34], %f27;
	sub.f32 	%f28, %f10, %f11;
	cvt.f64.f32	%fd13, %f28;
	div.rn.f64 	%fd14, %fd13, %fd3;
	sub.f32 	%f29, %f7, %f6;
	mul.f32 	%f30, %f29, 0f41000000;
	cvt.f64.f32	%fd15, %f30;
	div.rn.f64 	%fd16, %fd15, %fd3;
	add.f64 	%fd17, %fd14, %fd16;
	cvt.rn.f32.f64	%f31, %fd17;
	add.s64 	%rd35, %rd10, %rd32;
	ld.global.f32 	%f32, [%rd35];
	add.f32 	%f33, %f32, %f31;
	st.global.f32 	[%rd35], %f33;

BB0_6:
	ret;
}


`
 )
