package ext_kernels

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for spkernmulRSymm3D kernel
var spkernmulRSymm3D_code cu.Function

// Stores the arguments for spkernmulRSymm3D kernel invocation
type spkernmulRSymm3D_args_t struct{
	 arg_fftMx unsafe.Pointer
	 arg_fftMy unsafe.Pointer
	 arg_fftMz unsafe.Pointer
	 arg_fftKx unsafe.Pointer
	 arg_fftKy unsafe.Pointer
	 arg_fftKz unsafe.Pointer
	 arg_Nx int
	 arg_Ny int
	 arg_Nz int
	 argptr [9]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for spkernmulRSymm3D kernel invocation
var spkernmulRSymm3D_args spkernmulRSymm3D_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 spkernmulRSymm3D_args.argptr[0] = unsafe.Pointer(&spkernmulRSymm3D_args.arg_fftMx)
	 spkernmulRSymm3D_args.argptr[1] = unsafe.Pointer(&spkernmulRSymm3D_args.arg_fftMy)
	 spkernmulRSymm3D_args.argptr[2] = unsafe.Pointer(&spkernmulRSymm3D_args.arg_fftMz)
	 spkernmulRSymm3D_args.argptr[3] = unsafe.Pointer(&spkernmulRSymm3D_args.arg_fftKx)
	 spkernmulRSymm3D_args.argptr[4] = unsafe.Pointer(&spkernmulRSymm3D_args.arg_fftKy)
	 spkernmulRSymm3D_args.argptr[5] = unsafe.Pointer(&spkernmulRSymm3D_args.arg_fftKz)
	 spkernmulRSymm3D_args.argptr[6] = unsafe.Pointer(&spkernmulRSymm3D_args.arg_Nx)
	 spkernmulRSymm3D_args.argptr[7] = unsafe.Pointer(&spkernmulRSymm3D_args.arg_Ny)
	 spkernmulRSymm3D_args.argptr[8] = unsafe.Pointer(&spkernmulRSymm3D_args.arg_Nz)
	 }

// Wrapper for spkernmulRSymm3D CUDA kernel, asynchronous.
func K_ext_spkernmulRSymm3D_async ( fftMx unsafe.Pointer, fftMy unsafe.Pointer, fftMz unsafe.Pointer, fftKx unsafe.Pointer, fftKy unsafe.Pointer, fftKz unsafe.Pointer, Nx int, Ny int, Nz int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("spkernmulRSymm3D")
	}

	spkernmulRSymm3D_args.Lock()
	defer spkernmulRSymm3D_args.Unlock()

	if spkernmulRSymm3D_code == 0{
		spkernmulRSymm3D_code = fatbinLoad(spkernmulRSymm3D_map, "spkernmulRSymm3D")
	}

	 spkernmulRSymm3D_args.arg_fftMx = fftMx
	 spkernmulRSymm3D_args.arg_fftMy = fftMy
	 spkernmulRSymm3D_args.arg_fftMz = fftMz
	 spkernmulRSymm3D_args.arg_fftKx = fftKx
	 spkernmulRSymm3D_args.arg_fftKy = fftKy
	 spkernmulRSymm3D_args.arg_fftKz = fftKz
	 spkernmulRSymm3D_args.arg_Nx = Nx
	 spkernmulRSymm3D_args.arg_Ny = Ny
	 spkernmulRSymm3D_args.arg_Nz = Nz
	

	args := spkernmulRSymm3D_args.argptr[:]
	cu.LaunchKernel(spkernmulRSymm3D_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("spkernmulRSymm3D")
	}
}

// maps compute capability on PTX code for spkernmulRSymm3D kernel.
var spkernmulRSymm3D_map = map[int]string{ 0: "" ,
20: spkernmulRSymm3D_ptx_20 ,
30: spkernmulRSymm3D_ptx_30 ,
35: spkernmulRSymm3D_ptx_35 ,
50: spkernmulRSymm3D_ptx_50 ,
52: spkernmulRSymm3D_ptx_52 ,
53: spkernmulRSymm3D_ptx_53  }

// spkernmulRSymm3D PTX code for various compute capabilities.
const(
  spkernmulRSymm3D_ptx_20 = `
.version 5.0
.target sm_20
.address_size 64

	// .globl	spkernmulRSymm3D

.visible .entry spkernmulRSymm3D(
	.param .u64 spkernmulRSymm3D_param_0,
	.param .u64 spkernmulRSymm3D_param_1,
	.param .u64 spkernmulRSymm3D_param_2,
	.param .u64 spkernmulRSymm3D_param_3,
	.param .u64 spkernmulRSymm3D_param_4,
	.param .u64 spkernmulRSymm3D_param_5,
	.param .u32 spkernmulRSymm3D_param_6,
	.param .u32 spkernmulRSymm3D_param_7,
	.param .u32 spkernmulRSymm3D_param_8
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<23>;
	.reg .b32 	%r<32>;
	.reg .b64 	%rd<21>;


	ld.param.u64 	%rd1, [spkernmulRSymm3D_param_0];
	ld.param.u64 	%rd2, [spkernmulRSymm3D_param_1];
	ld.param.u64 	%rd3, [spkernmulRSymm3D_param_2];
	ld.param.u64 	%rd4, [spkernmulRSymm3D_param_3];
	ld.param.u64 	%rd5, [spkernmulRSymm3D_param_4];
	ld.param.u64 	%rd6, [spkernmulRSymm3D_param_5];
	ld.param.u32 	%r4, [spkernmulRSymm3D_param_6];
	ld.param.u32 	%r5, [spkernmulRSymm3D_param_7];
	ld.param.u32 	%r6, [spkernmulRSymm3D_param_8];
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %ctaid.x;
	mov.u32 	%r9, %tid.x;
	mad.lo.s32 	%r1, %r7, %r8, %r9;
	mov.u32 	%r10, %ntid.y;
	mov.u32 	%r11, %ctaid.y;
	mov.u32 	%r12, %tid.y;
	mad.lo.s32 	%r2, %r10, %r11, %r12;
	mov.u32 	%r13, %ntid.z;
	mov.u32 	%r14, %ctaid.z;
	mov.u32 	%r15, %tid.z;
	mad.lo.s32 	%r3, %r13, %r14, %r15;
	setp.ge.s32	%p1, %r2, %r5;
	setp.ge.s32	%p2, %r1, %r4;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r6;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_2;

	cvta.to.global.u64 	%rd7, %rd3;
	cvta.to.global.u64 	%rd8, %rd2;
	cvta.to.global.u64 	%rd9, %rd1;
	cvta.to.global.u64 	%rd10, %rd4;
	mad.lo.s32 	%r16, %r3, %r5, %r2;
	mad.lo.s32 	%r17, %r16, %r4, %r1;
	shl.b32 	%r18, %r17, 1;
	mul.wide.s32 	%rd11, %r18, 4;
	add.s64 	%rd12, %rd9, %rd11;
	ld.global.f32 	%f1, [%rd12];
	add.s64 	%rd13, %rd8, %rd11;
	ld.global.f32 	%f2, [%rd13];
	add.s64 	%rd14, %rd7, %rd11;
	ld.global.f32 	%f3, [%rd14];
	shr.u32 	%r19, %r5, 31;
	add.s32 	%r20, %r5, %r19;
	shr.s32 	%r21, %r20, 1;
	setp.gt.s32	%p6, %r2, %r21;
	sub.s32 	%r22, %r5, %r2;
	selp.b32	%r23, %r22, %r2, %p6;
	selp.f32	%f4, 0fBF800000, 0f3F800000, %p6;
	shr.u32 	%r24, %r6, 31;
	add.s32 	%r25, %r6, %r24;
	shr.s32 	%r26, %r25, 1;
	setp.gt.s32	%p7, %r3, %r26;
	sub.s32 	%r27, %r6, %r3;
	selp.b32	%r28, %r27, %r3, %p7;
	selp.f32	%f5, 0fBF800000, 0f3F800000, %p7;
	add.s32 	%r29, %r21, 1;
	mad.lo.s32 	%r30, %r28, %r29, %r23;
	mad.lo.s32 	%r31, %r30, %r4, %r1;
	mul.wide.s32 	%rd15, %r31, 4;
	add.s64 	%rd16, %rd10, %rd15;
	cvta.to.global.u64 	%rd17, %rd5;
	add.s64 	%rd18, %rd17, %rd15;
	ld.global.f32 	%f6, [%rd18];
	mul.f32 	%f7, %f4, %f6;
	cvta.to.global.u64 	%rd19, %rd6;
	add.s64 	%rd20, %rd19, %rd15;
	ld.global.f32 	%f8, [%rd20];
	mul.f32 	%f9, %f5, %f8;
	ld.global.f32 	%f10, [%rd16];
	ld.global.f32 	%f11, [%rd12+4];
	mul.f32 	%f12, %f11, %f10;
	neg.f32 	%f13, %f12;
	ld.global.f32 	%f14, [%rd13+4];
	mul.f32 	%f15, %f14, %f7;
	sub.f32 	%f16, %f13, %f15;
	ld.global.f32 	%f17, [%rd14+4];
	mul.f32 	%f18, %f17, %f9;
	sub.f32 	%f19, %f16, %f18;
	st.global.f32 	[%rd12], %f19;
	mul.f32 	%f20, %f2, %f7;
	fma.rn.f32 	%f21, %f1, %f10, %f20;
	fma.rn.f32 	%f22, %f3, %f9, %f21;
	st.global.f32 	[%rd12+4], %f22;

BB0_2:
	ret;
}


`
   spkernmulRSymm3D_ptx_30 = `
.version 5.0
.target sm_30
.address_size 64

	// .globl	spkernmulRSymm3D

.visible .entry spkernmulRSymm3D(
	.param .u64 spkernmulRSymm3D_param_0,
	.param .u64 spkernmulRSymm3D_param_1,
	.param .u64 spkernmulRSymm3D_param_2,
	.param .u64 spkernmulRSymm3D_param_3,
	.param .u64 spkernmulRSymm3D_param_4,
	.param .u64 spkernmulRSymm3D_param_5,
	.param .u32 spkernmulRSymm3D_param_6,
	.param .u32 spkernmulRSymm3D_param_7,
	.param .u32 spkernmulRSymm3D_param_8
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<23>;
	.reg .b32 	%r<32>;
	.reg .b64 	%rd<21>;


	ld.param.u64 	%rd1, [spkernmulRSymm3D_param_0];
	ld.param.u64 	%rd2, [spkernmulRSymm3D_param_1];
	ld.param.u64 	%rd3, [spkernmulRSymm3D_param_2];
	ld.param.u64 	%rd4, [spkernmulRSymm3D_param_3];
	ld.param.u64 	%rd5, [spkernmulRSymm3D_param_4];
	ld.param.u64 	%rd6, [spkernmulRSymm3D_param_5];
	ld.param.u32 	%r4, [spkernmulRSymm3D_param_6];
	ld.param.u32 	%r5, [spkernmulRSymm3D_param_7];
	ld.param.u32 	%r6, [spkernmulRSymm3D_param_8];
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %ctaid.x;
	mov.u32 	%r9, %tid.x;
	mad.lo.s32 	%r1, %r7, %r8, %r9;
	mov.u32 	%r10, %ntid.y;
	mov.u32 	%r11, %ctaid.y;
	mov.u32 	%r12, %tid.y;
	mad.lo.s32 	%r2, %r10, %r11, %r12;
	mov.u32 	%r13, %ntid.z;
	mov.u32 	%r14, %ctaid.z;
	mov.u32 	%r15, %tid.z;
	mad.lo.s32 	%r3, %r13, %r14, %r15;
	setp.ge.s32	%p1, %r2, %r5;
	setp.ge.s32	%p2, %r1, %r4;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r6;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_2;

	cvta.to.global.u64 	%rd7, %rd3;
	cvta.to.global.u64 	%rd8, %rd2;
	cvta.to.global.u64 	%rd9, %rd1;
	cvta.to.global.u64 	%rd10, %rd4;
	mad.lo.s32 	%r16, %r3, %r5, %r2;
	mad.lo.s32 	%r17, %r16, %r4, %r1;
	shl.b32 	%r18, %r17, 1;
	mul.wide.s32 	%rd11, %r18, 4;
	add.s64 	%rd12, %rd9, %rd11;
	ld.global.f32 	%f1, [%rd12];
	add.s64 	%rd13, %rd8, %rd11;
	ld.global.f32 	%f2, [%rd13];
	add.s64 	%rd14, %rd7, %rd11;
	ld.global.f32 	%f3, [%rd14];
	shr.u32 	%r19, %r5, 31;
	add.s32 	%r20, %r5, %r19;
	shr.s32 	%r21, %r20, 1;
	setp.gt.s32	%p6, %r2, %r21;
	sub.s32 	%r22, %r5, %r2;
	selp.b32	%r23, %r22, %r2, %p6;
	selp.f32	%f4, 0fBF800000, 0f3F800000, %p6;
	shr.u32 	%r24, %r6, 31;
	add.s32 	%r25, %r6, %r24;
	shr.s32 	%r26, %r25, 1;
	setp.gt.s32	%p7, %r3, %r26;
	sub.s32 	%r27, %r6, %r3;
	selp.b32	%r28, %r27, %r3, %p7;
	selp.f32	%f5, 0fBF800000, 0f3F800000, %p7;
	add.s32 	%r29, %r21, 1;
	mad.lo.s32 	%r30, %r28, %r29, %r23;
	mad.lo.s32 	%r31, %r30, %r4, %r1;
	mul.wide.s32 	%rd15, %r31, 4;
	add.s64 	%rd16, %rd10, %rd15;
	cvta.to.global.u64 	%rd17, %rd5;
	add.s64 	%rd18, %rd17, %rd15;
	ld.global.f32 	%f6, [%rd18];
	mul.f32 	%f7, %f4, %f6;
	cvta.to.global.u64 	%rd19, %rd6;
	add.s64 	%rd20, %rd19, %rd15;
	ld.global.f32 	%f8, [%rd20];
	mul.f32 	%f9, %f5, %f8;
	ld.global.f32 	%f10, [%rd16];
	ld.global.f32 	%f11, [%rd12+4];
	mul.f32 	%f12, %f11, %f10;
	neg.f32 	%f13, %f12;
	ld.global.f32 	%f14, [%rd13+4];
	mul.f32 	%f15, %f14, %f7;
	sub.f32 	%f16, %f13, %f15;
	ld.global.f32 	%f17, [%rd14+4];
	mul.f32 	%f18, %f17, %f9;
	sub.f32 	%f19, %f16, %f18;
	st.global.f32 	[%rd12], %f19;
	mul.f32 	%f20, %f2, %f7;
	fma.rn.f32 	%f21, %f1, %f10, %f20;
	fma.rn.f32 	%f22, %f3, %f9, %f21;
	st.global.f32 	[%rd12+4], %f22;

BB0_2:
	ret;
}


`
   spkernmulRSymm3D_ptx_35 = `
.version 5.0
.target sm_35
.address_size 64

	// .globl	spkernmulRSymm3D

.visible .entry spkernmulRSymm3D(
	.param .u64 spkernmulRSymm3D_param_0,
	.param .u64 spkernmulRSymm3D_param_1,
	.param .u64 spkernmulRSymm3D_param_2,
	.param .u64 spkernmulRSymm3D_param_3,
	.param .u64 spkernmulRSymm3D_param_4,
	.param .u64 spkernmulRSymm3D_param_5,
	.param .u32 spkernmulRSymm3D_param_6,
	.param .u32 spkernmulRSymm3D_param_7,
	.param .u32 spkernmulRSymm3D_param_8
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<23>;
	.reg .b32 	%r<32>;
	.reg .b64 	%rd<21>;


	ld.param.u64 	%rd1, [spkernmulRSymm3D_param_0];
	ld.param.u64 	%rd2, [spkernmulRSymm3D_param_1];
	ld.param.u64 	%rd3, [spkernmulRSymm3D_param_2];
	ld.param.u64 	%rd4, [spkernmulRSymm3D_param_3];
	ld.param.u64 	%rd5, [spkernmulRSymm3D_param_4];
	ld.param.u64 	%rd6, [spkernmulRSymm3D_param_5];
	ld.param.u32 	%r4, [spkernmulRSymm3D_param_6];
	ld.param.u32 	%r5, [spkernmulRSymm3D_param_7];
	ld.param.u32 	%r6, [spkernmulRSymm3D_param_8];
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %ctaid.x;
	mov.u32 	%r9, %tid.x;
	mad.lo.s32 	%r1, %r7, %r8, %r9;
	mov.u32 	%r10, %ntid.y;
	mov.u32 	%r11, %ctaid.y;
	mov.u32 	%r12, %tid.y;
	mad.lo.s32 	%r2, %r10, %r11, %r12;
	mov.u32 	%r13, %ntid.z;
	mov.u32 	%r14, %ctaid.z;
	mov.u32 	%r15, %tid.z;
	mad.lo.s32 	%r3, %r13, %r14, %r15;
	setp.ge.s32	%p1, %r2, %r5;
	setp.ge.s32	%p2, %r1, %r4;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r6;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_2;

	cvta.to.global.u64 	%rd7, %rd3;
	cvta.to.global.u64 	%rd8, %rd2;
	cvta.to.global.u64 	%rd9, %rd1;
	cvta.to.global.u64 	%rd10, %rd4;
	mad.lo.s32 	%r16, %r3, %r5, %r2;
	mad.lo.s32 	%r17, %r16, %r4, %r1;
	shl.b32 	%r18, %r17, 1;
	mul.wide.s32 	%rd11, %r18, 4;
	add.s64 	%rd12, %rd9, %rd11;
	ld.global.f32 	%f1, [%rd12];
	add.s64 	%rd13, %rd8, %rd11;
	ld.global.nc.f32 	%f2, [%rd13];
	add.s64 	%rd14, %rd7, %rd11;
	ld.global.nc.f32 	%f3, [%rd14];
	shr.u32 	%r19, %r5, 31;
	add.s32 	%r20, %r5, %r19;
	shr.s32 	%r21, %r20, 1;
	setp.gt.s32	%p6, %r2, %r21;
	sub.s32 	%r22, %r5, %r2;
	selp.b32	%r23, %r22, %r2, %p6;
	selp.f32	%f4, 0fBF800000, 0f3F800000, %p6;
	shr.u32 	%r24, %r6, 31;
	add.s32 	%r25, %r6, %r24;
	shr.s32 	%r26, %r25, 1;
	setp.gt.s32	%p7, %r3, %r26;
	sub.s32 	%r27, %r6, %r3;
	selp.b32	%r28, %r27, %r3, %p7;
	selp.f32	%f5, 0fBF800000, 0f3F800000, %p7;
	add.s32 	%r29, %r21, 1;
	mad.lo.s32 	%r30, %r28, %r29, %r23;
	mad.lo.s32 	%r31, %r30, %r4, %r1;
	mul.wide.s32 	%rd15, %r31, 4;
	add.s64 	%rd16, %rd10, %rd15;
	cvta.to.global.u64 	%rd17, %rd5;
	add.s64 	%rd18, %rd17, %rd15;
	ld.global.nc.f32 	%f6, [%rd18];
	mul.f32 	%f7, %f4, %f6;
	cvta.to.global.u64 	%rd19, %rd6;
	add.s64 	%rd20, %rd19, %rd15;
	ld.global.nc.f32 	%f8, [%rd20];
	mul.f32 	%f9, %f5, %f8;
	ld.global.nc.f32 	%f10, [%rd16];
	ld.global.f32 	%f11, [%rd12+4];
	mul.f32 	%f12, %f11, %f10;
	neg.f32 	%f13, %f12;
	ld.global.nc.f32 	%f14, [%rd13+4];
	mul.f32 	%f15, %f14, %f7;
	sub.f32 	%f16, %f13, %f15;
	ld.global.nc.f32 	%f17, [%rd14+4];
	mul.f32 	%f18, %f17, %f9;
	sub.f32 	%f19, %f16, %f18;
	st.global.f32 	[%rd12], %f19;
	mul.f32 	%f20, %f2, %f7;
	fma.rn.f32 	%f21, %f1, %f10, %f20;
	fma.rn.f32 	%f22, %f3, %f9, %f21;
	st.global.f32 	[%rd12+4], %f22;

BB0_2:
	ret;
}


`
   spkernmulRSymm3D_ptx_50 = `
.version 5.0
.target sm_50
.address_size 64

	// .globl	spkernmulRSymm3D

.visible .entry spkernmulRSymm3D(
	.param .u64 spkernmulRSymm3D_param_0,
	.param .u64 spkernmulRSymm3D_param_1,
	.param .u64 spkernmulRSymm3D_param_2,
	.param .u64 spkernmulRSymm3D_param_3,
	.param .u64 spkernmulRSymm3D_param_4,
	.param .u64 spkernmulRSymm3D_param_5,
	.param .u32 spkernmulRSymm3D_param_6,
	.param .u32 spkernmulRSymm3D_param_7,
	.param .u32 spkernmulRSymm3D_param_8
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<23>;
	.reg .b32 	%r<32>;
	.reg .b64 	%rd<21>;


	ld.param.u64 	%rd1, [spkernmulRSymm3D_param_0];
	ld.param.u64 	%rd2, [spkernmulRSymm3D_param_1];
	ld.param.u64 	%rd3, [spkernmulRSymm3D_param_2];
	ld.param.u64 	%rd4, [spkernmulRSymm3D_param_3];
	ld.param.u64 	%rd5, [spkernmulRSymm3D_param_4];
	ld.param.u64 	%rd6, [spkernmulRSymm3D_param_5];
	ld.param.u32 	%r4, [spkernmulRSymm3D_param_6];
	ld.param.u32 	%r5, [spkernmulRSymm3D_param_7];
	ld.param.u32 	%r6, [spkernmulRSymm3D_param_8];
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %ctaid.x;
	mov.u32 	%r9, %tid.x;
	mad.lo.s32 	%r1, %r7, %r8, %r9;
	mov.u32 	%r10, %ntid.y;
	mov.u32 	%r11, %ctaid.y;
	mov.u32 	%r12, %tid.y;
	mad.lo.s32 	%r2, %r10, %r11, %r12;
	mov.u32 	%r13, %ntid.z;
	mov.u32 	%r14, %ctaid.z;
	mov.u32 	%r15, %tid.z;
	mad.lo.s32 	%r3, %r13, %r14, %r15;
	setp.ge.s32	%p1, %r2, %r5;
	setp.ge.s32	%p2, %r1, %r4;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r6;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_2;

	cvta.to.global.u64 	%rd7, %rd3;
	cvta.to.global.u64 	%rd8, %rd2;
	cvta.to.global.u64 	%rd9, %rd1;
	cvta.to.global.u64 	%rd10, %rd4;
	mad.lo.s32 	%r16, %r3, %r5, %r2;
	mad.lo.s32 	%r17, %r16, %r4, %r1;
	shl.b32 	%r18, %r17, 1;
	mul.wide.s32 	%rd11, %r18, 4;
	add.s64 	%rd12, %rd9, %rd11;
	ld.global.f32 	%f1, [%rd12];
	add.s64 	%rd13, %rd8, %rd11;
	ld.global.nc.f32 	%f2, [%rd13];
	add.s64 	%rd14, %rd7, %rd11;
	ld.global.nc.f32 	%f3, [%rd14];
	shr.u32 	%r19, %r5, 31;
	add.s32 	%r20, %r5, %r19;
	shr.s32 	%r21, %r20, 1;
	setp.gt.s32	%p6, %r2, %r21;
	sub.s32 	%r22, %r5, %r2;
	selp.b32	%r23, %r22, %r2, %p6;
	selp.f32	%f4, 0fBF800000, 0f3F800000, %p6;
	shr.u32 	%r24, %r6, 31;
	add.s32 	%r25, %r6, %r24;
	shr.s32 	%r26, %r25, 1;
	setp.gt.s32	%p7, %r3, %r26;
	sub.s32 	%r27, %r6, %r3;
	selp.b32	%r28, %r27, %r3, %p7;
	selp.f32	%f5, 0fBF800000, 0f3F800000, %p7;
	add.s32 	%r29, %r21, 1;
	mad.lo.s32 	%r30, %r28, %r29, %r23;
	mad.lo.s32 	%r31, %r30, %r4, %r1;
	mul.wide.s32 	%rd15, %r31, 4;
	add.s64 	%rd16, %rd10, %rd15;
	cvta.to.global.u64 	%rd17, %rd5;
	add.s64 	%rd18, %rd17, %rd15;
	ld.global.nc.f32 	%f6, [%rd18];
	mul.f32 	%f7, %f4, %f6;
	cvta.to.global.u64 	%rd19, %rd6;
	add.s64 	%rd20, %rd19, %rd15;
	ld.global.nc.f32 	%f8, [%rd20];
	mul.f32 	%f9, %f5, %f8;
	ld.global.nc.f32 	%f10, [%rd16];
	ld.global.f32 	%f11, [%rd12+4];
	mul.f32 	%f12, %f11, %f10;
	neg.f32 	%f13, %f12;
	ld.global.nc.f32 	%f14, [%rd13+4];
	mul.f32 	%f15, %f14, %f7;
	sub.f32 	%f16, %f13, %f15;
	ld.global.nc.f32 	%f17, [%rd14+4];
	mul.f32 	%f18, %f17, %f9;
	sub.f32 	%f19, %f16, %f18;
	st.global.f32 	[%rd12], %f19;
	mul.f32 	%f20, %f2, %f7;
	fma.rn.f32 	%f21, %f1, %f10, %f20;
	fma.rn.f32 	%f22, %f3, %f9, %f21;
	st.global.f32 	[%rd12+4], %f22;

BB0_2:
	ret;
}


`
   spkernmulRSymm3D_ptx_52 = `
.version 5.0
.target sm_52
.address_size 64

	// .globl	spkernmulRSymm3D

.visible .entry spkernmulRSymm3D(
	.param .u64 spkernmulRSymm3D_param_0,
	.param .u64 spkernmulRSymm3D_param_1,
	.param .u64 spkernmulRSymm3D_param_2,
	.param .u64 spkernmulRSymm3D_param_3,
	.param .u64 spkernmulRSymm3D_param_4,
	.param .u64 spkernmulRSymm3D_param_5,
	.param .u32 spkernmulRSymm3D_param_6,
	.param .u32 spkernmulRSymm3D_param_7,
	.param .u32 spkernmulRSymm3D_param_8
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<23>;
	.reg .b32 	%r<32>;
	.reg .b64 	%rd<21>;


	ld.param.u64 	%rd1, [spkernmulRSymm3D_param_0];
	ld.param.u64 	%rd2, [spkernmulRSymm3D_param_1];
	ld.param.u64 	%rd3, [spkernmulRSymm3D_param_2];
	ld.param.u64 	%rd4, [spkernmulRSymm3D_param_3];
	ld.param.u64 	%rd5, [spkernmulRSymm3D_param_4];
	ld.param.u64 	%rd6, [spkernmulRSymm3D_param_5];
	ld.param.u32 	%r4, [spkernmulRSymm3D_param_6];
	ld.param.u32 	%r5, [spkernmulRSymm3D_param_7];
	ld.param.u32 	%r6, [spkernmulRSymm3D_param_8];
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %ctaid.x;
	mov.u32 	%r9, %tid.x;
	mad.lo.s32 	%r1, %r7, %r8, %r9;
	mov.u32 	%r10, %ntid.y;
	mov.u32 	%r11, %ctaid.y;
	mov.u32 	%r12, %tid.y;
	mad.lo.s32 	%r2, %r10, %r11, %r12;
	mov.u32 	%r13, %ntid.z;
	mov.u32 	%r14, %ctaid.z;
	mov.u32 	%r15, %tid.z;
	mad.lo.s32 	%r3, %r13, %r14, %r15;
	setp.ge.s32	%p1, %r2, %r5;
	setp.ge.s32	%p2, %r1, %r4;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r6;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_2;

	cvta.to.global.u64 	%rd7, %rd3;
	cvta.to.global.u64 	%rd8, %rd2;
	cvta.to.global.u64 	%rd9, %rd1;
	cvta.to.global.u64 	%rd10, %rd4;
	mad.lo.s32 	%r16, %r3, %r5, %r2;
	mad.lo.s32 	%r17, %r16, %r4, %r1;
	shl.b32 	%r18, %r17, 1;
	mul.wide.s32 	%rd11, %r18, 4;
	add.s64 	%rd12, %rd9, %rd11;
	ld.global.f32 	%f1, [%rd12];
	add.s64 	%rd13, %rd8, %rd11;
	ld.global.nc.f32 	%f2, [%rd13];
	add.s64 	%rd14, %rd7, %rd11;
	ld.global.nc.f32 	%f3, [%rd14];
	shr.u32 	%r19, %r5, 31;
	add.s32 	%r20, %r5, %r19;
	shr.s32 	%r21, %r20, 1;
	setp.gt.s32	%p6, %r2, %r21;
	sub.s32 	%r22, %r5, %r2;
	selp.b32	%r23, %r22, %r2, %p6;
	selp.f32	%f4, 0fBF800000, 0f3F800000, %p6;
	shr.u32 	%r24, %r6, 31;
	add.s32 	%r25, %r6, %r24;
	shr.s32 	%r26, %r25, 1;
	setp.gt.s32	%p7, %r3, %r26;
	sub.s32 	%r27, %r6, %r3;
	selp.b32	%r28, %r27, %r3, %p7;
	selp.f32	%f5, 0fBF800000, 0f3F800000, %p7;
	add.s32 	%r29, %r21, 1;
	mad.lo.s32 	%r30, %r28, %r29, %r23;
	mad.lo.s32 	%r31, %r30, %r4, %r1;
	mul.wide.s32 	%rd15, %r31, 4;
	add.s64 	%rd16, %rd10, %rd15;
	cvta.to.global.u64 	%rd17, %rd5;
	add.s64 	%rd18, %rd17, %rd15;
	ld.global.nc.f32 	%f6, [%rd18];
	mul.f32 	%f7, %f4, %f6;
	cvta.to.global.u64 	%rd19, %rd6;
	add.s64 	%rd20, %rd19, %rd15;
	ld.global.nc.f32 	%f8, [%rd20];
	mul.f32 	%f9, %f5, %f8;
	ld.global.nc.f32 	%f10, [%rd16];
	ld.global.f32 	%f11, [%rd12+4];
	mul.f32 	%f12, %f11, %f10;
	neg.f32 	%f13, %f12;
	ld.global.nc.f32 	%f14, [%rd13+4];
	mul.f32 	%f15, %f14, %f7;
	sub.f32 	%f16, %f13, %f15;
	ld.global.nc.f32 	%f17, [%rd14+4];
	mul.f32 	%f18, %f17, %f9;
	sub.f32 	%f19, %f16, %f18;
	st.global.f32 	[%rd12], %f19;
	mul.f32 	%f20, %f2, %f7;
	fma.rn.f32 	%f21, %f1, %f10, %f20;
	fma.rn.f32 	%f22, %f3, %f9, %f21;
	st.global.f32 	[%rd12+4], %f22;

BB0_2:
	ret;
}


`
   spkernmulRSymm3D_ptx_53 = `
.version 5.0
.target sm_53
.address_size 64

	// .globl	spkernmulRSymm3D

.visible .entry spkernmulRSymm3D(
	.param .u64 spkernmulRSymm3D_param_0,
	.param .u64 spkernmulRSymm3D_param_1,
	.param .u64 spkernmulRSymm3D_param_2,
	.param .u64 spkernmulRSymm3D_param_3,
	.param .u64 spkernmulRSymm3D_param_4,
	.param .u64 spkernmulRSymm3D_param_5,
	.param .u32 spkernmulRSymm3D_param_6,
	.param .u32 spkernmulRSymm3D_param_7,
	.param .u32 spkernmulRSymm3D_param_8
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<23>;
	.reg .b32 	%r<32>;
	.reg .b64 	%rd<21>;


	ld.param.u64 	%rd1, [spkernmulRSymm3D_param_0];
	ld.param.u64 	%rd2, [spkernmulRSymm3D_param_1];
	ld.param.u64 	%rd3, [spkernmulRSymm3D_param_2];
	ld.param.u64 	%rd4, [spkernmulRSymm3D_param_3];
	ld.param.u64 	%rd5, [spkernmulRSymm3D_param_4];
	ld.param.u64 	%rd6, [spkernmulRSymm3D_param_5];
	ld.param.u32 	%r4, [spkernmulRSymm3D_param_6];
	ld.param.u32 	%r5, [spkernmulRSymm3D_param_7];
	ld.param.u32 	%r6, [spkernmulRSymm3D_param_8];
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %ctaid.x;
	mov.u32 	%r9, %tid.x;
	mad.lo.s32 	%r1, %r7, %r8, %r9;
	mov.u32 	%r10, %ntid.y;
	mov.u32 	%r11, %ctaid.y;
	mov.u32 	%r12, %tid.y;
	mad.lo.s32 	%r2, %r10, %r11, %r12;
	mov.u32 	%r13, %ntid.z;
	mov.u32 	%r14, %ctaid.z;
	mov.u32 	%r15, %tid.z;
	mad.lo.s32 	%r3, %r13, %r14, %r15;
	setp.ge.s32	%p1, %r2, %r5;
	setp.ge.s32	%p2, %r1, %r4;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r6;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_2;

	cvta.to.global.u64 	%rd7, %rd3;
	cvta.to.global.u64 	%rd8, %rd2;
	cvta.to.global.u64 	%rd9, %rd1;
	cvta.to.global.u64 	%rd10, %rd4;
	mad.lo.s32 	%r16, %r3, %r5, %r2;
	mad.lo.s32 	%r17, %r16, %r4, %r1;
	shl.b32 	%r18, %r17, 1;
	mul.wide.s32 	%rd11, %r18, 4;
	add.s64 	%rd12, %rd9, %rd11;
	ld.global.f32 	%f1, [%rd12];
	add.s64 	%rd13, %rd8, %rd11;
	ld.global.nc.f32 	%f2, [%rd13];
	add.s64 	%rd14, %rd7, %rd11;
	ld.global.nc.f32 	%f3, [%rd14];
	shr.u32 	%r19, %r5, 31;
	add.s32 	%r20, %r5, %r19;
	shr.s32 	%r21, %r20, 1;
	setp.gt.s32	%p6, %r2, %r21;
	sub.s32 	%r22, %r5, %r2;
	selp.b32	%r23, %r22, %r2, %p6;
	selp.f32	%f4, 0fBF800000, 0f3F800000, %p6;
	shr.u32 	%r24, %r6, 31;
	add.s32 	%r25, %r6, %r24;
	shr.s32 	%r26, %r25, 1;
	setp.gt.s32	%p7, %r3, %r26;
	sub.s32 	%r27, %r6, %r3;
	selp.b32	%r28, %r27, %r3, %p7;
	selp.f32	%f5, 0fBF800000, 0f3F800000, %p7;
	add.s32 	%r29, %r21, 1;
	mad.lo.s32 	%r30, %r28, %r29, %r23;
	mad.lo.s32 	%r31, %r30, %r4, %r1;
	mul.wide.s32 	%rd15, %r31, 4;
	add.s64 	%rd16, %rd10, %rd15;
	cvta.to.global.u64 	%rd17, %rd5;
	add.s64 	%rd18, %rd17, %rd15;
	ld.global.nc.f32 	%f6, [%rd18];
	mul.f32 	%f7, %f4, %f6;
	cvta.to.global.u64 	%rd19, %rd6;
	add.s64 	%rd20, %rd19, %rd15;
	ld.global.nc.f32 	%f8, [%rd20];
	mul.f32 	%f9, %f5, %f8;
	ld.global.nc.f32 	%f10, [%rd16];
	ld.global.f32 	%f11, [%rd12+4];
	mul.f32 	%f12, %f11, %f10;
	neg.f32 	%f13, %f12;
	ld.global.nc.f32 	%f14, [%rd13+4];
	mul.f32 	%f15, %f14, %f7;
	sub.f32 	%f16, %f13, %f15;
	ld.global.nc.f32 	%f17, [%rd14+4];
	mul.f32 	%f18, %f17, %f9;
	sub.f32 	%f19, %f16, %f18;
	st.global.f32 	[%rd12], %f19;
	mul.f32 	%f20, %f2, %f7;
	fma.rn.f32 	%f21, %f1, %f10, %f20;
	fma.rn.f32 	%f22, %f3, %f9, %f21;
	st.global.f32 	[%rd12+4], %f22;

BB0_2:
	ret;
}


`
 )
