package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
	"unsafe"
)

// CUDA handle for addexchange kernel
var addexchange_code cu.Function

// Stores the arguments for addexchange kernel invocation
type addexchange_args_t struct {
	arg_Bx      unsafe.Pointer
	arg_By      unsafe.Pointer
	arg_Bz      unsafe.Pointer
	arg_mx      unsafe.Pointer
	arg_my      unsafe.Pointer
	arg_mz      unsafe.Pointer
	arg_Ms_     unsafe.Pointer
	arg_Ms_mul  float32
	arg_aLUT2d  unsafe.Pointer
	arg_regions unsafe.Pointer
	arg_wx      float32
	arg_wy      float32
	arg_wz      float32
	arg_Nx      int
	arg_Ny      int
	arg_Nz      int
	arg_PBC     byte
	argptr      [17]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for addexchange kernel invocation
var addexchange_args addexchange_args_t

func init() {
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	addexchange_args.argptr[0] = unsafe.Pointer(&addexchange_args.arg_Bx)
	addexchange_args.argptr[1] = unsafe.Pointer(&addexchange_args.arg_By)
	addexchange_args.argptr[2] = unsafe.Pointer(&addexchange_args.arg_Bz)
	addexchange_args.argptr[3] = unsafe.Pointer(&addexchange_args.arg_mx)
	addexchange_args.argptr[4] = unsafe.Pointer(&addexchange_args.arg_my)
	addexchange_args.argptr[5] = unsafe.Pointer(&addexchange_args.arg_mz)
	addexchange_args.argptr[6] = unsafe.Pointer(&addexchange_args.arg_Ms_)
	addexchange_args.argptr[7] = unsafe.Pointer(&addexchange_args.arg_Ms_mul)
	addexchange_args.argptr[8] = unsafe.Pointer(&addexchange_args.arg_aLUT2d)
	addexchange_args.argptr[9] = unsafe.Pointer(&addexchange_args.arg_regions)
	addexchange_args.argptr[10] = unsafe.Pointer(&addexchange_args.arg_wx)
	addexchange_args.argptr[11] = unsafe.Pointer(&addexchange_args.arg_wy)
	addexchange_args.argptr[12] = unsafe.Pointer(&addexchange_args.arg_wz)
	addexchange_args.argptr[13] = unsafe.Pointer(&addexchange_args.arg_Nx)
	addexchange_args.argptr[14] = unsafe.Pointer(&addexchange_args.arg_Ny)
	addexchange_args.argptr[15] = unsafe.Pointer(&addexchange_args.arg_Nz)
	addexchange_args.argptr[16] = unsafe.Pointer(&addexchange_args.arg_PBC)
}

// Wrapper for addexchange CUDA kernel, asynchronous.
func k_addexchange_async(Bx unsafe.Pointer, By unsafe.Pointer, Bz unsafe.Pointer, mx unsafe.Pointer, my unsafe.Pointer, mz unsafe.Pointer, Ms_ unsafe.Pointer, Ms_mul float32, aLUT2d unsafe.Pointer, regions unsafe.Pointer, wx float32, wy float32, wz float32, Nx int, Ny int, Nz int, PBC byte, cfg *config) {
	if Synchronous { // debug
		Sync()
		timer.Start("addexchange")
	}

	addexchange_args.Lock()
	defer addexchange_args.Unlock()

	if addexchange_code == 0 {
		addexchange_code = fatbinLoad(addexchange_map, "addexchange")
	}

	addexchange_args.arg_Bx = Bx
	addexchange_args.arg_By = By
	addexchange_args.arg_Bz = Bz
	addexchange_args.arg_mx = mx
	addexchange_args.arg_my = my
	addexchange_args.arg_mz = mz
	addexchange_args.arg_Ms_ = Ms_
	addexchange_args.arg_Ms_mul = Ms_mul
	addexchange_args.arg_aLUT2d = aLUT2d
	addexchange_args.arg_regions = regions
	addexchange_args.arg_wx = wx
	addexchange_args.arg_wy = wy
	addexchange_args.arg_wz = wz
	addexchange_args.arg_Nx = Nx
	addexchange_args.arg_Ny = Ny
	addexchange_args.arg_Nz = Nz
	addexchange_args.arg_PBC = PBC

	args := addexchange_args.argptr[:]
	cu.LaunchKernel(addexchange_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous { // debug
		Sync()
		timer.Stop("addexchange")
	}
}

// maps compute capability on PTX code for addexchange kernel.
var addexchange_map = map[int]string{0: "",
	20: addexchange_ptx_20,
	30: addexchange_ptx_30,
	35: addexchange_ptx_35,
	50: addexchange_ptx_50,
	52: addexchange_ptx_52,
	53: addexchange_ptx_53}

// addexchange PTX code for various compute capabilities.
const (
	addexchange_ptx_20 = `
.version 5.0
.target sm_20
.address_size 64

	// .globl	addexchange

.visible .entry addexchange(
	.param .u64 addexchange_param_0,
	.param .u64 addexchange_param_1,
	.param .u64 addexchange_param_2,
	.param .u64 addexchange_param_3,
	.param .u64 addexchange_param_4,
	.param .u64 addexchange_param_5,
	.param .u64 addexchange_param_6,
	.param .f32 addexchange_param_7,
	.param .u64 addexchange_param_8,
	.param .u64 addexchange_param_9,
	.param .f32 addexchange_param_10,
	.param .f32 addexchange_param_11,
	.param .f32 addexchange_param_12,
	.param .u32 addexchange_param_13,
	.param .u32 addexchange_param_14,
	.param .u32 addexchange_param_15,
	.param .u8 addexchange_param_16
)
{
	.reg .pred 	%p<22>;
	.reg .b16 	%rs<21>;
	.reg .f32 	%f<79>;
	.reg .b32 	%r<251>;
	.reg .b64 	%rd<108>;


	ld.param.u64 	%rd2, [addexchange_param_0];
	ld.param.u64 	%rd3, [addexchange_param_1];
	ld.param.u64 	%rd4, [addexchange_param_2];
	ld.param.u64 	%rd5, [addexchange_param_3];
	ld.param.u64 	%rd6, [addexchange_param_4];
	ld.param.u64 	%rd7, [addexchange_param_5];
	ld.param.u64 	%rd8, [addexchange_param_6];
	ld.param.f32 	%f77, [addexchange_param_7];
	ld.param.u64 	%rd9, [addexchange_param_8];
	ld.param.u64 	%rd10, [addexchange_param_9];
	ld.param.f32 	%f45, [addexchange_param_10];
	ld.param.f32 	%f46, [addexchange_param_11];
	ld.param.f32 	%f47, [addexchange_param_12];
	ld.param.u32 	%r52, [addexchange_param_13];
	ld.param.u32 	%r53, [addexchange_param_14];
	ld.param.u32 	%r54, [addexchange_param_15];
	ld.param.u8 	%rs3, [addexchange_param_16];
	mov.u32 	%r55, %ntid.x;
	mov.u32 	%r56, %ctaid.x;
	mov.u32 	%r57, %tid.x;
	mad.lo.s32 	%r1, %r55, %r56, %r57;
	mov.u32 	%r58, %ntid.y;
	mov.u32 	%r59, %ctaid.y;
	mov.u32 	%r60, %tid.y;
	mad.lo.s32 	%r2, %r58, %r59, %r60;
	mov.u32 	%r61, %ntid.z;
	mov.u32 	%r62, %ctaid.z;
	mov.u32 	%r63, %tid.z;
	mad.lo.s32 	%r3, %r61, %r62, %r63;
	setp.ge.s32	%p1, %r1, %r52;
	setp.ge.s32	%p2, %r2, %r53;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r54;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_45;

	cvta.to.global.u64 	%rd11, %rd7;
	cvta.to.global.u64 	%rd12, %rd6;
	cvta.to.global.u64 	%rd13, %rd5;
	mad.lo.s32 	%r64, %r3, %r53, %r2;
	mad.lo.s32 	%r65, %r64, %r52, %r1;
	cvt.s64.s32	%rd1, %r65;
	mul.wide.s32 	%rd14, %r65, 4;
	add.s64 	%rd15, %rd13, %rd14;
	add.s64 	%rd16, %rd12, %rd14;
	add.s64 	%rd17, %rd11, %rd14;
	ld.global.f32 	%f48, [%rd15];
	ld.global.f32 	%f49, [%rd16];
	mul.f32 	%f50, %f49, %f49;
	fma.rn.f32 	%f51, %f48, %f48, %f50;
	ld.global.f32 	%f52, [%rd17];
	fma.rn.f32 	%f53, %f52, %f52, %f51;
	setp.eq.f32	%p6, %f53, 0f00000000;
	@%p6 bra 	BB0_45;

	cvta.to.global.u64 	%rd18, %rd10;
	add.s64 	%rd19, %rd18, %rd1;
	ld.global.u8 	%rs1, [%rd19];
	cvt.u32.u16	%r66, %rs1;
	and.b32  	%r4, %r66, 255;
	and.b16  	%rs4, %rs3, 1;
	setp.eq.b16	%p7, %rs4, 1;
	@!%p7 bra 	BB0_4;
	bra.uni 	BB0_3;

BB0_3:
	add.s32 	%r71, %r1, -1;
	rem.s32 	%r72, %r71, %r52;
	add.s32 	%r73, %r72, %r52;
	rem.s32 	%r239, %r73, %r52;
	bra.uni 	BB0_5;

BB0_4:
	add.s32 	%r78, %r1, -1;
	mov.u32 	%r79, 0;
	max.s32 	%r239, %r78, %r79;

BB0_5:
	mad.lo.s32 	%r89, %r64, %r52, %r239;
	cvt.s64.s32	%rd20, %r89;
	mul.wide.s32 	%rd22, %r89, 4;
	add.s64 	%rd23, %rd13, %rd22;
	ld.global.f32 	%f1, [%rd23];
	add.s64 	%rd25, %rd12, %rd22;
	ld.global.f32 	%f2, [%rd25];
	add.s64 	%rd27, %rd11, %rd22;
	ld.global.f32 	%f3, [%rd27];
	add.s64 	%rd29, %rd18, %rd20;
	ld.global.u8 	%rs5, [%rd29];
	setp.gt.u16	%p8, %rs5, %rs1;
	cvt.u32.u16	%r8, %rs5;
	@%p8 bra 	BB0_7;
	bra.uni 	BB0_6;

BB0_7:
	add.s32 	%r93, %r8, 1;
	mul.lo.s32 	%r94, %r93, %r8;
	shr.u32 	%r95, %r94, 1;
	add.s32 	%r240, %r95, %r4;
	bra.uni 	BB0_8;

BB0_6:
	add.s32 	%r90, %r4, 1;
	mul.lo.s32 	%r91, %r90, %r4;
	shr.u32 	%r92, %r91, 1;
	add.s32 	%r240, %r8, %r92;

BB0_8:
	setp.eq.b16	%p9, %rs4, 1;
	cvta.to.global.u64 	%rd30, %rd9;
	mul.wide.s32 	%rd31, %r240, 4;
	add.s64 	%rd32, %rd30, %rd31;
	ld.global.f32 	%f54, [%rd32];
	mul.f32 	%f55, %f54, %f45;
	fma.rn.f32 	%f4, %f1, %f55, 0f00000000;
	fma.rn.f32 	%f5, %f2, %f55, 0f00000000;
	fma.rn.f32 	%f6, %f3, %f55, 0f00000000;
	add.s32 	%r12, %r1, 1;
	@!%p9 bra 	BB0_10;
	bra.uni 	BB0_9;

BB0_9:
	rem.s32 	%r100, %r12, %r52;
	add.s32 	%r101, %r100, %r52;
	rem.s32 	%r241, %r101, %r52;
	bra.uni 	BB0_11;

BB0_10:
	add.s32 	%r102, %r52, -1;
	min.s32 	%r241, %r12, %r102;

BB0_11:
	mad.lo.s32 	%r112, %r64, %r52, %r241;
	cvt.s64.s32	%rd33, %r112;
	mul.wide.s32 	%rd35, %r112, 4;
	add.s64 	%rd36, %rd13, %rd35;
	ld.global.f32 	%f7, [%rd36];
	add.s64 	%rd38, %rd12, %rd35;
	ld.global.f32 	%f8, [%rd38];
	add.s64 	%rd40, %rd11, %rd35;
	ld.global.f32 	%f9, [%rd40];
	add.s64 	%rd42, %rd18, %rd33;
	ld.global.u8 	%rs8, [%rd42];
	setp.gt.u16	%p10, %rs8, %rs1;
	cvt.u32.u16	%r16, %rs8;
	@%p10 bra 	BB0_13;
	bra.uni 	BB0_12;

BB0_13:
	add.s32 	%r116, %r16, 1;
	mul.lo.s32 	%r117, %r116, %r16;
	shr.u32 	%r118, %r117, 1;
	add.s32 	%r242, %r118, %r4;
	bra.uni 	BB0_14;

BB0_12:
	add.s32 	%r113, %r4, 1;
	mul.lo.s32 	%r114, %r113, %r4;
	shr.u32 	%r115, %r114, 1;
	add.s32 	%r242, %r16, %r115;

BB0_14:
	mul.wide.s32 	%rd44, %r242, 4;
	add.s64 	%rd45, %rd30, %rd44;
	ld.global.f32 	%f56, [%rd45];
	mul.f32 	%f57, %f56, %f45;
	fma.rn.f32 	%f10, %f7, %f57, %f4;
	fma.rn.f32 	%f11, %f8, %f57, %f5;
	fma.rn.f32 	%f12, %f9, %f57, %f6;
	and.b16  	%rs10, %rs3, 2;
	setp.eq.s16	%p11, %rs10, 0;
	add.s32 	%r20, %r2, -1;
	@%p11 bra 	BB0_16;

	rem.s32 	%r123, %r20, %r53;
	add.s32 	%r124, %r123, %r53;
	rem.s32 	%r243, %r124, %r53;
	bra.uni 	BB0_17;

BB0_16:
	mov.u32 	%r125, 0;
	max.s32 	%r243, %r20, %r125;

BB0_17:
	mad.lo.s32 	%r130, %r3, %r53, %r243;
	mad.lo.s32 	%r135, %r130, %r52, %r1;
	cvt.s64.s32	%rd46, %r135;
	mul.wide.s32 	%rd48, %r135, 4;
	add.s64 	%rd49, %rd13, %rd48;
	ld.global.f32 	%f13, [%rd49];
	add.s64 	%rd51, %rd12, %rd48;
	ld.global.f32 	%f14, [%rd51];
	add.s64 	%rd53, %rd11, %rd48;
	ld.global.f32 	%f15, [%rd53];
	add.s64 	%rd55, %rd18, %rd46;
	ld.global.u8 	%rs11, [%rd55];
	setp.gt.u16	%p12, %rs11, %rs1;
	cvt.u32.u16	%r24, %rs11;
	@%p12 bra 	BB0_19;
	bra.uni 	BB0_18;

BB0_19:
	add.s32 	%r139, %r24, 1;
	mul.lo.s32 	%r140, %r139, %r24;
	shr.u32 	%r141, %r140, 1;
	add.s32 	%r244, %r141, %r4;
	bra.uni 	BB0_20;

BB0_18:
	add.s32 	%r136, %r4, 1;
	mul.lo.s32 	%r137, %r136, %r4;
	shr.u32 	%r138, %r137, 1;
	add.s32 	%r244, %r24, %r138;

BB0_20:
	mul.wide.s32 	%rd57, %r244, 4;
	add.s64 	%rd58, %rd30, %rd57;
	ld.global.f32 	%f58, [%rd58];
	mul.f32 	%f59, %f58, %f46;
	fma.rn.f32 	%f16, %f13, %f59, %f10;
	fma.rn.f32 	%f17, %f14, %f59, %f11;
	fma.rn.f32 	%f18, %f15, %f59, %f12;
	add.s32 	%r28, %r2, 1;
	@%p11 bra 	BB0_22;

	rem.s32 	%r146, %r28, %r53;
	add.s32 	%r147, %r146, %r53;
	rem.s32 	%r245, %r147, %r53;
	bra.uni 	BB0_23;

BB0_22:
	add.s32 	%r148, %r53, -1;
	min.s32 	%r245, %r28, %r148;

BB0_23:
	mad.lo.s32 	%r153, %r3, %r53, %r245;
	mad.lo.s32 	%r158, %r153, %r52, %r1;
	cvt.s64.s32	%rd59, %r158;
	mul.wide.s32 	%rd61, %r158, 4;
	add.s64 	%rd62, %rd13, %rd61;
	ld.global.f32 	%f19, [%rd62];
	add.s64 	%rd64, %rd12, %rd61;
	ld.global.f32 	%f20, [%rd64];
	add.s64 	%rd66, %rd11, %rd61;
	ld.global.f32 	%f21, [%rd66];
	add.s64 	%rd68, %rd18, %rd59;
	ld.global.u8 	%rs14, [%rd68];
	setp.gt.u16	%p14, %rs14, %rs1;
	cvt.u32.u16	%r32, %rs14;
	@%p14 bra 	BB0_25;
	bra.uni 	BB0_24;

BB0_25:
	add.s32 	%r162, %r32, 1;
	mul.lo.s32 	%r163, %r162, %r32;
	shr.u32 	%r164, %r163, 1;
	add.s32 	%r246, %r164, %r4;
	bra.uni 	BB0_26;

BB0_24:
	add.s32 	%r159, %r4, 1;
	mul.lo.s32 	%r160, %r159, %r4;
	shr.u32 	%r161, %r160, 1;
	add.s32 	%r246, %r32, %r161;

BB0_26:
	mul.wide.s32 	%rd70, %r246, 4;
	add.s64 	%rd71, %rd30, %rd70;
	ld.global.f32 	%f60, [%rd71];
	mul.f32 	%f61, %f60, %f46;
	fma.rn.f32 	%f74, %f19, %f61, %f16;
	fma.rn.f32 	%f75, %f20, %f61, %f17;
	fma.rn.f32 	%f76, %f21, %f61, %f18;
	setp.eq.s32	%p15, %r54, 1;
	@%p15 bra 	BB0_40;

	and.b16  	%rs2, %rs3, 4;
	setp.eq.s16	%p16, %rs2, 0;
	add.s32 	%r36, %r3, -1;
	@%p16 bra 	BB0_29;

	rem.s32 	%r169, %r36, %r54;
	add.s32 	%r170, %r169, %r54;
	rem.s32 	%r247, %r170, %r54;
	bra.uni 	BB0_30;

BB0_29:
	mov.u32 	%r171, 0;
	max.s32 	%r247, %r36, %r171;

BB0_30:
	mad.lo.s32 	%r176, %r247, %r53, %r2;
	mad.lo.s32 	%r181, %r176, %r52, %r1;
	cvt.s64.s32	%rd72, %r181;
	mul.wide.s32 	%rd74, %r181, 4;
	add.s64 	%rd75, %rd13, %rd74;
	ld.global.f32 	%f25, [%rd75];
	add.s64 	%rd77, %rd12, %rd74;
	ld.global.f32 	%f26, [%rd77];
	add.s64 	%rd79, %rd11, %rd74;
	ld.global.f32 	%f27, [%rd79];
	add.s64 	%rd81, %rd18, %rd72;
	ld.global.u8 	%rs16, [%rd81];
	setp.gt.u16	%p17, %rs16, %rs1;
	cvt.u32.u16	%r40, %rs16;
	@%p17 bra 	BB0_32;
	bra.uni 	BB0_31;

BB0_32:
	add.s32 	%r185, %r40, 1;
	mul.lo.s32 	%r186, %r185, %r40;
	shr.u32 	%r187, %r186, 1;
	add.s32 	%r248, %r187, %r4;
	bra.uni 	BB0_33;

BB0_31:
	add.s32 	%r182, %r4, 1;
	mul.lo.s32 	%r183, %r182, %r4;
	shr.u32 	%r184, %r183, 1;
	add.s32 	%r248, %r40, %r184;

BB0_33:
	mul.wide.s32 	%rd83, %r248, 4;
	add.s64 	%rd84, %rd30, %rd83;
	ld.global.f32 	%f62, [%rd84];
	mul.f32 	%f63, %f62, %f47;
	fma.rn.f32 	%f28, %f25, %f63, %f74;
	fma.rn.f32 	%f29, %f26, %f63, %f75;
	fma.rn.f32 	%f30, %f27, %f63, %f76;
	add.s32 	%r44, %r3, 1;
	@%p16 bra 	BB0_35;

	rem.s32 	%r192, %r44, %r54;
	add.s32 	%r193, %r192, %r54;
	rem.s32 	%r249, %r193, %r54;
	bra.uni 	BB0_36;

BB0_35:
	add.s32 	%r194, %r54, -1;
	min.s32 	%r249, %r44, %r194;

BB0_36:
	mad.lo.s32 	%r199, %r249, %r53, %r2;
	mad.lo.s32 	%r204, %r199, %r52, %r1;
	cvt.s64.s32	%rd85, %r204;
	mul.wide.s32 	%rd87, %r204, 4;
	add.s64 	%rd88, %rd13, %rd87;
	ld.global.f32 	%f31, [%rd88];
	add.s64 	%rd90, %rd12, %rd87;
	ld.global.f32 	%f32, [%rd90];
	add.s64 	%rd92, %rd11, %rd87;
	ld.global.f32 	%f33, [%rd92];
	add.s64 	%rd94, %rd18, %rd85;
	ld.global.u8 	%rs19, [%rd94];
	setp.gt.u16	%p19, %rs19, %rs1;
	cvt.u32.u16	%r48, %rs19;
	@%p19 bra 	BB0_38;
	bra.uni 	BB0_37;

BB0_38:
	add.s32 	%r208, %r48, 1;
	mul.lo.s32 	%r209, %r208, %r48;
	shr.u32 	%r210, %r209, 1;
	add.s32 	%r250, %r210, %r4;
	bra.uni 	BB0_39;

BB0_37:
	add.s32 	%r205, %r4, 1;
	mul.lo.s32 	%r206, %r205, %r4;
	shr.u32 	%r207, %r206, 1;
	add.s32 	%r250, %r48, %r207;

BB0_39:
	mul.wide.s32 	%rd96, %r250, 4;
	add.s64 	%rd97, %rd30, %rd96;
	ld.global.f32 	%f64, [%rd97];
	mul.f32 	%f65, %f64, %f47;
	fma.rn.f32 	%f74, %f31, %f65, %f28;
	fma.rn.f32 	%f75, %f32, %f65, %f29;
	fma.rn.f32 	%f76, %f33, %f65, %f30;

BB0_40:
	setp.eq.s64	%p20, %rd8, 0;
	@%p20 bra 	BB0_42;

	cvta.to.global.u64 	%rd98, %rd8;
	add.s64 	%rd100, %rd98, %rd14;
	ld.global.f32 	%f66, [%rd100];
	mul.f32 	%f77, %f66, %f77;

BB0_42:
	setp.eq.f32	%p21, %f77, 0f00000000;
	mov.f32 	%f78, 0f00000000;
	@%p21 bra 	BB0_44;

	rcp.rn.f32 	%f78, %f77;

BB0_44:
	cvta.to.global.u64 	%rd101, %rd2;
	add.s64 	%rd103, %rd101, %rd14;
	ld.global.f32 	%f68, [%rd103];
	fma.rn.f32 	%f69, %f74, %f78, %f68;
	st.global.f32 	[%rd103], %f69;
	cvta.to.global.u64 	%rd104, %rd3;
	add.s64 	%rd105, %rd104, %rd14;
	ld.global.f32 	%f70, [%rd105];
	fma.rn.f32 	%f71, %f75, %f78, %f70;
	st.global.f32 	[%rd105], %f71;
	cvta.to.global.u64 	%rd106, %rd4;
	add.s64 	%rd107, %rd106, %rd14;
	ld.global.f32 	%f72, [%rd107];
	fma.rn.f32 	%f73, %f76, %f78, %f72;
	st.global.f32 	[%rd107], %f73;

BB0_45:
	ret;
}


`
	addexchange_ptx_30 = `
.version 5.0
.target sm_30
.address_size 64

	// .globl	addexchange

.visible .entry addexchange(
	.param .u64 addexchange_param_0,
	.param .u64 addexchange_param_1,
	.param .u64 addexchange_param_2,
	.param .u64 addexchange_param_3,
	.param .u64 addexchange_param_4,
	.param .u64 addexchange_param_5,
	.param .u64 addexchange_param_6,
	.param .f32 addexchange_param_7,
	.param .u64 addexchange_param_8,
	.param .u64 addexchange_param_9,
	.param .f32 addexchange_param_10,
	.param .f32 addexchange_param_11,
	.param .f32 addexchange_param_12,
	.param .u32 addexchange_param_13,
	.param .u32 addexchange_param_14,
	.param .u32 addexchange_param_15,
	.param .u8 addexchange_param_16
)
{
	.reg .pred 	%p<22>;
	.reg .b16 	%rs<21>;
	.reg .f32 	%f<79>;
	.reg .b32 	%r<251>;
	.reg .b64 	%rd<108>;


	ld.param.u64 	%rd2, [addexchange_param_0];
	ld.param.u64 	%rd3, [addexchange_param_1];
	ld.param.u64 	%rd4, [addexchange_param_2];
	ld.param.u64 	%rd5, [addexchange_param_3];
	ld.param.u64 	%rd6, [addexchange_param_4];
	ld.param.u64 	%rd7, [addexchange_param_5];
	ld.param.u64 	%rd8, [addexchange_param_6];
	ld.param.f32 	%f77, [addexchange_param_7];
	ld.param.u64 	%rd9, [addexchange_param_8];
	ld.param.u64 	%rd10, [addexchange_param_9];
	ld.param.f32 	%f45, [addexchange_param_10];
	ld.param.f32 	%f46, [addexchange_param_11];
	ld.param.f32 	%f47, [addexchange_param_12];
	ld.param.u32 	%r52, [addexchange_param_13];
	ld.param.u32 	%r53, [addexchange_param_14];
	ld.param.u32 	%r54, [addexchange_param_15];
	ld.param.u8 	%rs3, [addexchange_param_16];
	mov.u32 	%r55, %ntid.x;
	mov.u32 	%r56, %ctaid.x;
	mov.u32 	%r57, %tid.x;
	mad.lo.s32 	%r1, %r55, %r56, %r57;
	mov.u32 	%r58, %ntid.y;
	mov.u32 	%r59, %ctaid.y;
	mov.u32 	%r60, %tid.y;
	mad.lo.s32 	%r2, %r58, %r59, %r60;
	mov.u32 	%r61, %ntid.z;
	mov.u32 	%r62, %ctaid.z;
	mov.u32 	%r63, %tid.z;
	mad.lo.s32 	%r3, %r61, %r62, %r63;
	setp.ge.s32	%p1, %r1, %r52;
	setp.ge.s32	%p2, %r2, %r53;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r54;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_45;

	cvta.to.global.u64 	%rd11, %rd7;
	cvta.to.global.u64 	%rd12, %rd6;
	cvta.to.global.u64 	%rd13, %rd5;
	mad.lo.s32 	%r64, %r3, %r53, %r2;
	mad.lo.s32 	%r65, %r64, %r52, %r1;
	cvt.s64.s32	%rd1, %r65;
	mul.wide.s32 	%rd14, %r65, 4;
	add.s64 	%rd15, %rd13, %rd14;
	add.s64 	%rd16, %rd12, %rd14;
	add.s64 	%rd17, %rd11, %rd14;
	ld.global.f32 	%f48, [%rd15];
	ld.global.f32 	%f49, [%rd16];
	mul.f32 	%f50, %f49, %f49;
	fma.rn.f32 	%f51, %f48, %f48, %f50;
	ld.global.f32 	%f52, [%rd17];
	fma.rn.f32 	%f53, %f52, %f52, %f51;
	setp.eq.f32	%p6, %f53, 0f00000000;
	@%p6 bra 	BB0_45;

	cvta.to.global.u64 	%rd18, %rd10;
	add.s64 	%rd19, %rd18, %rd1;
	ld.global.u8 	%rs1, [%rd19];
	cvt.u32.u16	%r66, %rs1;
	and.b32  	%r4, %r66, 255;
	and.b16  	%rs4, %rs3, 1;
	setp.eq.b16	%p7, %rs4, 1;
	@!%p7 bra 	BB0_4;
	bra.uni 	BB0_3;

BB0_3:
	add.s32 	%r71, %r1, -1;
	rem.s32 	%r72, %r71, %r52;
	add.s32 	%r73, %r72, %r52;
	rem.s32 	%r239, %r73, %r52;
	bra.uni 	BB0_5;

BB0_4:
	add.s32 	%r78, %r1, -1;
	mov.u32 	%r79, 0;
	max.s32 	%r239, %r78, %r79;

BB0_5:
	mad.lo.s32 	%r89, %r64, %r52, %r239;
	cvt.s64.s32	%rd20, %r89;
	mul.wide.s32 	%rd22, %r89, 4;
	add.s64 	%rd23, %rd13, %rd22;
	ld.global.f32 	%f1, [%rd23];
	add.s64 	%rd25, %rd12, %rd22;
	ld.global.f32 	%f2, [%rd25];
	add.s64 	%rd27, %rd11, %rd22;
	ld.global.f32 	%f3, [%rd27];
	add.s64 	%rd29, %rd18, %rd20;
	ld.global.u8 	%rs5, [%rd29];
	setp.gt.u16	%p8, %rs5, %rs1;
	cvt.u32.u16	%r8, %rs5;
	@%p8 bra 	BB0_7;
	bra.uni 	BB0_6;

BB0_7:
	add.s32 	%r93, %r8, 1;
	mul.lo.s32 	%r94, %r93, %r8;
	shr.u32 	%r95, %r94, 1;
	add.s32 	%r240, %r95, %r4;
	bra.uni 	BB0_8;

BB0_6:
	add.s32 	%r90, %r4, 1;
	mul.lo.s32 	%r91, %r90, %r4;
	shr.u32 	%r92, %r91, 1;
	add.s32 	%r240, %r8, %r92;

BB0_8:
	setp.eq.b16	%p9, %rs4, 1;
	cvta.to.global.u64 	%rd30, %rd9;
	mul.wide.s32 	%rd31, %r240, 4;
	add.s64 	%rd32, %rd30, %rd31;
	ld.global.f32 	%f54, [%rd32];
	mul.f32 	%f55, %f54, %f45;
	fma.rn.f32 	%f4, %f1, %f55, 0f00000000;
	fma.rn.f32 	%f5, %f2, %f55, 0f00000000;
	fma.rn.f32 	%f6, %f3, %f55, 0f00000000;
	add.s32 	%r12, %r1, 1;
	@!%p9 bra 	BB0_10;
	bra.uni 	BB0_9;

BB0_9:
	rem.s32 	%r100, %r12, %r52;
	add.s32 	%r101, %r100, %r52;
	rem.s32 	%r241, %r101, %r52;
	bra.uni 	BB0_11;

BB0_10:
	add.s32 	%r102, %r52, -1;
	min.s32 	%r241, %r12, %r102;

BB0_11:
	mad.lo.s32 	%r112, %r64, %r52, %r241;
	cvt.s64.s32	%rd33, %r112;
	mul.wide.s32 	%rd35, %r112, 4;
	add.s64 	%rd36, %rd13, %rd35;
	ld.global.f32 	%f7, [%rd36];
	add.s64 	%rd38, %rd12, %rd35;
	ld.global.f32 	%f8, [%rd38];
	add.s64 	%rd40, %rd11, %rd35;
	ld.global.f32 	%f9, [%rd40];
	add.s64 	%rd42, %rd18, %rd33;
	ld.global.u8 	%rs8, [%rd42];
	setp.gt.u16	%p10, %rs8, %rs1;
	cvt.u32.u16	%r16, %rs8;
	@%p10 bra 	BB0_13;
	bra.uni 	BB0_12;

BB0_13:
	add.s32 	%r116, %r16, 1;
	mul.lo.s32 	%r117, %r116, %r16;
	shr.u32 	%r118, %r117, 1;
	add.s32 	%r242, %r118, %r4;
	bra.uni 	BB0_14;

BB0_12:
	add.s32 	%r113, %r4, 1;
	mul.lo.s32 	%r114, %r113, %r4;
	shr.u32 	%r115, %r114, 1;
	add.s32 	%r242, %r16, %r115;

BB0_14:
	mul.wide.s32 	%rd44, %r242, 4;
	add.s64 	%rd45, %rd30, %rd44;
	ld.global.f32 	%f56, [%rd45];
	mul.f32 	%f57, %f56, %f45;
	fma.rn.f32 	%f10, %f7, %f57, %f4;
	fma.rn.f32 	%f11, %f8, %f57, %f5;
	fma.rn.f32 	%f12, %f9, %f57, %f6;
	and.b16  	%rs10, %rs3, 2;
	setp.eq.s16	%p11, %rs10, 0;
	add.s32 	%r20, %r2, -1;
	@%p11 bra 	BB0_16;

	rem.s32 	%r123, %r20, %r53;
	add.s32 	%r124, %r123, %r53;
	rem.s32 	%r243, %r124, %r53;
	bra.uni 	BB0_17;

BB0_16:
	mov.u32 	%r125, 0;
	max.s32 	%r243, %r20, %r125;

BB0_17:
	mad.lo.s32 	%r130, %r3, %r53, %r243;
	mad.lo.s32 	%r135, %r130, %r52, %r1;
	cvt.s64.s32	%rd46, %r135;
	mul.wide.s32 	%rd48, %r135, 4;
	add.s64 	%rd49, %rd13, %rd48;
	ld.global.f32 	%f13, [%rd49];
	add.s64 	%rd51, %rd12, %rd48;
	ld.global.f32 	%f14, [%rd51];
	add.s64 	%rd53, %rd11, %rd48;
	ld.global.f32 	%f15, [%rd53];
	add.s64 	%rd55, %rd18, %rd46;
	ld.global.u8 	%rs11, [%rd55];
	setp.gt.u16	%p12, %rs11, %rs1;
	cvt.u32.u16	%r24, %rs11;
	@%p12 bra 	BB0_19;
	bra.uni 	BB0_18;

BB0_19:
	add.s32 	%r139, %r24, 1;
	mul.lo.s32 	%r140, %r139, %r24;
	shr.u32 	%r141, %r140, 1;
	add.s32 	%r244, %r141, %r4;
	bra.uni 	BB0_20;

BB0_18:
	add.s32 	%r136, %r4, 1;
	mul.lo.s32 	%r137, %r136, %r4;
	shr.u32 	%r138, %r137, 1;
	add.s32 	%r244, %r24, %r138;

BB0_20:
	mul.wide.s32 	%rd57, %r244, 4;
	add.s64 	%rd58, %rd30, %rd57;
	ld.global.f32 	%f58, [%rd58];
	mul.f32 	%f59, %f58, %f46;
	fma.rn.f32 	%f16, %f13, %f59, %f10;
	fma.rn.f32 	%f17, %f14, %f59, %f11;
	fma.rn.f32 	%f18, %f15, %f59, %f12;
	add.s32 	%r28, %r2, 1;
	@%p11 bra 	BB0_22;

	rem.s32 	%r146, %r28, %r53;
	add.s32 	%r147, %r146, %r53;
	rem.s32 	%r245, %r147, %r53;
	bra.uni 	BB0_23;

BB0_22:
	add.s32 	%r148, %r53, -1;
	min.s32 	%r245, %r28, %r148;

BB0_23:
	mad.lo.s32 	%r153, %r3, %r53, %r245;
	mad.lo.s32 	%r158, %r153, %r52, %r1;
	cvt.s64.s32	%rd59, %r158;
	mul.wide.s32 	%rd61, %r158, 4;
	add.s64 	%rd62, %rd13, %rd61;
	ld.global.f32 	%f19, [%rd62];
	add.s64 	%rd64, %rd12, %rd61;
	ld.global.f32 	%f20, [%rd64];
	add.s64 	%rd66, %rd11, %rd61;
	ld.global.f32 	%f21, [%rd66];
	add.s64 	%rd68, %rd18, %rd59;
	ld.global.u8 	%rs14, [%rd68];
	setp.gt.u16	%p14, %rs14, %rs1;
	cvt.u32.u16	%r32, %rs14;
	@%p14 bra 	BB0_25;
	bra.uni 	BB0_24;

BB0_25:
	add.s32 	%r162, %r32, 1;
	mul.lo.s32 	%r163, %r162, %r32;
	shr.u32 	%r164, %r163, 1;
	add.s32 	%r246, %r164, %r4;
	bra.uni 	BB0_26;

BB0_24:
	add.s32 	%r159, %r4, 1;
	mul.lo.s32 	%r160, %r159, %r4;
	shr.u32 	%r161, %r160, 1;
	add.s32 	%r246, %r32, %r161;

BB0_26:
	mul.wide.s32 	%rd70, %r246, 4;
	add.s64 	%rd71, %rd30, %rd70;
	ld.global.f32 	%f60, [%rd71];
	mul.f32 	%f61, %f60, %f46;
	fma.rn.f32 	%f74, %f19, %f61, %f16;
	fma.rn.f32 	%f75, %f20, %f61, %f17;
	fma.rn.f32 	%f76, %f21, %f61, %f18;
	setp.eq.s32	%p15, %r54, 1;
	@%p15 bra 	BB0_40;

	and.b16  	%rs2, %rs3, 4;
	setp.eq.s16	%p16, %rs2, 0;
	add.s32 	%r36, %r3, -1;
	@%p16 bra 	BB0_29;

	rem.s32 	%r169, %r36, %r54;
	add.s32 	%r170, %r169, %r54;
	rem.s32 	%r247, %r170, %r54;
	bra.uni 	BB0_30;

BB0_29:
	mov.u32 	%r171, 0;
	max.s32 	%r247, %r36, %r171;

BB0_30:
	mad.lo.s32 	%r176, %r247, %r53, %r2;
	mad.lo.s32 	%r181, %r176, %r52, %r1;
	cvt.s64.s32	%rd72, %r181;
	mul.wide.s32 	%rd74, %r181, 4;
	add.s64 	%rd75, %rd13, %rd74;
	ld.global.f32 	%f25, [%rd75];
	add.s64 	%rd77, %rd12, %rd74;
	ld.global.f32 	%f26, [%rd77];
	add.s64 	%rd79, %rd11, %rd74;
	ld.global.f32 	%f27, [%rd79];
	add.s64 	%rd81, %rd18, %rd72;
	ld.global.u8 	%rs16, [%rd81];
	setp.gt.u16	%p17, %rs16, %rs1;
	cvt.u32.u16	%r40, %rs16;
	@%p17 bra 	BB0_32;
	bra.uni 	BB0_31;

BB0_32:
	add.s32 	%r185, %r40, 1;
	mul.lo.s32 	%r186, %r185, %r40;
	shr.u32 	%r187, %r186, 1;
	add.s32 	%r248, %r187, %r4;
	bra.uni 	BB0_33;

BB0_31:
	add.s32 	%r182, %r4, 1;
	mul.lo.s32 	%r183, %r182, %r4;
	shr.u32 	%r184, %r183, 1;
	add.s32 	%r248, %r40, %r184;

BB0_33:
	mul.wide.s32 	%rd83, %r248, 4;
	add.s64 	%rd84, %rd30, %rd83;
	ld.global.f32 	%f62, [%rd84];
	mul.f32 	%f63, %f62, %f47;
	fma.rn.f32 	%f28, %f25, %f63, %f74;
	fma.rn.f32 	%f29, %f26, %f63, %f75;
	fma.rn.f32 	%f30, %f27, %f63, %f76;
	add.s32 	%r44, %r3, 1;
	@%p16 bra 	BB0_35;

	rem.s32 	%r192, %r44, %r54;
	add.s32 	%r193, %r192, %r54;
	rem.s32 	%r249, %r193, %r54;
	bra.uni 	BB0_36;

BB0_35:
	add.s32 	%r194, %r54, -1;
	min.s32 	%r249, %r44, %r194;

BB0_36:
	mad.lo.s32 	%r199, %r249, %r53, %r2;
	mad.lo.s32 	%r204, %r199, %r52, %r1;
	cvt.s64.s32	%rd85, %r204;
	mul.wide.s32 	%rd87, %r204, 4;
	add.s64 	%rd88, %rd13, %rd87;
	ld.global.f32 	%f31, [%rd88];
	add.s64 	%rd90, %rd12, %rd87;
	ld.global.f32 	%f32, [%rd90];
	add.s64 	%rd92, %rd11, %rd87;
	ld.global.f32 	%f33, [%rd92];
	add.s64 	%rd94, %rd18, %rd85;
	ld.global.u8 	%rs19, [%rd94];
	setp.gt.u16	%p19, %rs19, %rs1;
	cvt.u32.u16	%r48, %rs19;
	@%p19 bra 	BB0_38;
	bra.uni 	BB0_37;

BB0_38:
	add.s32 	%r208, %r48, 1;
	mul.lo.s32 	%r209, %r208, %r48;
	shr.u32 	%r210, %r209, 1;
	add.s32 	%r250, %r210, %r4;
	bra.uni 	BB0_39;

BB0_37:
	add.s32 	%r205, %r4, 1;
	mul.lo.s32 	%r206, %r205, %r4;
	shr.u32 	%r207, %r206, 1;
	add.s32 	%r250, %r48, %r207;

BB0_39:
	mul.wide.s32 	%rd96, %r250, 4;
	add.s64 	%rd97, %rd30, %rd96;
	ld.global.f32 	%f64, [%rd97];
	mul.f32 	%f65, %f64, %f47;
	fma.rn.f32 	%f74, %f31, %f65, %f28;
	fma.rn.f32 	%f75, %f32, %f65, %f29;
	fma.rn.f32 	%f76, %f33, %f65, %f30;

BB0_40:
	setp.eq.s64	%p20, %rd8, 0;
	@%p20 bra 	BB0_42;

	cvta.to.global.u64 	%rd98, %rd8;
	add.s64 	%rd100, %rd98, %rd14;
	ld.global.f32 	%f66, [%rd100];
	mul.f32 	%f77, %f66, %f77;

BB0_42:
	setp.eq.f32	%p21, %f77, 0f00000000;
	mov.f32 	%f78, 0f00000000;
	@%p21 bra 	BB0_44;

	rcp.rn.f32 	%f78, %f77;

BB0_44:
	cvta.to.global.u64 	%rd101, %rd2;
	add.s64 	%rd103, %rd101, %rd14;
	ld.global.f32 	%f68, [%rd103];
	fma.rn.f32 	%f69, %f74, %f78, %f68;
	st.global.f32 	[%rd103], %f69;
	cvta.to.global.u64 	%rd104, %rd3;
	add.s64 	%rd105, %rd104, %rd14;
	ld.global.f32 	%f70, [%rd105];
	fma.rn.f32 	%f71, %f75, %f78, %f70;
	st.global.f32 	[%rd105], %f71;
	cvta.to.global.u64 	%rd106, %rd4;
	add.s64 	%rd107, %rd106, %rd14;
	ld.global.f32 	%f72, [%rd107];
	fma.rn.f32 	%f73, %f76, %f78, %f72;
	st.global.f32 	[%rd107], %f73;

BB0_45:
	ret;
}


`
	addexchange_ptx_35 = `
.version 5.0
.target sm_35
.address_size 64

	// .globl	addexchange

.visible .entry addexchange(
	.param .u64 addexchange_param_0,
	.param .u64 addexchange_param_1,
	.param .u64 addexchange_param_2,
	.param .u64 addexchange_param_3,
	.param .u64 addexchange_param_4,
	.param .u64 addexchange_param_5,
	.param .u64 addexchange_param_6,
	.param .f32 addexchange_param_7,
	.param .u64 addexchange_param_8,
	.param .u64 addexchange_param_9,
	.param .f32 addexchange_param_10,
	.param .f32 addexchange_param_11,
	.param .f32 addexchange_param_12,
	.param .u32 addexchange_param_13,
	.param .u32 addexchange_param_14,
	.param .u32 addexchange_param_15,
	.param .u8 addexchange_param_16
)
{
	.reg .pred 	%p<22>;
	.reg .b16 	%rs<26>;
	.reg .f32 	%f<79>;
	.reg .b32 	%r<152>;
	.reg .b64 	%rd<79>;


	ld.param.u64 	%rd7, [addexchange_param_0];
	ld.param.u64 	%rd8, [addexchange_param_1];
	ld.param.u64 	%rd9, [addexchange_param_2];
	ld.param.u64 	%rd11, [addexchange_param_3];
	ld.param.u64 	%rd12, [addexchange_param_4];
	ld.param.u64 	%rd13, [addexchange_param_5];
	ld.param.u64 	%rd10, [addexchange_param_6];
	ld.param.f32 	%f77, [addexchange_param_7];
	ld.param.u64 	%rd14, [addexchange_param_8];
	ld.param.u64 	%rd15, [addexchange_param_9];
	ld.param.f32 	%f45, [addexchange_param_10];
	ld.param.f32 	%f46, [addexchange_param_11];
	ld.param.f32 	%f47, [addexchange_param_12];
	ld.param.u32 	%r55, [addexchange_param_13];
	ld.param.u32 	%r56, [addexchange_param_14];
	ld.param.u32 	%r57, [addexchange_param_15];
	ld.param.u8 	%rs5, [addexchange_param_16];
	cvta.to.global.u64 	%rd1, %rd14;
	cvta.to.global.u64 	%rd2, %rd15;
	cvta.to.global.u64 	%rd3, %rd13;
	cvta.to.global.u64 	%rd4, %rd12;
	cvta.to.global.u64 	%rd5, %rd11;
	mov.u32 	%r58, %ntid.x;
	mov.u32 	%r59, %ctaid.x;
	mov.u32 	%r60, %tid.x;
	mad.lo.s32 	%r1, %r58, %r59, %r60;
	mov.u32 	%r61, %ntid.y;
	mov.u32 	%r62, %ctaid.y;
	mov.u32 	%r63, %tid.y;
	mad.lo.s32 	%r2, %r61, %r62, %r63;
	mov.u32 	%r64, %ntid.z;
	mov.u32 	%r65, %ctaid.z;
	mov.u32 	%r66, %tid.z;
	mad.lo.s32 	%r3, %r64, %r65, %r66;
	setp.ge.s32	%p1, %r1, %r55;
	setp.ge.s32	%p2, %r2, %r56;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r57;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_45;

	mul.lo.s32 	%r4, %r3, %r56;
	add.s32 	%r67, %r4, %r2;
	mul.lo.s32 	%r5, %r67, %r55;
	add.s32 	%r68, %r5, %r1;
	cvt.s64.s32	%rd6, %r68;
	mul.wide.s32 	%rd16, %r68, 4;
	add.s64 	%rd17, %rd5, %rd16;
	add.s64 	%rd18, %rd4, %rd16;
	add.s64 	%rd19, %rd3, %rd16;
	ld.global.nc.f32 	%f48, [%rd17];
	ld.global.nc.f32 	%f49, [%rd18];
	mul.f32 	%f50, %f49, %f49;
	fma.rn.f32 	%f51, %f48, %f48, %f50;
	ld.global.nc.f32 	%f52, [%rd19];
	fma.rn.f32 	%f53, %f52, %f52, %f51;
	setp.eq.f32	%p6, %f53, 0f00000000;
	@%p6 bra 	BB0_45;

	add.s64 	%rd20, %rd2, %rd6;
	ld.global.nc.u8 	%rs1, [%rd20];
	cvt.u32.u16	%r69, %rs1;
	and.b32  	%r6, %r69, 255;
	and.b16  	%rs2, %rs5, 1;
	setp.eq.s16	%p7, %rs2, 0;
	add.s32 	%r7, %r1, -1;
	@%p7 bra 	BB0_4;

	rem.s32 	%r70, %r7, %r55;
	add.s32 	%r71, %r70, %r55;
	rem.s32 	%r140, %r71, %r55;
	bra.uni 	BB0_5;

BB0_4:
	mov.u32 	%r72, 0;
	max.s32 	%r140, %r7, %r72;

BB0_5:
	add.s32 	%r73, %r140, %r5;
	cvt.s64.s32	%rd21, %r73;
	mul.wide.s32 	%rd22, %r73, 4;
	add.s64 	%rd23, %rd5, %rd22;
	ld.global.nc.f32 	%f1, [%rd23];
	add.s64 	%rd24, %rd4, %rd22;
	ld.global.nc.f32 	%f2, [%rd24];
	add.s64 	%rd25, %rd3, %rd22;
	ld.global.nc.f32 	%f3, [%rd25];
	add.s64 	%rd26, %rd2, %rd21;
	ld.global.nc.u8 	%rs6, [%rd26];
	setp.gt.u16	%p8, %rs6, %rs1;
	cvt.u32.u16	%r74, %rs6;
	and.b32  	%r11, %r74, 255;
	@%p8 bra 	BB0_7;
	bra.uni 	BB0_6;

BB0_7:
	add.s32 	%r78, %r11, 1;
	mul.lo.s32 	%r79, %r78, %r11;
	shr.u32 	%r80, %r79, 1;
	add.s32 	%r141, %r80, %r6;
	bra.uni 	BB0_8;

BB0_6:
	add.s32 	%r75, %r6, 1;
	mul.lo.s32 	%r76, %r75, %r6;
	shr.u32 	%r77, %r76, 1;
	add.s32 	%r141, %r11, %r77;

BB0_8:
	mul.wide.s32 	%rd27, %r141, 4;
	add.s64 	%rd28, %rd1, %rd27;
	ld.global.nc.f32 	%f54, [%rd28];
	mul.f32 	%f55, %f54, %f45;
	fma.rn.f32 	%f4, %f1, %f55, 0f00000000;
	fma.rn.f32 	%f5, %f2, %f55, 0f00000000;
	fma.rn.f32 	%f6, %f3, %f55, 0f00000000;
	add.s32 	%r15, %r1, 1;
	@%p7 bra 	BB0_10;

	rem.s32 	%r81, %r15, %r55;
	add.s32 	%r82, %r81, %r55;
	rem.s32 	%r142, %r82, %r55;
	bra.uni 	BB0_11;

BB0_10:
	add.s32 	%r83, %r55, -1;
	min.s32 	%r142, %r15, %r83;

BB0_11:
	add.s32 	%r84, %r142, %r5;
	cvt.s64.s32	%rd29, %r84;
	mul.wide.s32 	%rd30, %r84, 4;
	add.s64 	%rd31, %rd5, %rd30;
	ld.global.nc.f32 	%f7, [%rd31];
	add.s64 	%rd32, %rd4, %rd30;
	ld.global.nc.f32 	%f8, [%rd32];
	add.s64 	%rd33, %rd3, %rd30;
	ld.global.nc.f32 	%f9, [%rd33];
	add.s64 	%rd34, %rd2, %rd29;
	ld.global.nc.u8 	%rs9, [%rd34];
	setp.gt.u16	%p10, %rs9, %rs1;
	cvt.u32.u16	%r85, %rs9;
	and.b32  	%r19, %r85, 255;
	@%p10 bra 	BB0_13;
	bra.uni 	BB0_12;

BB0_13:
	add.s32 	%r89, %r19, 1;
	mul.lo.s32 	%r90, %r89, %r19;
	shr.u32 	%r91, %r90, 1;
	add.s32 	%r143, %r91, %r6;
	bra.uni 	BB0_14;

BB0_12:
	add.s32 	%r86, %r6, 1;
	mul.lo.s32 	%r87, %r86, %r6;
	shr.u32 	%r88, %r87, 1;
	add.s32 	%r143, %r19, %r88;

BB0_14:
	mul.wide.s32 	%rd35, %r143, 4;
	add.s64 	%rd36, %rd1, %rd35;
	ld.global.nc.f32 	%f56, [%rd36];
	mul.f32 	%f57, %f56, %f45;
	fma.rn.f32 	%f10, %f7, %f57, %f4;
	fma.rn.f32 	%f11, %f8, %f57, %f5;
	fma.rn.f32 	%f12, %f9, %f57, %f6;
	and.b16  	%rs3, %rs5, 2;
	setp.eq.s16	%p11, %rs3, 0;
	add.s32 	%r23, %r2, -1;
	@%p11 bra 	BB0_16;

	rem.s32 	%r92, %r23, %r56;
	add.s32 	%r93, %r92, %r56;
	rem.s32 	%r144, %r93, %r56;
	bra.uni 	BB0_17;

BB0_16:
	mov.u32 	%r94, 0;
	max.s32 	%r144, %r23, %r94;

BB0_17:
	add.s32 	%r95, %r144, %r4;
	mad.lo.s32 	%r96, %r95, %r55, %r1;
	cvt.s64.s32	%rd37, %r96;
	mul.wide.s32 	%rd38, %r96, 4;
	add.s64 	%rd39, %rd5, %rd38;
	ld.global.nc.f32 	%f13, [%rd39];
	add.s64 	%rd40, %rd4, %rd38;
	ld.global.nc.f32 	%f14, [%rd40];
	add.s64 	%rd41, %rd3, %rd38;
	ld.global.nc.f32 	%f15, [%rd41];
	add.s64 	%rd42, %rd2, %rd37;
	ld.global.nc.u8 	%rs12, [%rd42];
	setp.gt.u16	%p12, %rs12, %rs1;
	cvt.u32.u16	%r97, %rs12;
	and.b32  	%r27, %r97, 255;
	@%p12 bra 	BB0_19;
	bra.uni 	BB0_18;

BB0_19:
	add.s32 	%r101, %r27, 1;
	mul.lo.s32 	%r102, %r101, %r27;
	shr.u32 	%r103, %r102, 1;
	add.s32 	%r145, %r103, %r6;
	bra.uni 	BB0_20;

BB0_18:
	add.s32 	%r98, %r6, 1;
	mul.lo.s32 	%r99, %r98, %r6;
	shr.u32 	%r100, %r99, 1;
	add.s32 	%r145, %r27, %r100;

BB0_20:
	mul.wide.s32 	%rd43, %r145, 4;
	add.s64 	%rd44, %rd1, %rd43;
	ld.global.nc.f32 	%f58, [%rd44];
	mul.f32 	%f59, %f58, %f46;
	fma.rn.f32 	%f16, %f13, %f59, %f10;
	fma.rn.f32 	%f17, %f14, %f59, %f11;
	fma.rn.f32 	%f18, %f15, %f59, %f12;
	add.s32 	%r31, %r2, 1;
	@%p11 bra 	BB0_22;

	rem.s32 	%r104, %r31, %r56;
	add.s32 	%r105, %r104, %r56;
	rem.s32 	%r146, %r105, %r56;
	bra.uni 	BB0_23;

BB0_22:
	add.s32 	%r106, %r56, -1;
	min.s32 	%r146, %r31, %r106;

BB0_23:
	add.s32 	%r107, %r146, %r4;
	mad.lo.s32 	%r108, %r107, %r55, %r1;
	cvt.s64.s32	%rd45, %r108;
	mul.wide.s32 	%rd46, %r108, 4;
	add.s64 	%rd47, %rd5, %rd46;
	ld.global.nc.f32 	%f19, [%rd47];
	add.s64 	%rd48, %rd4, %rd46;
	ld.global.nc.f32 	%f20, [%rd48];
	add.s64 	%rd49, %rd3, %rd46;
	ld.global.nc.f32 	%f21, [%rd49];
	add.s64 	%rd50, %rd2, %rd45;
	ld.global.nc.u8 	%rs16, [%rd50];
	setp.gt.u16	%p14, %rs16, %rs1;
	cvt.u32.u16	%r109, %rs16;
	and.b32  	%r35, %r109, 255;
	@%p14 bra 	BB0_25;
	bra.uni 	BB0_24;

BB0_25:
	add.s32 	%r113, %r35, 1;
	mul.lo.s32 	%r114, %r113, %r35;
	shr.u32 	%r115, %r114, 1;
	add.s32 	%r147, %r115, %r6;
	bra.uni 	BB0_26;

BB0_24:
	add.s32 	%r110, %r6, 1;
	mul.lo.s32 	%r111, %r110, %r6;
	shr.u32 	%r112, %r111, 1;
	add.s32 	%r147, %r35, %r112;

BB0_26:
	mul.wide.s32 	%rd51, %r147, 4;
	add.s64 	%rd52, %rd1, %rd51;
	ld.global.nc.f32 	%f60, [%rd52];
	mul.f32 	%f61, %f60, %f46;
	fma.rn.f32 	%f74, %f19, %f61, %f16;
	fma.rn.f32 	%f75, %f20, %f61, %f17;
	fma.rn.f32 	%f76, %f21, %f61, %f18;
	setp.eq.s32	%p15, %r57, 1;
	@%p15 bra 	BB0_40;

	and.b16  	%rs4, %rs5, 4;
	setp.eq.s16	%p16, %rs4, 0;
	add.s32 	%r39, %r3, -1;
	@%p16 bra 	BB0_29;

	rem.s32 	%r116, %r39, %r57;
	add.s32 	%r117, %r116, %r57;
	rem.s32 	%r148, %r117, %r57;
	bra.uni 	BB0_30;

BB0_29:
	mov.u32 	%r118, 0;
	max.s32 	%r148, %r39, %r118;

BB0_30:
	mad.lo.s32 	%r119, %r148, %r56, %r2;
	mad.lo.s32 	%r120, %r119, %r55, %r1;
	cvt.s64.s32	%rd53, %r120;
	mul.wide.s32 	%rd54, %r120, 4;
	add.s64 	%rd55, %rd5, %rd54;
	ld.global.nc.f32 	%f25, [%rd55];
	add.s64 	%rd56, %rd4, %rd54;
	ld.global.nc.f32 	%f26, [%rd56];
	add.s64 	%rd57, %rd3, %rd54;
	ld.global.nc.f32 	%f27, [%rd57];
	add.s64 	%rd58, %rd2, %rd53;
	ld.global.nc.u8 	%rs19, [%rd58];
	setp.gt.u16	%p17, %rs19, %rs1;
	cvt.u32.u16	%r121, %rs19;
	and.b32  	%r43, %r121, 255;
	@%p17 bra 	BB0_32;
	bra.uni 	BB0_31;

BB0_32:
	add.s32 	%r125, %r43, 1;
	mul.lo.s32 	%r126, %r125, %r43;
	shr.u32 	%r127, %r126, 1;
	add.s32 	%r149, %r127, %r6;
	bra.uni 	BB0_33;

BB0_31:
	add.s32 	%r122, %r6, 1;
	mul.lo.s32 	%r123, %r122, %r6;
	shr.u32 	%r124, %r123, 1;
	add.s32 	%r149, %r43, %r124;

BB0_33:
	mul.wide.s32 	%rd59, %r149, 4;
	add.s64 	%rd60, %rd1, %rd59;
	ld.global.nc.f32 	%f62, [%rd60];
	mul.f32 	%f63, %f62, %f47;
	fma.rn.f32 	%f28, %f25, %f63, %f74;
	fma.rn.f32 	%f29, %f26, %f63, %f75;
	fma.rn.f32 	%f30, %f27, %f63, %f76;
	add.s32 	%r47, %r3, 1;
	@%p16 bra 	BB0_35;

	rem.s32 	%r128, %r47, %r57;
	add.s32 	%r129, %r128, %r57;
	rem.s32 	%r150, %r129, %r57;
	bra.uni 	BB0_36;

BB0_35:
	add.s32 	%r130, %r57, -1;
	min.s32 	%r150, %r47, %r130;

BB0_36:
	mad.lo.s32 	%r131, %r150, %r56, %r2;
	mad.lo.s32 	%r132, %r131, %r55, %r1;
	cvt.s64.s32	%rd61, %r132;
	mul.wide.s32 	%rd62, %r132, 4;
	add.s64 	%rd63, %rd5, %rd62;
	ld.global.nc.f32 	%f31, [%rd63];
	add.s64 	%rd64, %rd4, %rd62;
	ld.global.nc.f32 	%f32, [%rd64];
	add.s64 	%rd65, %rd3, %rd62;
	ld.global.nc.f32 	%f33, [%rd65];
	add.s64 	%rd66, %rd2, %rd61;
	ld.global.nc.u8 	%rs23, [%rd66];
	setp.gt.u16	%p19, %rs23, %rs1;
	cvt.u32.u16	%r133, %rs23;
	and.b32  	%r51, %r133, 255;
	@%p19 bra 	BB0_38;
	bra.uni 	BB0_37;

BB0_38:
	add.s32 	%r137, %r51, 1;
	mul.lo.s32 	%r138, %r137, %r51;
	shr.u32 	%r139, %r138, 1;
	add.s32 	%r151, %r139, %r6;
	bra.uni 	BB0_39;

BB0_37:
	add.s32 	%r134, %r6, 1;
	mul.lo.s32 	%r135, %r134, %r6;
	shr.u32 	%r136, %r135, 1;
	add.s32 	%r151, %r51, %r136;

BB0_39:
	mul.wide.s32 	%rd67, %r151, 4;
	add.s64 	%rd68, %rd1, %rd67;
	ld.global.nc.f32 	%f64, [%rd68];
	mul.f32 	%f65, %f64, %f47;
	fma.rn.f32 	%f74, %f31, %f65, %f28;
	fma.rn.f32 	%f75, %f32, %f65, %f29;
	fma.rn.f32 	%f76, %f33, %f65, %f30;

BB0_40:
	setp.eq.s64	%p20, %rd10, 0;
	@%p20 bra 	BB0_42;

	cvta.to.global.u64 	%rd69, %rd10;
	shl.b64 	%rd70, %rd6, 2;
	add.s64 	%rd71, %rd69, %rd70;
	ld.global.nc.f32 	%f66, [%rd71];
	mul.f32 	%f77, %f66, %f77;

BB0_42:
	setp.eq.f32	%p21, %f77, 0f00000000;
	mov.f32 	%f78, 0f00000000;
	@%p21 bra 	BB0_44;

	rcp.rn.f32 	%f78, %f77;

BB0_44:
	cvta.to.global.u64 	%rd72, %rd9;
	cvta.to.global.u64 	%rd73, %rd8;
	cvta.to.global.u64 	%rd74, %rd7;
	shl.b64 	%rd75, %rd6, 2;
	add.s64 	%rd76, %rd74, %rd75;
	ld.global.f32 	%f68, [%rd76];
	fma.rn.f32 	%f69, %f74, %f78, %f68;
	st.global.f32 	[%rd76], %f69;
	add.s64 	%rd77, %rd73, %rd75;
	ld.global.f32 	%f70, [%rd77];
	fma.rn.f32 	%f71, %f75, %f78, %f70;
	st.global.f32 	[%rd77], %f71;
	add.s64 	%rd78, %rd72, %rd75;
	ld.global.f32 	%f72, [%rd78];
	fma.rn.f32 	%f73, %f76, %f78, %f72;
	st.global.f32 	[%rd78], %f73;

BB0_45:
	ret;
}


`
	addexchange_ptx_50 = `
.version 5.0
.target sm_50
.address_size 64

	// .globl	addexchange

.visible .entry addexchange(
	.param .u64 addexchange_param_0,
	.param .u64 addexchange_param_1,
	.param .u64 addexchange_param_2,
	.param .u64 addexchange_param_3,
	.param .u64 addexchange_param_4,
	.param .u64 addexchange_param_5,
	.param .u64 addexchange_param_6,
	.param .f32 addexchange_param_7,
	.param .u64 addexchange_param_8,
	.param .u64 addexchange_param_9,
	.param .f32 addexchange_param_10,
	.param .f32 addexchange_param_11,
	.param .f32 addexchange_param_12,
	.param .u32 addexchange_param_13,
	.param .u32 addexchange_param_14,
	.param .u32 addexchange_param_15,
	.param .u8 addexchange_param_16
)
{
	.reg .pred 	%p<22>;
	.reg .b16 	%rs<26>;
	.reg .f32 	%f<79>;
	.reg .b32 	%r<152>;
	.reg .b64 	%rd<79>;


	ld.param.u64 	%rd7, [addexchange_param_0];
	ld.param.u64 	%rd8, [addexchange_param_1];
	ld.param.u64 	%rd9, [addexchange_param_2];
	ld.param.u64 	%rd11, [addexchange_param_3];
	ld.param.u64 	%rd12, [addexchange_param_4];
	ld.param.u64 	%rd13, [addexchange_param_5];
	ld.param.u64 	%rd10, [addexchange_param_6];
	ld.param.f32 	%f77, [addexchange_param_7];
	ld.param.u64 	%rd14, [addexchange_param_8];
	ld.param.u64 	%rd15, [addexchange_param_9];
	ld.param.f32 	%f45, [addexchange_param_10];
	ld.param.f32 	%f46, [addexchange_param_11];
	ld.param.f32 	%f47, [addexchange_param_12];
	ld.param.u32 	%r55, [addexchange_param_13];
	ld.param.u32 	%r56, [addexchange_param_14];
	ld.param.u32 	%r57, [addexchange_param_15];
	ld.param.u8 	%rs5, [addexchange_param_16];
	cvta.to.global.u64 	%rd1, %rd14;
	cvta.to.global.u64 	%rd2, %rd15;
	cvta.to.global.u64 	%rd3, %rd13;
	cvta.to.global.u64 	%rd4, %rd12;
	cvta.to.global.u64 	%rd5, %rd11;
	mov.u32 	%r58, %ntid.x;
	mov.u32 	%r59, %ctaid.x;
	mov.u32 	%r60, %tid.x;
	mad.lo.s32 	%r1, %r58, %r59, %r60;
	mov.u32 	%r61, %ntid.y;
	mov.u32 	%r62, %ctaid.y;
	mov.u32 	%r63, %tid.y;
	mad.lo.s32 	%r2, %r61, %r62, %r63;
	mov.u32 	%r64, %ntid.z;
	mov.u32 	%r65, %ctaid.z;
	mov.u32 	%r66, %tid.z;
	mad.lo.s32 	%r3, %r64, %r65, %r66;
	setp.ge.s32	%p1, %r1, %r55;
	setp.ge.s32	%p2, %r2, %r56;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r57;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_45;

	mul.lo.s32 	%r4, %r3, %r56;
	add.s32 	%r67, %r4, %r2;
	mul.lo.s32 	%r5, %r67, %r55;
	add.s32 	%r68, %r5, %r1;
	cvt.s64.s32	%rd6, %r68;
	mul.wide.s32 	%rd16, %r68, 4;
	add.s64 	%rd17, %rd5, %rd16;
	add.s64 	%rd18, %rd4, %rd16;
	add.s64 	%rd19, %rd3, %rd16;
	ld.global.nc.f32 	%f48, [%rd17];
	ld.global.nc.f32 	%f49, [%rd18];
	mul.f32 	%f50, %f49, %f49;
	fma.rn.f32 	%f51, %f48, %f48, %f50;
	ld.global.nc.f32 	%f52, [%rd19];
	fma.rn.f32 	%f53, %f52, %f52, %f51;
	setp.eq.f32	%p6, %f53, 0f00000000;
	@%p6 bra 	BB0_45;

	add.s64 	%rd20, %rd2, %rd6;
	ld.global.nc.u8 	%rs1, [%rd20];
	cvt.u32.u16	%r69, %rs1;
	and.b32  	%r6, %r69, 255;
	and.b16  	%rs2, %rs5, 1;
	setp.eq.s16	%p7, %rs2, 0;
	add.s32 	%r7, %r1, -1;
	@%p7 bra 	BB0_4;

	rem.s32 	%r70, %r7, %r55;
	add.s32 	%r71, %r70, %r55;
	rem.s32 	%r140, %r71, %r55;
	bra.uni 	BB0_5;

BB0_4:
	mov.u32 	%r72, 0;
	max.s32 	%r140, %r7, %r72;

BB0_5:
	add.s32 	%r73, %r140, %r5;
	cvt.s64.s32	%rd21, %r73;
	mul.wide.s32 	%rd22, %r73, 4;
	add.s64 	%rd23, %rd5, %rd22;
	ld.global.nc.f32 	%f1, [%rd23];
	add.s64 	%rd24, %rd4, %rd22;
	ld.global.nc.f32 	%f2, [%rd24];
	add.s64 	%rd25, %rd3, %rd22;
	ld.global.nc.f32 	%f3, [%rd25];
	add.s64 	%rd26, %rd2, %rd21;
	ld.global.nc.u8 	%rs6, [%rd26];
	setp.gt.u16	%p8, %rs6, %rs1;
	cvt.u32.u16	%r74, %rs6;
	and.b32  	%r11, %r74, 255;
	@%p8 bra 	BB0_7;
	bra.uni 	BB0_6;

BB0_7:
	add.s32 	%r78, %r11, 1;
	mul.lo.s32 	%r79, %r78, %r11;
	shr.u32 	%r80, %r79, 1;
	add.s32 	%r141, %r80, %r6;
	bra.uni 	BB0_8;

BB0_6:
	add.s32 	%r75, %r6, 1;
	mul.lo.s32 	%r76, %r75, %r6;
	shr.u32 	%r77, %r76, 1;
	add.s32 	%r141, %r11, %r77;

BB0_8:
	mul.wide.s32 	%rd27, %r141, 4;
	add.s64 	%rd28, %rd1, %rd27;
	ld.global.nc.f32 	%f54, [%rd28];
	mul.f32 	%f55, %f54, %f45;
	fma.rn.f32 	%f4, %f1, %f55, 0f00000000;
	fma.rn.f32 	%f5, %f2, %f55, 0f00000000;
	fma.rn.f32 	%f6, %f3, %f55, 0f00000000;
	add.s32 	%r15, %r1, 1;
	@%p7 bra 	BB0_10;

	rem.s32 	%r81, %r15, %r55;
	add.s32 	%r82, %r81, %r55;
	rem.s32 	%r142, %r82, %r55;
	bra.uni 	BB0_11;

BB0_10:
	add.s32 	%r83, %r55, -1;
	min.s32 	%r142, %r15, %r83;

BB0_11:
	add.s32 	%r84, %r142, %r5;
	cvt.s64.s32	%rd29, %r84;
	mul.wide.s32 	%rd30, %r84, 4;
	add.s64 	%rd31, %rd5, %rd30;
	ld.global.nc.f32 	%f7, [%rd31];
	add.s64 	%rd32, %rd4, %rd30;
	ld.global.nc.f32 	%f8, [%rd32];
	add.s64 	%rd33, %rd3, %rd30;
	ld.global.nc.f32 	%f9, [%rd33];
	add.s64 	%rd34, %rd2, %rd29;
	ld.global.nc.u8 	%rs9, [%rd34];
	setp.gt.u16	%p10, %rs9, %rs1;
	cvt.u32.u16	%r85, %rs9;
	and.b32  	%r19, %r85, 255;
	@%p10 bra 	BB0_13;
	bra.uni 	BB0_12;

BB0_13:
	add.s32 	%r89, %r19, 1;
	mul.lo.s32 	%r90, %r89, %r19;
	shr.u32 	%r91, %r90, 1;
	add.s32 	%r143, %r91, %r6;
	bra.uni 	BB0_14;

BB0_12:
	add.s32 	%r86, %r6, 1;
	mul.lo.s32 	%r87, %r86, %r6;
	shr.u32 	%r88, %r87, 1;
	add.s32 	%r143, %r19, %r88;

BB0_14:
	mul.wide.s32 	%rd35, %r143, 4;
	add.s64 	%rd36, %rd1, %rd35;
	ld.global.nc.f32 	%f56, [%rd36];
	mul.f32 	%f57, %f56, %f45;
	fma.rn.f32 	%f10, %f7, %f57, %f4;
	fma.rn.f32 	%f11, %f8, %f57, %f5;
	fma.rn.f32 	%f12, %f9, %f57, %f6;
	and.b16  	%rs3, %rs5, 2;
	setp.eq.s16	%p11, %rs3, 0;
	add.s32 	%r23, %r2, -1;
	@%p11 bra 	BB0_16;

	rem.s32 	%r92, %r23, %r56;
	add.s32 	%r93, %r92, %r56;
	rem.s32 	%r144, %r93, %r56;
	bra.uni 	BB0_17;

BB0_16:
	mov.u32 	%r94, 0;
	max.s32 	%r144, %r23, %r94;

BB0_17:
	add.s32 	%r95, %r144, %r4;
	mad.lo.s32 	%r96, %r95, %r55, %r1;
	cvt.s64.s32	%rd37, %r96;
	mul.wide.s32 	%rd38, %r96, 4;
	add.s64 	%rd39, %rd5, %rd38;
	ld.global.nc.f32 	%f13, [%rd39];
	add.s64 	%rd40, %rd4, %rd38;
	ld.global.nc.f32 	%f14, [%rd40];
	add.s64 	%rd41, %rd3, %rd38;
	ld.global.nc.f32 	%f15, [%rd41];
	add.s64 	%rd42, %rd2, %rd37;
	ld.global.nc.u8 	%rs12, [%rd42];
	setp.gt.u16	%p12, %rs12, %rs1;
	cvt.u32.u16	%r97, %rs12;
	and.b32  	%r27, %r97, 255;
	@%p12 bra 	BB0_19;
	bra.uni 	BB0_18;

BB0_19:
	add.s32 	%r101, %r27, 1;
	mul.lo.s32 	%r102, %r101, %r27;
	shr.u32 	%r103, %r102, 1;
	add.s32 	%r145, %r103, %r6;
	bra.uni 	BB0_20;

BB0_18:
	add.s32 	%r98, %r6, 1;
	mul.lo.s32 	%r99, %r98, %r6;
	shr.u32 	%r100, %r99, 1;
	add.s32 	%r145, %r27, %r100;

BB0_20:
	mul.wide.s32 	%rd43, %r145, 4;
	add.s64 	%rd44, %rd1, %rd43;
	ld.global.nc.f32 	%f58, [%rd44];
	mul.f32 	%f59, %f58, %f46;
	fma.rn.f32 	%f16, %f13, %f59, %f10;
	fma.rn.f32 	%f17, %f14, %f59, %f11;
	fma.rn.f32 	%f18, %f15, %f59, %f12;
	add.s32 	%r31, %r2, 1;
	@%p11 bra 	BB0_22;

	rem.s32 	%r104, %r31, %r56;
	add.s32 	%r105, %r104, %r56;
	rem.s32 	%r146, %r105, %r56;
	bra.uni 	BB0_23;

BB0_22:
	add.s32 	%r106, %r56, -1;
	min.s32 	%r146, %r31, %r106;

BB0_23:
	add.s32 	%r107, %r146, %r4;
	mad.lo.s32 	%r108, %r107, %r55, %r1;
	cvt.s64.s32	%rd45, %r108;
	mul.wide.s32 	%rd46, %r108, 4;
	add.s64 	%rd47, %rd5, %rd46;
	ld.global.nc.f32 	%f19, [%rd47];
	add.s64 	%rd48, %rd4, %rd46;
	ld.global.nc.f32 	%f20, [%rd48];
	add.s64 	%rd49, %rd3, %rd46;
	ld.global.nc.f32 	%f21, [%rd49];
	add.s64 	%rd50, %rd2, %rd45;
	ld.global.nc.u8 	%rs16, [%rd50];
	setp.gt.u16	%p14, %rs16, %rs1;
	cvt.u32.u16	%r109, %rs16;
	and.b32  	%r35, %r109, 255;
	@%p14 bra 	BB0_25;
	bra.uni 	BB0_24;

BB0_25:
	add.s32 	%r113, %r35, 1;
	mul.lo.s32 	%r114, %r113, %r35;
	shr.u32 	%r115, %r114, 1;
	add.s32 	%r147, %r115, %r6;
	bra.uni 	BB0_26;

BB0_24:
	add.s32 	%r110, %r6, 1;
	mul.lo.s32 	%r111, %r110, %r6;
	shr.u32 	%r112, %r111, 1;
	add.s32 	%r147, %r35, %r112;

BB0_26:
	mul.wide.s32 	%rd51, %r147, 4;
	add.s64 	%rd52, %rd1, %rd51;
	ld.global.nc.f32 	%f60, [%rd52];
	mul.f32 	%f61, %f60, %f46;
	fma.rn.f32 	%f74, %f19, %f61, %f16;
	fma.rn.f32 	%f75, %f20, %f61, %f17;
	fma.rn.f32 	%f76, %f21, %f61, %f18;
	setp.eq.s32	%p15, %r57, 1;
	@%p15 bra 	BB0_40;

	and.b16  	%rs4, %rs5, 4;
	setp.eq.s16	%p16, %rs4, 0;
	add.s32 	%r39, %r3, -1;
	@%p16 bra 	BB0_29;

	rem.s32 	%r116, %r39, %r57;
	add.s32 	%r117, %r116, %r57;
	rem.s32 	%r148, %r117, %r57;
	bra.uni 	BB0_30;

BB0_29:
	mov.u32 	%r118, 0;
	max.s32 	%r148, %r39, %r118;

BB0_30:
	mad.lo.s32 	%r119, %r148, %r56, %r2;
	mad.lo.s32 	%r120, %r119, %r55, %r1;
	cvt.s64.s32	%rd53, %r120;
	mul.wide.s32 	%rd54, %r120, 4;
	add.s64 	%rd55, %rd5, %rd54;
	ld.global.nc.f32 	%f25, [%rd55];
	add.s64 	%rd56, %rd4, %rd54;
	ld.global.nc.f32 	%f26, [%rd56];
	add.s64 	%rd57, %rd3, %rd54;
	ld.global.nc.f32 	%f27, [%rd57];
	add.s64 	%rd58, %rd2, %rd53;
	ld.global.nc.u8 	%rs19, [%rd58];
	setp.gt.u16	%p17, %rs19, %rs1;
	cvt.u32.u16	%r121, %rs19;
	and.b32  	%r43, %r121, 255;
	@%p17 bra 	BB0_32;
	bra.uni 	BB0_31;

BB0_32:
	add.s32 	%r125, %r43, 1;
	mul.lo.s32 	%r126, %r125, %r43;
	shr.u32 	%r127, %r126, 1;
	add.s32 	%r149, %r127, %r6;
	bra.uni 	BB0_33;

BB0_31:
	add.s32 	%r122, %r6, 1;
	mul.lo.s32 	%r123, %r122, %r6;
	shr.u32 	%r124, %r123, 1;
	add.s32 	%r149, %r43, %r124;

BB0_33:
	mul.wide.s32 	%rd59, %r149, 4;
	add.s64 	%rd60, %rd1, %rd59;
	ld.global.nc.f32 	%f62, [%rd60];
	mul.f32 	%f63, %f62, %f47;
	fma.rn.f32 	%f28, %f25, %f63, %f74;
	fma.rn.f32 	%f29, %f26, %f63, %f75;
	fma.rn.f32 	%f30, %f27, %f63, %f76;
	add.s32 	%r47, %r3, 1;
	@%p16 bra 	BB0_35;

	rem.s32 	%r128, %r47, %r57;
	add.s32 	%r129, %r128, %r57;
	rem.s32 	%r150, %r129, %r57;
	bra.uni 	BB0_36;

BB0_35:
	add.s32 	%r130, %r57, -1;
	min.s32 	%r150, %r47, %r130;

BB0_36:
	mad.lo.s32 	%r131, %r150, %r56, %r2;
	mad.lo.s32 	%r132, %r131, %r55, %r1;
	cvt.s64.s32	%rd61, %r132;
	mul.wide.s32 	%rd62, %r132, 4;
	add.s64 	%rd63, %rd5, %rd62;
	ld.global.nc.f32 	%f31, [%rd63];
	add.s64 	%rd64, %rd4, %rd62;
	ld.global.nc.f32 	%f32, [%rd64];
	add.s64 	%rd65, %rd3, %rd62;
	ld.global.nc.f32 	%f33, [%rd65];
	add.s64 	%rd66, %rd2, %rd61;
	ld.global.nc.u8 	%rs23, [%rd66];
	setp.gt.u16	%p19, %rs23, %rs1;
	cvt.u32.u16	%r133, %rs23;
	and.b32  	%r51, %r133, 255;
	@%p19 bra 	BB0_38;
	bra.uni 	BB0_37;

BB0_38:
	add.s32 	%r137, %r51, 1;
	mul.lo.s32 	%r138, %r137, %r51;
	shr.u32 	%r139, %r138, 1;
	add.s32 	%r151, %r139, %r6;
	bra.uni 	BB0_39;

BB0_37:
	add.s32 	%r134, %r6, 1;
	mul.lo.s32 	%r135, %r134, %r6;
	shr.u32 	%r136, %r135, 1;
	add.s32 	%r151, %r51, %r136;

BB0_39:
	mul.wide.s32 	%rd67, %r151, 4;
	add.s64 	%rd68, %rd1, %rd67;
	ld.global.nc.f32 	%f64, [%rd68];
	mul.f32 	%f65, %f64, %f47;
	fma.rn.f32 	%f74, %f31, %f65, %f28;
	fma.rn.f32 	%f75, %f32, %f65, %f29;
	fma.rn.f32 	%f76, %f33, %f65, %f30;

BB0_40:
	setp.eq.s64	%p20, %rd10, 0;
	@%p20 bra 	BB0_42;

	cvta.to.global.u64 	%rd69, %rd10;
	shl.b64 	%rd70, %rd6, 2;
	add.s64 	%rd71, %rd69, %rd70;
	ld.global.nc.f32 	%f66, [%rd71];
	mul.f32 	%f77, %f66, %f77;

BB0_42:
	setp.eq.f32	%p21, %f77, 0f00000000;
	mov.f32 	%f78, 0f00000000;
	@%p21 bra 	BB0_44;

	rcp.rn.f32 	%f78, %f77;

BB0_44:
	cvta.to.global.u64 	%rd72, %rd9;
	cvta.to.global.u64 	%rd73, %rd8;
	cvta.to.global.u64 	%rd74, %rd7;
	shl.b64 	%rd75, %rd6, 2;
	add.s64 	%rd76, %rd74, %rd75;
	ld.global.f32 	%f68, [%rd76];
	fma.rn.f32 	%f69, %f74, %f78, %f68;
	st.global.f32 	[%rd76], %f69;
	add.s64 	%rd77, %rd73, %rd75;
	ld.global.f32 	%f70, [%rd77];
	fma.rn.f32 	%f71, %f75, %f78, %f70;
	st.global.f32 	[%rd77], %f71;
	add.s64 	%rd78, %rd72, %rd75;
	ld.global.f32 	%f72, [%rd78];
	fma.rn.f32 	%f73, %f76, %f78, %f72;
	st.global.f32 	[%rd78], %f73;

BB0_45:
	ret;
}


`
	addexchange_ptx_52 = `
.version 5.0
.target sm_52
.address_size 64

	// .globl	addexchange

.visible .entry addexchange(
	.param .u64 addexchange_param_0,
	.param .u64 addexchange_param_1,
	.param .u64 addexchange_param_2,
	.param .u64 addexchange_param_3,
	.param .u64 addexchange_param_4,
	.param .u64 addexchange_param_5,
	.param .u64 addexchange_param_6,
	.param .f32 addexchange_param_7,
	.param .u64 addexchange_param_8,
	.param .u64 addexchange_param_9,
	.param .f32 addexchange_param_10,
	.param .f32 addexchange_param_11,
	.param .f32 addexchange_param_12,
	.param .u32 addexchange_param_13,
	.param .u32 addexchange_param_14,
	.param .u32 addexchange_param_15,
	.param .u8 addexchange_param_16
)
{
	.reg .pred 	%p<22>;
	.reg .b16 	%rs<26>;
	.reg .f32 	%f<79>;
	.reg .b32 	%r<152>;
	.reg .b64 	%rd<79>;


	ld.param.u64 	%rd7, [addexchange_param_0];
	ld.param.u64 	%rd8, [addexchange_param_1];
	ld.param.u64 	%rd9, [addexchange_param_2];
	ld.param.u64 	%rd11, [addexchange_param_3];
	ld.param.u64 	%rd12, [addexchange_param_4];
	ld.param.u64 	%rd13, [addexchange_param_5];
	ld.param.u64 	%rd10, [addexchange_param_6];
	ld.param.f32 	%f77, [addexchange_param_7];
	ld.param.u64 	%rd14, [addexchange_param_8];
	ld.param.u64 	%rd15, [addexchange_param_9];
	ld.param.f32 	%f45, [addexchange_param_10];
	ld.param.f32 	%f46, [addexchange_param_11];
	ld.param.f32 	%f47, [addexchange_param_12];
	ld.param.u32 	%r55, [addexchange_param_13];
	ld.param.u32 	%r56, [addexchange_param_14];
	ld.param.u32 	%r57, [addexchange_param_15];
	ld.param.u8 	%rs5, [addexchange_param_16];
	cvta.to.global.u64 	%rd1, %rd14;
	cvta.to.global.u64 	%rd2, %rd15;
	cvta.to.global.u64 	%rd3, %rd13;
	cvta.to.global.u64 	%rd4, %rd12;
	cvta.to.global.u64 	%rd5, %rd11;
	mov.u32 	%r58, %ntid.x;
	mov.u32 	%r59, %ctaid.x;
	mov.u32 	%r60, %tid.x;
	mad.lo.s32 	%r1, %r58, %r59, %r60;
	mov.u32 	%r61, %ntid.y;
	mov.u32 	%r62, %ctaid.y;
	mov.u32 	%r63, %tid.y;
	mad.lo.s32 	%r2, %r61, %r62, %r63;
	mov.u32 	%r64, %ntid.z;
	mov.u32 	%r65, %ctaid.z;
	mov.u32 	%r66, %tid.z;
	mad.lo.s32 	%r3, %r64, %r65, %r66;
	setp.ge.s32	%p1, %r1, %r55;
	setp.ge.s32	%p2, %r2, %r56;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r57;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_45;

	mul.lo.s32 	%r4, %r3, %r56;
	add.s32 	%r67, %r4, %r2;
	mul.lo.s32 	%r5, %r67, %r55;
	add.s32 	%r68, %r5, %r1;
	cvt.s64.s32	%rd6, %r68;
	mul.wide.s32 	%rd16, %r68, 4;
	add.s64 	%rd17, %rd5, %rd16;
	add.s64 	%rd18, %rd4, %rd16;
	add.s64 	%rd19, %rd3, %rd16;
	ld.global.nc.f32 	%f48, [%rd17];
	ld.global.nc.f32 	%f49, [%rd18];
	mul.f32 	%f50, %f49, %f49;
	fma.rn.f32 	%f51, %f48, %f48, %f50;
	ld.global.nc.f32 	%f52, [%rd19];
	fma.rn.f32 	%f53, %f52, %f52, %f51;
	setp.eq.f32	%p6, %f53, 0f00000000;
	@%p6 bra 	BB0_45;

	add.s64 	%rd20, %rd2, %rd6;
	ld.global.nc.u8 	%rs1, [%rd20];
	cvt.u32.u16	%r69, %rs1;
	and.b32  	%r6, %r69, 255;
	and.b16  	%rs2, %rs5, 1;
	setp.eq.s16	%p7, %rs2, 0;
	add.s32 	%r7, %r1, -1;
	@%p7 bra 	BB0_4;

	rem.s32 	%r70, %r7, %r55;
	add.s32 	%r71, %r70, %r55;
	rem.s32 	%r140, %r71, %r55;
	bra.uni 	BB0_5;

BB0_4:
	mov.u32 	%r72, 0;
	max.s32 	%r140, %r7, %r72;

BB0_5:
	add.s32 	%r73, %r140, %r5;
	cvt.s64.s32	%rd21, %r73;
	mul.wide.s32 	%rd22, %r73, 4;
	add.s64 	%rd23, %rd5, %rd22;
	ld.global.nc.f32 	%f1, [%rd23];
	add.s64 	%rd24, %rd4, %rd22;
	ld.global.nc.f32 	%f2, [%rd24];
	add.s64 	%rd25, %rd3, %rd22;
	ld.global.nc.f32 	%f3, [%rd25];
	add.s64 	%rd26, %rd2, %rd21;
	ld.global.nc.u8 	%rs6, [%rd26];
	setp.gt.u16	%p8, %rs6, %rs1;
	cvt.u32.u16	%r74, %rs6;
	and.b32  	%r11, %r74, 255;
	@%p8 bra 	BB0_7;
	bra.uni 	BB0_6;

BB0_7:
	add.s32 	%r78, %r11, 1;
	mul.lo.s32 	%r79, %r78, %r11;
	shr.u32 	%r80, %r79, 1;
	add.s32 	%r141, %r80, %r6;
	bra.uni 	BB0_8;

BB0_6:
	add.s32 	%r75, %r6, 1;
	mul.lo.s32 	%r76, %r75, %r6;
	shr.u32 	%r77, %r76, 1;
	add.s32 	%r141, %r11, %r77;

BB0_8:
	mul.wide.s32 	%rd27, %r141, 4;
	add.s64 	%rd28, %rd1, %rd27;
	ld.global.nc.f32 	%f54, [%rd28];
	mul.f32 	%f55, %f54, %f45;
	fma.rn.f32 	%f4, %f1, %f55, 0f00000000;
	fma.rn.f32 	%f5, %f2, %f55, 0f00000000;
	fma.rn.f32 	%f6, %f3, %f55, 0f00000000;
	add.s32 	%r15, %r1, 1;
	@%p7 bra 	BB0_10;

	rem.s32 	%r81, %r15, %r55;
	add.s32 	%r82, %r81, %r55;
	rem.s32 	%r142, %r82, %r55;
	bra.uni 	BB0_11;

BB0_10:
	add.s32 	%r83, %r55, -1;
	min.s32 	%r142, %r15, %r83;

BB0_11:
	add.s32 	%r84, %r142, %r5;
	cvt.s64.s32	%rd29, %r84;
	mul.wide.s32 	%rd30, %r84, 4;
	add.s64 	%rd31, %rd5, %rd30;
	ld.global.nc.f32 	%f7, [%rd31];
	add.s64 	%rd32, %rd4, %rd30;
	ld.global.nc.f32 	%f8, [%rd32];
	add.s64 	%rd33, %rd3, %rd30;
	ld.global.nc.f32 	%f9, [%rd33];
	add.s64 	%rd34, %rd2, %rd29;
	ld.global.nc.u8 	%rs9, [%rd34];
	setp.gt.u16	%p10, %rs9, %rs1;
	cvt.u32.u16	%r85, %rs9;
	and.b32  	%r19, %r85, 255;
	@%p10 bra 	BB0_13;
	bra.uni 	BB0_12;

BB0_13:
	add.s32 	%r89, %r19, 1;
	mul.lo.s32 	%r90, %r89, %r19;
	shr.u32 	%r91, %r90, 1;
	add.s32 	%r143, %r91, %r6;
	bra.uni 	BB0_14;

BB0_12:
	add.s32 	%r86, %r6, 1;
	mul.lo.s32 	%r87, %r86, %r6;
	shr.u32 	%r88, %r87, 1;
	add.s32 	%r143, %r19, %r88;

BB0_14:
	mul.wide.s32 	%rd35, %r143, 4;
	add.s64 	%rd36, %rd1, %rd35;
	ld.global.nc.f32 	%f56, [%rd36];
	mul.f32 	%f57, %f56, %f45;
	fma.rn.f32 	%f10, %f7, %f57, %f4;
	fma.rn.f32 	%f11, %f8, %f57, %f5;
	fma.rn.f32 	%f12, %f9, %f57, %f6;
	and.b16  	%rs3, %rs5, 2;
	setp.eq.s16	%p11, %rs3, 0;
	add.s32 	%r23, %r2, -1;
	@%p11 bra 	BB0_16;

	rem.s32 	%r92, %r23, %r56;
	add.s32 	%r93, %r92, %r56;
	rem.s32 	%r144, %r93, %r56;
	bra.uni 	BB0_17;

BB0_16:
	mov.u32 	%r94, 0;
	max.s32 	%r144, %r23, %r94;

BB0_17:
	add.s32 	%r95, %r144, %r4;
	mad.lo.s32 	%r96, %r95, %r55, %r1;
	cvt.s64.s32	%rd37, %r96;
	mul.wide.s32 	%rd38, %r96, 4;
	add.s64 	%rd39, %rd5, %rd38;
	ld.global.nc.f32 	%f13, [%rd39];
	add.s64 	%rd40, %rd4, %rd38;
	ld.global.nc.f32 	%f14, [%rd40];
	add.s64 	%rd41, %rd3, %rd38;
	ld.global.nc.f32 	%f15, [%rd41];
	add.s64 	%rd42, %rd2, %rd37;
	ld.global.nc.u8 	%rs12, [%rd42];
	setp.gt.u16	%p12, %rs12, %rs1;
	cvt.u32.u16	%r97, %rs12;
	and.b32  	%r27, %r97, 255;
	@%p12 bra 	BB0_19;
	bra.uni 	BB0_18;

BB0_19:
	add.s32 	%r101, %r27, 1;
	mul.lo.s32 	%r102, %r101, %r27;
	shr.u32 	%r103, %r102, 1;
	add.s32 	%r145, %r103, %r6;
	bra.uni 	BB0_20;

BB0_18:
	add.s32 	%r98, %r6, 1;
	mul.lo.s32 	%r99, %r98, %r6;
	shr.u32 	%r100, %r99, 1;
	add.s32 	%r145, %r27, %r100;

BB0_20:
	mul.wide.s32 	%rd43, %r145, 4;
	add.s64 	%rd44, %rd1, %rd43;
	ld.global.nc.f32 	%f58, [%rd44];
	mul.f32 	%f59, %f58, %f46;
	fma.rn.f32 	%f16, %f13, %f59, %f10;
	fma.rn.f32 	%f17, %f14, %f59, %f11;
	fma.rn.f32 	%f18, %f15, %f59, %f12;
	add.s32 	%r31, %r2, 1;
	@%p11 bra 	BB0_22;

	rem.s32 	%r104, %r31, %r56;
	add.s32 	%r105, %r104, %r56;
	rem.s32 	%r146, %r105, %r56;
	bra.uni 	BB0_23;

BB0_22:
	add.s32 	%r106, %r56, -1;
	min.s32 	%r146, %r31, %r106;

BB0_23:
	add.s32 	%r107, %r146, %r4;
	mad.lo.s32 	%r108, %r107, %r55, %r1;
	cvt.s64.s32	%rd45, %r108;
	mul.wide.s32 	%rd46, %r108, 4;
	add.s64 	%rd47, %rd5, %rd46;
	ld.global.nc.f32 	%f19, [%rd47];
	add.s64 	%rd48, %rd4, %rd46;
	ld.global.nc.f32 	%f20, [%rd48];
	add.s64 	%rd49, %rd3, %rd46;
	ld.global.nc.f32 	%f21, [%rd49];
	add.s64 	%rd50, %rd2, %rd45;
	ld.global.nc.u8 	%rs16, [%rd50];
	setp.gt.u16	%p14, %rs16, %rs1;
	cvt.u32.u16	%r109, %rs16;
	and.b32  	%r35, %r109, 255;
	@%p14 bra 	BB0_25;
	bra.uni 	BB0_24;

BB0_25:
	add.s32 	%r113, %r35, 1;
	mul.lo.s32 	%r114, %r113, %r35;
	shr.u32 	%r115, %r114, 1;
	add.s32 	%r147, %r115, %r6;
	bra.uni 	BB0_26;

BB0_24:
	add.s32 	%r110, %r6, 1;
	mul.lo.s32 	%r111, %r110, %r6;
	shr.u32 	%r112, %r111, 1;
	add.s32 	%r147, %r35, %r112;

BB0_26:
	mul.wide.s32 	%rd51, %r147, 4;
	add.s64 	%rd52, %rd1, %rd51;
	ld.global.nc.f32 	%f60, [%rd52];
	mul.f32 	%f61, %f60, %f46;
	fma.rn.f32 	%f74, %f19, %f61, %f16;
	fma.rn.f32 	%f75, %f20, %f61, %f17;
	fma.rn.f32 	%f76, %f21, %f61, %f18;
	setp.eq.s32	%p15, %r57, 1;
	@%p15 bra 	BB0_40;

	and.b16  	%rs4, %rs5, 4;
	setp.eq.s16	%p16, %rs4, 0;
	add.s32 	%r39, %r3, -1;
	@%p16 bra 	BB0_29;

	rem.s32 	%r116, %r39, %r57;
	add.s32 	%r117, %r116, %r57;
	rem.s32 	%r148, %r117, %r57;
	bra.uni 	BB0_30;

BB0_29:
	mov.u32 	%r118, 0;
	max.s32 	%r148, %r39, %r118;

BB0_30:
	mad.lo.s32 	%r119, %r148, %r56, %r2;
	mad.lo.s32 	%r120, %r119, %r55, %r1;
	cvt.s64.s32	%rd53, %r120;
	mul.wide.s32 	%rd54, %r120, 4;
	add.s64 	%rd55, %rd5, %rd54;
	ld.global.nc.f32 	%f25, [%rd55];
	add.s64 	%rd56, %rd4, %rd54;
	ld.global.nc.f32 	%f26, [%rd56];
	add.s64 	%rd57, %rd3, %rd54;
	ld.global.nc.f32 	%f27, [%rd57];
	add.s64 	%rd58, %rd2, %rd53;
	ld.global.nc.u8 	%rs19, [%rd58];
	setp.gt.u16	%p17, %rs19, %rs1;
	cvt.u32.u16	%r121, %rs19;
	and.b32  	%r43, %r121, 255;
	@%p17 bra 	BB0_32;
	bra.uni 	BB0_31;

BB0_32:
	add.s32 	%r125, %r43, 1;
	mul.lo.s32 	%r126, %r125, %r43;
	shr.u32 	%r127, %r126, 1;
	add.s32 	%r149, %r127, %r6;
	bra.uni 	BB0_33;

BB0_31:
	add.s32 	%r122, %r6, 1;
	mul.lo.s32 	%r123, %r122, %r6;
	shr.u32 	%r124, %r123, 1;
	add.s32 	%r149, %r43, %r124;

BB0_33:
	mul.wide.s32 	%rd59, %r149, 4;
	add.s64 	%rd60, %rd1, %rd59;
	ld.global.nc.f32 	%f62, [%rd60];
	mul.f32 	%f63, %f62, %f47;
	fma.rn.f32 	%f28, %f25, %f63, %f74;
	fma.rn.f32 	%f29, %f26, %f63, %f75;
	fma.rn.f32 	%f30, %f27, %f63, %f76;
	add.s32 	%r47, %r3, 1;
	@%p16 bra 	BB0_35;

	rem.s32 	%r128, %r47, %r57;
	add.s32 	%r129, %r128, %r57;
	rem.s32 	%r150, %r129, %r57;
	bra.uni 	BB0_36;

BB0_35:
	add.s32 	%r130, %r57, -1;
	min.s32 	%r150, %r47, %r130;

BB0_36:
	mad.lo.s32 	%r131, %r150, %r56, %r2;
	mad.lo.s32 	%r132, %r131, %r55, %r1;
	cvt.s64.s32	%rd61, %r132;
	mul.wide.s32 	%rd62, %r132, 4;
	add.s64 	%rd63, %rd5, %rd62;
	ld.global.nc.f32 	%f31, [%rd63];
	add.s64 	%rd64, %rd4, %rd62;
	ld.global.nc.f32 	%f32, [%rd64];
	add.s64 	%rd65, %rd3, %rd62;
	ld.global.nc.f32 	%f33, [%rd65];
	add.s64 	%rd66, %rd2, %rd61;
	ld.global.nc.u8 	%rs23, [%rd66];
	setp.gt.u16	%p19, %rs23, %rs1;
	cvt.u32.u16	%r133, %rs23;
	and.b32  	%r51, %r133, 255;
	@%p19 bra 	BB0_38;
	bra.uni 	BB0_37;

BB0_38:
	add.s32 	%r137, %r51, 1;
	mul.lo.s32 	%r138, %r137, %r51;
	shr.u32 	%r139, %r138, 1;
	add.s32 	%r151, %r139, %r6;
	bra.uni 	BB0_39;

BB0_37:
	add.s32 	%r134, %r6, 1;
	mul.lo.s32 	%r135, %r134, %r6;
	shr.u32 	%r136, %r135, 1;
	add.s32 	%r151, %r51, %r136;

BB0_39:
	mul.wide.s32 	%rd67, %r151, 4;
	add.s64 	%rd68, %rd1, %rd67;
	ld.global.nc.f32 	%f64, [%rd68];
	mul.f32 	%f65, %f64, %f47;
	fma.rn.f32 	%f74, %f31, %f65, %f28;
	fma.rn.f32 	%f75, %f32, %f65, %f29;
	fma.rn.f32 	%f76, %f33, %f65, %f30;

BB0_40:
	setp.eq.s64	%p20, %rd10, 0;
	@%p20 bra 	BB0_42;

	cvta.to.global.u64 	%rd69, %rd10;
	shl.b64 	%rd70, %rd6, 2;
	add.s64 	%rd71, %rd69, %rd70;
	ld.global.nc.f32 	%f66, [%rd71];
	mul.f32 	%f77, %f66, %f77;

BB0_42:
	setp.eq.f32	%p21, %f77, 0f00000000;
	mov.f32 	%f78, 0f00000000;
	@%p21 bra 	BB0_44;

	rcp.rn.f32 	%f78, %f77;

BB0_44:
	cvta.to.global.u64 	%rd72, %rd9;
	cvta.to.global.u64 	%rd73, %rd8;
	cvta.to.global.u64 	%rd74, %rd7;
	shl.b64 	%rd75, %rd6, 2;
	add.s64 	%rd76, %rd74, %rd75;
	ld.global.f32 	%f68, [%rd76];
	fma.rn.f32 	%f69, %f74, %f78, %f68;
	st.global.f32 	[%rd76], %f69;
	add.s64 	%rd77, %rd73, %rd75;
	ld.global.f32 	%f70, [%rd77];
	fma.rn.f32 	%f71, %f75, %f78, %f70;
	st.global.f32 	[%rd77], %f71;
	add.s64 	%rd78, %rd72, %rd75;
	ld.global.f32 	%f72, [%rd78];
	fma.rn.f32 	%f73, %f76, %f78, %f72;
	st.global.f32 	[%rd78], %f73;

BB0_45:
	ret;
}


`
	addexchange_ptx_53 = `
.version 5.0
.target sm_53
.address_size 64

	// .globl	addexchange

.visible .entry addexchange(
	.param .u64 addexchange_param_0,
	.param .u64 addexchange_param_1,
	.param .u64 addexchange_param_2,
	.param .u64 addexchange_param_3,
	.param .u64 addexchange_param_4,
	.param .u64 addexchange_param_5,
	.param .u64 addexchange_param_6,
	.param .f32 addexchange_param_7,
	.param .u64 addexchange_param_8,
	.param .u64 addexchange_param_9,
	.param .f32 addexchange_param_10,
	.param .f32 addexchange_param_11,
	.param .f32 addexchange_param_12,
	.param .u32 addexchange_param_13,
	.param .u32 addexchange_param_14,
	.param .u32 addexchange_param_15,
	.param .u8 addexchange_param_16
)
{
	.reg .pred 	%p<22>;
	.reg .b16 	%rs<26>;
	.reg .f32 	%f<79>;
	.reg .b32 	%r<152>;
	.reg .b64 	%rd<79>;


	ld.param.u64 	%rd7, [addexchange_param_0];
	ld.param.u64 	%rd8, [addexchange_param_1];
	ld.param.u64 	%rd9, [addexchange_param_2];
	ld.param.u64 	%rd11, [addexchange_param_3];
	ld.param.u64 	%rd12, [addexchange_param_4];
	ld.param.u64 	%rd13, [addexchange_param_5];
	ld.param.u64 	%rd10, [addexchange_param_6];
	ld.param.f32 	%f77, [addexchange_param_7];
	ld.param.u64 	%rd14, [addexchange_param_8];
	ld.param.u64 	%rd15, [addexchange_param_9];
	ld.param.f32 	%f45, [addexchange_param_10];
	ld.param.f32 	%f46, [addexchange_param_11];
	ld.param.f32 	%f47, [addexchange_param_12];
	ld.param.u32 	%r55, [addexchange_param_13];
	ld.param.u32 	%r56, [addexchange_param_14];
	ld.param.u32 	%r57, [addexchange_param_15];
	ld.param.u8 	%rs5, [addexchange_param_16];
	cvta.to.global.u64 	%rd1, %rd14;
	cvta.to.global.u64 	%rd2, %rd15;
	cvta.to.global.u64 	%rd3, %rd13;
	cvta.to.global.u64 	%rd4, %rd12;
	cvta.to.global.u64 	%rd5, %rd11;
	mov.u32 	%r58, %ntid.x;
	mov.u32 	%r59, %ctaid.x;
	mov.u32 	%r60, %tid.x;
	mad.lo.s32 	%r1, %r58, %r59, %r60;
	mov.u32 	%r61, %ntid.y;
	mov.u32 	%r62, %ctaid.y;
	mov.u32 	%r63, %tid.y;
	mad.lo.s32 	%r2, %r61, %r62, %r63;
	mov.u32 	%r64, %ntid.z;
	mov.u32 	%r65, %ctaid.z;
	mov.u32 	%r66, %tid.z;
	mad.lo.s32 	%r3, %r64, %r65, %r66;
	setp.ge.s32	%p1, %r1, %r55;
	setp.ge.s32	%p2, %r2, %r56;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r57;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_45;

	mul.lo.s32 	%r4, %r3, %r56;
	add.s32 	%r67, %r4, %r2;
	mul.lo.s32 	%r5, %r67, %r55;
	add.s32 	%r68, %r5, %r1;
	cvt.s64.s32	%rd6, %r68;
	mul.wide.s32 	%rd16, %r68, 4;
	add.s64 	%rd17, %rd5, %rd16;
	add.s64 	%rd18, %rd4, %rd16;
	add.s64 	%rd19, %rd3, %rd16;
	ld.global.nc.f32 	%f48, [%rd17];
	ld.global.nc.f32 	%f49, [%rd18];
	mul.f32 	%f50, %f49, %f49;
	fma.rn.f32 	%f51, %f48, %f48, %f50;
	ld.global.nc.f32 	%f52, [%rd19];
	fma.rn.f32 	%f53, %f52, %f52, %f51;
	setp.eq.f32	%p6, %f53, 0f00000000;
	@%p6 bra 	BB0_45;

	add.s64 	%rd20, %rd2, %rd6;
	ld.global.nc.u8 	%rs1, [%rd20];
	cvt.u32.u16	%r69, %rs1;
	and.b32  	%r6, %r69, 255;
	and.b16  	%rs2, %rs5, 1;
	setp.eq.s16	%p7, %rs2, 0;
	add.s32 	%r7, %r1, -1;
	@%p7 bra 	BB0_4;

	rem.s32 	%r70, %r7, %r55;
	add.s32 	%r71, %r70, %r55;
	rem.s32 	%r140, %r71, %r55;
	bra.uni 	BB0_5;

BB0_4:
	mov.u32 	%r72, 0;
	max.s32 	%r140, %r7, %r72;

BB0_5:
	add.s32 	%r73, %r140, %r5;
	cvt.s64.s32	%rd21, %r73;
	mul.wide.s32 	%rd22, %r73, 4;
	add.s64 	%rd23, %rd5, %rd22;
	ld.global.nc.f32 	%f1, [%rd23];
	add.s64 	%rd24, %rd4, %rd22;
	ld.global.nc.f32 	%f2, [%rd24];
	add.s64 	%rd25, %rd3, %rd22;
	ld.global.nc.f32 	%f3, [%rd25];
	add.s64 	%rd26, %rd2, %rd21;
	ld.global.nc.u8 	%rs6, [%rd26];
	setp.gt.u16	%p8, %rs6, %rs1;
	cvt.u32.u16	%r74, %rs6;
	and.b32  	%r11, %r74, 255;
	@%p8 bra 	BB0_7;
	bra.uni 	BB0_6;

BB0_7:
	add.s32 	%r78, %r11, 1;
	mul.lo.s32 	%r79, %r78, %r11;
	shr.u32 	%r80, %r79, 1;
	add.s32 	%r141, %r80, %r6;
	bra.uni 	BB0_8;

BB0_6:
	add.s32 	%r75, %r6, 1;
	mul.lo.s32 	%r76, %r75, %r6;
	shr.u32 	%r77, %r76, 1;
	add.s32 	%r141, %r11, %r77;

BB0_8:
	mul.wide.s32 	%rd27, %r141, 4;
	add.s64 	%rd28, %rd1, %rd27;
	ld.global.nc.f32 	%f54, [%rd28];
	mul.f32 	%f55, %f54, %f45;
	fma.rn.f32 	%f4, %f1, %f55, 0f00000000;
	fma.rn.f32 	%f5, %f2, %f55, 0f00000000;
	fma.rn.f32 	%f6, %f3, %f55, 0f00000000;
	add.s32 	%r15, %r1, 1;
	@%p7 bra 	BB0_10;

	rem.s32 	%r81, %r15, %r55;
	add.s32 	%r82, %r81, %r55;
	rem.s32 	%r142, %r82, %r55;
	bra.uni 	BB0_11;

BB0_10:
	add.s32 	%r83, %r55, -1;
	min.s32 	%r142, %r15, %r83;

BB0_11:
	add.s32 	%r84, %r142, %r5;
	cvt.s64.s32	%rd29, %r84;
	mul.wide.s32 	%rd30, %r84, 4;
	add.s64 	%rd31, %rd5, %rd30;
	ld.global.nc.f32 	%f7, [%rd31];
	add.s64 	%rd32, %rd4, %rd30;
	ld.global.nc.f32 	%f8, [%rd32];
	add.s64 	%rd33, %rd3, %rd30;
	ld.global.nc.f32 	%f9, [%rd33];
	add.s64 	%rd34, %rd2, %rd29;
	ld.global.nc.u8 	%rs9, [%rd34];
	setp.gt.u16	%p10, %rs9, %rs1;
	cvt.u32.u16	%r85, %rs9;
	and.b32  	%r19, %r85, 255;
	@%p10 bra 	BB0_13;
	bra.uni 	BB0_12;

BB0_13:
	add.s32 	%r89, %r19, 1;
	mul.lo.s32 	%r90, %r89, %r19;
	shr.u32 	%r91, %r90, 1;
	add.s32 	%r143, %r91, %r6;
	bra.uni 	BB0_14;

BB0_12:
	add.s32 	%r86, %r6, 1;
	mul.lo.s32 	%r87, %r86, %r6;
	shr.u32 	%r88, %r87, 1;
	add.s32 	%r143, %r19, %r88;

BB0_14:
	mul.wide.s32 	%rd35, %r143, 4;
	add.s64 	%rd36, %rd1, %rd35;
	ld.global.nc.f32 	%f56, [%rd36];
	mul.f32 	%f57, %f56, %f45;
	fma.rn.f32 	%f10, %f7, %f57, %f4;
	fma.rn.f32 	%f11, %f8, %f57, %f5;
	fma.rn.f32 	%f12, %f9, %f57, %f6;
	and.b16  	%rs3, %rs5, 2;
	setp.eq.s16	%p11, %rs3, 0;
	add.s32 	%r23, %r2, -1;
	@%p11 bra 	BB0_16;

	rem.s32 	%r92, %r23, %r56;
	add.s32 	%r93, %r92, %r56;
	rem.s32 	%r144, %r93, %r56;
	bra.uni 	BB0_17;

BB0_16:
	mov.u32 	%r94, 0;
	max.s32 	%r144, %r23, %r94;

BB0_17:
	add.s32 	%r95, %r144, %r4;
	mad.lo.s32 	%r96, %r95, %r55, %r1;
	cvt.s64.s32	%rd37, %r96;
	mul.wide.s32 	%rd38, %r96, 4;
	add.s64 	%rd39, %rd5, %rd38;
	ld.global.nc.f32 	%f13, [%rd39];
	add.s64 	%rd40, %rd4, %rd38;
	ld.global.nc.f32 	%f14, [%rd40];
	add.s64 	%rd41, %rd3, %rd38;
	ld.global.nc.f32 	%f15, [%rd41];
	add.s64 	%rd42, %rd2, %rd37;
	ld.global.nc.u8 	%rs12, [%rd42];
	setp.gt.u16	%p12, %rs12, %rs1;
	cvt.u32.u16	%r97, %rs12;
	and.b32  	%r27, %r97, 255;
	@%p12 bra 	BB0_19;
	bra.uni 	BB0_18;

BB0_19:
	add.s32 	%r101, %r27, 1;
	mul.lo.s32 	%r102, %r101, %r27;
	shr.u32 	%r103, %r102, 1;
	add.s32 	%r145, %r103, %r6;
	bra.uni 	BB0_20;

BB0_18:
	add.s32 	%r98, %r6, 1;
	mul.lo.s32 	%r99, %r98, %r6;
	shr.u32 	%r100, %r99, 1;
	add.s32 	%r145, %r27, %r100;

BB0_20:
	mul.wide.s32 	%rd43, %r145, 4;
	add.s64 	%rd44, %rd1, %rd43;
	ld.global.nc.f32 	%f58, [%rd44];
	mul.f32 	%f59, %f58, %f46;
	fma.rn.f32 	%f16, %f13, %f59, %f10;
	fma.rn.f32 	%f17, %f14, %f59, %f11;
	fma.rn.f32 	%f18, %f15, %f59, %f12;
	add.s32 	%r31, %r2, 1;
	@%p11 bra 	BB0_22;

	rem.s32 	%r104, %r31, %r56;
	add.s32 	%r105, %r104, %r56;
	rem.s32 	%r146, %r105, %r56;
	bra.uni 	BB0_23;

BB0_22:
	add.s32 	%r106, %r56, -1;
	min.s32 	%r146, %r31, %r106;

BB0_23:
	add.s32 	%r107, %r146, %r4;
	mad.lo.s32 	%r108, %r107, %r55, %r1;
	cvt.s64.s32	%rd45, %r108;
	mul.wide.s32 	%rd46, %r108, 4;
	add.s64 	%rd47, %rd5, %rd46;
	ld.global.nc.f32 	%f19, [%rd47];
	add.s64 	%rd48, %rd4, %rd46;
	ld.global.nc.f32 	%f20, [%rd48];
	add.s64 	%rd49, %rd3, %rd46;
	ld.global.nc.f32 	%f21, [%rd49];
	add.s64 	%rd50, %rd2, %rd45;
	ld.global.nc.u8 	%rs16, [%rd50];
	setp.gt.u16	%p14, %rs16, %rs1;
	cvt.u32.u16	%r109, %rs16;
	and.b32  	%r35, %r109, 255;
	@%p14 bra 	BB0_25;
	bra.uni 	BB0_24;

BB0_25:
	add.s32 	%r113, %r35, 1;
	mul.lo.s32 	%r114, %r113, %r35;
	shr.u32 	%r115, %r114, 1;
	add.s32 	%r147, %r115, %r6;
	bra.uni 	BB0_26;

BB0_24:
	add.s32 	%r110, %r6, 1;
	mul.lo.s32 	%r111, %r110, %r6;
	shr.u32 	%r112, %r111, 1;
	add.s32 	%r147, %r35, %r112;

BB0_26:
	mul.wide.s32 	%rd51, %r147, 4;
	add.s64 	%rd52, %rd1, %rd51;
	ld.global.nc.f32 	%f60, [%rd52];
	mul.f32 	%f61, %f60, %f46;
	fma.rn.f32 	%f74, %f19, %f61, %f16;
	fma.rn.f32 	%f75, %f20, %f61, %f17;
	fma.rn.f32 	%f76, %f21, %f61, %f18;
	setp.eq.s32	%p15, %r57, 1;
	@%p15 bra 	BB0_40;

	and.b16  	%rs4, %rs5, 4;
	setp.eq.s16	%p16, %rs4, 0;
	add.s32 	%r39, %r3, -1;
	@%p16 bra 	BB0_29;

	rem.s32 	%r116, %r39, %r57;
	add.s32 	%r117, %r116, %r57;
	rem.s32 	%r148, %r117, %r57;
	bra.uni 	BB0_30;

BB0_29:
	mov.u32 	%r118, 0;
	max.s32 	%r148, %r39, %r118;

BB0_30:
	mad.lo.s32 	%r119, %r148, %r56, %r2;
	mad.lo.s32 	%r120, %r119, %r55, %r1;
	cvt.s64.s32	%rd53, %r120;
	mul.wide.s32 	%rd54, %r120, 4;
	add.s64 	%rd55, %rd5, %rd54;
	ld.global.nc.f32 	%f25, [%rd55];
	add.s64 	%rd56, %rd4, %rd54;
	ld.global.nc.f32 	%f26, [%rd56];
	add.s64 	%rd57, %rd3, %rd54;
	ld.global.nc.f32 	%f27, [%rd57];
	add.s64 	%rd58, %rd2, %rd53;
	ld.global.nc.u8 	%rs19, [%rd58];
	setp.gt.u16	%p17, %rs19, %rs1;
	cvt.u32.u16	%r121, %rs19;
	and.b32  	%r43, %r121, 255;
	@%p17 bra 	BB0_32;
	bra.uni 	BB0_31;

BB0_32:
	add.s32 	%r125, %r43, 1;
	mul.lo.s32 	%r126, %r125, %r43;
	shr.u32 	%r127, %r126, 1;
	add.s32 	%r149, %r127, %r6;
	bra.uni 	BB0_33;

BB0_31:
	add.s32 	%r122, %r6, 1;
	mul.lo.s32 	%r123, %r122, %r6;
	shr.u32 	%r124, %r123, 1;
	add.s32 	%r149, %r43, %r124;

BB0_33:
	mul.wide.s32 	%rd59, %r149, 4;
	add.s64 	%rd60, %rd1, %rd59;
	ld.global.nc.f32 	%f62, [%rd60];
	mul.f32 	%f63, %f62, %f47;
	fma.rn.f32 	%f28, %f25, %f63, %f74;
	fma.rn.f32 	%f29, %f26, %f63, %f75;
	fma.rn.f32 	%f30, %f27, %f63, %f76;
	add.s32 	%r47, %r3, 1;
	@%p16 bra 	BB0_35;

	rem.s32 	%r128, %r47, %r57;
	add.s32 	%r129, %r128, %r57;
	rem.s32 	%r150, %r129, %r57;
	bra.uni 	BB0_36;

BB0_35:
	add.s32 	%r130, %r57, -1;
	min.s32 	%r150, %r47, %r130;

BB0_36:
	mad.lo.s32 	%r131, %r150, %r56, %r2;
	mad.lo.s32 	%r132, %r131, %r55, %r1;
	cvt.s64.s32	%rd61, %r132;
	mul.wide.s32 	%rd62, %r132, 4;
	add.s64 	%rd63, %rd5, %rd62;
	ld.global.nc.f32 	%f31, [%rd63];
	add.s64 	%rd64, %rd4, %rd62;
	ld.global.nc.f32 	%f32, [%rd64];
	add.s64 	%rd65, %rd3, %rd62;
	ld.global.nc.f32 	%f33, [%rd65];
	add.s64 	%rd66, %rd2, %rd61;
	ld.global.nc.u8 	%rs23, [%rd66];
	setp.gt.u16	%p19, %rs23, %rs1;
	cvt.u32.u16	%r133, %rs23;
	and.b32  	%r51, %r133, 255;
	@%p19 bra 	BB0_38;
	bra.uni 	BB0_37;

BB0_38:
	add.s32 	%r137, %r51, 1;
	mul.lo.s32 	%r138, %r137, %r51;
	shr.u32 	%r139, %r138, 1;
	add.s32 	%r151, %r139, %r6;
	bra.uni 	BB0_39;

BB0_37:
	add.s32 	%r134, %r6, 1;
	mul.lo.s32 	%r135, %r134, %r6;
	shr.u32 	%r136, %r135, 1;
	add.s32 	%r151, %r51, %r136;

BB0_39:
	mul.wide.s32 	%rd67, %r151, 4;
	add.s64 	%rd68, %rd1, %rd67;
	ld.global.nc.f32 	%f64, [%rd68];
	mul.f32 	%f65, %f64, %f47;
	fma.rn.f32 	%f74, %f31, %f65, %f28;
	fma.rn.f32 	%f75, %f32, %f65, %f29;
	fma.rn.f32 	%f76, %f33, %f65, %f30;

BB0_40:
	setp.eq.s64	%p20, %rd10, 0;
	@%p20 bra 	BB0_42;

	cvta.to.global.u64 	%rd69, %rd10;
	shl.b64 	%rd70, %rd6, 2;
	add.s64 	%rd71, %rd69, %rd70;
	ld.global.nc.f32 	%f66, [%rd71];
	mul.f32 	%f77, %f66, %f77;

BB0_42:
	setp.eq.f32	%p21, %f77, 0f00000000;
	mov.f32 	%f78, 0f00000000;
	@%p21 bra 	BB0_44;

	rcp.rn.f32 	%f78, %f77;

BB0_44:
	cvta.to.global.u64 	%rd72, %rd9;
	cvta.to.global.u64 	%rd73, %rd8;
	cvta.to.global.u64 	%rd74, %rd7;
	shl.b64 	%rd75, %rd6, 2;
	add.s64 	%rd76, %rd74, %rd75;
	ld.global.f32 	%f68, [%rd76];
	fma.rn.f32 	%f69, %f74, %f78, %f68;
	st.global.f32 	[%rd76], %f69;
	add.s64 	%rd77, %rd73, %rd75;
	ld.global.f32 	%f70, [%rd77];
	fma.rn.f32 	%f71, %f75, %f78, %f70;
	st.global.f32 	[%rd77], %f71;
	add.s64 	%rd78, %rd72, %rd75;
	ld.global.f32 	%f72, [%rd78];
	fma.rn.f32 	%f73, %f76, %f78, %f72;
	st.global.f32 	[%rd78], %f73;

BB0_45:
	ret;
}


`
)
